### ISSUE TITLE
Including relationship details in party detail page

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1001]
Currently we can check the different relationships that are attached to a single location (Open Location > Relationships tab), but we have no way to check the different relationships that are attached to one single party (for instance, different parcels owned by a single farmer). 

A way to provide this information would be to include the list of relationships in the Party detail page (we are now providing the party details and the list of resources attached to the party). 

Thoughts? 

![screen shot 2016-12-12 at 19 59 46](https://cloud.githubusercontent.com/assets/17198051/21112288/8fb762bc-c0a5-11e6-8c5a-668d12280157.png)

**Comment by dpalomino** [comment]
Hi. Trying to resume the discussion around this issue, as we've been talking in other meeting. With the imminent deployment of the search feature this issue is now more important, because when a user click on a party/relationship result (for instance, when querying with national id or mobile numbers), there is no way to access to the locations that are linked to that party. 

@clash99, @oliverroick. Is there any quick/easy solution that we could implement in the short term? Like including the list of locations linked to that party in the Party Detail page (maybe after Resources)?

![screen shot 2017-01-27 at 13 06 10](https://cloud.githubusercontent.com/assets/17198051/22370373/6d4aa13e-e491-11e6-86c5-43dd42f8d462.png)

**Comment by seav** [comment]
I think we can have the party detail page copy the format of the location detail page in having three tabs: Overview, Relationships, and Resources. The Relationships list would also link to the connected location in the same way that the Relationships list of the location detail page also links to the connected party.

**Comment by clash99** [comment]
@seav - I like that idea.  That would parallel the location flow perfectly.  I can create a quick mock this afternoon.

**Comment by dpalomino** [comment]
That's great. Thanks @clash99, @seav!

**Comment by clash99** [comment]
**Party Detail - Overview tab**
![2 2 list with party detail - overview tab](https://cloud.githubusercontent.com/assets/1119621/22444701/b5de76c6-e709-11e6-9420-f86f5b509807.png)

**Party Detail - Relationships tab**
![2 2 list with party - relationships tab](https://cloud.githubusercontent.com/assets/1119621/22444976/efdb6040-e70a-11e6-9c09-8c7c30a49aed.png)

**Party Detail - Resources tab**
![2 2 list with party - resources tab](https://cloud.githubusercontent.com/assets/1119621/22444984/f5e12a7e-e70a-11e6-9783-41b91ad6d66c.png)

(there are some small differences from the current platform because these were taken from map interaction wireframes - main content should be focus of development)

Let me know if there is any feedback or suggested changes.  Thanks, Chandra

**Comment by dpalomino** [comment]
Thanks a lot @clash99. Looks very good to me!

**Comment by oliverroick** [comment]
I got the basic functionality ready for this in branch `enhancement/party-detail-page`. I'm waiting for #1120 to be merged so I can add translated labels to the party relationships too.

The wireframes show "Add relationship" buttons. I think, we need to come up with a workflow for this if we want to implement this. When you create a relationship for a location the location is already selected. That is not the case when you create a relationship for a party; we would need to implement a view that allows users to fill the relationship form and also be able to select an existing location from the map or create a new location (similar to the process of selecting or creating a party when you create a relationship for a location).

**Comment by clash99** [comment]
@oliverroick I don't see the "Add relationship" button.  Are you referring to the "Add resource" button under relationships tab?

**Comment by oliverroick** [comment]
Ah right. I confused that.
