### ISSUE TITLE
Include Search and Go-To-My-Location in Overview and Map pages

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1002]
# Outreachy/GSoC candidates: A PR for this issue has been approved and is waiting to be merged.

Currently in the dashboard page we are showing the following map tools: 
- Zoom in/out
- Search 
- Go-to-my-location

![screen shot 2016-12-12 at 20 04 26_](https://cloud.githubusercontent.com/assets/17198051/21113089/86054dee-c0a8-11e6-9f89-dbf4d2339d47.jpg)

But either in Overview and Map pages for projects, we are just showing zoom in/out: 

![screen shot 2016-12-12 at 20 16 17_](https://cloud.githubusercontent.com/assets/17198051/21113100/8bf4c680-c0a8-11e6-91c3-aa40d44f6635.jpg)

I think we should also include Search and Go-to-my-location buttons in those pages.

**Comment by yoshi2095** [comment]
I am working on this. Thanks.

**Comment by yoshi2095** [comment]
Hi @dpalomino, I have fixed the bug. Please review. Thanks.  #1200

**Comment by yoshi2095** [comment]
Hi @dpalomino, I have fixed this issue. Please review. Thanks. #1201
