### ISSUE TITLE
Line Tool Should Inform User they Need to use the Polygon Tool to Draw Polygons

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1005]
Feedback on the drawing tools. It is not clear to some users that they need to select the polygon tool to draw polygons when using the line tool. Having a messages making it clear they need to switch tools would make it easier for the user. 

@clash99 thoughts?

**Comment by clash99** [comment]
Couple of thoughts here:

1)  @bethschechter and I have discussed the need for a "how-to" video demonstration to be available on the map editing pages.  This would provide a step-by-step guide on how to interact with the map editing tools.

2)  We can add a quick overlay triggered by a "?" that shows a tooltip-type of key that defines the map controls. 

3)  We can improve the current single control tooltips to better inform the user the difference between the line and polygon tool. 

4)  I can do some research and see if we can tell if the user meant a polygon once they've drawn a closed line segment and ask them if they would like to convert it to a polygon.  (Unsure about this one)

#1 and #2 can be implemented using inlinemanual.  Obviously #2 and #3 will be easier to implement.  

Thoughts on any of these ideas?

**Comment by wonderchook** [comment]
@oliverroick @seav aka "mappy people" thoughts on this? 

Also here is a screenshot from the main OSM web editor iD. It requires you to pick the type, but the buttons are much bigger and more clear. 

![id-editor](https://cloud.githubusercontent.com/assets/67992/21164670/6d543b6e-c14f-11e6-9ea6-255257062f39.jpg)

**Comment by seav** [comment]
If we can influence upstream (Leaflet.draw) to have a better and not-confusing UI, that would be great. I hesitate to implement a custom solution just for our platform.

**Comment by wonderchook** [comment]
@seav I'm thinking we are unlikely to be able to do that much influence. I do think we could potentially make the buttons bigger and labeled though.

**Comment by oliverroick** [comment]
I think, we can either try to change the look and positioning via CSS or research if there are means to create a custom UI (i.e. bigger/different buttons) and still use the functionality of Leaflet.Draw. We could, for instance, implement a custom toolbar using [the API](https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html). 

Chandra's suggestion #4 fits in here as well. If users select the line tool, we can ask them if they wanted to draw a polygon and close the polygon programmatically. There are draw events that allow us to intercept the process. There's also a [snapping example](https://leaflet.github.io/Leaflet.draw/docs/examples-0.7.x/snapping.html) that might be useful for this issue. 

If we decide to invest time to build a custom solution to improve the usability of drawing, I would also suggest fixing other outstanding map-related issues (#299 and #718). These require upgrading to Leaflet 1.0, which will be a larger chunk of work, so it's a good opportunity to work on all of those issues at once.

**Comment by SteadyCadence** [comment]
I have run into this issue a few times this week (ODPD and Ecohub). They used polylines to create polygons and needed help to figure out how to click on the polyline that was created (since you have to click the line to open the location).

**Comment by clash99** [comment]
Refer to wireframes in #1608 for recommended improvements to map toolbar ui.

**Comment by clash99** [comment]
I'm closing this task since it it redundant with #1608.
