### ISSUE TITLE
Ability to invite users to an organization

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1011]
When organization admins want to add users as members of their organization, the users currently need to have an account created beforehand. 

We should add the ability to invite any user to an organization by providing an email address (or phone number at some point). When a user is asked to join an organization, a preliminary user account is set up so organization admins can set the user’s permissions for the organization. 

Users receive an email containing a link to finalize the account. To finalize the account, a username and password must be provided; the full name is optional. Creating the account via the link confirms the email address.

**Comment by valaparthvi** [comment]
hey @oliverroick , this feature looks interesting and I don't think it has been implemented yet.So if no one else is working on it, I would like to work on it. I haven't figured out the exact way to implement this, but I would like to try. So can I get started with it?

**Comment by oliverroick** [comment]
Hey @valaparthvi, thanks for your interest. 

We haven't defined any requirements nor have we done any design work, which usually precedes the implementation of more complex features like this. There are a lot of questions that need to be considered (e.g. Who can invite users?, What information will be required to create a preliminary user account?, How will the data model for this feature look like? What's the UX for inviting a user, accepting an invitation or rejecting an invitation?). 

Given the lack of information, even very experienced developers will very likely end up with a solution that doesn't address what our users want. I wouldn't start any work on this if I was you until we have clarified the requirements and design.

**Comment by valaparthvi** [comment]
Hey @oliverroick, Even I thought about few problems that you mentioned above and I understand it would be difficult to come up with a solution without having the necessary information. I was interested in the Backend development of this feature, but I guess I'll just wait until requirements and design are clear.

Also, I would like to learn how features like this one are developed from scratch, so is there a way to get involved with the development process?

**Comment by valaparthvi** [comment]
hey @oliverroick, I want to work on this one, or at least try to implement it. If you don't mind, can I plan out a proposal for this one?

**Comment by oliverroick** [comment]
Like I said before, this is quite a complex feature; so before you start writing any code, I would suggest you write up a detailed proposal and think this through from different angles. I would write it up in a Google Doc so it's easier for us to comment on.

**Comment by valaparthvi** [comment]
yes @oliverroick, that is what I was suggesting, creating a proposal. I will start working on it then. Thanks.

**Comment by valaparthvi** [comment]
Hey @oliverroick, I have created a proposal for this feature in a Google Doc. You can check it [here](https://docs.google.com/document/d/1DEisv8wPMxxQUU-7sIvYDgTREnyAUyLuAXv8sa0NwRg/edit?usp=sharing)
Let me know what needs to be changed.

**Comment by dpalomino** [comment]
Items 65.* in the backlog.

**Comment by dpalomino** [comment]
For backlog issues, this is tracked via #1448.

**Comment by laura-barluzzi** [comment]
@dpalomino @valaparthvi @oliverroick I am not sure what's the current discussion over this task. But I can tell that this is a good feature to add and I worked on writing up the draft of a [2nd proposal](https://docs.google.com/document/d/1NiTkv8218v7ynjCHMWoa_IPDVPYuxjjZdEA34rR3oOY/edit?usp=sharing).
I read existing proposals and suggestions, but I believe an approach without a customized link is a bit more suitable for the case.
I thought to share my ideas on how I'd tackle this task, maybe this can help people currently involved in taking the final decision on how to implement this feature.
Feel free to leave comments on the Google doc.

**Comment by clash99** [comment]
@laura-barluzzi This is another related issue: #1532. This one focuses on adding a new user to a project (and by default the organization). The new user would receive an email link similar to your proposal.

**Comment by laura-barluzzi** [comment]
@oliverroick @clash99 it looks like there multiple open issues talking about the same thing. Maybe some issues should be closed, and all the proposals and conversation should be converged into one issue.

**Comment by dpalomino** [comment]
Thanks @laura-barluzzi for the proposal! It looks very good!

I would suggest to use #1448 for tracking all user invites (it's the backlog task). 

Also, I'd like to note the security concerns that @adri raised time ago about inviting users to a project/org not having a Cadasta account (see [here](https://github.com/Cadasta/cadasta-platform/issues/1532#issuecomment-308191684)).

**Comment by oliverroick** [comment]
Duplicate of #1448, closing
