### ISSUE TITLE
Icon lookups for audio files fail

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1013]
### Steps to reproduce the error

In settings, we have defined a `dict` (`MIME_LOOKUP`) to lookup the thumbnail icon for the resource's mime type. The corresponding thumbnail images are stored on our production S3 bucket. 

For of the audio mime types, the lookup will fail because there is not file in the bucket. For mime type `audio/3gpp`there is no file called `3gpp.png` in the bucket.

### Actual behavior

See above.

### Expected behavior

For each of the mime types the corresponding icon file should exist in our production buckets. I suggest to create a generic audio file icon (so far we have mp3 and mp4) the we use for all audio types.

**Comment by clash99** [comment]
Do we just need a 3gpp.png or are there others?  I can also make a generic "audio" png.

**Comment by clash99** [comment]
There is a new 3GPP and AUDIO png added here:  https://drive.google.com/drive/folders/0BzpiEtMtHC3rbXRya0FiVVU2bm8?usp=sharing

Let me know if any others need to be created.

**Comment by oliverroick** [comment]
@clash99 Thanks for preparing those images. 

If we want to have a custom icon for each of the audio types, we'd need create a whole heap of images, [see here](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/settings/default.py#L349-L489). That's why I thought we'd go with a generic audio icon for all the less common formats.
