### ISSUE TITLE
Localize platform in Spanish

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1016]
Spanish is already available [in Transifex](https://www.transifex.com/cadasta/cadasta-platform/language/es/), we should include it in the platform. 

Thanks a lot @clash99 for taking this!

**Comment by clash99** [comment]
Added translation strings from transifex and added Spanish to footer language dropdown.

![screenshot 2016-12-22 10 05 30](https://cloud.githubusercontent.com/assets/1119621/21431963/256d7c34-c82f-11e6-8039-d19953cb0916.png)

**Comment by seav** [comment]
Resolved by #1020
