### ISSUE TITLE
Import will not accept .xlsx

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#1022]
### Steps to reproduce the error

On demo...

- Go to Demonstration of Customary Rights
- Go to Import data
- Try to select an xlsx file that I've used before

### Actual behavior

I get an error that the file type is not accepted. 

![image](https://cloud.githubusercontent.com/assets/3361475/21464713/3d949420-c93b-11e6-8b39-75f665dfba03.png)

### Expected behavior

I expected the file to upload (since it's worked before)

**Comment by bethschechter** [comment]
EDIT: so the problem was that I didn't select xlsx in the options above. However, I think that's a really wonky message to get. It should be, "Select .xlsx above" instead of just "invalid file type." Also, is it necessary for someone to choose which kind of file? Why not simply be able to upload valid file types?

</ .02>

**Comment by seav** [comment]
We are actually considering to remove the file type option in the form in favor of checking the actual filename's extension. Please see the relevant discussion at #976.

**Comment by dpalomino** [comment]
Closing issue as it is dup of #976.
