### ISSUE TITLE
User Roles API Docs: Roles not displaying as described

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#103]
Not sure what the state of this is, but user roles aren't showing up like they do in the docs when I use the `/organizations/<org-slug>/users` endpoint.

This user has `"org_admin": true`, and it works when I test it, it's just not displaying.
```
{
        "email": "email_2@example.com",
        "email_verified": true,
        "first_name": "Breanne",
        "last_name": "Gorczany",
        "username": "testuser2"
},
```

**Comment by oliverroick** [comment]
What branch have you tested this on? The code for user roles API has not yet been merged into master, it's only available in `feature/projects-roles-api`.

**Comment by linzjax** [comment]
Ah that would explain it. I hadn't tested it on the `feature/projects-roles-api` branch, and with the current gutting going on I'll have to wait and test it later...
