### ISSUE TITLE
User Removed from Organization can still submit questionnaires

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1037]
### Steps to reproduce the error

1. Add user to org as Data Collector
2. Download form to ODK
3. Remove user from org
4. Fill out ODK form
5. Submit

### Actual behavior

Data is submitted to the project

### Expected behavior

I would have expected a permissions error

**Comment by dpalomino** [comment]
It seems similar issue to #1036. Permissions are only checked when downloading the form to the app, but not when submitting them to the platform. We will use #1036 to track this, closing issue.
