### ISSUE TITLE
Drop-down menu for active/archived/all projects not appearing in orgs with more than 10 projects

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1065]
### Steps to reproduce the error

1. Go to an organization with more than 10 projects
2. Archive one project (not one of the first 10 projects) 
3. The drop-down menu for active/archived/all projects doesn't appear

See video here: 
https://screencast.com/t/FF7auXqA

### Actual behavior

See above. 

### Expected behavior

Drop-down menu for listing active/archived/all projects should appear when there is at least one archived project.

**Comment by seav** [comment]
Oops. I've submitted a PR for this (#1066) that should improve on the solution of #765.
