### ISSUE TITLE
Options for user behaviour tracking

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1068]
We need to decide what options we have to safely track user behavior throughout our platform without violating our data security policy.

From a ux perspective I would like to start with general task analysis.  This will be a good starting point to compare usability testing with actual platform use.  Going forward this can also be used as a basis for new enhancements and ensure we are properly optimizing.

This affects many groups within the company so I'm putting this as a github task to try to keep track of what we agree to implement.

**Comment by wonderchook** [comment]
should this be a research task for someone to see what the options are out there?

@nastynoel do you have thoughts on this since you were involved in the Terms of Service drafting?

**Comment by nastynoel** [comment]
I don't think this would violate our privacy policy in terms of our collection of the data, or what we use it for, i.e. allowing us to improve the Site and the services we provide, such as by better tailoring our content to our users’ needs and preferences; generating and analyzing statistics about your use of the Site

Information Automatically Collected From You – We and our service providers may automatically collect certain technical information from your computer when you use the Site, such as your Internet Protocol address, your browser type, your operating system, the pages you view on the Site, the pages you view immediately before and after you access the Site, and the search terms you enter on the Site.  This information allows us to recognize you and personalize your experience if you return to the Site using the same computer, or mobile device, and to improve the Site and the services we provide.  We and our service providers may collect this information using “cookies,” which are small text files that the Site saves on your computer using your web browser and accesses when you return, or similar technologies.

**Comment by wonderchook** [comment]
@nastynoel one of the questions was would we collect this information through Google Analytics or a self hosted option.

**Comment by amplifi** [comment]
Google Analytics to be implemented in patch deployment.

**Comment by amplifi** [comment]
Google Analytics is implemented across all environments, configured for anonymizing users.
