### ISSUE TITLE
Delete a party results in Map View of a Project

### ISSUE THREAD

**Issue by manoramahp** [Cadasta/cadasta-platform#1073]
### Steps to reproduce the error

Select a project from projects page
Go to Parties page by selecting Paties from side bar
Select a party
Delete a party
Confirm delete

### Actual behavior

After confirming Delete, the user is redirected to Map view of the Project

### Expected behavior

User should redirect to Parties view of the Project

**Comment by dpalomino** [comment]
Thanks for raising this @manoramahp :-)
