### ISSUE TITLE
Platform user communication - define touchpoints and strategy

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1078]
This is a starting point for a larger discussion.  I've been collecting mostly email messages that have been sent to me from various trial subscriptions I've registered for while doing research.  Its interesting to see how some are leveraging certain user actions on their sites to trigger email messaging to the user.  Although I know we aren't trying to actively solicit, I think we are missing a lot of opportunities to engage and retain users.

- First we need to define what we want those touchpoints within the platform to be.
- Second we need to decide on what we want our communication to be at those points.

Initial thoughts of user actions we should be communicating on:
- After registration
- 10(?) days after completing registration but nothing else
- 3(?) days after a failed attempt at project creation
- 1(?) day after a new project has been created 

Here is a folder to drop in communication samples collected along the way:  https://drive.google.com/open?id=0BzpiEtMtHC3rT0tHZ2hrUnhMVTQ

There is not an immediate need for this but more of something to be thinking about.

**Comment by SteadyCadence** [comment]
My end goal is to send out emails for onboarding users. The users in Cadasta come to us with different experiences on the platform (demo vs survey created vs stumbled upon). 

This first email would require some logic (whether they have received a training or not).

For example, if they have recieved training and have the survey ready-to-go:

```
Hello {user_name},

We are so excited to have you on the Cadasta platform!  You should have received a confirmation email with a verification link.  Please click on this link within the next 48 hours to confirm your account.

To begin collecting data*, you can start by using either of these three Android apps:
- (GeoODK)[https://play.google.com/store/apps/details?id=com.geoodk.collect.android]
- (ODK)[https://play.google.com/store/apps/details?id=org.odk.collect.android]
- (KoboToolbox)[https://play.google.com/store/apps/details?id=org.koboc.collect.android]
*these all require an Android phone or tablet
 
After installing either of the apps, you can sync up the Cadasta platform through these main steps: 
 
1. Go to Settings (from the main menu) > General Settings > Configure platform settings
2. Configure URL, Username and Password here: 
    URL: https://platform.cadasta.org/collect**
    Username: (your username or your mail address)
    Password: (your password)

** It is very important that you include "https" and not "http".  If you would like to test out the platform, then use  "https://demo.cadasta.org/collect" as the URL.
3. And then go back to the main menu. To check that everything is ok we can go to Settings > Form Management, and see if there is a list of available forms here (first I need to create the accounts). 
```

**Comment by wonderchook** [comment]
We should keep in mind that though lots of our users either are having data imported or are using mobile phones that they could also do paper data collection. I don't think we want people to make an account and then think "oh I can't use Cadasta I don't have an Android". 

Also have we tested KoboToolbox with the platform? If not we shouldn't be recommending it.

**Comment by clash99** [comment]
I'm closing this since marketing has started a project defining our user communication.
