### ISSUE TITLE
Change cluster tolerance (increase the threshold that clusters require to bring in points)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1084]
I think this is the cartographer coming out in me, it is quite difficult to view the distribution of data when there are so many clusters.  

The easiest, most straightforward recommendation would be to increase the clustering tolerance so that more markers appear without clusters when you zoom in.

**Comment by clash99** [comment]
@SteadyCadence - I can make this change but it would be helpful if you could provide a link or screenshot so I could make sure I'm make the correct adjustment.

**Comment by SteadyCadence** [comment]
@clash99 I'm thinking we could wait until the new map features are out. So maybe address this issue then? Or maybe we could screen share next week. I can show some example projects where the clustering tolerance is not ideal.

**Comment by dpalomino** [comment]
> @clash99 I'm thinking we could wait until the new map features are out. So maybe address this issue then? Or maybe we could screen share next week. I can show some example projects where the clustering tolerance is not ideal

Yes, I agree with that @SteadyCadence. 

cc @linzjax for her info.

**Comment by linzjax** [comment]
I had been asking about this because a fix that I made to one thing broke clustering. I wanted to make sure before I put too much time into fixing it whether or not we would want to keep using it in the future. I'm going to continue to try and fix it, if for no other reason than my pride, but it we have strong feelings about it one way or the other that would be good to know.

**Comment by linzjax** [comment]
So the one thing I will say, having now (sort of) fixed it, is that including deflate/clustering in projects that have a couple thousand records causes my browser to slow down so much it crashes. It's possible I'm just not going about it the right way, but it's pretty rough.

**Comment by SteadyCadence** [comment]
@linzjax If it is slowing down the map loading, I would skip fixing that for now....  There are mainly two use cases for clustering:  improving map performance and showing how many overlapping points there are in one area.   There are not too many use cases with the latter option, so I think we can temporarily skip clustering for the time being... unless someone has any other opinions.  @wonderchook @dpalomino @oliverroick

**Comment by wonderchook** [comment]
The performance reason would be server side clustering so I think we can wait on that.

**Comment by clash99** [comment]
Sounds like this task can be closed based on comments here and our discussion in the dev meeting this morning.  I'm closing and we can re-open in the future if needed but with the new smap, it would probably be related to that project.
