### ISSUE TITLE
Show password option 

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1087]
Related to #735 and #967, we should implement an option to toggle the view of the password input when registering.  

Backlogid 36.03.

**Comment by sunnypalace** [comment]
Hi, I would like to take this up issue. I will implement it and will post a demo screenshot before submitting the PR soon.
Thanks.

**Comment by Shruti9520** [comment]
PR- #1151

**Comment by Yash17Agrawal** [comment]
Please close this issue if completed . @dpalomino
