### ISSUE TITLE
Minor Import Annoyance :: "Location_type" wants to map to "party_type"

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1090]
### Steps to reproduce the error

Click Import and go through Step 2 of the import process.  

### Actual behavior

"Location Type" matches with "party_type".

### Expected behavior

I expect "Location Type" to map to "location_type".

Github doesnt let me upload CSVs so let me know if you need a file reference. 
![screen shot 2017-02-01 at 4 22 01 pm](https://cloud.githubusercontent.com/assets/25337622/22531495/638bbb72-e89e-11e6-9869-698b947f3cd6.png)

**Comment by Sanny26** [comment]
Can I get a file reference to reproduce that form?

**Comment by SteadyCadence** [comment]
Hi @Sanny26,

Here is a test form:

[UrbanInfrastructure.xlsx](https://github.com/Cadasta/cadasta-platform/files/800081/UrbanInfrastructure.xlsx)

... and dummy csv for you to use. (GH doesn't allow me to upload csvs, so you will have to convert it from a txt file)
[urban-infrastructure-v2.txt](https://github.com/Cadasta/cadasta-platform/files/800092/urban-infrastructure-v2.txt)

Let me know if you have any questions on the form and import process.

**Comment by Sanny26** [comment]
Hi @SteadyCadence,
Thanks for providing the info I needed. After looking at the template for the form, default is chosen if it has 'type' as a substring. In this particular case, party_type is encountered at the end of the list, so party_type is mapped to that location type. Could you suggest me how I change the behavior?
 If 'location' is in headers is checked/searched for, instead of 'type', is that an appropriate solution?

**Comment by SteadyCadence** [comment]
@sanny26 sorry for the delay! Good question. I would recommend having the exact matches (with spaces stripped on the end and beg in case someone imports spaces in the headers). So 'location_type' matches to 'location_type' and 'party_type' matches to 'party_type'. The reason for that is because users may import multiple 'location' or 'party' fields and so for now exact matches are the best solution. 

Further down the line we can consider smarter matching for imports.

**Comment by Sanny26** [comment]
@SteadyCadence Can you look at this if- else block in the template https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/organization/project_defaults_import.html#L35

So, are you suggesting me to remove the if-else block and just print 'location-type' and 'party_type' ?

**Comment by SteadyCadence** [comment]
Now that I think about it, that code was set up so that it supports the ability of a user to export out of a Cadasta project and then use that file to import into a new project. 

The export may need to be adjusted before this annoyance can be solved because both the "location type" and "party type" are both labeled "type" in the export files. 

For now, you can adjust the code so that the if statement is still in there but it uses "location _type" instead of just "type" for field mapping. Ultimately, I want to see functionality where if I have a CSV header named "party type" it maps with "party_type" and same with " location type".

**Comment by Sanny26** [comment]
@SteadyCadence I opened  a PR. With the changes I made, it works as expected for urban-infrastructure-v2.txt. However, for UrbanInfrastructure.xlsx party_type and location_type are mapped to a random field since both the files have 'type' as field. I assume that this file could be an exported file.
