### ISSUE TITLE
Minor responsive issue :: Change order of divs (contact vs projects) on org pages

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1092]
Super minor issue... Just something that's been bothering me... 

Go to an org page on a mobile phone and observe contact info first before project list. 

![screenshot_20170202-165425](https://cloud.githubusercontent.com/assets/25337622/22573995/3add9ae4-e969-11e6-85f3-81038e40b359.png)

![screenshot_20170202-165431](https://cloud.githubusercontent.com/assets/25337622/22574000/407fdd5e-e969-11e6-9929-6c762bed2a1f.png)

A majority of times that someone is viewing the org page from their mobile is for getting into projects. 

Can we swap the scroll hierarchy of the divs? And have projects listed before contacts?

**Comment by yoshi2095** [comment]
Hi @wonderchook,
I have fixed this bug and made a pull request : https://github.com/Cadasta/cadasta-platform/pull/1145. Please review. Thanks

**Comment by clash99** [comment]
@SteadyCadence - This has been fixed and should be reviewable in the next release to staging.  Feel free to reopen at that time if it isn't as you intended.  Thanks!
