### ISSUE TITLE
Update standard cadasta questionnaire in repo

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#1096]
The standard cadasta questionnaire in the repo is out of date and should be updated to reflect the current standard questionnaire at https://s3-us-west-2.amazonaws.com/cadasta-resources/sample-forms/standard_cadasta_questionnaire.xlsx

**Comment by seav** [comment]
I think fixing this also fixes #1052?

**Comment by dpalomino** [comment]
Hey @seav. #1052 is already fixed (it was updated in the S3 bucket where the online documentation links to. I just maintained this open to update a couple of screenshots and texts in the online doc.

**Comment by bjohare** [comment]
I submitted a PR for this yesterday but made a mess of it so I closed it. I'll fix this as part of a PR for #1098
