### ISSUE TITLE
Registering with an email that is no longer associated with an account throws an error

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1102]
# Outreachy/GSoC candidates: A PR for this issue has been approved and is waiting to be merged.

### Steps to reproduce the error
- Create a user profile (i.e. example@example.com)
- Edit profile and change email address (i.e. example_email@example.com)
- Register a second user using first password (example@example.com)

### Actual behavior
- Happy little platform error:
```
IntegrityError at /account/signup/
duplicate key value violates unique constraint "account_emailaddress_email_key"
DETAIL: Key (email)=(example@example.com) already exists.
```

### Expected behavior
- I would assume that they should be able to use the 'released' email.

**Comment by py-geek** [comment]
I would like to work on this ticket.

**Comment by wonderchook** [comment]
@py-geek great! Go at it (looks like you already have)

**Comment by py-geek** [comment]
@wonderchook Yes, I have submitted a PR for review. Thanks.
