### ISSUE TITLE
Usernames should be case insensitive when checked in password

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1105]
1. Register
2. Create username in this example: bobby
3. Add password "bobby1234!" cannot save user because username is in password
4. Try "Bobby1234!" user is saved

We should be case insensitive when checking for usernames in passwords.

**Comment by shailysangwan** [comment]
Can you please assign me to this issue?
I have a pending PR which if merged, will cause a merge conflict if I start working on this now.

**Comment by wonderchook** [comment]
More than one person is free to try to solve an issue at time. Whether a pull request is accepted will not be the only basis of determining the success of your outreachy application.

**Comment by wonderchook** [comment]
@saurabhgoyaliitr there are multiple pull requests open for this ticket. You are certainly welcome to work on it, but it is unlikely to get merged into the master branch. I would suggest working on another ticket that doesn't already have multiple solutions for it.
