### ISSUE TITLE
Changing user from admin should leave you on the Member Permissions Page

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1106]
Currently if you change a user from an Administrator to an Organization Member after confirming the change it takes the user to the Organization Members List Page. I would expect the user to be left on the individual member page so the user has the opportunity to assign the individual permission by project to the "downgraded" user.

**Comment by oliverroick** [comment]
@clash99 Would it make sense to always stay on the members page after updating the roles. The current solution in the PR only stays on the page when the user was downgraded from org admin to org member and redirects to the org members list in all other cases. I think the behaviour should be consistent; what do you think?

**Comment by clash99** [comment]
@oliverroick and @wonderchook:  I agree.  After a role change, the user should stay on the member page.  

Here is a quick flow:

![orgmember-rolechange](https://cloud.githubusercontent.com/assets/1119621/23709172/32e16fc0-03de-11e7-890f-92e48a5baf2f.png)

**Comment by clash99** [comment]
@dpalomino I think this could be first-contributor friendly.  What do you think?

**Comment by oliverroick** [comment]
@clash99 So when you just save the project permissions and don't change the org membership, you're redirected to the members list? — There's already a PR for that, which is almost ready, we actually need to clarify that.

**Comment by Sanny26** [comment]
Following

**Comment by clash99** [comment]
@oliverroick sorry for the delay - just saw this.  Yes, the Save button should redirect to members list.

**Comment by oliverroick** [comment]
👍  The PR is approved!
