### ISSUE TITLE
Possible to Create Duplicate Resource Entries

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1107]
### Steps to reproduce the error
1. Click "Add Resource"
2. Select "Upload New"
3. Click "Choose File"
4. Select file for upload
5. Name the Resource
6. Click Save quickly a few times

### Actual behavior

The result is multiple resources. They all point to the same file on S3, but there are duplicate database entries. 

### Expected behavior

I would have expected to only be able to submit the resource 1x. After clicking submit the button should be disabled to prevent additional submissions.

**Comment by laura-barluzzi** [comment]
Hi @wonderchook , I'd like to fix this bug as part of the Outreachy project. I'm thinking to add just a bit of Javascript to disable the attach button after you click it. Does that sound like a reasonable approach?

**Comment by wonderchook** [comment]
@laura-barluzzi yes exactly, to make it not possible to click the button a bunch of extra times.
