### ISSUE TITLE
Placeholders for missing values when adding or editing parties

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#1108]
### Steps to reproduce the error

Add a new party which has non-required attributes defined in the project schema (using standard questionnaire for example). When the party is saved with missing values there are no placeholders shown on the party detail page. In particular the value `None` is shown for `date` fields.

![party_detail](https://cloud.githubusercontent.com/assets/3308136/22795883/2ddac894-eef0-11e6-81f4-d240dad5333b.png)

### Actual behavior

No placeholders.

### Expected behavior

Empty values on Party detail page should show placeholders, eg `--` when there are missing values.

**Comment by dvlshah** [comment]
I have a possible solution.Can you tell me where party details is written in code?

**Comment by oliverroick** [comment]
@dvlshah This issue is a bit more complex. We don't recommend this for first contribution because it required changes to `jsonattrs`, which we use to manage `jsonb` fields.
