### ISSUE TITLE
Functional testing for user management pages

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#111]
Whoever does this will need to:

1. Develop some ideas for test scripts.
2. Implement a page class for the user management page.
3. Write test scripts.

The sort of things you'll want to test include:

 - Permissioned and non-permissioned attempts to access the user management page.
 - Sorting, searching, pagination on the user management page.
 - User activation and deactivation.

You could implement a complete set of interactions: register a new user and login, then logout; login as an administrative user and deactivate the newly created user, then logout; attempt to login as the deactivated user (you should see a page saying something like "This user is not active").

**Comment by ian-ross** [comment]
@seav What's the current status of this?  I see that you've checked in some tests and have moved on to tests for the projects UI.  Is the code in your `testing/users-ui` branch ready for review?  Would you like to make a PR?  I've suggested to @linzjax that once you've both got some working functional tests going, you can talk together and come up with some ways to refactor the functional testing framework: I set that up more or less blind, without any tests as examples to work with, so it would definitely benefit from some reorganisation by people who've been writing real functional tests!  We could merge your current user UI tests, then you could rework them when you decide with Lindsey how to make things better.

**Comment by seav** [comment]
I still have to check in a couple or so tests. I just created the branch for projects UI with the intent of doing similar tests in parallel.

**Comment by seav** [comment]
By the way, it seems that the pagination, sorting, and search features are provided by the [DataTables plugin](https://datatables.net/). I don't think we need to make functional tests for these features since we are not really testing functionality provided by our own code. Just as long as we verify that the correct and complete data is provided to the front-end, I think we can assume that the plugin works as advertised ("backed by a suite of 2900+ unit tests").

**Comment by ian-ross** [comment]
OK, sounds good!  I think I agree with you about the data tables, except for one thing: the reason they have "2900+ unit tests" is because there are so many configuration options, which means it's really easy to set them up in a way different from what you want.  That's the only sense in which it would be reasonable to have tests that check the functionality of the tables.  I think we can defer writing tests like that for now though.  The time to add them is probably when we start trying to do server-side pagination, and there's no point in doing that until we have enough data in the platform to make it necessary.

**Comment by seav** [comment]
Yeah, I was meaning to eventually ask regarding server-side pagination, sorting, and searching. If the amount of users, projects, or organizations is small, it makes sense to implement these features on the frontend. But when the data is huge, these eventually need to be done on the backend.

**Comment by ian-ross** [comment]
That's right.  The data table widget we're using supports server-side pagination via Ajax calls.  It's just a matter of setting it up (we can use the API endpoints to do it, obviously).  But as you say, for an initial implementation where the data volumes are low, client-side processing is simpler.  (We'll probably have to do the server-side stuff as soon as we deal with parties, parcels and relationships, because those will immediately have many more entries than the project or organisation lists.)
