### ISSUE TITLE
Search text & css changes

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1110]
Shorten update text and adjust spacing to left of image in list to match left table padding.
<img width="1158" alt="screenshot 2017-02-09 14 35 14" src="https://cloud.githubusercontent.com/assets/1119621/22802221/96cf4cc8-eed5-11e6-9938-44f26b15cc82.png">
<img width="1145" alt="screenshot 2017-02-09 14 35 24" src="https://cloud.githubusercontent.com/assets/1119621/22802220/96cc3f92-eed5-11e6-93f5-bf7e565f83c5.png">

**Comment by wonderchook** [comment]
Shorten update text to "Search was last updated on...."?

**Comment by clash99** [comment]
Simplified text on search:

- From "Search index was lasted updated on" to "Last updated on"
- From "We’re sorry, it seems the search index is currently not available" to "We’re sorry, search is currently not available"
- Add margin to left of resource thumbnail to align with other search result details

**Comment by oliverroick** [comment]
Can this be closed; the PR is merged?

**Comment by dpalomino** [comment]
Yep, it seems it is: 

![screen shot 2017-02-10 at 11 35 30](https://cloud.githubusercontent.com/assets/17198051/22823722/1aa207fc-ef85-11e6-8c84-2c3bf3c5b7f2.png)

**Comment by dpalomino** [comment]
Already fixed, closing the issue.
