### ISSUE TITLE
API: Can created an organization with no users

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1114]
# Outreachy/GSoC candidates: A PR for this issue has been approved and is waiting to be merged.

### Steps to reproduce the error
- `http POST https://platform-staging.cadasta.org/api/v1/organizations/ name='API Created Organization [Anonymous]'`

### Actual behavior
- Creates an organization with no users or owner.

### Expected behavior
- Should require an actual user.

**Comment by Yashwanthv21** [comment]
Can you help me reproduce this bug, in local environment.

**Comment by linzjax** [comment]
Do you have your local environment set up? If so, pip install httpie, run the server, and then run the line of code listed in the issue.
