### ISSUE TITLE
Search only matches on exact strings

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1118]
### Steps to reproduce the error

Open any project, search for any partial term. Example: Project "Chocolate Factory" contains a party named David.

### Actual behavior

Search returns zero results if there is no match for the exact string entered. Example: Searching "Chocolate Factory" for davi returns zero results.

### Expected behavior

According to the requirements in #826, an exact string match should be conducted iff the search term is enclosed in quotation marks. A string entered without quotation marks should return the results that best match. Example: Searching for davi without quotes should return the party named David.

**Comment by dpalomino** [comment]
Thanks @amplifi for raising this and for all the explanations :) 

@seav (see discussion #search channel) Do you think we could change this in Sprint 14?

**Comment by khantaalaman** [comment]
@dpalomino @amplifi Is the issue still persisting? It seems to be fixed to me.

Thanks!

**Comment by amplifi** [comment]
@khantaalaman This issue has not yet been fixed.

**Comment by laura-barluzzi** [comment]
Hi @seav, is this issue still open? I tried to use the search after entering inside my project but it looks like the search doesn't work with exact string either now.. it doesn't find any party name and resource name. Did it use to work for any exact string?
