### ISSUE TITLE
SMAP: Implement replacement for LeafletWidget

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#1124]
Part of Map Single Page App (https://github.com/Cadasta/cadasta-platform/issues/1031)

### Task

We need to keep our dependency on `django-leaflet` for the project creation wizard. For SMAP `django-leaflet` appears to break vector tiles so we need to implement location creation and editing for SMAP separately. This issue is intended to capture that work.

**Comment by oliverroick** [comment]
Let's be honest; we'll never dig this up from the graveyard of unfinished work. Closing.
