### ISSUE TITLE
Resources: Support more MIME types

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1135]
Updating the whole list of file types to be supported: 

Just drafting a list here for discussion:

Audio: 
- .mp3 (supported)
- .m4a (supported, but not listed)
- .mpa
- .ogg
- .wav
- .wma

Spreadsheet like: 
- .csv (supported)
- .xlsx (supported but not listed)
- .xls 
- .ods

Documents: 
- .docx (supported)
- .doc (supported)
- .odt 
- .rtf
- .txt

Presentation: 
- .ppt
- .pptx
- .key
- .odp

Images: 
- .jpg (supported)
- .png (supported)
- . jpeg (supported but not listed) 
- .bmp
- .gif
- .ps
- .svg
- .tif
- .tiff

Videos: 
- .mp4 (supported)
- .3gp
- .avi
- .m4v
- .mkv
- .mov
- .mpg
- .mpeg
- .wmv

----

There are some partners interested being able to upload Open Office formats: 
- .odt
- .ods
- .odp

BTW, is there any reason why we don't want to allow uploading many other file types? (.ppt, .pptx, .zip, etc?)

If there isn't I could propose a list with the filetypes... wdyt?

Thoughts @wonderchook, @bjohare ?

**Comment by amplifi** [comment]
The more file types we allow for upload, the more potential vulnerabilities and attack vectors. I would exclude .zip for sure. We should continue to operating on a whitelist basis.

**Comment by dpalomino** [comment]
Ah, ok, I can draft a list for this in addition to the Open Office formats and maybe we can review... Thanks!

**Comment by wonderchook** [comment]
Are there reasons that people can't just convert to PDF? I think supporting some Open Office formats is fine, but I'm wondering what they plan to do with the files once they upload them.

**Comment by dpalomino** [comment]
I think it's just because it is the format that they usually use (in the case of this particular partner). If there is a partner with many documents/resources that wants to upload to the platform, convert all of them to pdf could be time consuming for them. For those that there would not be a security thread I think we could include them... 

Just drafting a list here for discussion: 

Audio: 
- .mp3 (supported)
- .m4a (supported, but not listed)
- .mpa
- .ogg
- .wav
- .wma

Spreadsheet like: 
- .csv (supported)
- .xlsx (supported but not listed)
- .xls 
- .ods

Documents: 
- .docx (supported)
- .doc (supported)
- .odt 
- .rtf
- .txt

Presentation: 
- .ppt
- .pptx
- .key
- .odp

Images: 
- .jpg (supported)
- .png (supported)
- . jpeg (supported but not listed) 
- .bmp
- .gif
- .ps
- .svg
- .tif
- .tiff

Videos: 
- .mp4 (supported)
- .3gp
- .avi
- .m4v
- .mkv
- .mov
- .mpg
- .mpeg
- .wmv

**Comment by wonderchook** [comment]
@amplifi are there any of these formats above that are scarier than others?

**Comment by amplifi** [comment]
@wonderchook The list above should be ok, in the context of secure implementation:

1. validating file name before upload
2. validating file contents and size before upload 
3. setting appropriate maximum file size limit(s)
4. upload processing async/decoupled from the platform
5. scanning of all uploads for malicious content

1, 2, & 3 will need to be handled on the platform side. 4 & 5 we have in progress as part of the async I/O refactor. Basically, we need to make sure that every file uploaded is what it claims to be, isn't so large as to cause performance problems (either on upload or on viewing/export later), and isn't likely to contain executable or malicious code.

**Comment by dpalomino** [comment]
Thanks @amplifi. In terms of file size, which limit do you recommend?

**Comment by amplifi** [comment]
@dpalomino This will depend on users' needs and available bandwidth. Even if we use S3's multipart upload and configure a browser upload policy to restrict file size, some of the files on the list can be quite large -- especially if users aren't familiar with working in these formats or optimizing for the web. The vast majority of existing resource files are under 5MB, with a few at 10-15MB, then one extreme outlier PDF at 47MB. In light of this, I would recommend a file size max of 10MB, possibly increasing to 15MB in the future if there's enough need expressed to warrant the overhead. The larger the files, the longer it takes to transfer, scan, process, and export them.

**Comment by dpalomino** [comment]
Thanks @amplifi! Can we customize this per file type? For most formats I think 10/15MB would be enough, but I can imagine audio and specially video files being larger than that...

**Comment by amplifi** [comment]
@dpalomino No, the S3 policy doesn't support dynamic file size limitations. While we could implement a custom dynamic file size limit on the django-buckets side, we really should have the limits match consistently throughout the process flow.

**Comment by dpalomino** [comment]
Agreed with @amplifi to try to include this in the next sprint (to be confirmed, tentatively assigning to Sprint 16), with the list of file types mentioned above. We can use 10MB as a file size limit for now.

**Comment by dpalomino** [comment]
Hey @linzjax. Do you think you could take care of this issue during the next sprint? Please, ping me if you need to clarify... thnks!

**Comment by linzjax** [comment]
@dpalomino Do you have sample files you could send me?

**Comment by linzjax** [comment]
Or wait, @bjohare are you working on this now?

**Comment by dpalomino** [comment]
Hey @linzjax, yes I think @bjohare is working on this issue. It is just to add the MIME types in the whitelist (the list described in the first comment). Thanks!

**Comment by dpalomino** [comment]
Regarding the text to show when uploading a new resource: 
![screen shot 2017-06-28 at 20 51 20](https://user-images.githubusercontent.com/17198051/27654868-ac9810cc-5c43-11e7-9e6c-316de310c9d1.png)

I think we cannot include the whole list, it is too long. Maybe we can include something like: 

"You can upload images, audios, videos, documents (including pdf's, Office and Open Office), spreadsheets (Office and Open Office), and presentations (Office, Open Office and Keynote). You can check the complete list [here](https://docs.cadasta.org/en/04-records.html#project-resources)."

What do you think @bethschechter? We'd need also to update the online documentation.

**Comment by oliverroick** [comment]
@amplifi @alukach — I opened a [PR for django-buckets](https://github.com/Cadasta/django-buckets/pull/32) that implements the file-size limit. Could you both have a look?
