### ISSUE TITLE
Staging on demand

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1136]
Create internal developer UI for generation of staging environments on demand, such that:

- launch will spin up an isolated staging environment
- with choice of GitHub branch for deployment
- with choice of database (blank, staging, demo) for backend
- branches should pass all tests in Travis to be permitted to deploy to staging
- environments not torn down via the UI will expire after a duration to conserve resources and cost
- the developer who launches the staging environment will have SSH access to that environment

This implementation will remove the need for coordination of isolated branch testing and testing against staging/demo/production backends, and improve identification of bugs during the QA process via use of real data sets.

**Comment by wonderchook** [comment]
This sounds great! How will we determine when it gets shutdown? Just worried about the AWS bill if we have a ton of these up at a time (we still should do this).

**Comment by wonderchook** [comment]
Oops I see you did answer my question. We'll have to determine what is a good number for that. What about setting a duration when it is launched?

**Comment by amplifi** [comment]
@wonderchook I was thinking of using containers rather than a new EC2 instance per user, so we could run multiple isolated staging envs per instance (or possibly all envs in one instance), then when the last container on an instance is shut down, it stops the instance (we only pay the cost of volume storage for a stopped instance). We could also potentially replace the dev VM with a local container down the road.

**Comment by amplifi** [comment]
@wonderchook I like the idea of setting a duration when you launch! I could implement choice from a given range, like 30 mins to 48 hours, with a default value of 2 hours or something.
