### ISSUE TITLE
Change of email process security updates

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1140]
### Steps to reproduce the error

Go to Edit Profile and change the email address on a user account

### Actual behavior

The user is not prompted to verify their password to confirm identity before submitting change of email address.

A confirmation email is sent to the new email address, which includes the account username.

The new email address is applied to the account upon form submission (before it is verified via the link in the confirmation email). This means anyone who accesses a user account can change the email address and the user would not be alerted, or the user could change to an incorrect/invalid email address and have no way to recover their account.

### Expected behavior

- [x] The confirmation email sent to the new email address should not include the username for security purposes.

- [x] The user's email address in the database should not be updated until after the user clicks the verification link in the confirmation email.

- [x] A separate notification email should also be sent to the old address. In the event of unauthorized changes, this will alert the user to the change.

- [x] The notification email to the old email address should advise the user to let us know immediately if this change was not authorized, and provide them with a contact method.

**Comment by dvlshah** [comment]
I have solved "The confirmation email sent to the new email address should not include the username for security purposes." part of problem.
I am not able to understand how to solve the second issue that user's email address should not be updated until verification.Can someone please me guide how to approach this.?

**Comment by oliverroick** [comment]
Changing the email address and sending the verification email happens [here](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/accounts/forms.py#L67-L108) for the website and [here](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/accounts/views/api.py#L17-L34) for the API.

**Comment by dvlshah** [comment]
I have changed code for following behavior.Can I make a pull request? Also it passed all tests in "runtests.py" in vagrant directory. 

- The confirmation email sent to the new email address does not include the username as mentioned for security purposes.

- A separate notification email is sent to the old address. If the event of unauthorized changes occurs, this will alert the user to the change.The notification email to the old email addresses  advise the user to let us know immediately if this change was not authorized, and contact method is provided in email itself.

**Comment by rjain111** [comment]
Hi @amplifi @oliverroick 
I was going through this issue and I wanted to ask if it would be nice to create a separate view for changing email where the user would be asked to enter the current password and only after the password entered matches with the user's password, a confirmation mail will be sent to the new email.
If we follow the method as mentioned in the issue, we probably would have to change our DB structure and save both the new email and current email, though I am not sure about it. It would be nice if you could share more information about it.

**Comment by oliverroick** [comment]
Hi @rjain111 thanks for your interest in fixing this issue. Fully addressing this issue requires some design work and planning upfront, which haven't completed yet. That's why we haven't tagged this issue for as first-contribution friendly.
