### ISSUE TITLE
Search textbox spans over so the map moves to right (Chrome)

### ISSUE THREAD

**Issue by manoramahp** [Cadasta/cadasta-platform#1143]
### Steps to reproduce the error

Open a project in Chrome browser

### Actual behavior

Search textbox spans over the entire width so that the map moves to the right side.
![image](https://cloud.githubusercontent.com/assets/10743861/23100091/6e715968-f69d-11e6-9022-b0f51c25e501.png)

### Expected behavior

Search textbox should behave as a layer on top of map when click on left tab Search button (As in firefox browser)

**Comment by SteadyCadence** [comment]
I ran into this issue as well.  You need to clear your *cache*/browser history and it should fix that.  I think only the Cadasta team run into that issue ;) . 

At least I hope none of the current users are running into this...

**Comment by dpalomino** [comment]
Hi @manoramahp, can you please check if the issue is fixed when clearing the cache? Thanks!

**Comment by manoramahp** [comment]
This is no longer there after clearing the cache. Therefore closing the issue.
