### ISSUE TITLE
Search: Clear textbox 

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1147]
We currently have not implemented yet the "Clear textbox" that should be on the right side of the search box (see wireframes [here](https://drive.google.com/file/d/0BzpiEtMtHC3rVFlVelgzNHBxaUk/view)), page 5. Of course not a high priority but it'd be nice to include this to improve usability. 

Screenshot: 
![screen shot 2017-02-21 at 11 59 13](https://cloud.githubusercontent.com/assets/17198051/23162338/e3fa1e7c-f82d-11e6-9469-51554ab634a6.png)

**Comment by dvlshah** [comment]
Can you help me find search template in code so that I can add functionality to it?

**Comment by oliverroick** [comment]
There's a directory called `templates`.

**Comment by brymut** [comment]
Hi, is anyone still working on this issue?

**Comment by oliverroick** [comment]
@brymut There are two active PRs, which we are currently reviewing. No need to get started with this.
