### ISSUE TITLE
Search: clicking on search panel should go to the top of the page?

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1148]
This is a really low prio issue, just in case it could improve usability. 

Steps to reproduce: 
1. Execute a search query resulting in many results
2. Going to the end of the query list (where the pagination is)
3. Click on search icon on the left panel. 

Current behaviour: 

Nothing happens

Expected behaviour: 

I think if the user would be redirected to the top of the page (where the search box is), usability would be better. 

What do you think @clash99?

**Comment by clash99** [comment]
@dpalomino sounds good - perhaps this would be first-contribution friendly?

**Comment by dpalomino** [comment]
> @dpalomino sounds good - perhaps this would be first-contribution friendly?

Great idea. Adding label :-)

**Comment by jinankjain** [comment]
@dpalomino I was looking at bug status. Right now I don't find any search button. Do you want to create a search button and link to search at the top.

![screen shot 2017-02-24 at 1 50 22 pm](https://cloud.githubusercontent.com/assets/3854904/23304117/5e8757b0-fa98-11e6-9e0b-26373f1439c0.png)

**Comment by Sarthak30** [comment]
Hi, 
I am new here. As a beginner, I would love to solve this bug. Please, guide me how to get started with project setup.

**Comment by oliverroick** [comment]
@jinankjain This is referring to the button in the left-hand side menu:

![screen shot 2017-02-28 at 09 43 31](https://cloud.githubusercontent.com/assets/159510/23397841/6f7c43c8-fd9a-11e6-940f-f00309d5c1b6.png)

**Comment by oliverroick** [comment]
@Sarthak30 Please have a look at the repository's README, it contains instructions how to set up the development environment

**Comment by dvlshah** [comment]
@oliverroick Do we have to add search button that remains on left hand side when user scroll down project lists and when user clicks it ,it should redirect it to top search bar?

**Comment by oliverroick** [comment]
@dvlshah This applies only to the search in a project. I.e. when you click search (see the screenshot above), you enter a term, you are being redirected to the page with all results, you scroll down and when you click the search button again you will stay on that page but the page jumps back to the top where you can enter a new search.

**Comment by maitreyaverma** [comment]
I have added a pull request that fixes this issue. Looking forward for your feedback on it.
