### ISSUE TITLE
(This is a work in progress... ) Cartography Considerations :: List of Items for Discussion and Improving (WIP)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1150]
I am compiling a list here and then will break each item out into separate issues once it is determined it is worth working on. 

- [ ] Change Color of Polygons :: blue for polygons is not recommended unless it is a water body-- as blue is the universal color of water.  I also think it would be good to get a color that works well with the OSM/vector maps as well as sticks out on the satellite imagery. There are a number of resources (big fan of https://carto.com/academy/courses/intermediate-design/choose-colors-1). Some colors like: 
<img width="70" alt="color options" src="https://cloud.githubusercontent.com/assets/25337622/23183636/f831c668-f839-11e6-9490-d214338b0ec8.png">

- [ ] Change marker icons to point icons :: This suggestion is so that the map interaction and clicking is more accurate and precise.  The markers are quite large, and especially is high density, urban areas, it can be difficult to tell what lat/lng the marker is meant to represent. 

- [ ] Remove zooming and centering on marker when user clicks through to information page about that point :: minimize map movement

- [ ] Baselayer issue (bug?)  :: When you select the satellite imagery and then use the platform, the map changes back to OSM when you go to another page.  It should stay on satellite as that is what I selected last. 

- [ ] Clustering tolerance and colors :: needs discussion.  Maybe change the tolerance on different zooms?  This one is tricky because we need good project examples. 

- [ ] Large data loads and map performance ::

**Comment by wonderchook** [comment]
@SteadyCadence some of these things already have related tickets (large data loads and map performance for one). @linzjax's work turning the map into a single page application I believe will change some of the interactions as well. 

I don't read any of these as feature requests, but if you do have those as well they belong in the backlog that @dpalomino keeps.

**Comment by SteadyCadence** [comment]
Hey @linzjax, do you want to talk about some of these items next week and then I can close this issue?

**Comment by wonderchook** [comment]
@SteadyCadence, perhaps I was not clear. The reason some of the team is meeting in SF next week is to review the map interactions, so I don't think it is necessary for you and @linzjax to discuss separately at this time. In due time we will be asking for feedback.
