### ISSUE TITLE
Hardcoded S3 paths

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1155]
Hardcoded S3 bucket paths appear across multiple files: https://github.com/Cadasta/cadasta-platform/search?utf8=%E2%9C%93&q=platformprod&type=Code

This results in all environments (staging, demo, and production) hitting the production S3 bucket, which violates our isolation requirements. It also exposes the bucket names.

We should remove hardcoded references to bucket names/paths and change bucket names ASAP. We should also avoid commingling static assets like platform icons with project data, to allow for stricter security policies.

**Comment by Yashwanthv21** [comment]
Any ideas how to change this?
