### ISSUE TITLE
Input fields should be sanitized to exclude code

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1157]
**TEST IN LOCAL DEVELOPMENT VMs ONLY**

**Do NOT test this bug on any of the live servers**

### Steps to reproduce the error

Create an organization, project, party, resource, etc. Set the name to be a snippet of code (html, js, sql, Excel macro, whatever you like).

### Actual behavior

Value is accepted and stored in the database. Code can then be retrieved from database (example: can be exported along with all project data into an export file, and possibly executed on a user's local machine)

### Expected behavior

All input should be sanitized on a whitelist basis to exclude possible code and characters required for code. Entity names containing code should be rejected and not stored in the database.

**Comment by amplifi** [comment]
In case it's not obvious, **do not test this bug in staging, demo, or production**. Doing so will results in executable code being stored in those environments' databases.

Test to verify this bug in **local development envs only**. Solution will be tested in isolated staging env when ready.

**Comment by khantaalaman** [comment]
I am working on this. 

Thanks!

**Comment by amplifi** [comment]
Also applies to XLSForms/questionnaires/imports; no validation currently implemented, code is accepted.
