### ISSUE TITLE
Search add location icon not working with Internet Explorer

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1165]
### Steps to reproduce the error

1. Open Internet Explorer
2. Go to a project and start adding a new location
3. Use the search icon included in the drawing tools when adding the location 
![screen shot 2017-02-28 at 11 09 40](https://cloud.githubusercontent.com/assets/17198051/23436798/ac6e7e42-fdc0-11e6-9ce2-2ec16e33c270.png)

4. Search icon is unresponsive

Tested with Windows 10 and IE 11 (latest version), and Windows 7 and IE 11 (latest version).

**Comment by seav** [comment]
Maybe this will help? http://stackoverflow.com/questions/28591039/geolocation-getcurrentposition-always-fails-in-ie-11

**Comment by jack17529** [comment]
@dpalomino  assign me this.

**Comment by wonderchook** [comment]
@jack17529 during the application process for GSoC we don't assign issues to anyone. It is okay to have more than one pull request for the same issue, we will still consider it as part of your application.

**Comment by wonderchook** [comment]
So the examples provided by Mapzen work with IE, so something to keep in mind. 

https://mapzen.github.io/leaflet-geocoder/examples/index.html
https://github.com/mapzen/leaflet-geocoder/tree/master/examples

**Comment by jack17529** [comment]
@wonderchook , please help when I run ./runserver I am getting this error - 
Traceback (most recent call last):
  File "/home/jack/Desktop/cadasta-platform-master/cadasta/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jack/Desktop/cadasta-platform-master/cadasta/config/settings/dev.py", line 1, in <module>
    from .default import *  # NOQA
  File "/home/jack/Desktop/cadasta-platform-master/cadasta/config/settings/default.py", line 17, in <module>
    from .languages import FORM_LANGS  # noqa
  File "/home/jack/Desktop/cadasta-platform-master/cadasta/config/settings/languages.py", line 54
SyntaxError: Non-ASCII character '\xc3' in file /home/jack/Desktop/cadasta-platform-master/cadasta/config/settings/languages.py on line 54, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by wonderchook** [comment]
@jack17529 not the right place to ask this question. gitter is the right place to ask it.

**Comment by clash99** [comment]
While testing on browser stack - windows 10, internet explorer 11, leaflet-touch styles are overriding other styles for leaflet-pelias-expanded and other styles.

![screenshot 2017-03-15 16 32 03](https://cloud.githubusercontent.com/assets/1119621/23971754/380e302c-099d-11e7-8702-e9de1f541252.png)

**Comment by jack17529** [comment]
@clash99 can you please help me solve my issue?

**Comment by clash99** [comment]
@jack17529 - Have you tried looking here?  https://gitter.im/Cadasta/cadasta

**Comment by clash99** [comment]
Some screenshots of fixed search from browserstack:

<img width="1426" alt="screenshot 2017-03-15 20 58 17" src="https://cloud.githubusercontent.com/assets/1119621/23979012/fa94611c-09c4-11e7-99f1-8b1e5b32d80d.png">
<img width="1421" alt="screenshot 2017-03-15 21 06 59" src="https://cloud.githubusercontent.com/assets/1119621/23979026/04a4e780-09c5-11e7-96a3-29e649b6308d.png">
<img width="1425" alt="screenshot 2017-03-15 21 07 38" src="https://cloud.githubusercontent.com/assets/1119621/23979025/04a31e5a-09c5-11e7-9e35-0082cde80a03.png">
![Uploading Screenshot 2017-03-15 21.08.24.png…]()
