### ISSUE TITLE
Design CSS

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#118]
Implement basic design and css for platform (style guide).

# Specific Clean-up Tasks

- [x] Base CSS
- [x] Project Index Page CSS
- [x] Project Overview Page CSS
- [x] Project - Edit Location Page CSS
- [x] Project - Edit Details Page CSS
- [x] Project - Edit Permissions CSS
- [x] Organization Index Page CSS
- [x] Organization Overview Page CSS
- [x] Organization Members Page CSS
- [x] Organization Members - Edit Page CSS
- [x] #90 
- [x] #92 
- [x] Info icon in header
- [x] Dashboard (popovers)
- [x] Table headers - sorting icons, etc.
- [x] Registration page background
- [x] Account pages text updates
- [x] Active top levels
- [x] Active subnav levels

**Comment by clash99** [comment]
Branch feature/css-ui-clean has been passed off to Lindsey to adjust functional tests.  That branch addressed top 5 on checklist.

**Comment by ian-ross** [comment]
@clash99 Would you consider the other tasks on the list here to be done as well?  If so, we can close this issue: I think you have another issue open for CSS for the project pages.

**Comment by clash99** [comment]
This is complete.  Additional design css tasks will be created for new pages that need attention.
