### ISSUE TITLE
Enhancement: Add forgot password link to the change password page.

### ISSUE THREAD

**Issue by rinklejain** [Cadasta/cadasta-platform#1188]
### Steps to reproduce the error

On the /account/password/change/ page there is no 'forgot password' link
 

### Actual behavior
On addition of the forgot password link, user experience shall be enhanced. Otherwise, the user will have to again go back to his/her account page and then to the reset password page to reset his/her password. 

### Expected behavior
The user will have to again go to his/her profile page and then to reset password page to reset his/her password.

**Comment by dvlshah** [comment]
As you are already in change password page what is the primary use of keeping a forgot password link there?Can you please elaborate?

**Comment by rjain111** [comment]
There is a possibility that user might not remember his password but he thinks that he remembers it. In all such situations, a forgot password link would be useful.

**Comment by valaparthvi** [comment]
@rinklejain @amplifi Looks like this issue has been solved. Closing this issue. Thanks.
