### ISSUE TITLE
Readme does not shows what this project does.

### ISSUE THREAD

**Issue by jack17529** [Cadasta/cadasta-platform#1196]
### Expected behavior

Should put precisely what this project does as the organisation is selected for GSOC 2017.

**Comment by oliverroick** [comment]
Hi @jack17529, would you care to elaborate what information you are missing?

**Comment by jack17529** [comment]
@oliverroick  it's good that we have docs but what will happen when I run the project , the final output should be mentioned in the readme.md and what is it's significance. Other projects have it ,as far as I have seen.

**Comment by oliverroick** [comment]
> but what will happen when I run the project , the final output should be mentioned in the readme.md 

I'm not sure I understand. What do you mean when you say "the final output?" This project is a platform that you run on a server, there is a web interface and an API. "Running the project" will just start the web server (unless you run the tests). It's not like you run a commend in the shell, some input is processed and you get something back.

**Comment by jack17529** [comment]
@oliverroick sir,I only want to say that it should show in readme that it starts a server, and some features that it has okay.

**Comment by SteadyCadence** [comment]
@jack17529 Are you recommending an overall description of what the platform does (as supposed to what the setup in the Readme does)?

 If so, would a GIF of the platform and basic capabilities of the platform suffice?

**Comment by SteadyCadence** [comment]
@olivierroick I can tackle this one.

**Comment by jack17529** [comment]
@SteadyCadence  ,yes sir that' it,and would be nice.

**Comment by oliverroick** [comment]
This isn't a priority at the moment. Closing...
