### ISSUE TITLE
Focussing on password field does not show password criteria

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1216]
### Steps to reproduce the error

1. Register a new user
2. Click on password field

### Actual behavior

The password validation criteria are not displayed.

### Expected behavior

The password validation criteria are displayed.

**Comment by laura-barluzzi** [comment]
Hi @oliverroick, has this been fixed?

**Comment by oliverroick** [comment]
@laura-barluzzi There are some PRs dealing with this, which are close to completion. No need to start with this.
