### ISSUE TITLE
Datatables should not show row filter drop-down if <= 10 results

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1221]
### Steps to reproduce the error

View any table on the platform with less than 10 results. As an example, on the Organizations page, enter a search term that results in no matches.

### Actual behavior

The "Show 10/25/50/100" drop-down appears.

<img width="438" alt="screen shot 2017-03-07 at 9 18 09 pm" src="https://cloud.githubusercontent.com/assets/4269749/23660417/f54e9884-037b-11e7-99b9-89d8e3b71385.png">

### Expected behavior

The drop-down should be hidden if there are 10 or fewer entries in the table. Fixing this in Datatables should fix it across the platform; also occurs in Search.

**Comment by yoshi2095** [comment]
@amplifi, I am working on this bug. Thanks.

**Comment by yoshi2095** [comment]
@amplifi I have fixed this issue. Please review. #1245
