### ISSUE TITLE
Search pagination UI violates ES max limit

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1223]
### Steps to reproduce the error

Search a project for a term with more than 10,000 search results. Example: search the "Uttaran Import" project for the term "e*"

### Actual behavior

Platform returns 10,444 search results, violating the ES max limit of 10,000:

<img width="340" alt="screen shot 2017-03-07 at 9 40 09 pm" src="https://cloud.githubusercontent.com/assets/4269749/23661277/d7386e58-037e-11e7-91cb-a5eb3b3dfa91.png">

If you set the results per page drop-down to show 100 results per page, then click the pagination arrows, all is fine through result # 10,000: 

<img width="379" alt="screen shot 2017-03-07 at 9 43 53 pm" src="https://cloud.githubusercontent.com/assets/4269749/23661430/52c3059c-037f-11e7-9520-4dd098ef7528.png">

But once you reach result # 10,001, the search UI dumps all results and fails with the error "Search is currently not available." The search query must be re-submitted.

<img width="428" alt="screen shot 2017-03-07 at 9 44 01 pm" src="https://cloud.githubusercontent.com/assets/4269749/23661418/4db631f0-037f-11e7-9fb8-670fb7800d57.png">

(Setting the drop-down to display 100 results per page is irrelevant; it just makes clicking through to result # 10,001 a lot less painful.)

### Expected behavior

The platform UI must adhere to the ElasticSearch max results limit, currently set to the default of 10,000 as noted in Issue #1097 . Results should be capped at 10,000 with an appropriate message informing the user of this limit and (once implemented) the alternative option for project managers to export project data.

**Comment by dpalomino** [comment]
As agreed in the search check-in, @seav was going to work on this to fix it this week (thanks Eugene!).
