### ISSUE TITLE
Sample questionnaires still contain the Project Extent location type

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1226]
### Steps to reproduce the error
1. In a new project (or one with no records yet), attach either the sample minimum or standard questionnaire.
2. Go to the add location page and draw a geometry for the new location.
3. Select "Project Extent" location type.
4. Submit.

### Actual behavior
You get the following error:
> Select a valid choice. PX is not one of the available choices.

### Expected behavior
The "Project Extent" choice should not be included. See PR #693.

### Remarks
The sample minimum and standard questionnaires still include the Project extent (PX) location type among the choices. Both are also missing the Utility corridor (UC) location type.

**Comment by dpalomino** [comment]
Wow, this is quite weird. It only happens with that location type... I think we should fix it.

**Comment by wonderchook** [comment]
We just need to remove it as an option, right?

**Comment by dpalomino** [comment]
Ah ok, true. Sorry, I misunderstood the issue. Reprioritizing and assigning to me to remove this option in the S3 files.

**Comment by dpalomino** [comment]
I've updated the files in S3 removing the PX option. Let me know if you see any other issue. 

In addition, we are in the process of updating these sample files in the documentation: 
https://docs.cadasta.org/en/09-XLSForms.html
