### ISSUE TITLE
I can add a group with negative members

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1230]
### Steps to reproduce the error

- Add a party as a group.  

### Actual behavior

- You can set "Number of Members" to a negative value.

### Expected behavior

- Seems like you should only be able to have a group with a positive value.

![screenshot 2017-03-07 11 02 06](https://cloud.githubusercontent.com/assets/1119621/23668073/858d4352-0325-11e7-9d10-2c940b511c5b.png)

**Comment by dpalomino** [comment]
Hi @clash99. This is because that field is defined as integer in that specific project (standard questionnaire), with no other restriction, so any integer (positive or negative) can be included. I think this not an issue... closing it, but please reopen if needed...
