### ISSUE TITLE
Integer values get converted to float for text fields when importing

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#1231]
### Steps to reproduce the error

During data import, if a field in a questionnaire (for example the *standard cadasta questionnaire*) is defined as a text field (eg **nid_number**), if this field contains an integer value, then the field gets converted to a floating point value during the import. 

![party](https://cloud.githubusercontent.com/assets/3308136/23669464/2b84fa08-035c-11e7-866b-4df0a9834dd5.png)

### Actual behavior

Integers are converted to float during import of text fields.

### Expected behavior

Integers should not be converted to floating point.

**Comment by bjohare** [comment]
Only seems to happen for xlsx imports.

**Comment by dpalomino** [comment]
Thanks @bjohare. If only happens with xlsx imports is a bit less concerning, although I think we should fix it maybe during the next sprint...

**Comment by valaparthvi** [comment]
I would like to work on this issue if no one else is working on it? Can I go ahead?

**Comment by rishabhiitbhu** [comment]
I would like to work on this issue.

**Comment by bjohare** [comment]
@valaparthvi and @rishabhiitbhu thanks for your interest but this is not a 'First Contribution Friendly' issue, please find another issue with the first contribution label.

**Comment by rishabhiitbhu** [comment]
@bjohare almost all 'First Contribution Friendly' issues have already PRs. It would not be good to raise PR for those issues. I want to work for this issue. Please let me try for it. I want to learn about cadasta-platform, rather than getting my PR merged. thanks

**Comment by valaparthvi** [comment]
@bjohare okay.

**Comment by bjohare** [comment]
@rishabhiitbhu ok that's fair enough, please feel free to go ahead. @valaparthvi, if you want to try this as well, please go ahead. We'll work out the PR stuff later.

**Comment by valaparthvi** [comment]
@bjohare I've submitted my first PR for another issue, so it's okay if @rishabhiitbhu wants to solve this issue. I'll find another issue to work on.

**Comment by rishabhiitbhu** [comment]
@bjohare okay. @valaparthvi thanks for your support.

**Comment by bjohare** [comment]
thanks @valaparthvi

**Comment by rishabhiitbhu** [comment]
@bjohare 
### Steps taken:
- Created a project.
- Added [Standard cadasta questionnaire](https://s3-us-west-2.amazonaws.com/cadasta-resources/sample-forms/standard_cadasta_questionnaire.xlsx) as questionnaire.
- Added a location, followed by adding a relationship for that location, with "NATIONAL ID NUMBER" (national_id) and "MOBILE NUMBER" (mobile_number) as intergers.
-Under "Parties" overview of newly added relationship shows this:
![1](https://cloud.githubusercontent.com/assets/17473589/23755265/ba535af4-0505-11e7-8e8d-65530b2b509f.png)

- Downloaded project data as xls file, modified "national_id" and "mobile_number" field with different integer values.
- Imported modified xls file, new party added.
- Under "Parties" overview of newly added relationship / party show this:
![2](https://cloud.githubusercontent.com/assets/17473589/23755572/d1f14576-0506-11e7-9123-e238a44b9808.

According to this issue, after importing xls file, the "NATIONAL ID NUMBER" (national_id) and "MOBILE NUMBER" (mobile_number) fields should have changed their datatype to float, but they are still integer.
Please help.

**Comment by bjohare** [comment]
@rishabhiitbhu I can't see the second screenshot you posted above.. I've just confirmed this on platform-staging.cadasta.org

**Comment by rishabhiitbhu** [comment]
I have edited the link, It may be visible to you now. I have checked it on local development server (forked repo, branch master) and on demo.cadasta.org both same results. Will checkout platform-staging.cadasta.org

**Comment by rishabhiitbhu** [comment]
@bjohare I signed in on platform-staging.cadasta.org with "iross" user. Created a new project with standard-cadasta-questionnaire. Imported same xls file which I had downloaded from local development server. Checked out the newly created party and it gives me same results, i.e., NO conversion from integer to float.

here is the [link](https://platform-staging.cadasta.org/organizations/ir-test/projects/project_varanasi/records/parties/usi7hk4f72kkq2u8fcugycgi/#overview) you might be able to look at it by using username = "iross" and password = "password"

**Comment by bjohare** [comment]
Ok @rishabhiitbhu thanks for your investigation, I'll have a closer look at this and see if I missed something at my end..

**Comment by bjohare** [comment]
@rishabhiitbhu would you mind sanity checking this import? Please register a new user account and create a new project from scratch using the standard cadasta questionnaire. Thanks.
[testing_integers.xlsx](https://github.com/Cadasta/cadasta-platform/files/831632/testing_integers.xlsx)

**Comment by rishabhiitbhu** [comment]
@bjohare Sure.

**Comment by rishabhiitbhu** [comment]
@bjohare I registered a new user account. Created a new organisation. Created a new project under that organisation using standard cadasta questionnaire. Imported same xls file. Got same results as before. Imported the file you linked in previous comment. Got same results. Screenshot attached.
![3](https://cloud.githubusercontent.com/assets/17473589/23763358/3e7feef0-051f-11e7-914d-7704b985816a.png)

**Comment by bjohare** [comment]
@rishabhiitbhu what values do you get for Individual party types?

**Comment by rishabhiitbhu** [comment]
@bjohare same Integer values (no float). Screenshot attached:
![4](https://cloud.githubusercontent.com/assets/17473589/23763478/c4d12708-051f-11e7-9905-18d091bcbe67.png)

**Comment by bjohare** [comment]
@rishabhiitbhu ok, thanks for your help. We'll need to do some investigation as @dpalomino has just confirmed the issue again using https://github.com/Cadasta/cadasta-platform/files/831632/testing_integers.xlsx

**Comment by rishabhiitbhu** [comment]
@bjohare I got the error this time. Actually the attached image of individual party in my last comment is that of my own imported xls file. When I imported your testing_integers.xlsx file, it changed the integer values to float for individual party. Sorry for misunderstanding.
Screenshot attached.
![5](https://cloud.githubusercontent.com/assets/17473589/23765441/3b451c30-0527-11e7-98b2-741a440f3830.png)

**Comment by bjohare** [comment]
Ok @rishabhiitbhu, thanks for confirming that. Could you post your import file so we can investigate this further? If necessary, please sanitize before sharing publicly.

**Comment by rishabhiitbhu** [comment]
@bjohare this is my import file.
[import_test.xlsx](https://github.com/Cadasta/cadasta-platform/files/834615/import_test.xlsx)

**Comment by oliverroick** [comment]
Duplicated by #1758. Closing...
