### ISSUE TITLE
Hide location edit and delete buttons for project users

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1233]
### Steps to reproduce the error

- Look at the location detail for a project that you have project user permissions.

### Actual behavior

- I can view the edit and delete buttons but when I try to do anything, I'm denied.

### Expected behavior

- I would expect the edit and delete buttons to be hidden if a user doesn't have permissions to edit or delete.  (Same is true for location relationships, parties and resources).

![screenshot 2017-03-07 12 54 46](https://cloud.githubusercontent.com/assets/1119621/23672852/b4b9c366-0335-11e7-919b-7ec3827b1aa7.png)
![screenshot 2017-03-07 12 54 54](https://cloud.githubusercontent.com/assets/1119621/23672851/b4b7bc6a-0335-11e7-8d02-0599d666e888.png)

**Comment by laura-barluzzi** [comment]
Hi @clash99, I'm interested in working on this. I get the general idea for which the buttons should be hidden if the user cannot use them, but is a user with "project permission" allowed to make changes or not? This is unclear to me. Thanks.

**Comment by wonderchook** [comment]
@laura-barluzzi you mean the "project user"? They should not be able to make changes

**Comment by laura-barluzzi** [comment]
Hi @clash99  and @wonderchook, I fixed this; please take a look at #1268 and let me know what you think.

**Comment by niharika1995** [comment]
FWIW, this issue has been fixed by #1268
