### ISSUE TITLE
Language Support Error Message (on Staging)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1234]
### Steps to reproduce the error

1. Create a project with a questionnaire that has at least two language options (in this case French and English)
2. Go to the overview page and look at the language toggle option on the top right.  View the green question mark icon that says that the language you are using is not supported. 

### Actual behavior

When I toggle the languages in the questionnaire, I get an error message for all languages (even supported ones)

<img width="277" alt="screen shot 2017-03-07 at 11 56 30 am" src="https://cloud.githubusercontent.com/assets/25337622/23673851/077f5fd4-0331-11e7-8b6b-9ff23769f0f1.png">

### Expected behavior

I expect this error message only to show up for languages that Cadasta does **not** support.

**Comment by dpalomino** [comment]
Hi, @clash99 already fixed this issue (thanks Candra!). 

See new text: 
![screen shot 2017-03-09 at 13 57 14](https://cloud.githubusercontent.com/assets/17198051/23751175/6f01daec-04d0-11e7-984b-64b54b9d7841.png)

Please reopen if needed.

**Comment by clash99** [comment]
Thanks for closing @dpalomino  - sorry @SteadyCadence, I didn't realize there was an issue filed.
