### ISSUE TITLE
Show Password Should be Available on Reset Password/Change Pages Too

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1236]
When signing up for an account there is a "show password" option, this is not the case for password reset or the change password pages.

**Comment by Divya063** [comment]
@wonderchook but  there is a prompt box of "show password" option by the firefox browser in password reset or the change password pages.

**Comment by wonderchook** [comment]
Can you attach a screenshot? It isn't there on Chrome

**Comment by clash99** [comment]
Would like same integration as #1240.
