### ISSUE TITLE
403 after sign in

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1250]
### Steps to reproduce the error

- Sign in as existing user.

### Actual behavior

- Receiving 403.

### Expected behavior

- Would expect to be redirected to the dashboard. 

If I hit refresh, I do get redirected to the dashboard and sign-in was successful. 

This is a sporadic error I've received about a dozen times over the past 2 days.  I just want to document it in case others are seeing the same thing.  I'm unable to pinpoint the cause.

<img width="1423" alt="screenshot 2017-03-08 12 28 40" src="https://cloud.githubusercontent.com/assets/1119621/23717924/57121634-03fb-11e7-8f3c-52196410ddca.png">

**Comment by dpalomino** [comment]
I haven't seen any 403 in te last couple of days. @amplifi do you know if we can see something in the logs?

**Comment by amplifi** [comment]
@dpalomino There are sporadic 403 http responses on the POST to account/login/ in staging, demo, and production. This isn't an "error" necessarily; as far as the logs are concerned that's the appropriate behavior for invalid CSRF tokens. Django handles CSRF, so we'd have to check that it's being implemented correctly on the platform side.

**Comment by dpalomino** [comment]
I think we can close this issue for now. Please reopen if you think this is happening too frequently. 

Thanks!

**Comment by SteadyCadence** [comment]
I just had this happen to me on demo in Chrome.
