### ISSUE TITLE
Review location geometry creation via imports and ODK

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#1254]
### The issue

Its currently possible to create locations with empty or null geometries via imports and ODK form submissions. It should not be possible to do this. We should consider making `geometry` a `required` field on the `SpatialUnit` model. We should add stricter validation on imports and form submissions and reject locations with missing geometries.

### Actual behavior

Location records can be created without a geometry via the import process and ODK. This is not possible using the UI where the geometry is required.

### Expected behavior

Location records created using imports or ODK should be rejected if they contain an empty or null geometry.

**Comment by bjohare** [comment]
Related to https://github.com/Cadasta/cadasta-platform/issues/1113

**Comment by alukach** [comment]
@bjohare Is there a difference between _empty_ and _null_ geometries?  Am I correct in that _empty_ geometry is still a valid `GEOSGeometry` object while `null` geometry would simply be a `None` object?

**Comment by wonderchook** [comment]
@bjohare so originally it was supposed to be possible to create a location with a location that was described instead of having coordinates not sure if this is related. We could decide to deal with that particular use case later though.

**Comment by alukach** [comment]
@wonderchook @bjohare 

I suppose the most important thing to then answer is: 

Should the system support `SpatialUnit` instances that have either empty or null geometries?

- If yes:
  - We should update the `SpatialUnit.pre_save` signal handler `check_extent()` to not run `reassign_spatial_geometry()` if the `instance.geometry` is empty (it already works around the idea that `instance.geometry` could be empty).
  - Is there anything down the line from import (such as when data is serialized/exported) that would expect the `geometry` data to be not null/empty?  If so, that should be addressed.
- If no:
  - We alter the `geometry` field to be a required attribute.
  - Write a migration to deal with all empty `SpatialUnit` instances with an empty or null `geometry` field.
  - Throw a `ValidationError` when empty/null `geometry` data is inputted (I'm thinking in `cadasta.organization.importors.validators`, however there may be a better place?).

Does this sound about right?

**Comment by wonderchook** [comment]
@dpalomino @SteadyCadence I'm inclined to think some partners will want to import data that doesn't have geometries and then add the geometries later (for example from satellite imagery in the Cadasta web interface). 

What do you think and if this is a non-issue then we will require geoms (though I suspect this will cause an issue for someone importing data at some point).

**Comment by seav** [comment]
@wonderchook: the problem that this issue causes right now is that the export operation throws an error when it encounters locations that don't have a geometry. So the question goes back to whether we really require geometries as mentioned by @alukach. Whatever the answer, we will adjust the platform code as needed.

**Comment by bjohare** [comment]
@alukach there is a difference between `empty` and `null` geometries. Its possible to create a valid `empty` `GEOSGeometry` from a WKT string like `'POLYGON EMPTY'`. Passing `None` or `' '` to the `GEOSGeometry` constructor will raise an exception. We could support `empty` geometries but as you mentioned we'd need to fix the `pre_save` method on `SpatialUnit`. As @seav says, we would also need to check how exports react to `empty` geometries, although I suspect they'd be ok. The question then is what we do when an import contains `' '`. We could either reject it (current behaviour) or convert it to something like `'POINT EMPTY'`? 

As a final complication, imports must support both `WKT` and the weird `ODK` geometry string format. At the moment if we can't create a `GEOSGeometry` from either `WKT` or `WKB` then we try to parse it as `ODK` geom. If we can't create a valid geom from any of these then maybe we revert to `'POINT EMPTY'` as a default?

In any case, as you mentioned,  we would probably need to run a migration to update any existing `null` geoms in the db to an `empty` geom. Maybe @amplifi could check how many there are and if this step is required?

**Comment by dpalomino** [comment]
@wonderchook @bjohare @alukach @seav 

Thanks to all for raising this and for the useful discussion. Although it is not a very typical case, I do also think that partners would need to import without any geometry defined so I think we should allow that case (at least when importing). 

Indeed we've already seen this case. We worked with a partner that imported data related to villages with some records just including the village name without any geometry data. We worked around the issue including a geopoint with the coordinates of the village for the records that lacked of geometry. But of course it'd be better if we can directly support records without geometries. 

Those records without geometry will be then only accessible through search results and when downloading the project data. @clash99, is there any other implications related to map interactions that I'd be missing?

**Comment by alukach** [comment]
@dpalomino Thanks!  This gives me what I need to go ahead.

**Comment by alukach** [comment]
@seav I've put together #1344 to resolve the issue of importing empty geometries (#1113), however it still allows for `None` and empty `SpatialUnit.geometry` values to be stored. Can you direct me to a log where an issue occurs during an export operation?  If so, I can hopefully roll that fix into #1344 as well.

**Comment by seav** [comment]
@alukach, I'm not sure if you already have access to our Opbeat account, but here's an example error encountered when trying to export a location that has `geometry` = `None`: https://opbeat.com/cadasta/platform-demo/errors/83/

Here, the platform is populating the `geometry.ewkt` column of the XLSX file but since `geometry` = `None`, the operation throws an error because `None` does not have the `ewkt` attribute.

**Comment by dpalomino** [comment]
Need to be tested with GeoODK.

**Comment by dpalomino** [comment]
It should be fixed now, closing the issue.
