### ISSUE TITLE
Rework Member Profile page into two sections

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1256]
Rework Member Profile Page so that it is two columns instead of one.  Since left and the right sections have separate actions, I think it will be more intuitive this way.

Quick mockup for general idea:

![two columns](https://cloud.githubusercontent.com/assets/1119621/23757299/063ae7d4-04ac-11e7-9078-02a62bf21884.png)

**Comment by clash99** [comment]
@dpalomino and @wonderchook - I think this if first contributor-friendly.  Thoughts?

**Comment by dpalomino** [comment]
hi @clash99. I agree, it looks nice. I think it'd be a good first-contributor yes.

**Comment by khantaalaman** [comment]
Please review whenever possible. 

Thanks!
