### ISSUE TITLE
Incorrect text when adding a relationship through GUI

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1257]
### Steps to reproduce the error

1. Select one location and add a relationship
2. In the Relationship details, the following text appears: 
"What is the social tenure type?"
![screen shot 2017-03-09 at 16 41 36](https://cloud.githubusercontent.com/assets/17198051/23757619/abb360de-04e7-11e7-85b2-6ae2e161b293.png)

However it'd be better not to use the term "social tenure", I'd suggest to use: 
"What is the relationship type?"

@clash99, what do you think?

**Comment by wonderchook** [comment]
agreed

**Comment by Shruti9520** [comment]
@dpalomino Can I work on this issue?

**Comment by dpalomino** [comment]
Sure @Shruti9520, you can work on this issue. 

I think you're not seeing the wrong message because it is the first party in that project. If you first add a party, and then repeat the operation described in the STR, you will see the wrong string. With the first party created in the project the strings are ok. 

See screenshot: 
![screen shot 2017-03-10 at 11 02 56](https://cloud.githubusercontent.com/assets/17198051/23790874/3595366c-0581-11e7-9818-74c970c9773e.png)

**Comment by Shruti9520** [comment]
@dpalomino I can't see the wrong message even if I add second or third party. Also "Tenure Notes" part isn't visible. Will you please see the screenshot-

![cadasta2](https://cloud.githubusercontent.com/assets/20228417/23791995/2f5a6c52-05ab-11e7-9753-25bb35d2e522.png)

Thanks :)

**Comment by dpalomino** [comment]
Ahh I see now. The bug only appears [in staging](https://platform-staging.cadasta.org) not in demo.

**Comment by seav** [comment]
@dpalomino, this is a defect on the questionnaire, not the platform. The platform took the “social tenure” wording from the project's questionnaire.

**Comment by dpalomino** [comment]
Ah thanks @seav! I didn't notice it. Closing the issue then. 

@Shruti9520, sorry for the inconvenience, this is not actually a bug. Please feel free to choose any other "First Contribution Friendly" issue to fix. Thanks!
