### ISSUE TITLE
Formatting issue with dataTables and lots of resources

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1259]
### Steps to reproduce the error
- Add more than 10 resources to a location or relationship

### Actual behavior
In full screen view:

<img width="1280" alt="screen shot 2017-03-09 at 11 54 11 am" src="https://cloud.githubusercontent.com/assets/8128188/23761017/6fdbfd46-04bf-11e7-8fde-e297e83eb865.png">

The arrows overlap rows slightly or (if the screen is slightly smaller), the arrows jump down a row. Also, if it's a long file name it throws the formatting off: 

<img width="1122" alt="screen shot 2017-03-09 at 11 54 34 am" src="https://cloud.githubusercontent.com/assets/8128188/23761028/7e6270e8-04bf-11e7-8a48-f2a34def09ff.png">

### Expected behavior
They would fit in the space to the right of 'rows'

**Comment by valaparthvi** [comment]
hey @linzjax , It seems to be working fine for me. I hope this is what you were talking about.
![screenshot from 2017-03-10 21-29-12](https://cloud.githubusercontent.com/assets/11015077/23802354/0eaac546-05d9-11e7-9e21-d9e04339cf16.png)

**Comment by valaparthvi** [comment]
I'm sorry I didn't notice before, but it does happen when the screen size is small.

**Comment by dpalomino** [comment]
@clash99, can you please take a look to this? thanks!

**Comment by clash99** [comment]
Made modifications to datatables and search datatables:
- Changed order of elements so pagination is first and floats right
- Made length menu wrap to second line when screen becomes very narrow 
- Changed length menu to have "per page" in dropdown and removed outside labels
- Changed css to adjust border and padding

<img width="1391" alt="screenshot 2017-04-06 20 18 30" src="https://cloud.githubusercontent.com/assets/1119621/24781620/8bb9b8b6-1b06-11e7-920c-c1bc8577b060.png">
<img width="1191" alt="screenshot 2017-04-06 20 18 46" src="https://cloud.githubusercontent.com/assets/1119621/24781621/8bbb0ab8-1b06-11e7-9988-f067c488917c.png">
<img width="1370" alt="screenshot 2017-04-06 20 19 37" src="https://cloud.githubusercontent.com/assets/1119621/24781622/8bc8052e-1b06-11e7-8bcb-56f253fbf24b.png">
<img width="465" alt="screenshot 2017-04-06 20 14 17" src="https://cloud.githubusercontent.com/assets/1119621/24781632/99b86002-1b06-11e7-9a2d-5b31395e8f3f.png">
