### ISSUE TITLE
Add translation ability for required questions (party_type, party_name, etc)

### ISSUE THREAD

**Issue by MappingKat** [Cadasta/cadasta-platform#1261]
### Steps to reproduce the error

1. Create a project and upload a non-english form
2. Add a location in the project. View all questions except the required ones are in the proper language. 
3. Click the supported languages option on the footer and notice that doesn't translate the questions either. 

### Actual behavior

English is hard coded into the questions and answers of the required fields. 

### Expected behavior

To see questions in the language of the form.

**Comment by wonderchook** [comment]
I'm thinking this might be best approached with the task to allow other types for the required questions. (Though parties would still need to be fixed)

**Comment by SteadyCadence** [comment]
@wonderchook, @dpalomino and I were talking about this and he suggested that we make those questions available in transifex. That's a decent workaround.

We will run into problems with that if a user translates the questions correctly in an XLS form, in Hindi for example, and is unable to view those translations on the web.  But it works with ODK...

**Comment by wonderchook** [comment]
Yeah, that makes sense. I just meant if we were going to go fiddle with this I think we just do the two together.

**Comment by dpalomino** [comment]
Currently we think it is only happening with forms using a non-English language as the default language. We will be doing more testing about this.

**Comment by SteadyCadence** [comment]
You can use this form to test: https://drive.google.com/file/d/0Bwu69XKTjUmwdmlFVm01UUNrMnM/view?usp=sharing

**Comment by dpalomino** [comment]
Workaround is to use two languages, we need to investigate further.

**Comment by dpalomino** [comment]
Hey @clash99! This is a nice to have for Sprint 19, only if you have time. Thanks!

**Comment by clash99** [comment]
Attached xls file above doesn't work. Using this one to troubleshoot: 
[Sustainable Sourcing (1_1) ID language.xlsx](https://github.com/Cadasta/cadasta-platform/files/1156222/Sustainable.Sourcing.1_1.ID.language.xlsx)

**Comment by clash99** [comment]
The required text is being properly translated according to the user's preferred platform language. You will see that if you change the preferred platform language to be Indonesian, the required text is translated.

The problem with relying on the language code from the project to supply the required fields is that the possibilities for those are unlimited so translations won't always be available in transifex.  Here are a few options I can think of off the top of my head:

- We could check to see if the project data language is available in a platform language and if so, ask the user if they want to switch to the platform language.
- We could check to see if that project data language is available in a platform language and if so, default to using that for the required fields (not sure if we can do this on a partial-page basis).
- Other ideas?

### Platform language = English, Project language = Indonesian
<img width="1062" alt="screenshot 2017-07-18 13 31 55" src="https://user-images.githubusercontent.com/1119621/28331316-8f68d3a8-6bbe-11e7-85b9-a7e78655805f.png">

### Platform language = Indonesian, Project language = Indonesian
<img width="1065" alt="screenshot 2017-07-18 13 33 07" src="https://user-images.githubusercontent.com/1119621/28331336-a5da3a96-6bbe-11e7-89e1-91e060d13fd0.png">

### Platform language = Spanish, Project language = Indonesian
<img width="1069" alt="screenshot 2017-07-18 13 35 34" src="https://user-images.githubusercontent.com/1119621/28331352-b40ff61e-6bbe-11e7-83fb-a538b3af6ee0.png">

**Comment by clash99** [comment]
We discussed this in the development team meeting yesterday. It was confirmed that this issue was raised when originally implemented so is working as-designed. This isn't a bug but I agree it isn't ideal either.  There are a few limitations as noted above.  At this time I recommend closing this task or adding it to the backlog/ feature list with one of the solutions presented above. 

@oliverroick - Do you have anything to add here?

**Comment by oliverroick** [comment]
@clash99 — Nothing to add

**Comment by dpalomino** [comment]
As discussed, closing the issue. Thanks @clash99 for checking this!
