### ISSUE TITLE
Emails from Cadasta should have a human readable name

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1269]
When you receive emails from the Cadasta platform right now it just shows as "platform" in many email clients. It should instead show "Cadasta Platform" to do this we need to add a human readable name when we send emails.

**Comment by rishabhiitbhu** [comment]
@wonderchook I registered on Cadasta plaform with username "ags", confirmation email I got was:

> from:	platform@cadasta.org via amazonses.com 
> to:	*my email_id*
> date:	Thu, Mar 9, 2017 at 11:12 PM
> subject:	[Cadasta] Please Confirm Your Email Address

> You're receiving this email because user ags at Cadasta Platform has given yours as an email address to connect their account.
> 
> To confirm this is correct, go to https://platform-staging.cadasta.org/account/confirm-email/iootoh3owezuzmlldpk2c8dojwdfe4hvg77mipxjzeoih5ynbshclkrcmwlkmfgu/
> 
> 
> Thank you from Cadasta.

When I tried to reset my password, the email I got : 
You're receiving this email because you or someone else has requested a password reset for your user account at Cadasta Platform.

> from:	platform@cadasta.org via amazonses.com 
> to:	*my email_id*
> date:	Fri, Mar 10, 2017 at 12:29 PM
> subject:	[Cadasta] Password Reset Email

> Click the link below to reset your password.
> 
> https://platform-staging.cadasta.org/account/password/reset/key/2d-4k8-d02b945e3b41b29ca2ad/
> 
> 
> If you did not request a password reset, please contact us immediately at security@cadasta.org

I need a clarification, the email client is platform@cadasta.org, are you talking of changing this?

**Comment by rjain111** [comment]
Hi @wonderchook 
I would like to work on this issue.
From what I have understood, we basically need to change 
DEFAULT_FROM_EMAIL = 'platform@cadasta.org'
to 
DEFAULT_FROM_EMAIL = 'Cadasta Platform<platform@cadasta.org>'
This will add a human readable name ('Cadasta Platform') to every mail sent from platform@cadasta.org.
What do you think?

**Comment by wonderchook** [comment]
I believe that is true. I think you probably need a space in there though.
