### ISSUE TITLE
Number of project listed on org index includes active AND archived projects

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1270]
While viewing the organization index, I noticed that it listed 8 projects in the Demo account-- even though there are only 3 active projects. 

![screen shot 2017-03-09 at 8 41 23 pm](https://cloud.githubusercontent.com/assets/25337622/23781238/1c2e9e34-0509-11e7-8655-1f69c3626cda.png)

Since I cannot delete projects (only archive them), I would only like to see the total of 3 on the list. 

Up for debate.

**Comment by clash99** [comment]
I agree - lets have it show only the active projects.  I think that is assumed.  

Another place we should verify only active numbers are showing is on the project overview page - the locations, parties and resources.

**Comment by clash99** [comment]
@dpalomino Added a low priority to this bug and made first contributor friendly.  Feel free to change if you don't agree.

**Comment by pamungkaski** [comment]
Hi, i would like to work on this issue as my GSoC first task>
My approach going to be check wheteher the project already archived or not. if it's not archived then inc num_project else continue

**Comment by wonderchook** [comment]
@pamungkaski sounds good, if you want to go ahead

**Comment by wonderchook** [comment]
@pamungkaski actually I just realized someone else is working on it. You could try it, but it is unlikely to get merged into the main code base. I would suggest looking for another issue.
