### ISSUE TITLE
Unmentioned file types when uploading a new resource.

### ISSUE THREAD

**Issue by valaparthvi** [Cadasta/cadasta-platform#1271]
[Add a new Resource](https://docs.cadasta.org/en/04-records.html#project-resources) suggests that acceptable file types are:
.pdf
.mp3
.mp4
.doc
.docx
.jpg
.png
.gif
.tiff
.xls
.xlsx
.xml

While Adding a new resource to any project, not all the file types(xls, xlsx, gif, tiff) are mentioned. Is there a reason for not mentioning these file types?

### Steps to reproduce the error
1) Open a Project and go to Resources.
2) Click on Attach. A dialog box will be displayed.
![screenshot from 2017-03-10 12-41-15](https://cloud.githubusercontent.com/assets/11015077/23785936/262c33ec-0590-11e7-86ad-102fcd629c7d.png)

### Actual behavior
Something like this is displayed.
Accepted file types: pdf, mp3, mp4, doc, docx, jpg, png, gpx, csv

### Expected behavior
Something like this should be displayed.
Accepted file types: pdf, mp3, mp4, doc, docx, jpg, png, gpx, csv, xls, xlsx, gif, tiff

**Comment by Shruti9520** [comment]
@dpalomino @valaparthvi  Can I take this issue? :)

**Comment by valaparthvi** [comment]
@Shruti9520 sure, I don't mind. 
@dpalomino Do you think there is a specific reason for not mentioning those types?

**Comment by aishwarya-an** [comment]
@valaparthvi Hi, I am Aishwarya. I am new to open source contribution. Can you please guide me as to , under which branch do i make the pull request for this issue?
Thanks.

**Comment by valaparthvi** [comment]
hey @aishwarya-an you can follow [this guideline](https://devwiki.corp.cadasta.org/Git%20workflow) and also [this](https://github.com/Cadasta/cadasta-project-ideas/wiki/GSoC-Outreachy-Issue-Contribution-Process) to make your contribution.

**Comment by aishwarya-an** [comment]
@valaparthvi  Thanks.

**Comment by aishwarya-an** [comment]
@valaparthvi  Can i make a pull request even though i have not been assigned this issue.

**Comment by valaparthvi** [comment]
hey @aishwarya-an @Shruti9520 , both of you made same changes and have made a PR, but I am not authorized to merge PRs. @dpalomino can you help here?

**Comment by oliverroick** [comment]
Both PRs are exactly the same; it's going to have to be first come, first serve.

**Comment by valaparthvi** [comment]
okay @oliverroick
