### ISSUE TITLE
User session has no expiry

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1273]
### Steps to reproduce the error

Log in to any platform user account.

### Actual behavior

User session has no expiry; the cookie never expires so the session can persist until the user manually logs out of the platform.

This means for **any** user who logs in, if they don't click to log out, **anyone using the same computer up to one year after them could access the platform without needing to log in.**

So if a user does not log out of their platform account on a shared/public computer, or if someone else accesses their personal computer, **all of the user's organization & project data is exposed.**

CSRF tokens are also currently set to a 1-year validity.

### Expected behavior

Django should be configured with a user session expiry set to a reasonable amount of time such that login is required once per site access (no greater than 24 hours). CSRF token validity should be lowered to match the maximum session time.

**Comment by wonderchook** [comment]
@SteadyCadence thoughts on what the expiry should be?
