### ISSUE TITLE
Import Issue :: Party file imports successfully but does not associate with location id

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1285]
### Steps to reproduce the error

1. Imported location data (geom, location_type) with one file (clicked only the location option on the import)
2. Imported party data (location_id, party_name, party_type, etc).  Import is successful!
3. When I review the party tab all of the rows have been added successfully.  However, when I go to a location there are no relationships associated with the location. 

View the project here: https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/smallholder-farmers/records/locations/6k2w3ihi9reugvhkgufbbdiw/#relationships

Could it be possible that I needed to use the exact `spatial_unit_id` header in order for the connection to take place? One solution for this issue may be better documentation? Either way, it is strange to have a successful import with no connection to locations. 

### Actual behavior

The party information is imported successfully as seen by clicking the Party tab and seeing 31 unique parties.  However, if you click on a location none of the parties are attached to the location id that I assigned those parties. 

(Note:  I did add one party manually to test out what was going on)

### Expected behavior

I expect to be able to import a file filled with party information and the Cadasta location id successfully.  I expect the import to match up the location id with the party fields. 

Import files: 

[import-smallholder-parties.xlsx](https://github.com/Cadasta/cadasta-platform/files/835018/import-smallholder-parties.xlsx)
[import-smallholders.xlsx](https://github.com/Cadasta/cadasta-platform/files/835017/import-smallholders.xlsx)

**Comment by dpalomino** [comment]
Closing for now, found a workaround for this.
