### ISSUE TITLE
Needs Investigation :: Overview Map Zooms to Extent of One Particular Polygon

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1289]
### Steps to reproduce the error

1. Imported location geometry and data for this project
2. Overview map seems to really like one certain polygon as it zooms in to the extent of the polygon

See https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/smallholder-farmers/

Now that I think about it... I did start adding parcels in India and then removed those manually and imported polygons in Indonesia.  Could that have caused this issue?

### Actual behavior

Map zooms in on one polygon.

### Expected behavior

I expect the map to zoom to the extent of the polygons on the Overview map setting.

**Comment by dpalomino** [comment]
Hi @SteadyCadence, 

I don't have permissions to see that location. Is this then a dup of #1131?

**Comment by SteadyCadence** [comment]
@dpalomino The issue is the Overview map.  When you click on the project, it zooms right in to a polygon instead of giving you an overview. 

I think it must be an import or multi-polygon issue.  If I have access to the Leaflet object I can figure it out, but I dont know how to grab that in the console.... 

![broken-overview-map](https://cloud.githubusercontent.com/assets/25337622/23958801/d58b69d0-0968-11e7-822f-f245bdb36985.gif)

**Comment by clash99** [comment]
The map was set to fit the boundaries of the locations (meaning if you only had one location, it would zoom in to that).  I've changed it to fit the boundaries of the project.

**Comment by clash99** [comment]
**Before:**
![screenshot 2017-03-15 13 56 06](https://cloud.githubusercontent.com/assets/1119621/23967035/6df5d2d8-098b-11e7-8e1b-be32168ccfd6.png)

**After:**
![screenshot 2017-03-15 14 27 51](https://cloud.githubusercontent.com/assets/1119621/23967085/9cc7d228-098b-11e7-835f-cd11d6d2c4c4.png)
