### ISSUE TITLE
Verification email : user is allowed to access site without verification

### ISSUE THREAD

**Issue by maitrishroff1995** [Cadasta/cadasta-platform#1296]
**Steps to reproduce the error**

1. click on 'Register'
2. enter details
3. when submitted, the email is sent but the user can browse the website even if email verification is not done 

### Actual behavior

1. User registers and is logged in
2. Without verification, the user is allowed to browse
3. The user is allowed to log out and log in again without issues

### Expected behavior
1. When the user is successfully registered, the screen should be frozen with a dialog box saying that he/she should click on the email verification link. Until then, the website should be inaccessible.
2. when the user verifies his/her identity, he should be navigated to the website with his/her account logged in.

**Comment by oliverroick** [comment]
This is expected behaviour, the user can use the site for 48 hours without verification. If the email is not verified after 48 hours, the user will be deactivated.
