### ISSUE TITLE
Incorrect rendering at Location Details page

### ISSUE THREAD

**Issue by narayanaditya95** [Cadasta/cadasta-platform#1306]
### Steps to reproduce the error

1. Go to a location detail page.
2. Add one or more relationships.

### Actual behavior

![screen shot 2017-03-16 at 6 14 55 am](https://cloud.githubusercontent.com/assets/6830800/23976944/15368440-0a11-11e7-9238-712ff32e69d7.png)

### Expected behavior

![screen shot 2017-03-16 at 6 27 19 am](https://cloud.githubusercontent.com/assets/6830800/23977016/8bddb230-0a11-11e7-8d6e-62f004689fa1.png)

**Comment by narayanaditya95** [comment]
Removing the css class `top-add` remove the negative bottom margin and fixes the issue. Can I submit a PR to fix the same?

**Comment by dpalomino** [comment]
thanks @narayanaditya95. Where are you testing this? In [staging](https://platform-staging.cadasta.org) or [demo](https://demo.cadasta.org)? Are you using a tablet or a mobile device?

I cannot reproduce the issue with a laptop.

**Comment by linzjax** [comment]
This formating is caused by a Datatable extension not being loaded. The photos above are also missing the search bar and the pagination information. (I ran into this during the smap work)

**Comment by narayanaditya95** [comment]
True. I cannot reproduce it now. The extension loads fine now.
