### ISSUE TITLE
Weird "}" symbol when including more than one relationship fields in a xlsform

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1309]
### Steps to reproduce the error

1. Create a project with more than one field in the "tenure_relationship_attributes"
2. Add a location
3. Add a relationship and a party via GUI 
4. In the web form, a weird "}" appears. 

See screenshot: 

![screen shot 2017-03-16 at 19 24 56](https://cloud.githubusercontent.com/assets/17198051/24012553/b684a558-0a7e-11e7-88e7-bec267d9dcd1.png)

However, if there is only one field within that group then behaviour is ok: 

![screen shot 2017-03-16 at 19 23 58](https://cloud.githubusercontent.com/assets/17198051/24012587/ceb82b68-0a7e-11e7-9f00-8ac52ca9f8f4.png)

A couple of xlsform's for reference: 

One with ONE relationship field: 
[1-person-to-many-locations-form_v_1_7.xlsx](https://github.com/Cadasta/cadasta-platform/files/848669/1-person-to-many-locations-form_v_1_7.xlsx)

Other with TWO relationship fields (which is failing): 
[1-person-to-many-locations-form_v_1_6.xlsx](https://github.com/Cadasta/cadasta-platform/files/848671/1-person-to-many-locations-form_v_1_6.xlsx)

@bjohare or @linzjax, any idea why this could be happening?

Thanks!

**Comment by SteadyCadence** [comment]
I converted the questionaire to xml and there doesnt seem to be an extra "}" in there.  

Had to save it as a .txt file because .xml is not supported in GH. 

[tester-script.txt](https://github.com/Cadasta/cadasta-platform/files/848698/tester-script.txt)

**Comment by linzjax** [comment]
There's a stray `}` in the template around datepicker, which is why it shows up on a calendar question. I'll submit a PR
