### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#1318]
### Steps to reproduce the error

1. log in to Demo
2. Go to Organization: Cadasta Foundation: The Official Demo Organization
3. Click on any of the projects
4. Click on Search
5. Enter the name of a party that you know is part of the project
6. Search returns a database error

### Actual behavior

This is the database error

![image](https://cloud.githubusercontent.com/assets/3361475/24089779/7c72e3b8-0cf7-11e7-909f-8068be3a8566.png)

### Expected behavior

I expect the search to return a party that I've searched for.

**Comment by amplifi** [comment]
Investigating

**Comment by bethschechter** [comment]
thank you!

**Comment by bethschechter** [comment]
@rishabhiitbhu thank you for trying! i'm sure one of those guys will come online soon and get you the info you need. :)

**Comment by amplifi** [comment]
@bethschechter This error should be resolved now.

@rishabhiitbhu Superuser access is restricted; I recommend focusing on issues labeled as "First Contribution Friendly" and those requiring basic user access. All testing should be conducted in the development VM (not on the demo or production platform sites). Thanks!
