### ISSUE TITLE
Adding forgot username functionality.

### ISSUE THREAD

**Issue by rishabhiitbhu** [Cadasta/cadasta-platform#1319]
### Why this is neccessary?

- When a new account is created, user is sent a email like this:

> You're receiving this email because user {{username}} at Cadasta Platform has given yours as an email address to connect their account.
>To confirm this is correct, go to https://demo.cadasta.org/account/confirm-email/<key>

Here username is sent with the email. Suppose user edits his/her profile by updating username, no email regarding changes is sent via email, and suppose after some time forgets the username, there's NO way to recover it back. 

Some approaches towards this issue:

1.
- Modify login process, by including login with _username or email_ instead of only username, as most of the sites do so, like twitter and facebook. 

2.
- Add a new link of _forgot username_ on login page.
- User clicks on _forgot username_ link and then enters email id.
- An email is sent containg _username reset link_.
- User visits _username reset link_ and sets a new username.

3.
- Add a new link of _forgot username_ on login page.
- User clicks the link and then enters email id.
- An email is sent to the user which contains user's username.

4.
- Whenever user updates his/her username, an email is sent notifying the changes. So whenever user forgets username he can check his/her inbox.

Would like to have comments and reviews on this issue.

**Comment by dpalomino** [comment]
Hi @rishabhiitbhu. Thanks for raising this and for your interest .

I believe it is already possible to login using the mail address (not only the username) but the UI message is not properly updated.

**Comment by rishabhiitbhu** [comment]
@dpalomino Thanks for your suggestion. I didn't know that login with email (not only username) was also possible. I raised issue #1308 and in discussion @seav found out that we need to modify [this](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/allauth/account/login.html#L48) lable in `allauth/account/login.html` from "Username" to "Username and e-mail" as according to [allauth](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L113) as we already have login with 'username or e-mail' functionality. I'll update this lable in my PR #1312 itself.
thanks.
