### ISSUE TITLE
Unclear Error (QuestionOption matching query) when Click on Location In Imported Project

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1321]
I thought I submitted this on Friday, but I cant find it in the issue list... 

### Steps to reproduce the error

 I think this is what I ran into before when I thought WKB was not supported. In this case, I am not sure if it is associated with the questionnaire or the geometries I am trying to import-- I did try multiple geometries and they all successfully imported but I still get an error when I try to click on a polygon.

1. Uploaded this questionnaire (https://docs.google.com/a/cadasta.org/spreadsheets/d/1hyF_uxZb4959lxD6vDMM574cQEFTyq636VAS7n3e0MA/edit?usp=sharing)
2. Uploaded this import file (https://drive.google.com/open?id=1JmudjHarecPPuM5YGp2kUyNVFVPSjM9sWHKIQr_QHuU). I have a few different copies with different geometry types.
3. Import is successful.  Looks good. However, when I click on a location to view details I am taking to an error page. 

Original project issue on demo: https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/sustainable-sourcing-palm-oil-indonesia/
Multiple tests on staging: 
Note: The polygons seems to work fine on this project--- which makes me think it must be the questionnaire... https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/smallholder-farmers/

The strange thing is that the exports on both of those projects work fine... you just cannot click on the individual locations.

### Actual behavior

Import is successful, but when I click on the polygon I get taken to the "Platform Error" page.

These are the errors that show up after clicking indiv locations: ```DoesNotExist at /organizations/cadasta-demo-organization/projects/sustainable-sourcing-palm-oil-indonesia/records/locations/cts73vq823xzeamdjqwi8f3m/
QuestionOption matching query does not exist.```

### Expected behavior

I expect there to be some sort of error handling if there was something incorrect in the questionnaire or import file...

**Comment by linzjax** [comment]
The land_type and tenure_type names in choices need to be capitalized to map properly (`AP` instead of `ap`).

**Comment by MappingKat** [comment]
wow!  I thought I had fixed that.  Thank you!

**Comment by SteadyCadence** [comment]
Wow!  I did not even think to look at the choices sheet.  I thought I had fixed those.  Thank you!

**Comment by seav** [comment]
Shouldn't we make the platform more robust by also allowing lowercase forms as input and mapping them to uppercase internally? If we can make things just a bit more fault-tolerant, I think it would be better.

**Comment by SteadyCadence** [comment]
@seav Yes!  I think that would be a good idea-- I think we should be lower-casing all values.
