### ISSUE TITLE
Sign in username/email texts 

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1323]
### Steps to reproduce the error
Go to the login page

![screen shot 2017-03-21 at 14 00 31](https://cloud.githubusercontent.com/assets/17198051/24148405/ef6db7a6-0e3e-11e7-9536-262dca43c269.png)

You're able to login using your email address (not only the username) but the UI is only asking for the username. 

We should change the text, instead "Username" using "Username or email address".

**Comment by seav** [comment]
This is actually related to #1308.
