### ISSUE TITLE
Wrong style used in party detail page

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1331]
### Steps to reproduce the error

Visit the detail page for a party

### Actual behavior

Main panel had some shading that shouldn't bee there.

### Expected behavior

Should use same layout and classes as Resources index.

**Panel should resemble this page:**
<img width="1364" alt="screenshot 2017-03-22 12 27 11" src="https://cloud.githubusercontent.com/assets/1119621/24211812/3153b1ea-0efb-11e7-9e5b-54cbb74d56f5.png">

**Currently looks like this (notice shading around panel):**
<img width="1362" alt="screenshot 2017-03-22 12 27 31" src="https://cloud.githubusercontent.com/assets/1119621/24211855/542af7e6-0efb-11e7-81a2-74479438b251.png">

At a glance I don't believe this requires a css change.  I believe the error is on the html side for what styles are being called.

**Comment by clash99** [comment]
@dpalomino - I marked this first contribution friendly.  Feel free to update if you disagree.  Thanks!

**Comment by rishabhiitbhu** [comment]
@clash99 I have looked into it and I found that in `party/party_list.html` there's an extra css class `default` attached with panel div, removing it fixes this issue. 
so basically `div.panel-body.detail` needs to be changed to `div.panel-body`.
I would open a PR if you say so.

**Comment by clash99** [comment]
Sounds good @rishabhiitbhu - make it happen :)
