### ISSUE TITLE
Browser Incompatibility: User dropdown does not work in Safari on Project pages

### ISSUE THREAD

**Issue by niharika1995** [Cadasta/cadasta-platform#1333]
### Steps to reproduce the error

1. Use Safari browser.
2. Head to <http://127.0.0.1:8000/organizations/cadasta/projects/london-2/>
3. Click on _User dropdown_ in the header.

### Actual behavior

Nothing happens.

### Expected behavior

A dropdown must appear.

**Comment by clash99** [comment]
Hi @niharika1995.  Thanks for reporting this bug but I haven't able to reproduce this.  Which device and version of Safari are you using?

Here are the three I've tested:
- Safari 5.1 on Windows 10
- Safari 8 on OS X Yosemite
- Safari 6 on OS X Lion

Here is what I'm seeing:
<img width="215" alt="screenshot 2017-03-22 20 58 09" src="https://cloud.githubusercontent.com/assets/1119621/24228633/868d9336-0f43-11e7-86b6-aa659504e90f.png">

**Comment by niharika1995** [comment]
Hi @clash99,

I am using Safari 10 on OS X Sierra. Also, looks like you are on the _dashboard_ page. The bug is only seen on _project_ pages.

**Comment by niharika1995** [comment]
Screencast:

![0XBtBx](http://i.makeagif.com/media/3-23-2017/0XBtBx.gif)

**Comment by clash99** [comment]
Same result - can't reproduce using BrowserStack (our cross-browser QA tool).  Perhaps someone else will be able to verify either way...

<img width="1438" alt="screenshot 2017-03-22 21 24 08" src="https://cloud.githubusercontent.com/assets/1119621/24229150/38cb59aa-0f46-11e7-9ee1-174767e2e11d.png">

**Comment by niharika1995** [comment]
The bug is only seen inside the incognito (private) mode. Closing the issue as it works fine in a normal window.

**Comment by clash99** [comment]
Very strange - I'll make a mental note in case we come across this in other areas so I can troubleshoot.  Thanks for the heads-up.
