### ISSUE TITLE
Pending migration not bundled

### ISSUE THREAD

**Issue by niharika1995** [Cadasta/cadasta-platform#1334]
### Steps to reproduce the error

1. Log into the VM.
2. Run `python manage.py makemigrations`

### Actual behavior

Migrations are created.

### Expected behavior

No migration should be created.

**Comment by artiladdha** [comment]
I would like to work on this issue.

**Comment by wonderchook** [comment]
@niharika1995 this is the expected behavior when running that command. Could you elaborate as to why you think it is a bug.

**Comment by oliverroick** [comment]
@wonderchook There's one migration that should have been created but wasn't. It's not a big deal because the migration in question would just add some meta options for two models. So this should be fixed but it's not urgent at the moment

**Comment by wonderchook** [comment]
ah okay, @niharika1995 you might want to update your bug report. The actual and expected behaviors are reversed.

**Comment by niharika1995** [comment]
>ah okay, @niharika1995 you might want to update your bug report. The actual and expected behaviors are reversed.

@wonderchook I am not sure that is correct. No migrations should be created, ideally.

>@wonderchook There's one migration that should have been created but wasn't. It's not a big deal because the migration in question would just add some meta options for two models. So this should be fixed but it's not urgent at the moment

I proposed that we add another test on Travis `python manage.py makemigrations --check`. It returns a non-zero exit code when there are changes not reflected in migrations.
