### ISSUE TITLE
Resource detail different than other detail pages

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1342]
### Steps to reproduce the error

Visit resource detail page

### Actual behavior

Missing page title style on other detail pages
Also edit page doesn't show resource title at all

### Expected behavior

Should match

![screenshot 2017-03-24 09 22 13](https://cloud.githubusercontent.com/assets/1119621/24298302/90dbac7a-1073-11e7-9442-7555fcb3bcd4.png)
![screenshot 2017-03-24 09 22 23](https://cloud.githubusercontent.com/assets/1119621/24298301/90d1d47a-1073-11e7-9b1e-e3ee19e5b803.png)

**Comment by clash99** [comment]
Update resource detail and edit page to have titles that match other detail pages.

![screenshot 2017-03-24 09 20 12](https://cloud.githubusercontent.com/assets/1119621/24298401/e9ff3f42-1073-11e7-8fa1-413bd8b9c5d9.png)
![screenshot 2017-03-24 09 20 20](https://cloud.githubusercontent.com/assets/1119621/24298402/ea004518-1073-11e7-8161-982834175d4d.png)
![screenshot 2017-03-24 09 18 10](https://cloud.githubusercontent.com/assets/1119621/24298418/f78c6b3a-1073-11e7-9927-972bb0494c6e.png)

**Comment by Shruti9520** [comment]
@clash99 @dpalomino Can I take this issue? :)

**Comment by wonderchook** [comment]
@Shruti9520 if you look above @clash99 has already submitted a pull request, so not. Thanks for your interest though

**Comment by Shruti9520** [comment]
@wonderchook Sorry! I didn't notice that.

**Comment by clash99** [comment]
Added some of the prep work of the details table for #1267
