### ISSUE TITLE
[ui] [enhancement] Make header "add dropdown buttons" contextual 

### ISSUE THREAD

**Issue by Tahirih-Natang** [Cadasta/cadasta-platform#1346]
### Steps to reproduce the error
Go to Organisations page.
On header, there is an "Add project" drop down button.
Click on the Members section on the left, though we are on the members section, the header dropdown button still reads "Add project", in its drop down, there is an "add member option", and this has the same effect as the add button in the page content.

### Expected behavior
Remove the "add member dropdown" option from the header dropdown in the members section in the Organisations page.

I would lie this feature / enhancement to be a first contribution friendly.

![selection_001](https://cloud.githubusercontent.com/assets/15211041/24350028/a772382a-12d8-11e7-89a4-dcd2ce89bf12.png)

**Comment by Tahirih-Natang** [comment]
@clash99 @wonderchook Please I would like to know if this could be a first contribution friendly issue.

**Comment by wonderchook** [comment]
@Tahirih-Natang sorry this is intentional and not considered a bug. Thanks for reporting though.
