### ISSUE TITLE
When trying to delete party, the 'x' button on top right of delete confirmation box is not working

### ISSUE THREAD

**Issue by pamungkaski** [Cadasta/cadasta-platform#1360]
### Steps to reproduce the error

- Try to delete party
- Press the 'x' button

### Actual behavior

- The button is not working at all

### Expected behavior

- The page will back at the party detail

**Comment by dpalomino** [comment]
Thanks @pamungkaski for raising this!

@clash99, can you please take a look?

**Comment by dpalomino** [comment]
BTW, it's reproducible with several browsers (tested with Chrome and FF).

**Comment by pamungkaski** [comment]
@dpalomino safari also.

**Comment by khantaalaman** [comment]
To solve this bug,
In `party_delete.html` (/templates/party) at line 10, replace the complete `button` tag with the following:
`<a href="{% url 'parties:detail' object.organization.slug object.slug party.id %}"  class="close">&times;</a>`

@dpalomino I have already solved a similar bug in my PR #1299. Should I go ahead and submit a PR for this one too?

**Comment by dpalomino** [comment]
Sure @khantaalaman! Thanks!

**Comment by pamungkaski** [comment]
@khantaalaman thx dude
