### ISSUE TITLE
Remove language around Standard and Minimal Questionnaire (or questionnaires in general)

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#1365]
I'm making a project to document importing GPX files, but when I uploaded a my form I got this message:

![image](https://cloud.githubusercontent.com/assets/3361475/24560802/6d480658-1601-11e7-971a-25b6ecd22b5c.png)

We no longer use the Standard and Minimum questionnaire; also the language has been changed to Cadasta XLS form

The types we're using can be found at this URL:
https://docs.cadasta.org/en/09-XLSForms.html#types

They are: 
• [Customary Rights (1:1) Form](https://docs.google.com/spreadsheets/d/1MHg6iok4SkDxN2NdMVt3P2W9UZe81VxH6CpAz_eUtOY/pub?output=xlsx)
• [Smallholder Agriculture (1:Many) Form](https://docs.google.com/spreadsheets/d/1HKal7WyNSji80cg7ID9FnXh9-4dFvjSuqHJKu4_vxxI/pub?output=xlsx)
• [Urban Informal Settlements (Many:1) Form](https://docs.google.com/spreadsheets/d/1iORFg75ofq-QzLB5x-WvuggEZN6JaE0iS6yqc7dE1Y0/pub?output=xlsx)

The links provided are XLSX docs that automatically update when the forms in[ this Google Drive folder](https://drive.google.com/drive/folders/0B1ZYvNKUYAT2SWZITHdlR1RJWGs) are updated, so they are better links to use...

...until we change the forms again ;)

Please bug me if you have any questions!!

**Comment by wonderchook** [comment]
@dpalomino I think it would be worth updating this in the next sprint.

**Comment by dpalomino** [comment]
Thanks @bethschechter for raising this. Yes @wonderchook I agree that we should fix this in the next sprint. 

Also note that the link to the xlsform section in the user guide is not properly updated either, it should be: 
https://docs.cadasta.org/en/09-XLSForms.html

I'd suggest to include the following text: 

"For assistance with questionnaires view our user guide. To help you get started three samples have been provided: [Customary Rights (1:1) Form](https://docs.google.com/spreadsheets/d/1MHg6iok4SkDxN2NdMVt3P2W9UZe81VxH6CpAz_eUtOY/pub?output=xlsx) (one person in relation with one location), [Smallholder Agriculture (1:Many) Form](https://docs.google.com/spreadsheets/d/1HKal7WyNSji80cg7ID9FnXh9-4dFvjSuqHJKu4_vxxI/pub?output=xlsx) (one person in relation with many locations, and [Urban Informal Settlements (Many:1) Form](https://docs.google.com/spreadsheets/d/1iORFg75ofq-QzLB5x-WvuggEZN6JaE0iS6yqc7dE1Y0/pub?output=xlsx) (many people in relation with one single location)." 

Another option would be to share the Google drive folder instead of the individual files. 

Thoughts?

**Comment by clash99** [comment]
@dpalomino - Let me know what you think of below.  Its a hybrid of what you have above and user guide document.

<img width="918" alt="screenshot 2017-04-06 16 33 38" src="https://cloud.githubusercontent.com/assets/1119621/24776547/df9a226a-1ae6-11e7-83dd-f267f67383b7.png">

------------------------------------------------------

@bethschechter - just noticed two small changes to user guide:  1)  missing period at end of bullet 2, and 2) I think you want "many" vs "may" in last bullet - so small but thought I would mention it before I forgot!

![screenshot 2017-04-06 16 32 25](https://cloud.githubusercontent.com/assets/1119621/24776582/0576bcdc-1ae7-11e7-8c2c-b5f8140254a3.png)

**Comment by wonderchook** [comment]
I don't like the explanations. I think they should specific to the use case and we should leave the one to many or one to one stuff out of describing of what people do.

**Comment by bethschechter** [comment]
@wonderchook @clash99 copy this! 

Before I make the changes, I want to bring in @dpalomino and @SteadyCadence. David and Katrina, does this make sense to you?

If not it might be worth jumping on a quick call to discuss. 

Another question: if we do this, do we need to make a starter xlsform for each of our use cases, like Sustainable Sourcing??

**Comment by bethschechter** [comment]
@wonderchook @clash99 we have agreement on how to describe these, but I likely won't have the descriptions done til early next week. Unless I can bust through a quick thing today - we'll see!!

**Comment by clash99** [comment]
@bethschechter - Any updates here?

**Comment by bethschechter** [comment]
@clash99 i will get these to you today. very sorry, travel threw me off.

**Comment by bethschechter** [comment]
@wonderchook @clash99 here is some (hopefully better) copy around these forms, which I've added to the documentation. Do you think more info is needed?

//

To get started, choose the form that most closely matches your documentation needs.

* The [Customary Rights Form](https://docs.google.com/spreadsheets/d/1MHg6iok4SkDxN2NdMVt3P2W9UZe81VxH6CpAz_eUtOY/pub?output=xlsx) is designed for documenting the rights of a single group of people who are using a single parcel or piece of land, like in this [Customary Rights project in Ghana](https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/customary-rights-ghana/). 
* The [Sustainable Sourcing Form](https://docs.google.com/spreadsheets/d/1hyF_uxZb4959lxD6vDMM574cQEFTyq636VAS7n3e0MA/pub?output=xlsx) is for documenting land that's being used for sustainable agricultural production.
* The [Smallholder Agriculture Form](https://docs.google.com/spreadsheets/d/1HKal7WyNSji80cg7ID9FnXh9-4dFvjSuqHJKu4_vxxI/pub?output=xlsx) is designed for documenting a farmer's rights to use one or more plots of land. See this [Smallholder Farming project](https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/smallholder-farmers-india/) as an example. 
* The [Urban Informal Settlements Form](https://docs.google.com/spreadsheets/d/1iORFg75ofq-QzLB5x-WvuggEZN6JaE0iS6yqc7dE1Y0/pub?output=xlsx) is for documenting many people who may be living in a very small urban area, like in [this Urban Informal Settlements project](https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/urban-informal-settlement-enumeration/).  

 If you need help or have questions, [please contact us](http://cadasta.org/contact/).

**Comment by clash99** [comment]
Hi @bethschechter - thanks for the text.  I've made the updates so take a look and let me know if its approved.  Thanks, Chandra

![screenshot 2017-04-18 08 53 44](https://cloud.githubusercontent.com/assets/1119621/25134228/abcfa25c-2414-11e7-8561-5647395ac08a.png)

**Comment by bethschechter** [comment]
works for me!

**Comment by clash99** [comment]
@bethschechter and @dpalomino - does this mean we should remove the old questionnaires housed on AWS?

**Comment by bethschechter** [comment]
I say yes


On Apr 18, 2017 10:57 AM, "Chandra Lash" <notifications@github.com> wrote:

@bethschechter <https://github.com/bethschechter> and @dpalomino
<https://github.com/dpalomino> - does this mean we should remove the old
questionnaires housed on AWS?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/1365#issuecomment-294929267>,
or mute the thread

**Comment by dpalomino** [comment]
Yes,they can be removed. Thanks @bethschechter and @clash99!
