### ISSUE TITLE
Subsequent activation emails not sent for inactive user accounts

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1370]
### Steps to reproduce the error

Register an account but do not click the link in the activation email. Allow the account to be marked inactive after waiting period, then try logging in with the account again.

<img width="479" src="https://cloud.githubusercontent.com/assets/4269749/24588257/099c340e-17ef-11e7-8ea2-8a1798a57954.png">

### Actual behavior

The error message as above states that an activation email has been sent. Activation email doesn't get re-sent.

### Expected behavior

Activation message should be re-sent to the email address registered to the user account to allow the user to activate.

**Comment by valaparthvi** [comment]
Hey @amplifi, I have tried this one before and I think it does resend an activation mail. But still I'll make sure of the issue, and I would like to solve this one if no one is working. Thanks.

**Comment by valaparthvi** [comment]
Hey @amplifi, so I tried reproducing the error on my local environment. 
1) I did `vagrant ssh`
2) Created new user account named "student".
3) logged out and logged back in
4) It showed `Account Inactive` page, but no confirmation mail is sent.
![screenshot from 2017-04-03 00-37-26](https://cloud.githubusercontent.com/assets/11015077/24590150/f13a45ec-1805-11e7-966e-587f0252b7ea.png)

5) I did `ctrl+c` and ended that session.
6) I ran `vagrant ssh` and started a new session.
7) logged in that user account.
8) It showed `Account Inactive` page, and sent a confirmation mail.
![screenshot from 2017-04-03 00-37-50](https://cloud.githubusercontent.com/assets/11015077/24590184/687e9838-1806-11e7-8753-c62e1d89b483.png)

So there is some bug, I'll update this asap.

**Comment by rishabhiitbhu** [comment]
@valaparthvi @amplifi I have found that `send_email_confirmation` method has a COOLDOWN_PERIOD set as 3 minutes. According to allauth:

    E-mail verification mails are sent:
    a) Explicitly: when a user signs up
    b) Implicitly: when a user attempts to log in using an unverified
    e-mail while EMAIL_VERIFICATION is mandatory.
    Especially in case of b), we want to limit the number of mails
    sent (consider a user retrying a few times), which is why there is
    a cooldown period before sending a new mail.

Check [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L283)
So, if you try logging in after 3 minutes, a new confirmation mail is sent. :)

**Comment by amplifi** [comment]
This isn't a case of the expected 3-minute delay. I have four inactive user accounts across staging and demo that have not received activation emails after log in attempts on Thursday last week. Our SMTP service also shows no activation emails triggered for these accounts. I'll be investigating further.

**Comment by valaparthvi** [comment]
okay @amplifi

**Comment by amplifi** [comment]
Can't replicate on current staging env; will re-open if issue occurs again.

**Comment by dpalomino** [comment]
Thanks @amplifi. I think this is still happening in demo, I tried with my "dpalomino" disabled account in demo and the mail was not sent.

**Comment by oliverroick** [comment]
@dpalomino Was your account manually deactivated or as a result of not verifying your email. 

In the former case, it is expected behavior that no verification email is sent. Accounts are usually deactivated for a reason. For example, when the account has been used inappropriately You shouldn't able to re-activate the account just by receiving an email and clicking on the link.

**Comment by amplifi** [comment]
@dpalomino @oliverroick According to the db, the `dpalomino` account in demo is both deactivated and already email verified. Confirmed: a verification email should not be expected behavior. Let's re-open if there are issues with expected behavior in the future.
