### ISSUE TITLE
SHP download breaks when there are empty geometries

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1373]
### Steps to reproduce the error

1. Create a project that contains empty geometries (you can import data from [import-2-questionnaire.zip](https://github.com/Cadasta/cadasta-platform/files/765045/import-2-questionnaire.zip)
2. Download data; select "SHP" or "All Data"

### Actual behavior

Server error is thrown; see the [corresponding log on Opbeat](https://opbeat.com/cadasta/platform-staging/errors/141/) for more details.

### Expected behavior

Data should be downloaded.

**Comment by dpalomino** [comment]
Also related to #1113 . 

AFAIK, there are no projects with empty geometries yet, but as we will allow them through imports as discussed in #1254, so I think we need to fix this (although not super urgent).

**Comment by Sanny26** [comment]
I'm trying to reproduce this error. When I try to import a file in zip, it throws a tuple index out of range error and a warning on select import field page(step 2)
![screenshot from 2017-04-05 01 04 43](https://cloud.githubusercontent.com/assets/16081303/24675295/32fd14a4-199c-11e7-9f7b-2866ad18e458.png)

Am I doing anything wrong?

**Comment by oliverroick** [comment]
@Sanny26 Have you loaded the questionnaire in the Zip first and then tried to import the data?

**Comment by dpalomino** [comment]
To be addressed in Sprint 17
