### ISSUE TITLE
No password verification when changing account's mail address

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1376]
### Steps to reproduce the error

1. Go to Edit Profile
2. Change mail address

### Actual behavior

User is not prompted to verify their password to confirm identity. 

All the other fixes described in bug #1140 are properly included though: 
1. Confirmation mail to new email address does not include username
2. The mail address is not actually updated until the verification link is clicked
3. Correct notification is sent to the old address

But I wonder if we should ask for password verification as well, as we do when changing the password for instance. 

### Expected behavior

Ask for password verification?

@amplifi, what do you think?

**Comment by amplifi** [comment]
@dpalomino Agreed, should have to confirm password before changing user details.

**Comment by wonderchook** [comment]
I think this is a priority prior to the release.
