### ISSUE TITLE
Clear search box formatting and URL change

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1377]
### Steps to reproduce the error

Submit a search term, click 'X' to clear the search field.

### Actual behavior

'X' appears before any search text has been entered, and is misaligned (Safari & Chrome on Mac OS) as shown:

<img width="773" alt="screen shot 2017-04-04 at 6 52 38 pm" src="https://cloud.githubusercontent.com/assets/4269749/24655473/a367c5e2-1968-11e7-9203-bfbe8bf0130b.png">

<img width="772" alt="screen shot 2017-04-04 at 6 52 49 pm" src="https://cloud.githubusercontent.com/assets/4269749/24655478/a8723630-1968-11e7-931d-65ab267669b2.png">

Page URL is not reset to clear search term as per discussion in #1147 

### Expected behavior

'X' should be properly aligned at right edge of search field. Page URL should be reset to clear search term. See #1147 for expected result.

**Comment by seav** [comment]
I don't have Mac OS, but I can't reproduce this on Firefox and Chrome on both Linux and Android.

Also, I instructed the intern applicant to no longer clear the page URL when the clear button is clicked. This is because we don't update the page URL when users type in or update the search input (but without clicking the search button yet) and clicking the clear button is effectively the same as selecting the input text and pressing backspace or delete. So basically, the page URL is only updated when the user actually submits a search request.

**Comment by khantaalaman** [comment]
Hi @amplifi I implemented the clear search-box functionality in PR #1171.

Just now I re-checked this on my Mac (OS X El Capitan) and found it to be working fine in Chrome as well as Safari. Following are the screenshots:

![screen shot 2017-04-04 at 5 39 34 pm](https://cloud.githubusercontent.com/assets/18065231/24656062/7f06ceb4-195e-11e7-977c-9ccf35e8e0b2.png)

![screen shot 2017-04-04 at 5 42 07 pm](https://cloud.githubusercontent.com/assets/18065231/24656069/83ce2f82-195e-11e7-92e5-f5bdea9f3e6a.png)

It would be great if you could tell the MacOS version also.

**Comment by amplifi** [comment]
Same appearance as my screenshots above in Safari (10.0.3) and Chrome (57), both El Capitan and Sierra.

Alignment is also broken in Safari on iOS 10.3.1 (iPhone 6) as shown:

![image](https://cloud.githubusercontent.com/assets/4269749/24656689/9ff05d02-196d-11e7-851e-ef7756461a45.png)

**Comment by seav** [comment]
I can confirm that on narrow screens, the alignment is not perfect. The iOS screenshot is the same on Firefox and Chrome on Android when in portrait mode.

**Comment by amplifi** [comment]
@seav re: no longer resetting the URL; there's no note of such change in requirements in the corresponding Issue or PR -- if your original instruction from #1181 to clear the URL was in error, we should be updating accordingly.

**Comment by seav** [comment]
@amplifi, there is a comment of the change in the page URL behavior in the PR, but it's hidden in GItHub because it was attached to an outdated code: https://github.com/Cadasta/cadasta-platform/pull/1171#discussion_r105172485

But agreed that any changes should be documented, preferably visible.
