### ISSUE TITLE
CSS: Long email spills outside of member profile

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1379]
### Steps to reproduce the error
[Osx, Chrome]
Add a user with a ridiculously long email.
Add them to an organization
View their member details within the organization.
Slowly decrease your browser window size to right before it switches to tablet view.

### Actual behavior
The email spills out of the member profile box.
<img width="255" alt="screen shot 2017-04-04 at 10 43 33 am" src="https://cloud.githubusercontent.com/assets/8128188/24662673/c2cc86f6-1923-11e7-84a1-8b125a839c16.png">

### Expected behavior
It would wrap? Shrink? I dunno.

**Comment by dpalomino** [comment]
I'd say wrap, but @clash99 is the biggest authority here :)

**Comment by clash99** [comment]
Added ability to break and wrap for really long emails addresses and modified last login css.

<img width="1440" alt="screenshot 2017-04-04 11 11 57" src="https://cloud.githubusercontent.com/assets/1119621/24667060/aec673d4-1927-11e7-8b17-6bd16bdda5de.png">
