### ISSUE TITLE
Deleted resources are included in the project data download

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1380]
### Steps to reproduce the error
1. Delete a resource in project.
2. Download the project data (select the "Resources" or "All data" option).

### Actual behavior
The deleted resource is included in the downloaded zip file and is listed in resources.xlsx.

### Expected behavior
The deleted resource should not be included.

### Notes
The filter in this queryset should also include `archived=False`: https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/organization/download/resources.py#L52

**Comment by rishabhiitbhu** [comment]
Hi @seav  and @dpalomino,  I have reproduced the error on my local setup and filtering queryset with `archived=False` [here](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/organization/download/resources.py#L52) fixes the bug. 
I would like to open a PR solving this bug, if you say so.
