### ISSUE TITLE
Search showing duplicate entries

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1382]
### Steps to reproduce the error

On staging in Lakeview River Project, search for "rw" (for right-of-way).

### Actual behavior

Seeing duplicate entries for same location, with same links.  There is only one location in this project.

### Expected behavior

See only one entry for a location.

<img width="1440" alt="screenshot 2017-04-04 11 39 26" src="https://cloud.githubusercontent.com/assets/1119621/24668553/eeeadad6-192c-11e7-86e5-9850e2101bc4.png">

**Comment by clash99** [comment]
More details:
- Search for "cat" is only showing "Laser Cat" party
- Search for "cats" is showing duplicate entries for "Flying saucer cats" resource

It seems like "cat" would show an entry for "Laser Cat" party and "Flying saucer cats".

<img width="1439" alt="screenshot 2017-04-04 12 03 38" src="https://cloud.githubusercontent.com/assets/1119621/24669163/f4c299ec-192e-11e7-9fa5-8739144d84da.png">
<img width="1438" alt="screenshot 2017-04-04 12 03 47" src="https://cloud.githubusercontent.com/assets/1119621/24669162/f4bf5f52-192e-11e7-8c52-cf11f9ff5c30.png">

**Comment by seav** [comment]
Re "cat" vs. "cats", this will be resolved as part of #1118.

**Comment by linzjax** [comment]
Adding to this: Only one of the two links works. The other gets a 404 error.

**Comment by amplifi** [comment]
According to index timestamps, the partial data duplication for this index occurred when the staging update interval was modified to sync more frequently for the QA period. Confirmed only this project was affected, potential scope of issue limited to staging env only and not possible to occur under normal operation. Added a check anyway to smooth large interval changes, but it's gold-plating at this point.

Search result links returning 404 indicate an issue on the platform side; should be investigated separately.

**Comment by dpalomino** [comment]
Thanks  @amplifi for digging into this (the duplicated stuff)! As we discussed the the search check-in meeting, closing this issue for now as it is a unusual case that in addition can only happening in staging. 

For the 404, it will be checked separately.
