### ISSUE TITLE
Platform Error thrown when accessing an org member that's been removed

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1383]
### Steps to reproduce the error
- Add a member to an organization.
- Grab their member detail page URL
- Remove them from the organization
- Go back to their member detail page URL

Similarly, if you try to view member details of a user that doesn't exist, you get a 404 not found.

### Actual behavior
- Triggers platform error

### Expected behavior
- Redirected with a "user not a member of this organization" message or something along those lines.

**Comment by Sanny26** [comment]
Can I fix this issue?

**Comment by linzjax** [comment]
@Sanny26 You're of course welcome to work on it. As a heads up, if you were hoping to work on it as part of an application process for GSoC or Outreachy, the deadline for those have passed and it won't necessarily be considered as part of your application.

If you just wanted to work on it for fun, that's also totally fine. Either way, have at it!

**Comment by oliverroick** [comment]
[Example exception](https://opbeat.com/cadasta/platform-staging/errors/143/)

**Comment by Sanny26** [comment]
To fix this issue, I think it would be nice to add a OrgMemberCheck class in mixins.py, and use this wherever required. Should I go ahead with this approach?

**Comment by oliverroick** [comment]
Fixed in #1924
