### ISSUE TITLE
Users with inactive account/unverified email should not be added to any organization

### ISSUE THREAD

**Issue by valaparthvi** [Cadasta/cadasta-platform#1389]
### Steps to reproduce the error
1) Make a new account, and do not verify the account.
2) Add that inactive account to an organization.

I created a username called "vatsal", and it has not been verified yet.
I added "vatsal" to an organization called "ABC" that I had created.

### Actual behavior
That member will be added to the organization without any error.
"vatsal" was successfully added to the organization "ABC"
![screenshot from 2017-04-07 00-45-50](https://cloud.githubusercontent.com/assets/11015077/24771586/cfb023a0-1b2b-11e7-84db-90f1c1bb34a9.png)

### Expected behavior
1) Perhaps, only verified users should be added to an organization.
2) If an organization admin tries to add an inactive user, an email reminder must be sent to the inactive account user, which says something like, " XYZ is trying to add you to their organization, please activate the account so that we can proceed further."

**Comment by wonderchook** [comment]
@valaparthvi thanks for this idea. I think this would make things complicated for org administrators. It is pretty typical to make a bunch of accounts for users and then add them to an org all at once. So if they had to wait until they were verified the process would be more difficult for them.

**Comment by valaparthvi** [comment]
okay, @wonderchook. I understand things would get complicated if org admins had to wait until a user had verified the account. But, once inactive account(user) is added to an org, do you think it would be a good idea to send a reminder to that user to activate their account?

**Comment by oliverroick** [comment]
Users get a reminder when they try to log in the next time. I don't think it's necessary to send this extra email.

**Comment by valaparthvi** [comment]
okay, @oliverroick.
