### ISSUE TITLE
Error message display over dashboard map

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#140]
Error alerts appear under the big map -- we need to mess with the z-index or something to get them appear on top instead.

**Comment by ian-ross** [comment]
@clash99 I assigned this one to myself, but I actually think it's something for you.  When you log into the platform, a message saying "You logged in as user blah" is supposed to appear.  Unfortunately, there's something funny about the z-index ordering of the messages and the main dashboard map, so if you're lucky, you see a flash of the message, then it disappears under the map.  I tried *very* briefly playing with some z-index values in the browser when we were in DC, but couldn't be bothered to investigate more then.  Now that you're doing CSS stuff though, do you think this is something for you?

**Comment by clash99** [comment]
yep, no problem - I'll check it out

**Comment by clash99** [comment]
Added position: relative and a z-index to #messages. #160

**Comment by ian-ross** [comment]
Looks good.  Thanks!
