### ISSUE TITLE
Added an Org on Demo and Don't have permissions to access members

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1405]
### Steps to reproduce the error

1. Create Organization
2. Go to Member tab to add a member and receive error message. 

### Actual behavior

An error message pops up indicating I cannot add members to an org I created. 

<img width="1101" alt="screen shot 2017-04-11 at 3 33 07 pm" src="https://cloud.githubusercontent.com/assets/25337622/24931887/49350c60-1ecc-11e7-81ac-fff80fd80896.png">

### Expected behavior

I expect to be able to add members since I am the admin of the org.

**Comment by SteadyCadence** [comment]
Logging in and out fixes the issue... but we should fix it.

**Comment by wonderchook** [comment]
@SteadyCadence are you able to reproduce it? Is it happening consistently? I agree about fixing it, but trying to get more to go on.

**Comment by SteadyCadence** [comment]
I tried reproducing on staging and could not.  I think there must be a specific caching/session setting that causes the permissions to act a little wacky.  Not sure what it is yet.

**Comment by dpalomino** [comment]
@clash99 volunteered to take a look, thanks!!!!

**Comment by amplifi** [comment]
All of the settings on staging and demo are the same, so variation between environments would be caused by something else. @SteadyCadence, on staging you're a member of 4 orgs and 0 projects. On demo, you're a member of 15 orgs and 2 projects. This sounds like a possible duplicate of #1232?

**Comment by SteadyCadence** [comment]
I was just thinking that... I am going to try again on demo to see if it is consistent.

**Comment by SteadyCadence** [comment]
Yes, it continues to happen in demo.  So that seems likely the issue... Hm. I will need to be able to set up demo accounts in the future so this could be a problem.  For now, I can have partners set up the accounts if need be.

**Comment by SteadyCadence** [comment]
Duplicate of #1232.
