### ISSUE TITLE
Long filenames breaking formatting in attach modal and location detail panel.

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1419]
### Steps to reproduce the error
Upload a resource with an silly long name.

### Actual behavior
<img width="930" alt="screen shot 2017-04-20 at 2 34 50 pm" src="https://cloud.githubusercontent.com/assets/8128188/25249223/c2d6f428-25d6-11e7-8f5c-b2b0748096a5.png">

<img width="431" alt="screen shot 2017-04-20 at 2 35 30 pm" src="https://cloud.githubusercontent.com/assets/8128188/25249226/c5a9d846-25d6-11e7-86f9-4a0d875016af.png">

### Expected behavior
Name would wrap so that the dataTable width stays constant.

**Comment by dpalomino** [comment]
thanks @linzjax  :-) @clash99, can you take a look please?

**Comment by clash99** [comment]
Added css to allow long file names to wrap.

<img width="456" alt="screenshot 2017-04-27 15 40 47" src="https://cloud.githubusercontent.com/assets/1119621/25503425/fbffa360-2b5f-11e7-8c5d-259913b71ca2.png">
<img width="1438" alt="screenshot 2017-04-27 15 40 58" src="https://cloud.githubusercontent.com/assets/1119621/25503426/fc010052-2b5f-11e7-829f-b28e14231db3.png">

**Comment by clash99** [comment]
Closing - already merged.
