### ISSUE TITLE
SMAP: Location adding/editing/deleting

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1421]
Since we don't have an open PR for this yet, I'm creating this issue as a place to collect my notes.
I don't know how much of this you already know, but here's my two cents FWIW:

### General:

- [x] `_createNew` in Editor, line 145: `feature.properties.url = 'records/location/new';` should be `'records/location/new/`

- [x]  `onLayerClick` in Editor, line 246: the `window.location.href = "#/" + feature.properties.url;` should have a `+ "/"` after.

- [x] in routes.js, update `records/location/new/` to this so the form is intercepted and the page isn't reloaded:
```
route('/records/location/new/', 'detail',
       route('/records/location/new/', 'detail',
        function () {
            rm.updatePage({
                'page_title': options.trans.location_add,
                'display_edit_panel': true,
                'display_modal': false,
            });
            map.locationEditor.fire('route:location:new');
        },
        function () {
            rm.updateState({
                'form': {
                    'type': 'location-wizard',
                    'success_url': 'overview',
                }
            });
        }
    );
```

- [x] You'll need to add `core_mixins.FormErrorMixin` to `LocationAdd` and `LocationEdit`
- [x]  The generic styling is inconsistent with what's already there, but that can be fixed later.
- [x]  Some of the issues that I ran into involved clicking the big save button before clicking the save button on the map. It was suggested in #1378 to add a JS hook so when a user clicks on the big save button, it covertly clicks on the little save button before submitting the form.

## Things I've ~broken~ tested:

- [x] When clicking between locations, they briefly flash pink, and then ones that had been click have the wrong border?
- [x] Sometimes geometries turn pink, then dark purple, then get confused.

### When adding a location:
- [x] The geometry toolbar is not shown in Chome/Mac, I can't draw the geometry. 
- [x] I finished adding a location and click "save" on the map. Realize I wanted to change it. Try clicking on the geometry. The geometry and tools locked up. Tried adding the location type and name and clicking "save" in the form. Get redirected to _just_ the location form with an error telling me I'm missing geometries. This redirect should be fixed after you update the route, but then it started just adding an extra backslash to the URL when I clicked on the geometry.
- [x] Started to add a geometry, decided halfway through I didn't want to, clicked cancel. Geometry is still on the screen.
- [x] Zooming around while in the midst of adding a geometry causes it to no longer be editable. 
- [x] Actually zooming around seems to cause all of the buttons to freak out. If I'm in the midst of deleting something and I've clicked on it to delete it, zoomed around, I then no longer have the option to save the deletion.
- [x] I added a geometry and hit save on the map. I then click on a _different_ polygon and was redirected to that geometries detail page. If I click on the geometry I just temporarily added, I'm taken to the location add page again. (or at least I was until I updated `records/location/new` to `records/location/new/`. Then I was redirected to `records/location/new//`
- [x] Saving the location add form causes the page to redirect, rather than using formSubmission to intercept. (should be fixed when you update the router and add FormErrorMixin)
- [x] When switching between types of geometries (square vs. polygon vs. point) I have to double click the buttons. Gets this error: `Cannot read property '_events' of null`
- [x]  When switching between types of geometries, the edit and delete buttons enable

### When editing a location:

- [x] If I edit a geometry, and then hit save in the form before hitting save on the map, the geometry stays in edit form, and everything is locked up until I go back to edit and hit save or cancel.
- [x] Hitting cancel doesn't revert the geometry back to its original shape. (Oliver: This works for me in Chrome)
- [x] If I delete the geometry in edit mode and try to save the form, it freezes. I get `Cannot set property 'innerHTML' of null` as an error.
- [x] If I delete the geometry and click cancel, the geometry doesn't come back until I refresh the page

### When deleting a location:

- [x] When deleting a location from its detail page, the geometry stays on the map

**Comment by SteadyCadence** [comment]
I'm noticing a bug on the current map interactions.  When editing a geometry...
...polygon: the map zooms to the extent of the polygon
...polyline:  at the moment cant create a polyline (filing a bug for that one)
...point (BUG): the map zooms out to the world map

**Comment by seav** [comment]
> point (BUG): the map zooms out to the world map

This is related to #718.

**Comment by oliverroick** [comment]
Let's be honest; we'll never dig this up from the graveyard of unfinished work. Closing.
