### ISSUE TITLE
No notification email is sent after adding a user to an organization.

### ISSUE THREAD

**Issue by valaparthvi** [Cadasta/cadasta-platform#1422]
According to the [documentation](https://devwiki.corp.cadasta.org/3.0%20Organizations#add-members-modal)
 > Once org admins have added the user a notification email goes to the user. The email includes a link that says “Did you not want to be added to this organization, click here.” That link then removes them from the organization. The user does not have to confirm they want to be added.

### Steps to reproduce the error
1) Add a user to an organization.

### Actual behavior
No notification email is sent to the user notifying they have been added to the organization.

### Expected behavior
A notification email must be sent to the user.

**Comment by seav** [comment]
Possibly related to #453.

**Comment by valaparthvi** [comment]
> Confirmation of getting added as an organization member (but only via the API)

I didn't quite understand when you said 'only via the API'. How are you suggesting this feature be implemented?

**Comment by dpalomino** [comment]
Hi @valaparthvi, thanks a lot for raising this!

Yes, indeed this is a duplicated issue of #453 as @seav mentioned. I think notification shoujld be sent in both circumstances, but currently is only working (or implemented) in the API. 

Closing this issue and doing the follow up in #453, please @valaparthvi feel free to jump in there.

**Comment by valaparthvi** [comment]
okay @dpalomino
