### ISSUE TITLE
Work in Progress :: Shapefile Export Issues

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1431]
### Steps to reproduce the error

1. Go to a project with data and export to a shapefile. 

### Notes
- [ ] project extent is exported in the shapefile (http://arcg.is/zrS5O)
- [ ] only ids are included in the attribute table of the polygon (ihttps://demo.cadasta.org/organizations/itc-university-of-twente/projects/itc-customary-rights/)

**Comment by alukach** [comment]
@SteadyCadence Any updates on this?

**Comment by wonderchook** [comment]
@SteadyCadence I think this is working as designed. (Not the project extent part that is a bug). Due to the limitation on shapefile column names they are exported in a different file and joined. @oliverroick is my memory correct?

**Comment by oliverroick** [comment]
Yes, that's correct. We figured it was too much work to work around the limitations of shapefile (field names, certain types), so you get a shape with all the geometries and IDs and a CSV with all the data. 

It might be worth replacing SHP with Geopackage, it's widely supported now and addresses the shortcomings of shape file.

**Comment by dpalomino** [comment]
To be followed in #1498, closing this issue.
