### ISSUE TITLE
Date are inconsistent between display/edit in location

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1434]
2017/01/01 is a valid, date but when I make edits to other attributes and save I'm told "Enter a valid date"

![image](https://cloud.githubusercontent.com/assets/67992/25491121/e1037366-2b23-11e7-9cd5-775f7704d86c.png)

Then when I make the date valid and save it I am shown it in the original format

![image](https://cloud.githubusercontent.com/assets/67992/25491189/0f6abf52-2b24-11e7-9b18-44aad2997a79.png)

**Comment by clash99** [comment]
Notes - Entering 01/01/2017 or 2017-01-01 seems to work.  As mentioned above, 2017/01/01 doesn't work.  01-01-2017 doesn't work either.

**Comment by dpalomino** [comment]
Hey @clash99! This is a nice to have for Sprint 19, only if you have time. Thanks!
