### ISSUE TITLE
Semi-Custom Reporting

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1456]
Draft Requirements: https://devwiki.corp.cadasta.org/Semi-Custom%20Reporting

generate reports from data in the platform for users

"We should provide some funcitonality to generate custom reports (considering the permissions of the users generating the report). This could include status reports at project level, a hh report for applying for some kind of tenure recognision, etc.

Example of report at a project level: project extent showing locations geometries included, stats (# locations, parties, resources), area covered, org/project logo, etc. 

Example of report at a HH level: location geometries and its immediate surroundings, location fields, party/parties fields, area. Logo of project/org"

**Comment by amplifi** [comment]
Superseded by #1609. Closing to continue with that issue.
