### ISSUE TITLE
Questionnaire Validation Is Not Working for Required Fields

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1461]
### Steps to reproduce the error
1. Upload questionaire without any of the required fields
2. Questionnaire uploads succesfully.

### Expected behavior
I expect to get an error about missing party_name or location_type. 

While the form uploads successfully, the record will not submit in GeoODK.

**Comment by SteadyCadence** [comment]
Also related (but not a new bug because it has been an issue I have run into):  We should not allow users to upload forms that have the *required fields inside groups*.  For example, if location_type is listed inside the location_attributes then the records will not submit properly with GeoODK.

**Comment by dpalomino** [comment]
Thanks @SteadyCadence 
Related to this: 

> Also related (but not a new bug because it has been an issue I have run into): We should not allow users to upload forms that have the required fields inside groups. For example, if location_type is listed inside the location_attributes then the records will not submit properly with GeoODK. 

I think we could leave this as it is for now. With the sample XLSForm we can cover this for now until we develop the UI form builder...

**Comment by oliverroick** [comment]
We need to validate that the following conditions are met:

- At least one of `location_geoshape`, `location_geotrace` or `location_geometry` is present; all questions that are present must be `required=yes`. 
- `location_type` is present and `required=yes`
- `party_type` is present and `required=yes`
- `party_name` is present and `required=yes`
- `tenure_type` is present and `required=yes`
