### ISSUE TITLE
Error Handling for AttributeType Errors :: Worth fixing? Wait for project wizard?

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1462]
### Steps to reproduce the error

There are a number of situations in the form building process that can cause platform errors (and not nice, clean descriptive errors). 

It would be nice to improve the errors esp for GeoODK use.

Situations
- [ ] An image, video or audio is inside a group
- [ ] A required field (party_name, party_type, location_type, etc) is inside of a group
WIP...

### Actual behavior

When upload form with an issue, a 500 error occurs on the platform and there is a `AttributeType matching query does not exist.` error.

### Expected behavior

Expect a warning, like the other errors, about why the form does not work with the platform.

**Comment by dpalomino** [comment]
Hi @SteadyCadence. As we talked during the meeting, I think it's worth to wait until the form builder is done. There are many ways to break xlsforms and it'd be difficult to parse all of them. 

Closing for now, reopen please if needed.
