### ISSUE TITLE
Export project data isn't as expected

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1463]
### Steps to reproduce the error

Download all data for a project that has locations, relationships, parties, and resources

### Actual behavior

I'm only seeing resource files, shape files, 2 empty xlsx files (I open them in Numbers), and a readme file.

### Expected behavior

As the readme files states, I would expect to see locations.csv, parties.csv and relationships.csv.

<img width="996" alt="screenshot 2017-05-03 09 14 52" src="https://cloud.githubusercontent.com/assets/1119621/25665112/47d1dcaa-2fe2-11e7-9ecf-1b2878ba8c36.png">

![screenshot 2017-05-03 09 15 06](https://cloud.githubusercontent.com/assets/1119621/25665227/8a86e450-2fe2-11e7-86de-d31e1bd0625c.png)

<img width="645" alt="screenshot 2017-05-03 11 24 55" src="https://cloud.githubusercontent.com/assets/1119621/25670711/2fa5ebc4-2ff3-11e7-877e-af9d3d2dc095.png">

[chandras-test-project-export.zip](https://github.com/Cadasta/cadasta-platform/files/973630/chandras-test-project-export.zip)

**Comment by alukach** [comment]
Possibly related to #1400.

**Comment by dpalomino** [comment]
The xlsx files can be opened with Excel or Google Spreadsheet. I think there is a specific issue for this (to raise an issue for this). 

csv files I think are no longer needed as data is already in the xlsx files. I think we need probably to update the README file.

**Comment by dpalomino** [comment]
Assigned to Chandra, thanks! :-)

**Comment by clash99** [comment]
The readme is correct now without the resources included. 

![screenshot 2017-06-07 09 41 51](https://user-images.githubusercontent.com/1119621/26884548-a3113cd4-4b65-11e7-9aa1-537e154571f6.png)

We should double-check it once resources are included once.  I'm closing this task.
