### ISSUE TITLE
Superusers can't view private projects in Projects list

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1470]
### Steps to reproduce the error

Private projects are hidden from the Projects list, even for superusers. This means there is no way to determine the total number of projects in an environment without manual database access.

### Expected behavior

Private projects should appear in the Projects list for superusers. It's critical that we be able to monitor the total number of projects in an environment. This will also be necessary in order to implement #1418 Superuser management tools; we would not be able to archive private projects via the tools if they are not visible.

**Comment by clash99** [comment]
Related - I suggest we follow a private project's name with a small "private" icon.

**Comment by amplifi** [comment]
Related: On the Organizations page, archived organizations show 0 projects, even if there are archived projects under that organization. Superusers should be able to view an accurate project count for both archived and active organizations.

**Comment by amplifi** [comment]
Resolved by PR #1651
