### ISSUE TITLE
Search: unsafe use of subprocesses & curl

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1471]
Both search and search exports spawn subprocesses to execute `curl`. In search export, there's no explicit timeout applied to either the `curl` or the subprocess itself, no return code check, etc. These uses of `subprocess.run()` and `curl` should be replaced with a safer mechanism that properly handles the calls and results/cleanup; plenty of formal options exist for implementing the two use cases with a lower level of risk).

https://github.com/Cadasta/cadasta-platform/blob/bc33ec47831432b7b5e5a324fbbd1fd09d2d1f26/cadasta/search/export/resource.py#L55

https://github.com/Cadasta/cadasta-platform/blob/665d7103f41001fcf9758568652724ff5930cb54/cadasta/search/views/async.py#L281

**Comment by seav** [comment]
Since the search export feature has been removed, and if we put it back it should be an asynchronous process by then, I think we can close this issue.
