### ISSUE TITLE
Superuser role views are different on local host versus other sites

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1472]
### Steps to reproduce the error

- Sign in to localhost as a superuser and you can view the users tab

![screenshot 2017-05-05 09 26 33](https://cloud.githubusercontent.com/assets/1119621/25750038/24f2f792-3176-11e7-8c66-fafddf48605b.png)

- Sign in to staging, demo or platform as a superuser and you cannot view the users tab

- Left subnavs within a project or organization are displayed on localhost but not others

- More actions buttons within a project or organization are displayed on localhost but not others

### Actual behavior

- There is a difference in the superuser role views on the different sites.

### Expected behavior

- I would expect them to all be the same view for a role. (I'm creating this issue for a permissions review since I anticipate there may be other bigger issues behind this.)

**Comment by clash99** [comment]
Questions to verify:

- At attempt to unarchive project that belongs to an archived org, what happens?

**Comment by oliverroick** [comment]
@clash99 Is this now sorted with PR #1651?

**Comment by amplifi** [comment]
Confirmed; this is fixed as of #1651
