### ISSUE TITLE
Organization "add button" disappears on member detail page

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1474]
### Steps to reproduce the error

- As an ORG ADMIN for an organization, select a member detail page.

### Actual behavior

- The "add button" disappears on the member detail page.

### Expected behavior

- The buttons in the header area should remain consistent for all pages within an organization.

![screenshot 2017-05-05 11 21 31](https://cloud.githubusercontent.com/assets/1119621/25754618/87122628-3185-11e7-9c84-35ad2dc758da.png)
![screenshot 2017-05-05 11 21 41](https://cloud.githubusercontent.com/assets/1119621/25754619/8714bbb8-3185-11e7-99c7-8ebf7cd50a96.png)

**Comment by dpalomino** [comment]
Thanks @clash99. Are you referring to the "Add project" button, right?

**Comment by clash99** [comment]
Quick code check reveals there is something buggy with the `if add_allowed` condition for org admin. Since these permissions are being replaced, I think we can close this one.
