### ISSUE TITLE
Add profile image to user dashboard

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1485]
## Objective
Allow users to upload and manage an image for their profile:
- [ ] Integrate profile image in user profile page (upload, ~~crop~~, replace, delete)
- [ ] Integrate library of placeholder avatars to be used if no profile image is provided
- [ ] Integrate profile image in top navigation bar
- [ ] Integrate profile image display in members area on dashboards
- [ ] Integrate profile image in member management

Keep in mind the various sizes that might be needed across the platform.

## Guidelines

For S3: https://cadasta.slack.com/archives/C0CLK7X2M/p1498234203590585

## Sample placements below

**Header area next to username**

![screenshot 2017-03-09 19 29 45](https://cloud.githubusercontent.com/assets/1119621/23778330/42a5af12-04ff-11e7-8d9d-bdadc3ea320d.png)

**Member list used in an overview page**

![project dashboard](https://cloud.githubusercontent.com/assets/1119621/23778436/c319ccaa-04ff-11e7-857b-19ac7722cd68.png)

**Member permissions page**

![screenshot 2017-03-09 19 33 03](https://cloud.githubusercontent.com/assets/1119621/23778419/a0d5f1dc-04ff-11e7-8a40-994211108c76.png)

**Comment by clash99** [comment]
Will also be used for #1447 team member area.

**Comment by laura-barluzzi** [comment]
@clash99 are the project and organization dashboards released?

**Comment by clash99** [comment]
@laura-barluzzi No, I believe they will be included in the next release.

**Comment by laura-barluzzi** [comment]
@clash99 just an update: I am working on using the [cropit open source package](https://github.com/scottcheng/cropit) to add the profile image. You can see their [demos here](http://scottcheng.github.io/cropit/).

**Comment by clash99** [comment]
@laura-barluzzi - Your branch looks good with the adding of the user profile image. I think we should wait on the other issues on this task (adding the avatar throughout the site next to the user name) until after the user dashboard is complete. This will provide a bigger incentive for users to add their avatar.
