### ISSUE TITLE
Exports in xlsx format is not compatible with Mac OS Numbers

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1496]
### Steps to reproduce the error

1. Download data from a project in xlsx format
2. Try to open with Numbers (Mac OS app) 

### Actual behavior

No data is shown. 

### Expected behavior

Data should be properly processed by the app. However the file can be properly open using Excel or Google Sheets.

**Comment by oliverroick** [comment]
We discussed this before; this is a bug in Numbers. I assume there's not much we can do...

**Comment by dpalomino** [comment]
Ah, thanks @oliverroick. I didn't remember. Closing the issue.
