### ISSUE TITLE
`vagrant up` fails with npm error

### ISSUE THREAD

**Issue by ingenieroariel** [Cadasta/cadasta-platform#150]
TASK [cadasta/application : Install Bootstrap for SASS processing] 

    *************
    fatal: [default]: FAILED! => {"changed": true, "cmd": ["npm", "install", "bootstrap-sass"], "delta": "0:00:04.139813", "end": "2016-04-19 10:33:07.392522", "failed": true, "rc": 1, "start": "2016-04-19 10:33:03.252709", "stderr": "npm ERR! Linux 3.13.0-77-generic\nnpm ERR! argv \"/usr/local/bin/node\" \"/usr/local/bin/npm\" \"install\" \"bootstrap-sass\"\nnpm ERR! node v5.5.0\nnpm ERR! npm  v2.15.3\n\nnpm ERR! shasum check failed for /tmp/npm-13815-72c3e731/registry.npmjs.org/bootstrap-sass/-/bootstrap-sass-3.3.6.tgz\nnpm ERR! Expected: 363b0d300e868d3e70134c1a742bb17288444fd1\nnpm ERR! Actual:   1156e2260fc64cff2a6867c1b7f6457d93e564ff\nnpm ERR! From:     https://registry.npmjs.org/bootstrap-sass/-/bootstrap-sass-3.3.6.tgz\nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /vagrant/cadasta/core/npm-debug.log", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by ingenieroariel** [comment]
Running `vagrant provision` a second time fixed the issue. I just pasted it here to help future googlers. Closing.

**Comment by ian-ross** [comment]
Right.  This is because NPM just goes away sometimes.
