### ISSUE TITLE
Add ability to add user to project as a public user

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1505]
Right now if a user is added to an org the lowest level of permissions they can have is project user. It should be possible for org admins to add users to an org and give them public user access to some projects. This would mean for example in private projects that they could not see the project. 

Feature use case: When a project manager invites a user to a project they should be able to set the users permissions for that project. All other projects the user should be added as a public user.

**Comment by clash99** [comment]
It is possible for an org admin to assign the role of Public User now. Actually the Public User role is the default for new users. I'm not sure we need any changes right now. When we do implement adding users at the project level, we need to ensure they are automatically assigned Public User roles to other organization projects. 

<img width="1256" alt="screenshot 2017-05-12 19 57 30" src="https://cloud.githubusercontent.com/assets/1119621/26021166/ecaae29a-374d-11e7-9e99-b5621e7f7b1d.png">

**Comment by dpalomino** [comment]
Yes, agree @clash99. It is already included in the description of the feature (in the old backlog spreadsheet, need to move it to the github backlog). 

I think we can close the issue for now. Please reopen if needed.
