### ISSUE TITLE
Add an async view to serve spatial resources

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#1513]
### The issue

Loading of spatial resources takes place via a request to an api endpoint at `/api/v1/organizations/{org}/projects/{prj}/spatialresources/`. This endpoint should not be used from clientside javascript. Instead, an `async` endpoint should be created to serve `spatialresources` to the platform UI. 

### Actual behavior

Uses an `api` endpoint rather than an `async` endpoint for loading spatial resources.

**Comment by alukach** [comment]
I would like to leave my 2 cents in that I believe we should push against the idea of creating anymore `async` endpoints. By having both `async` and `api` endpoints to handle AJAX requests, we are undermining the `api` and deterring the api from becoming full-featured and battle-hardened. I do think the `async` endpoints do have their purposes at times, for example returning HTML snippets for the SMAP or other very specific-to-Cadasta one-off use cases that are likely unneeded outside of our application.  I think the general rule of thumb should be that any AJAX requests made by Cadasta should be made through our API unless there is a very good reason to deviate from that pattern.

**Comment by dpalomino** [comment]
Agreed during triage to close the issue.
