### ISSUE TITLE
Provide attribution for the country borders dataset

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#152]
As discussed during the April 20 dev call, we should provide some sort of attribution to the country borders dataset that is used to determine country where a project is located (1b602ae5c19d248c04b9c83514406a64e930d28b). The dataset is sourced from [Thematic Mapping](http://thematicmapping.org/downloads/world_borders.php) and it says there that the dataset is licensed under CC-BY-SA 3.0.

Not discussed during the meeting, but possibly important, is the licensing of the `country` field in the projects that were derived from the dataset. In some circles, the set of `country` fields is considered a derivative dataset and thus needs to adhere to the share-alike license. (Cue in OSM licensing debates.)

An alternative solution is to use the [Natural Earth](http://www.naturalearthdata.com/) dataset which is [under the public domain](http://www.naturalearthdata.com/about/terms-of-use/). Thus there is no need for attribution and this also avoids any derivative data licensing issues too.

This issue is not urgent but will eventually need to be resolved before the official release.

**Comment by wonderchook** [comment]
For attribution we should have an about page, since I suspect this won't be the only case.

Specific to the derivative dataset I don't think this would be the case under US law. @nastynoel is working with lawyers on this and would be the right person to investigate. If it is an issue than Natural Earth seems the right path to me.

**Comment by ian-ross** [comment]
I've partially fixed this (PR #158 was today's morning warm-up exercise) replaces the Thematic Mapper dataset with the Natural Earth dataset.  I'll leave the issue open and move it to Backlog as a marker for this more general attribution question.

**Comment by wonderchook** [comment]
closing until attribution needs change
