### ISSUE TITLE
Add member form can be submitted more than once

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1543]
### Steps to reproduce the error
- Go to the member list for an organization.
- Add a member.
- Click the submit button twice.

### Actual behavior
- Error that this user has already been added to the organization.

### Expected behavior
- Submit button is disabled after the first click.

**Comment by laura-barluzzi** [comment]
Hi, is this still an issue? Because you could replicate the same solution I applied to others forms in my contribution back in March. There is a`core/static/js/form_submit.js` document that literally I created for this purpose. It just needs to be added in the form template.

**Comment by laura-barluzzi** [comment]
Hi, is this finished? Is there anything else to check? If not, it looks like this issue can be closed .
