### ISSUE TITLE
"Previous" button in step 2 of project wizard links to next page

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1545]
### Steps to reproduce the error

1. Create a new project
2. Click next in the project extent step
3. On the project details page, click the "previous" button

### Actual behavior

You end up on the permissions page.

### Expected behavior

You should end up on the project extent page.

**Comment by wonderchook** [comment]
@oliverroick to reproduce this I had to do:

1. Create new project
2. Click next on the project extent step
3. Give project a name
4. Click "previous"
5. Click "next"
6. "Click "previous"
