### ISSUE TITLE
Party detail page should have `can_edit` and `can_delete` checks

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1546]
### Steps to reproduce the error
- Sign in with a Project User
- View a party detail page

### Actual behavior
![screen shot 2017-05-30 at 3 29 08 pm](https://cloud.githubusercontent.com/assets/8128188/26601167/df12b1be-454c-11e7-9f72-0e7b1f3b0c8d.png)

The edit and delete buttons appear in the top left corner

### Expected behavior
- Should match behavior on location detail page.

**Comment by linzjax** [comment]
Same with the Relationship Detail page

**Comment by dpalomino** [comment]
Thanks @bjohare, will take a look at the same time he is working on tutelary stuff.

**Comment by dpalomino** [comment]
Hey @bjohare. Did you have a chance to take a look to this issue?

**Comment by bjohare** [comment]
Not yet. Will look today.

**Comment by oliverroick** [comment]
Duplicate of #1693. Closing
