### ISSUE TITLE
Non org member can add/edit/delete projects and project data

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1547]
### Steps to reproduce the error

On staging, user name **clash** and I'm not a member of an organization but can add/edit/delete projects and project data.

<img width="1356" alt="screenshot 2017-05-30 21 41 29" src="https://cloud.githubusercontent.com/assets/1119621/26613651/6b07b71c-4581-11e7-97a5-0357e42c94df.png">

### Actual behavior

Can add project and add/edit/delete project data.

<img width="1361" alt="screenshot 2017-05-30 21 42 56" src="https://cloud.githubusercontent.com/assets/1119621/26613726/cb45f4fe-4581-11e7-8abc-5745c9ca2297.png">

### Expected behavior

I shouldn't be able to do any actions if I'm not a member of the organization.

**Comment by amplifi** [comment]
clash was made a superuser on 5 May for testing the superuser views. Does this happen with any other accounts? (And let me know if you'd like it reverted to a regular account.)

**Comment by clash99** [comment]
@amplifi - Thank you. I had forgotten about that and since the other superuser bugs exist, I couldn't tell by looking at anything that I was a superuser. I'm going to add a task to add a superuser badge or something similar to the right of the username when logged in. I think this is good timing with the user dashboard stuff coming up. I will close this task.
