### ISSUE TITLE
Cannot upload forms with certain language fonts

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1549]
### Steps to reproduce the error

1. Go through the project steps and upload this questionnaire ([questions.xlsx](https://github.com/Cadasta/cadasta-platform/files/1041874/KESANquestions.xlsx)).
2. Get an error saying "Input does not support special characters, emojis, +, -, @"

### Actual behavior

We need to test if the Karen script or the Myanmar script is causing the issue.  I have a feeling it may be the Myanmar script because that one is not a Unicode font and does not get viewed properly in Cadasta.

### Expected behavior

I expect specific fonts that our partners use to be supported.  It may be that the myanmar font we are using is not Unicode and not being able to be read properly in Cadasta.

**Comment by wonderchook** [comment]
@SteadyCadence can you include some samples? You mentioned this was working on demo?

@oliverroick perhaps related to sanitation?

**Comment by SteadyCadence** [comment]
I uploaded the questionnaire.  I am almost 100% it has to do with the non-Unicode fonts in the ::my column. At least I hope that is the issue... :)

**Comment by wonderchook** [comment]
@SteadyCadence so it did let you upload the questionnaire? Or did you mean you added it to the ticket?

**Comment by clash99** [comment]
WIP font research:

- http://kanyawtech.org/tutorials/fonts

**Comment by dpalomino** [comment]
Hi, 

@SteadyCadence already uploaded, it was in the description, link [here](https://github.com/Cadasta/cadasta-platform/files/1041874/KESANquestions.xlsx)

**Comment by SteadyCadence** [comment]
It was the unsupported Unicode font in the questionnaire that caused the error.

**Comment by SteadyCadence** [comment]
I lied.  It is still happening with one computer.  I am going to record a GIF and find the version of it. Its Windows 10 Edge 38.14393.1066.0; EdgeHTML 14.14393 circa 2016

**Comment by dpalomino** [comment]
hey @SteadyCadence, can you upload the new questionnaire?

With the old one it is also happening to me with Mac OS 10.11.16, Chrome 58.0.3029.110 (64 bit). 

Error message: "Input can not contain HTML tags, emojis or start with any of + - = and @."
![screen shot 2017-06-01 at 11 19 25](https://cloud.githubusercontent.com/assets/17198051/26673221/65fcb7ea-46bc-11e7-826a-8cbdb33a4fda.png)

**Comment by SteadyCadence** [comment]
I need them to send it. They are testing.  Can you remove the `::my` columns?  That will let it work.

**Comment by dpalomino** [comment]
We have been reviewing during the programs call. This is only happening with non-unicode Burmise language, which is not properly displayed anyway, so having the questionnaire rejected during the upload does not make a real difference. 

Closing the issue for now, pease reopen it if needed. Thanks all for the checking this!
