### ISSUE TITLE
Ability to upload custom fonts in Cadasta for specific partners

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1550]
### Steps to reproduce the error

If there was a way in the organization settings to upload specific .tffs and/or font files then I think we could support KESAN better. This may be the difference between them using us or keeping with their current workflow. 

I am still working out the kinks (seeing how to get the scripts to work locally). 

It would require being able to load the files and font (via CSS) for reading.  And then also maybe the keyboard somehow.  Google maps has something for that... still looking into it. 

### Actual behavior

When we type in the script on Excel, it works well but when we load it up in Cadasta the characters are "sticking" to each other, missing (Chrome) and/or different sizes (Firefox)-- making it difficult or impossible to read.

**Comment by wonderchook** [comment]
removing the priority label. Features need to be prioritized in the backlog against all the other features and partner requests.

**Comment by SteadyCadence** [comment]
I am closing this.  I think this is not the best solution for the issue at hand.

**Comment by clash99** [comment]
Just adding this note while fresh: One option might be to list Noto fonts that can be selected.  https://www.google.com/get/noto/
