### ISSUE TITLE
Possible solution for converting KNU to KNU Unicode (which is supported in Cadasta)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1552]
These scripts look like viable solutions for converting KNU files into KNU Unicode files. 
http://kanyawtech.org/development/scripts

They essentially re-map the characters so that they fit the web font standards (Unicode). 

Can we get this script to work on the example files: https://drive.google.com/drive/folders/0B7s_glOIxR37dzVfcUl6M3p4Mk0

** Probably requires the installation of KNU.tff (sent in email to clash, david, anthony) and KNUUnicode (install .tffs in this folder-- https://drive.google.com/drive/folders/0B26r9x9LftJDOUpsNHk1ZXh1Sms)

**Comment by SteadyCadence** [comment]
I think we may be getting close!!! I popped the script in the C:\Python\Scripts file and ran it from the PowerShell on Windows.  I had to make one adjustment to the script-- remove the encoding='ut8' parameter because that is not supported in Python2 (only Python 3).

Files:
[interview.txt](https://github.com/Cadasta/cadasta-platform/files/1044081/interview.txt)
[Unicodeinterview.txt](https://github.com/Cadasta/cadasta-platform/files/1044082/Unicodeinterview.txt)

View:
![success](https://cloud.githubusercontent.com/assets/25337622/26670929/dd0932ac-46dd-11e7-8523-22622963dc6b.PNG)

This will likely solve the issue of being able to copy and paste text.

We still need to support Karen script on the platform so that users do not have to install the script locally.  @clash99-- should I write that up as an issue?  We still need a solution for that.  At the moment people without the script see empty boxes.

**Comment by clash99** [comment]
Adding fonts to platform will be covered by #1554.

**Comment by amplifi** [comment]
Flagging this -- even if we can get the character set mapping to work, for any non-Unicode charset portions of the platform will still not function (at all, or may exhibit unpredictable behavior), including but not limited to: any type of sorting, search, string validation...

**Comment by clash99** [comment]
I believe we can close this with approval of [DR-0009](https://github.com/Cadasta/decision-records/blob/master/DR_0009_custom-fonts.md), which stats we will only support Unicode fonts. @amplifi - Can you close this if you agree?

**Comment by amplifi** [comment]
@clash99 👍 I think we're good. Closing.
