### ISSUE TITLE
Put indicator next to username if superuser

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1553]
Add an indicator next to the username in the header if user is a superuser. This will acknowledge the permission level for a superuser.

**Comment by clash99** [comment]
Adds small badge "SU" to right of user name if superuser.

![screenshot 2017-06-06 08 41 35](https://cloud.githubusercontent.com/assets/1119621/26834597/637de718-4a9b-11e7-8a07-f67ee26224aa.png)

**Comment by dpalomino** [comment]
PR was already merged. Closing the issue.
