### ISSUE TITLE
Ability to Associate GPX Files with Locations

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1556]
A few partners would like to add land parcels and information to the map using gpx as the source of the land data.  

When they "Add New Location", there should be an option to "Upload GPS trace" and choose to have it show up as a (1) map layer or as (2) the location geometry.

**Comment by dpalomino** [comment]
@SteadyCadence and I have been catching up regarding this feature.

Right now the GPX import implementation is oriented to show a layer on the map with the data contained in the GPX file, so we can enable/disable a few layer on the map. 

But the feature is not designed to use this GPX information to actually create a location. Some partners (specially those working with paper and transcribing the information later on via WUI) are using external GPS devices and .gpx and .gdb files to capture the location geometries. We need a way to be able to create a new location (at least the geometry) using those files and without showing them as layer on the map (as we cannot handle potentially thousands of them). 

I think this a good topic to discuss in our in-person meeting in Madrid. 

cc @clash99 @bjohare 

Also related to #664.

**Comment by dpalomino** [comment]
Being now followed via #1590. Closing.
