### ISSUE TITLE
String Sanitation - Organization and Project URLs accepts emojis

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1559]
Thanks @linzjax for detecting this. Issuing individual issues from the comments in PR #1395.

Steps To Reproduce:
1. Go to project or organization URL (when creating a new project/org or when editing the details)
2. URL field accepts emojis

**Comment by amplifi** [comment]
Emoji are valid characters in a URL (and there's even an emoji URL shortener: http://www.🍕💩.ws ) so we'll need to decide how we want to handle this.

**Comment by amplifi** [comment]
Because emoji are valid URL characters, we need to ensure the platform supports them else we're breaking from spec. Projects containing an emoji in the URL haven't caused any problems so far. Open a new issue if identified.
