### ISSUE TITLE
String Sanitation - Uploading questionnaires with emojis or script code 

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1560]
In relation with PR #1395. 

For emojis. Uploading questionnaires when creating projects:

1. You can include an emoji in a column name of a questionnaire (I tested with "tittle" column in settings tab). Interestingly:
    + If included in the "tittle" column of the settings tab, it is accepted. Example here
    + If included in the "name" column of the survey tab, it is not accepted (but you are able to upload)
2. I tried to change the tab name to include an emoji, and was rejected but not because we were filtering emojis, but because there were missing information:
![image](https://cloud.githubusercontent.com/assets/17198051/26787439/46ef47fe-4a0a-11e7-90c2-a164558b9af8.png)

For scripts: 

1. Including script in the "hint" column (hint<script>asdf</script>)is accepted and you can actually create a project, see [here](https://platform-staging.cadasta.org/organizations/david-3/projects/asdf2/). But in others columns (like tittle and name) is accepted. 

2. Same behaviour for title column in settings tab, was able to include "title<script>ha!</script>" and project was created (check [here](https://platform-staging.cadasta.org/organizations/david-3/projects/asdf3/))

**Comment by oliverroick** [comment]
I just spent 45 minutes trying to reproduce the issues reported only to find out that you're referring to column names, which we don't store. Closing.
