### ISSUE TITLE
Adding user names and emails cap sensitive?

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1563]
I struggle with adding members to orgs sometimes and I think it may be because they are cap sensitive.  Is that possible?  If so can we have a function that converts everything to lowercase on the backend so that when I write "Fpichel" it gets treated the same as "fpichel"?

Same with emails.

**Comment by dpalomino** [comment]
Yes, they are cap sensitive. Not sure if there is a security reason for this, but I agree it'd be better to make them case insensitive. 

Thoughts @amplifi @clash99 ?

**Comment by amplifi** [comment]
The security reason for this was that usernames were originally case-sensitive, so everywhere else usernames were referenced needed to be case-sensitive.

We made usernames case-insensitive in #946, so the Add Member field can now be changed to case-insensitive.

**Comment by dpalomino** [comment]
Thanks @amplifi for the clarification :)  

Adding as a bug then.
