### ISSUE TITLE
Remove max char length for tenure_type

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1576]
I need this character length removed for custom values!!

https://github.com/Cadasta/cadasta-platform/blob/4ba5b2527f4f6a973b9135b876e15de5dad872a8/cadasta/party/migrations/0003_convert_tenuretype_to_charfield.py

**Comment by seav** [comment]
Just use an abbreviation for the type (like "LH" for leasehold). Then use the full name as the label in the XLSForm.

**Comment by SteadyCadence** [comment]
Yea, I can work around it for now.

The abbreviations don't work well when you are using the QGIS plugin.  Right now it only pulls down the "keys"/names of the fields.  I guess that is the root of the problem--> QGIS only using the names of the fields and not the labels.

**Comment by dpalomino** [comment]
Dup of #1575. Closing this for now.
