### ISSUE TITLE
Broken links to devwiki.corp on readme

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1582]
### Steps to reproduce the error

Text on readme: See the wiki ([here](https://devwiki.corp.cadasta.org/Installation) and [here](https://devwiki.corp.cadasta.org/Run%20for%20development)) for detailed instructions on installation and running the platform for development.

### Actual behavior

Links to devwiki.corp are broken

### Expected behavior

Expect to go to wiki with instructions

**Screenshot of error:**

![screenshot 2017-06-12 11 07 07](https://user-images.githubusercontent.com/1119621/27043309-4ea8b782-4f5f-11e7-941b-96fc47554270.png)

**Comment by amplifi** [comment]
Fixed; this was an SSL certificate issue.
