### ISSUE TITLE
SMap Geometry Loading Performance Issues

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1600]
### @alukach 
**Tile loading overwhelming server, failed requests does not clear "loading locations"**

* Test with a large set of data (eg https://platform-staging.cadasta.org/organizations/12345-bleep-bloop-2/projects/all-of-mexico/#/overview/)
* A large number of XHR tile requests are initiated, most of them in "pending" status. At this time, the server pool becomes saturated and requests are waiting for other requests to finish before they can begin.
* If a request is in "pending status" for too long (1min), our server (I believe this would be NGINX) returns a 504 response.

**Result**: "Loading locations..." never clears

![image](https://user-images.githubusercontent.com/897290/27138792-92aec9fa-50de-11e7-838c-867d075b55d4.png)

**Expected Result**: If requests fail, that should be handled by our JS, likely delivering a notification of such to the user and clearing the "Loading locations..." indicator.

---

### @alukach 
**General tile request performance**

As mentioned in the above bug, the tile loading is very hard on our servers. I don't know if it's considered appropriate to suggest solutions here but here are a few thoughts as to how we could avoid this.

We basically have 4 variables to play with: 
* \# of simultaneous requests
* response time of each request
* limit of # request handlers
* timeout window for requests

We can improve how we work with those variables by the following, respectively:
* throttle the number of simultaneous requests we make. Our servers can currently handle 10 simultaneous requests. I'd suggest our front-end code never make more than 8 concurrent requests.
* some of my tiles took above 45 seconds to load (eg https://platform-staging.cadasta.org/async/organizations/12345-bleep-bloop-2/projects/all-of-mexico/spatial/tiled/4/3/6/?1497450446145). These could be prerendered or cached, with preference going to prerendering.
* we could expand the number of request handlers on the server. This could be either scaling horizontally or making a bigger pool size.
* we could increase the request timeout setting, however this is certainly a bad idea

I think the order of solutions written matches the order in which we should approach the problem for sake of ease.

---

### @linzjax

@alukach recommendations are definitely welcome. This one might need its own bug log since it's a bit more complex. I was sort of surprised at how poorly it's performing since it handled 6000 records without a hiccup on local.

It's also an issue that it's not canceling requests for tiles whose requests themselves have been canceled

---

### @alukach 

@linzjax Regarding the issues around performance being it's own bug, I think it comes down to how far with the solution we want to go.  I was about to recommend simply ensuring that we never make more than 8 concurrent requests as a first step, however [reading into it](https://stackoverflow.com/questions/10276784/jquery-limit-the-number-of-simultaneous-ajax-requests) it looks like browsers do this automatically so maybe my suggestion is misguided.

Have we done a once-over to see if we can get large requests to return a bit more quickly?  Something like https://platform-staging.cadasta.org/async/organizations/12345-bleep-bloop-2/projects/all-of-mexico/spatial/tiled/5/6/13/?1497464353224 seem to be timing out often. 

---

### @linzjax 

@alukach I think it's the complexity of the geometries. Because there are some that are incredibly jagged (i.e. have a ton of individual points). Was it you I was talking to about simplifying geometries at lower zoom levels?

---

### @alukach 

Yeah, we discuessed that although that operation itself may be expensive.  Another thought is that we could trim off some of the decimals from the coordinates to make the response size smaller (currently they're super precise), although again it's a question of whether trimming that down could cause more latency in the system (I doubt it would, although I also doubt it would make a huge difference either).

If we do end up saying that prerendering the tiles is the right way to go, then I do agree that it should be a separate issue.

---

### @amplifi 

@alukach @linzjax The performance issues here are actually caused by the large file sizes for tiles. This isn't going to be viable in production, especially with our requirements to support lower bandwidth connections.

Using the example project from @alukach ( [https://platform-staging.cadasta.org/organizations/12345-bleep-bloop-2/projects/all-of-mexico/#/overview/](https://platform-staging.cadasta.org/organizations/12345-bleep-bloop-2/projects/all-of-mexico/#/overview/) )... I didn't encounter the timeouts, because I wasn't testing SMAP at the same time as everyone else. The effects on performance wouldn't occur in local dev VMs because there's a max of one user at a time, and tiles are being generated locally rather than being downloaded from a remote server.

Looking at the page load breakdown below:
<img width="742" alt="screen shot 2017-06-15 at 9 45 33 am" src="https://user-images.githubusercontent.com/4269749/27170831-ad6feacc-51af-11e7-9ca1-69fdbf37a781.png">

There's a total transferred content size of ~15MB to load the project overview page. This includes the existing gzip compression, and according to Opbeat results in load times up to 57 seconds with no other traffic to the server at the time. These files are too large for a single page load given our target user base -- particularly for a project's default view. It doesn't matter how long a timeout we set[1], whether or not we enable caching of tiles[2], whether or not we throttle/how many concurrent connections we support on the server side[3], etc. Our users won't be able to load pages of this size, and we will inevitably encounter recurring scaling issues[3].

**Solution:** We have to reduce the size of the tiles, as step one, by: limiting the geometry detail, pre-rendering the tiles, and optimizing the compression of those tile images for web. As step two, we should be serving the tiles from cache to reduce processing requirements and further improve performance on subsequent page loads.

[1] We're not increasing the timeout; that's not a fix. That would increase our DDoS risk, it's bad practice, it doesn't do anything to address the root cause, and it'll actually exacerbate the strain of concurrent connections. It would result in the opposite of what we need to achieve.

[2] Caching doesn't do anything to address the problem here (an initial page load failing because it takes too long to download files this large). Caching would reduce the processing load on the server when generating the tiles, but our processing metrics are well below any threshold at which we need to optimize this; it's not at all a factor in what we're seeing.

[3] Increasing the number of concurrent requests the server can handle or throttling the number of concurrent requests we make won't fix this problem, either. It's a bandaid, at best, and only for our users with high-speed connections (users on slow connections would still be unable to load the pages because they'll struggle to download 15MB). It's false that "a large number of XHR tile requests are initiated" -- the number of requests per page is small. The number of concurrent connections on its own is also well within what our servers can support. Again, the problem isn't the requests or connections, it's the size of the response (the size of the files being served). The longer files take to download, the longer a single user's connections to the server remain open. Given that modern browsers allow multiple simultaneous persistent connections per server (this number varies between 2 and 8+ by browser, version, and user settings), times an increasing number of users (and surge in user activity for peak times like onboarding), and factoring in projects with significantly more geometries than the example, we'd need to continually scale up well beyond our real needs just to avoid page load failures for users on high-speed connections. This means the problem would continually get worse and more expensive in terms of infrastructure costs, quite disproportionate to any benefits derived for that portion of our users whose connections are fast enough to load 15MB pages to begin with. It's not a valid solution; we need to fix the root cause before rolling this out.

---

### @wonderchook 

@amplifi I was thinking we could have a call w/ @linzjax regarding the reducing the file sizes next week from Madrid. I have a couple different ideas, but I think we'd benefit from talking through the options as a group. 

---

### @alukach 
> Caching would reduce the processing load on the server when generating the tiles, but our processing metrics are well below any threshold at which we need to optimize this; it's not at all a factor in what we're seeing.

@amplifi I'm curious as to how you ruled out processing time being a factor. For example, when downloading [this tile](https://platform-staging.cadasta.org/async/organizations/12345-bleep-bloop-2/projects/all-of-mexico/spatial/tiled/3/1/3/?1497552885312&format=json) directly, you can see that it took me 2.63s to download the 9.6MB file but I had to wait 45s for the response to process before download began. which "processing metrics" were you referring to? Additionally, in the requests example image you posted, I believe that the majority of those requests' lifecycle were spent waiting for their first byte (represented by the green portion of the waterfall, maybe I'm misinterpretting this?).
![image](https://user-images.githubusercontent.com/897290/27197105-479a6c98-51ca-11e7-9767-7aac567016f3.png)

@wonderchook: @linzjax and I chatted yesterday and began putting together a couple ideas for solutions regarding performance:

* Cancel no-longer-needed requests (eg, if a user changes zoom levels, all tile requests at previous zoom level should be cancelled). This likely won't have a huge win, but at least will allow our system to ensure that all tile requests are of still interest to the user. This could probably wait until later stage optimizations.
* ~Setting a [max/min native zoom level](http://leafletjs.com/reference-1.0.3.html#tilelayer-maxnativezoom), stipulating that tiles should never be greater than a certain size (opting for many small tiles/requests rather than a few large tiles/requests).~ This doesn't feel like a great solution as complexity of geometry is independent of the spatial area of the geometry.
* Reducing tile size. At first blush, we could think of a few places for improvement:
  * Simplify geometries at lower zoom levels. This is standard operating procedure for webtiles. A potential risk is that the increased processing time by the simplification process might take away some from the benefit of smaller response sizes (this remains to be seen, and would still be a win for the users with slow connections that @amplifi mentioned). Here's a quick test script that was thrown together, it seems to be reasonably fast (admittetedly only tested for a single geometry with >500 coordinates):
    ```python
    def get_tolerance(z):
        """ Find simplification tolerance level based on zoom level """
        return (360/(2**z)) / 10000  
        # This is the width in degrees per zoom level divided by 10000, 
        # meaning we should cluster any points closer than 1/10000 the-
        # width-of-the-tile apart. This 10k number should be finetuned
        # after looking at the map, I just guessed this number as a 
        # starting point

    zoom_level = 10
    su = SpatialUnit.objects.first()
    geom = su.geometry
    simple_geom = su.geometry.simplify(get_tolerance(zoom_level))
    ```
  * Clipping tiles' geometries to the extent of the tile. Currently the async tiles endpoint is more of a _filter_ for locations than it is for a tiler, it returns the entire geometry if it any bit of the geometry exists in the requested tile's extent. For this reason, large geometries can be returned redundantly for each tile (imagine if we were zoomed into the map at a very high level and a geometry completely covered the map's viewport, our client would request N tiles from our system, each of those tiles would contain the entire geometry that is in the viewport.) If we were to clip geometries before sending them in a response and build in client-side logic to merge these geometries as they arrive, we should see some reduction in tile sizes. No comment on how difficult this would be on the client side or how much additional processing time would be added on the server side.
  * Chopping of some digits from our lat/long decimal values. Currently, we're returning values to their 14th decimal point. A value with 6 decimal points relates to an 11mm precision in the real world. I highly doubt anyone needs precision beyond that.

I am definitely in agreement that reducing response size of the tiles should be a first step and that it would be ideal to not have to pre-render any tiles, however I do suspect that the processing time added by these tile-size-reduction steps will push many tile request waittimes back towards an unacceptable number of seconds. I think this is "try-it-and-see" situation, as we'll want to be reducing tile size regardless of whether we're prerendering or not.

---

### @dpalomino 
Another example to test with re the perf issue, [this project](https://platform-staging.cadasta.org/organizations/david-org/projects/uttaran-import/) has around 5k geometries, being many of them just points or simple polygons. It's taking around 55sec. Another time when trying to load Chrome crashed. 

This [other project](https://platform-staging.cadasta.org/organizations/david-org/projects/csrc-demo/) is 500 geometries (only points) and taking 6-7 seconds. 

---

**Comment by linzjax** [comment]
One other possible bandaid: we can turn pagination back on for this endpoint. It results in WAY more requests, but limits the load on each individual request.

**Comment by alukach** [comment]
I'm hesitant to recommend pagination, as I think tiles is basically a form of pagination and it wouldn't necessarilly help our issue if there was a single geometry with a ton of coordinates (unless we actually paginate within geometries, however that sounds complicated).

**Comment by wonderchook** [comment]
maybe we should think through what people are doing. Usually you don't zoom to world level with a huge amount of data. Well at least the type of data we are collecting.

**Comment by oliverroick** [comment]
Let's be honest; we'll never dig this up from the graveyard of unfinished work. Closing.

**Comment by linzjax** [comment]
😭💀

**Comment by oliverroick** [comment]
Sorry @linzjax, but we dropped the ball on this and now it's too late. We still like you 💛
