### ISSUE TITLE
No search results for party-related information in demo/platform

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1604]
### Steps to reproduce the error

1. Try to execute any search query in demo or production with a keyword for a party: examples: "David", "IN" (for individual), etc. 
2. No results are returned

However in staging this is working as expected. And location and relationship related queries are also working fine in demo and platform. 

Can @seav or @amplifi take a look?

**Comment by amplifi** [comment]
Couldn't replicate last week, nor this week. Parties and relationships are indexed together so it doesn't make sense that one would work while the other doesn't. Recall that parties with associated relationships return a relationship result, not a party result. If this is still occurring, can we confirm a specific project?

**Comment by dpalomino** [comment]
Weird. Yes, it is also working for me now for both demo and platform. 

It was definitely failing two weeks ago, no results were shown in demo or platform when we search using party names or party types for instance. I will take an eye on to see if I see this again. 

Closing for now. Thanks @amplifi for checking it.
