### ISSUE TITLE
tox error

### ISSUE THREAD

**Issue by eomwandho** [Cadasta/cadasta-platform#161]
I keep getting the error below when running tox command

```
GLOB sdist-make: /vagrant/setup.py
ERROR: invocation failed (exit code 1), logfile: /vagrant/.tox/log/tox-0.log
ERROR: actionid: tox
msg: packaging
cmdargs: ['/opt/cadasta/env/bin/python3.5', local('/vagrant/setup.py'), 'sdist', '--formats=zip', '--dist-dir', local('/vagrant/.tox/dist')]
env: None

error in cadasta-platform setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

ERROR: FAIL could not package project - v = InvocationError('/opt/cadasta/env/bin/python3.5 /vagrant/setup.py sdist --formats=zip --dist-dir /vagrant/.tox/dist (see /vagrant/.tox/log/tox-0.log)', 1)
```

**Comment by ian-ross** [comment]
That's because you've added some random GitHub repo to `requirements/common.txt`. You can't do that: entries in there must be packages released on PyPI with fixed version numbers.

**Comment by eomwandho** [comment]
Thanks! I have removed the offending repo and it works. How do we deal with unpackaged git repos?

**Comment by ian-ross** [comment]
Short answer: we don't. There's no way to track changes in a reliable way. The only thing you can do is to refer to a specific commit in the repo using its hash, but there's no ordering to those, so if you decide to update the dependency at some point, you can't tell whether it's an upgrade, a downgrade, or something else.

**Comment by eomwandho** [comment]
Noted.
