### ISSUE TITLE
Check if project-slug exists when creating a project

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#162]
When creating a project with a name that already exists an `IntegrityError` is thrown, because the `slug` must be unique:

```
IntegrityError at /projects/new/
duplicate key value violates unique constraint "organization_project_project_slug_key"
DETAIL:  Key (project_slug)=(xls-project-3) already exists.
```

When creating a project, it should be checked if a project with the same slug already exists and then change the slug accordingly.

**Comment by seav** [comment]
This bug is still occurring on the latest master. I have created a functional test for this specific bug: projects/test_project_add_duplicate.py
