### ISSUE TITLE
Data collection contact prompt 

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1626]
On the project dashboard page, under data collection, the "If you need help, please contact us" links to http://cadasta.org/contact/ -- which offers the info@cadasta.org email address and a generic more info form. This should link to a support email address with a pre-populated subject line, so it's a single step for the user with a clear call to action.

**Comment by clash99** [comment]
Updates link in last line of blue info area here:

<img width="1432" alt="screenshot 2017-10-24 09 54 19" src="https://user-images.githubusercontent.com/1119621/31951059-af33ecb4-b8a2-11e7-9eff-041b8d8b9c99.png">
