### ISSUE TITLE
Resource name prefill script only replaces the first underscore with a space

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1627]
This is related to PR #1393.

### Steps to reproduce the error
1. Upload a resource file where the filename has at least 2 underscores.

### Actual behavior
In the pre-filled resource name field, only the first underscore is replaced with a space.

### Expected behavior
All underscores should be converted to a space.

### Bug fix
This can be fixed by changing the regex from `/_/` to `/_/g` here: https://github.com/Cadasta/cadasta-platform/pull/1393/files#diff-5023158cf9898833c6e99ca37d4adf89R17

**Comment by clash99** [comment]
Before and after (changes all underscores to spaces in image name:

<img width="528" alt="screenshot 2017-10-24 09 42 50" src="https://user-images.githubusercontent.com/1119621/31949866-f0a7c40c-b89f-11e7-98fe-168b45e7738c.png">
