### ISSUE TITLE
Superuser badge doesn't appear

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1628]
### Steps to reproduce the error

Log in as superuser account.

### Actual behavior

"SU" badge with tooltip doesn't appear.

### Expected behavior

Badge with tooltip should appear with username, as in #1568. Probably due to underlying `is_superuser` bug.

**Comment by dpalomino** [comment]
Thanks @amplifi. @clash99 can you take a look pls?

**Comment by laura-barluzzi** [comment]
Inside `cadasta/templates/core/base.html` there are other cases of the same logic though:
`{% if is_superuser %} ... {% endif %}`
Do these other cases work right? If so, the if should work just fine. You can double-check the other cases in the same template on these three different points:
[47](https://github.com/Cadasta/cadasta-platform/blob/405775388546d25d764a00f007664fb59328524c/cadasta/templates/core/base.html#L47), [87](https://github.com/Cadasta/cadasta-platform/blob/405775388546d25d764a00f007664fb59328524c/cadasta/templates/core/base.html#L87-L93) and [103](https://github.com/Cadasta/cadasta-platform/blob/405775388546d25d764a00f007664fb59328524c/cadasta/templates/core/base.html#L103).

I am not sure if I can login as a superuser so I cannot test this myself. I hope this may help a little bit.

**Comment by clash99** [comment]
Superuser is broken across the board for all the superuser conditionals on staging site (not local, not sure about demo or platform). I'm not sure how much effort to put into this since the whole permissions system is about to be replaced. Its tough to troubleshoot since its working as expected on my local site. @dpalomino - what do you think?

**Comment by dpalomino** [comment]
thanks @clash99. Yes, I think it makes sense to wait until #1467 is finished.

**Comment by amplifi** [comment]
@dpalomino This is a blocker for #1418 and should be resolved ASAP. If we can't detect whether or not someone is a superuser, we can't implement superuser UI tools. Detection is broken across stg/demo/prod.

**Comment by clash99** [comment]
@amplifi and @dpalomino - Can we pull this one out of the build? Or should I manually remove it? Let me know if I can do anything to assist.

**Comment by amplifi** [comment]
@clash No need to revert; the badge bug doesn't have any negative impact -- it just doesn't display the badge. After we fix the underlying `is_superuser` detection, we can re-test the code for this issue.

**Comment by dpalomino** [comment]
> @dpalomino This is a blocker for #1418 and should be resolved ASAP. If we can't detect whether or not someone is a superuser, we can't implement superuser UI tools. Detection is broken across stg/demo/prod.

My concern is that with the Tutelary work ongoing I don't know if this would interfere. Does it make sense then to reassign to @bjohare and tackle at the same time as #1467? 

@bjohare, what do you think?

**Comment by clash99** [comment]
@dpalomino Once all the new permission roles are established, this admin badge should be verified as displaying correctly. It shouldn't require any additional work by @bjohare.

**Comment by dpalomino** [comment]
Thanks @clash99. So then I think make sense to wait until the permission work is finished....
