### ISSUE TITLE
Tab CSS missing active color change

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1629]
### Steps to reproduce the error

View the details for a location.

### Actual behavior

Active tab isn't highlighted in amber. Appears as:

<img width="349" alt="screen shot 2017-07-05 at 10 39 08 am" src="https://user-images.githubusercontent.com/4269749/27856545-c7cb06e4-616e-11e7-9279-d4cc4d38c0f9.png">

### Expected behavior

Active tab should be highlighted (see screenshots in #1611 for expected appearance).

If you try to attach a resource when there is at least one resource already added to the project, the active tab on that modal **is** highlighted as expected. Active highlight is also working on the party detail page, so looks like it's just happening with location detail.

**Comment by dpalomino** [comment]
Thanks Adri!

@clash99, can you take a look please?

**Comment by clash99** [comment]
Fixed css

<img width="418" alt="screenshot 2017-07-10 08 41 57" src="https://user-images.githubusercontent.com/1119621/28018980-4c07bf74-654d-11e7-8135-46b63164f128.png">

**Comment by amplifi** [comment]
Fixed in #1642
