### ISSUE TITLE
Plus, minus and other forbidden chars are allowed in text attributes when they are not at the beginning of the string

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1631]
### Steps to reproduce the error

Related with #1619

Plus (+), minus (-) and other signs (<, >, etc) are allowed in text fields when these are not at the begging of the field. For instance, the following text strings are rejected: 

"-asdf"
"+asdf"
"++++asdf"

But these other ones are accepted: 

"text+++text"
"text+----text"

This behaviour is the same when adding or editing a field via the web interface, or submitting records with ODK or geoODK. 

See screenshot: 
![screen shot 2017-07-05 at 16 22 06](https://user-images.githubusercontent.com/17198051/27870382-031167a0-61a3-11e7-86f1-594d630bd8c1.png)

**Comment by seav** [comment]
I think this is acceptable behavior. If you disallow this, you would be rejecting perfectly fine text like "Adolfo Suárez Madrid-Barajas Airport", "Guinea-Bissau", and "Olivia Newton-John".

**Comment by dpalomino** [comment]
> I think this is acceptable behavior. If you disallow this, you would be rejecting perfectly fine text like "Adolfo Suárez Madrid-Barajas Airport", "Guinea-Bissau", and "Olivia Newton-John".

Sounds good @seav, that's true. Thanks :-)

**Comment by amplifi** [comment]
Expected behavior; closing.
