### ISSUE TITLE
500 when uploading xlsform with resource types within groups

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1633]
### Steps to reproduce the error

1. In a xlsform file, include a resource (image/audio/video) within an entity group (for instance location) 
2. Create a project using this file

### Actual behavior

Enjoy your 500

### Expected behavior

File should be rejected and an error message shown ("Resources are not allowed within entity groups").

**Comment by wonderchook** [comment]
why shouldn't resources be allowed in entity groups? Then attached as resources

**Comment by dpalomino** [comment]
For attaching resources to entities via ODK, we need to include them out of the entity groups (not within location_attribtes, party_attributes_default, etc), and following this naming syntax: 
- location_resource_*
- party_resource_*
- tenure_resource_*

Details [here](https://github.com/Cadasta/cadasta-platform/pull/697)

**Comment by oliverroick** [comment]
Since #1934, we're allowing resources in groups. Closing...
