### ISSUE TITLE
Possible to upload a xlsform with an invalid form_id value

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1634]
### Steps to reproduce the error

1. Include a form_id value that is not valid: for instance including some blank spaces "Demo_Urban_Infrastructure 201707063"
2. Create a project and upload the file
3. File is accepted
4. Download the form from ODK
5. An 500 error is obtained

### Actual behavior

See above

### Expected behavior

File should be rejected

**Comment by dpalomino** [comment]
To be fixed for prior to the release of sprint 18.

**Comment by amplifi** [comment]
@dpalomino This is for a patch release after Sprint 18 release.
