### ISSUE TITLE
Possible to upload a questionnaire with party_type and party_name within the party_attributes_default group

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1637]
### Steps to reproduce the error

1. Create a questionnaire with party_type and party_name within the party_attributes_default group (which is incorrect, should be out of that group
2. File is successfully uploaded and project created
3. Download from from ODK 
4. Submit a record
5. Error: "Party error: 'party_name'

### Actual behavior

See above

### Expected behavior

File should not be allowed.

**Comment by wonderchook** [comment]
@dpalomino agreed this is a bug, is there a reason we shouldn't allow those fields both in and out of that group?

**Comment by dpalomino** [comment]
> @dpalomino agreed this is a bug, is there a reason we shouldn't allow those fields both in and out of that group?

I think we need to include it out of the groups because if not the schema is not properly created and then it's causing an error when submitting records from ODK.

**Comment by wonderchook** [comment]
@dpalomino does it make sense logically to do it that way? My point was more how should it work and what bugs are there related to it. It would be possible instead to fix how the schema is created to remove that issue.

**Comment by dpalomino** [comment]
I think there is no reason for not allowing party_name and party_type to be in party_attributes_default  group. But I also think that  this could complicate things a little. 

For instance, we shouldn't allow to include them in the conditional party attributes (like party_attributes_inidividual) as they are not always included. And we would need to test how the templates with repeated parties are working with this. 

As the templates are already created with these fields out of the party group and are working fine, I think it is probably easier just to check when uploading the file that the syntax is like that...

**Comment by bjohare** [comment]
@dpalomino we should not allow `party_name` and `party_type` as attribute field names (either default or conditional). I think the form stuff is complicated enough. We should add a validation check to disallow entity level field names in attribute groups.

**Comment by dpalomino** [comment]
> @dpalomino we should not allow party_name and party_type as attribute field names (either default or conditional). I think the form stuff is complicated enough. We should add a validation check to disallow entity level field names in attribute groups.

Hi @bjohare. Yes agree. That's what I meant, technically it is possible to do it but I think it complicate things a little and add no much value...

**Comment by oliverroick** [comment]
Closed via #1998
