### ISSUE TITLE
Incorrect relevant conditions in questionnaires not detected when uploading a xlsform

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1638]
### Steps to reproduce the error

1. Upload a xlsform with an incorrect relevant condition (for instance $var='asdf' instead of ${var}='asdf')
2. File is accepted
3. From ODK you can download the form and submit records, the relevant condition is just ignored 

### Actual behavior

See above

### Expected behavior

The syntax error should be detected when uploading the file

**Comment by dpalomino** [comment]
Thanks Brian!

To be fixed prior to the release of Sprint 18.

**Comment by amplifi** [comment]
@dpalomino This is for a patch release after Sprint 18 release.
