### ISSUE TITLE
Inline Manual Icon floats in middle of map; should be to the side

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1647]
My screen is large (using a monitor), but I have noticed this the last few days on different devices. 

The inline manual icon seems to show up in places it should not be. 

![screen shot 2017-07-12 at 12 01 31 pm](https://user-images.githubusercontent.com/25337622/28132435-156d4d22-66fa-11e7-9cc3-24f5396ad83d.png)

**Comment by clash99** [comment]
Inline manual seems to have changed some of their interface and I couldn't make changes to just that topic launcher and have it work. After contacting them, I've cloned the original and made the adjustments and added again as an autolauncher. It should be fixed on demo and staging now.  This walk-through doesn't exist on platform.

<img width="1402" alt="screenshot 2017-07-13 21 36 31" src="https://user-images.githubusercontent.com/1119621/28194636-962d1950-6813-11e7-95f8-46e03471424a.png">

**Comment by clash99** [comment]
@SteadyCadence - Can you confirm this is working as expected for you and close this task if so?

**Comment by SteadyCadence** [comment]
Works!
