### ISSUE TITLE
UI bug with Italian translation

### ISSUE THREAD

**Issue by laura-barluzzi** [Cadasta/cadasta-platform#1649]
### Steps to reproduce the error

1. Create an organization
2. Add a project

### Actual behavior

On the `project_add_details.html` template the toggle (set project to public or private) on the top left covers a bit the Italian text.
![add_project_ui fix](https://user-images.githubusercontent.com/16849118/28145097-769e9662-6724-11e7-94c6-d5a376f87be6.png)

**Comment by clash99** [comment]
Eliminated the offending css

![screenshot 2017-09-01 09 07 09](https://user-images.githubusercontent.com/1119621/29973380-fabe78f2-8ef4-11e7-8533-18dc148ab43a.png)
