### ISSUE TITLE
Buttons That Public Users Do Not have permission to Should not be clickable 

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1657]
Note:  Not sure if this is a bug specifically to the demo account

### Steps to reproduce the error

1. Log into "demo" with the demo account
2. Go to https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/smallholder-farmers-india/.
3. Observe that the buttons (Parties and Resources) are clickable, but when you click on them you get a warning that you do not have permission to view the page.

<img width="1422" alt="screen shot 2017-07-14 at 1 24 14 pm" src="https://user-images.githubusercontent.com/25337622/28227577-d7d68baa-6897-11e7-9566-157a83aed0ee.png">

4.  Another related issue is the import and export buttons-- those should probably be removed entirely for those that do not access. 

### Actual behavior

Probably best to remove the elements that are not accessible.  @clash99, what do you think?

**Comment by clash99** [comment]
So there are few weird permission things here that should be resolved once we remove tutelary.  For one, you shouldn't see the cog button unless you are a pm or above. And yes, the import/export button and any other un-permissioned button actions shouldn't be visible unless you have permission. I will see where we are on that project and hope to correct what I can but it may have to wait until next sprint.

@adri - When you get a chance, can you let me know what permission role the demo user has for the project "Smallholder Farmers (India)"?

**Comment by amplifi** [comment]
@clash In the screenshot attached to the issue, it shows the `demo` user as having Project Manager access.

**Comment by alukach** [comment]
Sounds similar to #1693, however I doubt the fix for that will fix this.

**Comment by clash99** [comment]
@SteadyCadence - This seems to have been fixed with the permission changes. Can you confirm and close this task if you agree?

**Comment by clash99** [comment]
Rechecked and confirmed this is working correctly.

**Comment by MappingKat** [comment]
Sorry, just saw this.  It is working better for me. Thank you, @clash99!
