### ISSUE TITLE
Sanitation excluding "-" in lat/lon via API

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1664]
### Steps to reproduce the error

I'm seeing this error when importing shp via QGIS plugin and I think it's something similar to #1613 but affecting to the API (but I could be wrong). 

1. Use these shapefiles for testing: 
[itc-f-cadaster-community-form.zip](https://github.com/Cadasta/cadasta-platform/files/1160494/itc-f-cadaster-community-form.zip)

The Polygon layer for instance. It contains negative latitudes. 

2. Try to import the shp using QGIS plugin

3. We get a 500, and also the 400 emoji error message: 

![screen shot 2017-07-19 at 23 09 17](https://user-images.githubusercontent.com/17198051/28389908-4296aa58-6cd8-11e7-8d8d-3b7c7270a0eb.png)

@oliverroick, could you please take a look when you have a moment?

**Comment by dpalomino** [comment]
Thanks @oliverroick for the analysis and the chat re this issue. 

Open an issue for the plugin: 
https://github.com/Cadasta/cadasta-qgis-plugin/issues/227

Keeping this issue open for investigating what the 400 error is...

**Comment by oliverroick** [comment]
I tried to reproduce this; it works as expected. I left a [comment in the QGIS-plugin ticket #227](https://github.com/Cadasta/cadasta-qgis-plugin/issues/227#issuecomment-319028563). 

We need more information to reproduce this. I am downgrading the priority of this ticket for the time being.

**Comment by oliverroick** [comment]
We haven't been able to reproduce, closing
