### ISSUE TITLE
On Form Upload Required Form Fields Should be Checked For

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1665]
### Steps to reproduce the error
1. Create project
2. Upload form without "location_type"
3. Download form to ODK
4. Fill in form
5. Send

![screenshot_20170719-141414](https://user-images.githubusercontent.com/67992/28389928-eb8c56e0-6c8c-11e7-826e-ad02dc979ef4.png)

### Expected behavior

I would expect notification that location_type is a required field type.

**Comment by oliverroick** [comment]
Duplicate of #1461. Closing
