### ISSUE TITLE
Include areas in project dashboard and location detail pages

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1666]
PR #1534 adds area calculations for spatial units. We need to include the information in both the project dashboard and location detail pages.

*Note:* This task is dependent on the completion of #1658.

Rough task breakdown:

- [x] Create UX for Project Dashboard
- [x] Create UX for Location Details
- [x] Implement UX for Project Dashboard
- [x] Implement UX for Location Details

**Comment by clash99** [comment]
Screenshots of implementations

**Location Detail**

![screenshot 2017-08-08 14 07 39](https://user-images.githubusercontent.com/1119621/29089901-7db4d34c-7c43-11e7-8ff8-ca1ae6076177.png)

**Project Dashboard - Member**

<img width="641" alt="screenshot 2017-08-08 13 51 29" src="https://user-images.githubusercontent.com/1119621/29089899-7db1a956-7c43-11e7-9917-b2d1154f12c4.png">

**Project Dashboard - Non-Members**

<img width="622" alt="screenshot 2017-08-08 13 50 49" src="https://user-images.githubusercontent.com/1119621/29089900-7db3c8ee-7c43-11e7-9cf8-04e9373bb132.png">
