### ISSUE TITLE
Records Wireframes

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#168]
Simply process of creating a record. For version .1 we should have 1 way of doing it. 

All records must have at least one location to simplify process. For version .1 the workflow should be as follows:

1. Create location
2. Create relationship
3. Create record

Let's make this process as streamlined as possible and then once we've done some user testing look at other workflows.

**Comment by wonderchook** [comment]
Comment from @nastynoel on the locations. It is important to collect metadata on how the record was created. (GPS, handdrawn map, digitized from imagery, etc). This is available in the data model but not currently in the wireframes. @clash99 in reviewing the wireframes could you add this information as well?

**Comment by clash99** [comment]
Adding a record (location, relationship, resources) from the map tab:  https://drive.google.com/file/d/0BzpiEtMtHC3rZExvVWlia3FxQzQ/view?usp=sharing

Adding a record (location, relationship, resources) from the records tab:  coming soon

**Comment by wonderchook** [comment]
Initial comments:

* On the select a party page. Could we use a UI where the search is already there rather than click the drop down and then get to the search? My thinking is users that know what they want by search would save a click. 
* I think rather than geometry we should stick with location. It is a less technical term. I could see using tool tips to help users with some of the terms. E.g. if it said "Location collected by" and then help indicating this it the geometry. 
* Generally the word "location" doesn't need to be in front of some of the other items. E.g. just relationship instead of location relationship. On the page where they are adding the location it could just say "Name" instead of "Location Name". (Might need help for the user to understand)
* Rather than saying "Add Location Relationship" how about "Connect a party to this location".

**Comment by nastynoel** [comment]
@wonderchook - there are instances where the relationship being added could be between 2+ locations, not just a party and a relationship. e.g. a land parcel connected to a building footprint, while being connected to another land parcel with a right of access/easement.

I agree with using location over geometry

**Comment by wonderchook** [comment]
@clash99 thoughts on how to work the location relationships into the wizard? I suspect this will be a less common workflow but we also need to support it.

**Comment by wonderchook** [comment]
@clash99 @oliverroick let's review this soon. For the first release I think we are done with wireframing it is just tidying up the workflow @oliverroick is creating. We'll then gather user feedback and see about further adjustments later.

**Comment by wonderchook** [comment]
@clash99: leaving this open but realize the first release won't exactly match what is wireframed. A reminder for me to review this once things are finished.

**Comment by wonderchook** [comment]
@clash99 I'm going to move this off to the next milestone so we can get some feedback from users as to what is there now.

**Comment by wonderchook** [comment]
@dpalomino something to be aware of regarding the record entry areas of the platform

**Comment by wonderchook** [comment]
@clash99 + @dpalomino will be putting missing parts of the wireframes into the backlog as needed.
