### ISSUE TITLE
Maybe allow GIF images as the user avatar

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1682]
Based on [this line](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/settings/default.py#L294), only PNG and JPEG images are allowed for the user avatar. But this is a bit confusing because when I select a GIF image, I get a preview of the image on the page. In addition, the [help text](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/accounts/profile.html#L28) (that suggests square 200×200 pixel images are best) makes no mention of which image formats are allowed.

I suggest we resolve the following:
1. Decide if we should allow GIF images as the user avatar.
2. Include in the help text a list of image formats that are allowed.

**Comment by amplifi** [comment]
We should not permit gifs as file sizes can be significantly larger. Allowing the upload is a bug; documented in #1684
