### ISSUE TITLE
Default thumbnail images for the new allowed MIME types are missing

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1685]
### Steps to reproduce the error
1. Attach a resource of a MIME type that is included in PR #1659 such as an SVG image, ODT document, or ODS spreadsheet.

### Actual behavior
I get the broken image thumbnail. See screenshot below.

![screen shot 2017-08-01 at 20 25 40](https://user-images.githubusercontent.com/873653/28825250-06ec2a30-76f8-11e7-8996-5d6c98009154.png)

### Expected behavior
I should get a default thumbnail icon similar to our existing ones for non-image files. This is actually weird because PR #1659 says: "New thumbnails for non-images are already on the production buckets."

**Comment by amplifi** [comment]
Only default icons in production buckets are for:

<img width="76" alt="screen shot 2017-08-01 at 2 40 00 pm" src="https://user-images.githubusercontent.com/4269749/28825643-68938e26-76c7-11e7-8369-58507b28a74a.png">

**Comment by oliverroick** [comment]
I uploaded the icons to the wrong bucket. @seav can you check if that's ok now and close the ticket if it is?

**Comment by seav** [comment]
Confirming this is fixed. Closing...
