### ISSUE TITLE
User avatar: error message(s) not cleared

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1686]
### Steps to reproduce the error

Upload a file type not allowed. Relevant error message is displayed. Upload an allowed file type.

### Actual behavior

Error message is not cleared from first failed attempt.

<img width="390" alt="screen shot 2017-08-01 at 2 27 21 pm" src="https://user-images.githubusercontent.com/4269749/28825393-499429aa-76c6-11e7-8d73-bd85a4218fb1.png">

### Expected behavior

Error message should be cleared when new file upload is attempted.

**Comment by oliverroick** [comment]
I suggested a [fix in django-buckets](https://github.com/Cadasta/django-buckets/issues/34). Once the PR is accepted we can make a release and update the requirements for the platform.
