### ISSUE TITLE
User avatar: clickable area for upload button

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1687]
### Steps to reproduce the error

Browse to the user profile page

### Actual behavior

Large clickable area for uploading a user avatar extends throughout entire div

<img width="369" alt="screen shot 2017-08-01 at 2 25 54 pm" src="https://user-images.githubusercontent.com/4269749/28825429-7c1ce9c0-76c6-11e7-80d6-a334e7d1fd76.png">

### Expected behavior

Only button should be clickable.

**Comment by seav** [comment]
This also happens when uploading resources. If I'm not mistaken, I think this is the default browser behavior and not something that we can control on the platform.

**Comment by oliverroick** [comment]
This is default browser behaviour—Closing...
