### ISSUE TITLE
Attaching resources from multiple pages doesn't work

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1688]
### Steps to reproduce the error

1. Go to the project's dashboard page.
2. Follow the "Resources" link on the project sidebar.
3. Click the "+ Attach" button.
4. Check the check box for 1 existing resource in the table.
5. Go to the next table page.
6. Check the check box for another existing resource in the table.
7. Click the "Save" button.
8. Follow the link to the 1st resource in the table.
9. Follow the "Resources" link on the project sidebar.
10. Follow the link to the 2nd resource in the table.

### Actual behavior

Only the resource selected from page two is attached.

### Expected behavior

All selected resources should be attached.

**Comment by seav** [comment]
I can't reproduce this. I've tried attaching multiple resources from different pages to the project, a location, a party, and a tenure relationship and they all get attached.

**Comment by oliverroick** [comment]
Strange; it seems to work today. Who knows, what I did. Closing...
