### ISSUE TITLE
Upload of XML file fails

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1691]
### Steps to reproduce the error

1. Upload an XML file as a resource (I used [this](https://drive.google.com/file/d/0BxlZVjoFYP3jdkI5Y3JBVXNYYXc/view))

### Actual behavior

The file is uploaded but an error is thrown: "Error parsing GPX file: no geometry found."

### Expected behavior

The file should be accepted and stored without error.

**Comment by seav** [comment]
Is there actually a case where our users need to upload non-GPX XML files? I think we only allow `application/xml` files because GPX files could have an .xml extension and that MIME type. So we assume that `application/xml` files are GPX files and reject them if they aren't.

**Comment by oliverroick** [comment]
Looks like you're right. Mime types `application/xml`, `text/xml`, `application/gpx+xml` are all treated as GPX. I think we should make the errors message clearer in that case and also update the test script so it's obvious that it needs to be valid GPX.
