### ISSUE TITLE
Questionnaire data

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#17]
This information has been [moved into the wiki for further discussion and definition](https://devwiki.corp.cadasta.org/5.0%20Questionnaires).

# Questionnaire Creation 

1. Project Manager creates XLSForm with the questions they want (likely using Excel)
2. Project Manager uploads XLSForm to Cadasta Platform
3. Cadasta Platform parses XLSForm and creates custom data model from the form.
4. Data can then be entered into Cadasta in one or two ways. 

# Mobile Phone Data Entry:

Data Collectors :

1. Data Collector opens mobile phone app (ODK Collect/GeoODK) and enters in the "General Settings" their Cadasta username and password and the URL to the survey download endpoint of Cadasta
2. Data Collector connects to Cadasta Platform and downloads available questionnaire
3. Data Collector then selects a questionnaire to download and downloads the questionnaire
4. Data Collector fills out questions
5. Data Collector uploads responses to Cadasta platform

# Web Data Entry :

1. Data Collector logs into Cadasta web platform
2. Data Collector goes to project
3. Data Collector clicks "add new data"
4. Data collect enters responses

# Data Import

1. Project Manager logs into Cadasta web platform
2. Project Manager goes to project
3. Project Manager clicks "upload data"
4. File is uploaded into the project. 

# Data Review

- Project Manager reviews and validates/invalidates uploaded questionnaire data (all new data is considered unvalidated). 
- Project Manager can view a list of unapproved data sets (searchable, sortable, filterable list), and approve/reject data entries, either in bulk or on a per-item basis.

# Editing of Data

- If a record is edited its status becomes invalidated and it needs to be approved by a project manager
- Data collectors can edit existing records

**Notes:**

- Needs to be a way to map between default data and questions.
- Resources are considered part of the questionnaire data. For example a photo question should be imported as a photo resource into the Cadasta platform
- Project Manager can edit questionnaire data before approval

**Comment by wonderchook** [comment]
@ian-ross @oliverroick @clash99 I redid the language on this feature to try to make it more clear (for example we don't to be using Ona). This needs to be broken out into quite a few different pieces, but first can you review the workflows I've written and see if it brings up any questions for you so far.

**Comment by oliverroick** [comment]
That's much clearer now.

Few questions though:

- Will data uploaded generally be unvalidated or will there be exceptions, say if a project manager uploads data? 
- Same when editing data: If a project manager edits valid data, will it become invalid again?
- Web data entry: Will this be forms on the web or an upload of some structured data?

**Comment by wonderchook** [comment]
* Uploaded mobile data will generally be unvalidated. "Imported" data for example uploading a shapefile of published government data shouldn't go through a validation process. 
* If a project manager edits valid data I think it should become invalid and then be validated again. I think this workflow is a little awkward, but my thought process is in cases of corruption. Say a project manager is always editing data at least this could leave an audit trail that they are validating their own edits.
* Form on the web.
