### ISSUE TITLE
Relevant Logic is causing a questionnaire that works on demo not to work on staging

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1700]
### Steps to reproduce the error
1. Start a new project.
2. Upload this questionnaire: 
[Smallholder Farming (1-Many) Form (1).xlsx](https://github.com/Cadasta/cadasta-platform/files/1199129/Smallholder.Farming.1-Many.Form.1.xlsx)
3. Get an error about the relevant 

<img width="1022" alt="screen shot 2017-08-03 at 9 10 03 pm" src="https://user-images.githubusercontent.com/25337622/28952814-0ad70288-7891-11e7-804f-8e90125cd344.png">

### Actual behavior

Get error

### Expected behavior

Works fine on demo as there is no syntax issue.

**Comment by oliverroick** [comment]
This is a known issue. We have reverted the changes; they should go up on staging soon.
