### ISSUE TITLE
Date format inconsistencies with import vs manual input

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1715]
### Steps to reproduce the error

I took a screenshot of this a while back and need to track down which layer it was-- one of the demo projects (sustainable sourcing, I think). Essentially, I think I imported some data and then manually entered some and there seems to be different date formats occurring. 

This may be a QGIS bug, but I wanted to post it here to make sure. 

<img width="620" alt="screen shot 2017-08-03 at 11 31 18 am" src="https://user-images.githubusercontent.com/25337622/29201211-7bbe50e0-7e19-11e7-8d2f-492c10fd0e46.png">

### Actual behavior

Dates are formatted differently depending on how you input the data.

### Expected behavior

I expect all dates to be formatted in the same manner.

**Comment by clash99** [comment]
All dates entered through the platform ui datepicker are formatted yyyy-mm-dd.

**Comment by alukach** [comment]
@SteadyCadence Can you provide a link to the project that produced this output?

**Comment by oliverroick** [comment]
Closing as we don't have enough information to reproduce. Feel free to re-open with more information if this issue re-surfaces.
