### ISSUE TITLE
Goes to new user even when not logged in as a guest user.

### ISSUE THREAD

**Issue by Siddhant2016** [Cadasta/cadasta-platform#1731]
### Steps to reproduce the error

Check if the user is currently logged in as guest user in the POST request rather than using callback after going to the signup page.

### Actual behavior

It takes to the registration page and then calls back to signup page.

### Expected behavior

Should highlight that you are not logged in as a guest user.

**Comment by valaparthvi** [comment]
@Siddhant2016  Can you explain this issue in detail? I'm not sure I completely understand the problem.

**Comment by mish24** [comment]
@Siddhant2016 Can I take this up?

**Comment by Siddhant2016** [comment]
@valaparthvi  When one clicks on the signup page, it redirects to the page, opens it. and after sometime redirects again to the signin page. What I suggest to do is, add a POST req in the signin, and check if user is signed in. If yes the do the needed else it should give a pop-up saying, you're not logged in as guest user.

**Comment by Siddhant2016** [comment]
@mish24 Sure you can, hope you understand the problem 😄

**Comment by oliverroick** [comment]
Hi @Siddhant2016, thanks for reporting the issue. I have difficulties understanding the problem though. 

> When one clicks on the signup page

Do you mean, clicking the "signup" button in the top-right corner? If yes, from which page?

>  it redirects to the page, opens it.

From which page are you redirected and to which page does it redirect?

> What I suggest to do is, add a POST req in the signin, and check if user is signed in.

This sounds like you are signed in. If yes, then how are you accessing the sign-in page. 

> If yes the do the needed else it should give a pop-up saying, you're not logged in as guest user.

I don't understand this. What do you mean by "not logged in as guest user".
