### ISSUE TITLE
Invalid redirect on account registration

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1747]
### Steps to reproduce the error

Sign in to a user account, then click to Logout. On the Sign In page that appears, click "Register here"

### Actual behavior

You are taken to the registration page with a redirect to `None`, as in:
https://platform-staging.cadasta.org/account/signup/?next=None

Submitting a valid registration form will successfully create an account, but on redirect Django generates an unhandled exception causing uWSGI to throw a 500.

### Expected behavior

A valid destination should be populated for redirection

**Comment by dpalomino** [comment]
Thanks @amplifi. I understand that this would be solved just changing the redirection to next=/account/login/, right?

**Comment by amplifi** [comment]
@dpalomino Yes, for now. Default behavior beyond that will changed with the Additional Login Options work.
