### ISSUE TITLE
UserListTest sometimes throws error

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#175]
This happens only once in a while, need to investigate

```
_______________________________________________________________________ UserListTest.test_get_with_user _______________________________________________________________________

self = <organization.tests.test_views_default_users.UserListTest testMethod=test_get_with_user>

    def test_get_with_user(self):
        assign_user_policies(self.user, self.policy)
        response = self.view(self.request).render()
        content = response.content.decode('utf-8')

        dummy = default.UserList()
        dummy.object_list = self.users
        dummy.get_context_data()
        expected = render_to_string(
            'organization/user_list.html',
            {'object_list': self.users, 'user': self.request.user},
            request=self.request)
    
        assert response.status_code == 200
>       assert expected == content
E       AssertionError: assert '\n\n\n\n\n\n...y>\n</html>\n' == '\n\n\n\n\n\n<...y>\n</html>\n'
E         Skipping 2280 identical leading characters in diff, use -v to show
E         Skipping 3238 identical trailing characters in diff, use -v to show
E         - >testuser438</td>
E         ?           ^^
E         + >testuser441</td>
E         ?           ^^
E         +     <td>email_441@example.com</td>
E         +     <td>&mdash;</td>
E         +     <td>&mdash;</td>
E         Detailed information truncated (70 more lines), use "-vv" to show

organization/tests/test_views_default_users.py:64: AssertionError
```

**Comment by ian-ross** [comment]
This is weird.  Can't reproduce it with `py.test`.  I've seen it once on Travis.  I'm wondering if it's something to do with ordering of the user list.  Maybe making https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/organization/tests/test_views_default_users.py#L56 say

```
dummy.object_list = sorted(self.users)
```

might help?

I'm trying repeatedly runing the unit tests with `tox` to see if it's reproducible that way.  If it is, I'll try fixing it.

**Comment by seav** [comment]
This test error apparently still occurs once in a while:
https://travis-ci.org/Cadasta/cadasta-platform/jobs/140818066

**Comment by seav** [comment]
Happened again:
https://travis-ci.org/Cadasta/cadasta-platform/jobs/141597800

**Comment by clash99** [comment]
I've gotten this twice today.  This is the latest:  https://travis-ci.org/Cadasta/cadasta-platform/jobs/143129303

**Comment by clash99** [comment]
Another one:  https://travis-ci.org/Cadasta/cadasta-platform/jobs/143230172

**Comment by clash99** [comment]
Is this one fixed?  I just got the same sort of error:  https://travis-ci.org/Cadasta/cadasta-platform/jobs/143390647

Its not always on the UserList page, but its the same error.  This one is faulting OrganizationMembersEditTest.

**Comment by ian-ross** [comment]
It will be fixed when I finish the PR I'm working on.  I figured out what was causing it, but this PR is a bit complicated and broke a bunch of functional tests, so it's going to take me a little while to get it ready for merging.

**Comment by clash99** [comment]
That's great news!  (I mean the fix, not your broken tests :)
