### ISSUE TITLE
Signup allows parts of email as password

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1750]
### Steps to reproduce the error

1. Go to the signup page
2. Enter username and email
3. Enter a password containing the end of your email address (If your email is joe@example.com, use the password !20@example.com
4. Click register

### Actual behavior

Signup proceeds successfully

### Expected behavior

I believe, the password should be rejected and the user should not be able to finish signup.

**Comment by dpalomino** [comment]
hey @oliverroick!

I think the condition was that the password shouldn't contain the email address, but it was ok to have part of it. 

In the previous example for instance, where would we put the limit? Would be acceptable to include "xample.com" but not "@example.com"? IMO I think it'd be enough to not allowing password to contain the complete email address. Thoughts?

**Comment by amplifi** [comment]
@dpalomino That's not how validation is currently implemented. The check is that the password cannot contain the email account name, e.g. for test@example.org the password can't contain 'test'.

**Comment by oliverroick** [comment]
> test@example.org the password can't contain 'test'.

This works as described. If that's expected behaviour we can close the ticket.

**Comment by amplifi** [comment]
We should be good with the current password requirements. I don't see a measurable increase in security if we added exclusion of the email domain, given the length and encryption in place.
