### ISSUE TITLE
500 when retrieving available forms from ODK 

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1753]
### Steps to reproduce the error

1. Configure ODK with proper credentials
2. Retrieve xforms via Get Blank Forms
3. Enjoy the 500 

Same behaviour with GeoODK. 

### Actual behavior

See above

### Expected behavior

Xforms properly downloaded

**Comment by amplifi** [comment]
This is the same root cause as #1746.

**Comment by dpalomino** [comment]
According to the log: 

Exception Type: AttributeError at /collect/formList
Exception Value: 'WSGIRequest' object has no attribute 'user'
Request information:
USER: [unable to retrieve the current user]

**Comment by amplifi** [comment]
Tracking in #1746
