### ISSUE TITLE
Project Area hard to read

### ISSUE THREAD

**Issue by alukach** [Cadasta/cadasta-platform#1756]
The Project Area is hard to read. I recommend that we humanize the numbers with comma separators. Note that I'm already adding the `django.contrib.humanize` app in my [work for Async Tooling](https://github.com/Cadasta/cadasta-platform/blob/async/export-api/cadasta/config/settings/default.py#L43). We may want to lean on the [intcomma](https://docs.djangoproject.com/en/1.11/ref/contrib/humanize/#intcomma) filter.
![image](https://user-images.githubusercontent.com/897290/29844668-4b7c453c-8ccd-11e7-856b-2d4bc1432299.png)

**Comment by clash99** [comment]
Sounds great - totally agree. This was discussed as an enhancement but we didn't want to hold up the PR for it. I'm assuming this will be an improvement we can add in the future.

**Comment by clash99** [comment]
Updated location, area, party and resources numbers to insert commas when applicable.

**Before**

<img width="609" alt="screenshot 2017-11-02 12 48 30" src="https://user-images.githubusercontent.com/1119621/32343333-212faa26-bfd1-11e7-9de2-aca768843f03.png">

**Now**

<img width="699" alt="screenshot 2017-11-02 13 03 45" src="https://user-images.githubusercontent.com/1119621/32343334-214aa15a-bfd1-11e7-8826-1064650bc35c.png">
<img width="1440" alt="screenshot 2017-11-02 13 13 05" src="https://user-images.githubusercontent.com/1119621/32343336-21aaae7e-bfd1-11e7-890f-46a6de29d670.png">
<img width="1433" alt="screenshot 2017-11-02 13 22 08" src="https://user-images.githubusercontent.com/1119621/32343338-21ba8f24-bfd1-11e7-9b4d-bece97209b19.png">

**Comment by alukach** [comment]
Looks great!

**Comment by clash99** [comment]
I'm researching separate bug where `total_area` on project_dashboard_nonmember.html isn't displaying.
