### ISSUE TITLE
Not possible to attach a second resource after the first one is rejected

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1761]
### Steps to reproduce the error

1. Try to attach a resource in a project that would not be accepted (for instance, try to attach a pic with file size bigger than 10MB)
2. Resource is rejected and proper error message appears
3. Try to attach another resource (a pic less than 10MB in this case) 
4. Resource is accepted but Save button is still disabled

See video: 
https://screencast.com/t/Q7l6IiiceQ

### Actual behavior

See above

### Expected behavior

See above

**Comment by clash99** [comment]
At first glance, I believe this is going to require changes to buckets/js/scripts.js.

**Comment by oliverroick** [comment]
Agreed, I'll take a look this week.
