### ISSUE TITLE
Unable to Create New Project: No error messages or page loads

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1797]
### Steps to reproduce the error

I am trying creating a new project on https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/new/ and when I click "Finish" after assigning members new roles, nothing happens. 

Not sure if there is an error occurring with members or with the questionnaire.... 

![permissions-bug](https://user-images.githubusercontent.com/25337622/30444209-5df8ba0a-993f-11e7-9d6a-1d094a5f3b27.gif)

**Comment by SteadyCadence** [comment]
Tutelary issues for my old account.

**Comment by oliverroick** [comment]
@alukach is this addressed in #1918?

**Comment by alukach** [comment]
Yup, this is almost surely #1918.
