### ISSUE TITLE
Project model's `project_slug` field should not have `null=True`

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#180]
For the `Project` model, the `project_slug` field is declared with the `null=True` option. Since `project_slug` effectively acts as the primary key for projects, this field should not be null.

This defect does not seem to currently matter because `project_slug` is always assigned when a project is created (save for bug #162), but this should be corrected eventually.

**Comment by oliverroick** [comment]
I'm fixing this along with #162.
