### ISSUE TITLE
Relevant conditions in XLSForms are capped to 100 chars

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1804]
### Steps to reproduce the error

1. Create a XLSForm and include a relevant condition with more than 100 chars
2. Form is accepted
3. Download the form in ODK
4. Submit an answer
5. Enjoy a 500:  

DataError at /organizations/david-org/projects/congo-initiative-v01/edit/details/
value too long for type character varying(100)

Although it is not the most typical case, there are some partners creating sophisticated forms with long relevant conditions. We can somehow workaround this (shortening var names, for instance), but it's not ideal. 

I think we should increase the limit to maybe 300 or so...

**Comment by SteadyCadence** [comment]
Can you add the relevant condition here?  I'm curious what it looks like

**Comment by dpalomino** [comment]
There was a combination of `and` and nested group relevant conditions. As we don't support nested groups I had to use multiple `and` combinations. Finally I workaround this shortening the field names, but it's not ideal... 

${_1_Votre_parcelle_est_elle_enr} = 'oui' and ${Relation_de_tenure_sociale_du_} = '__propri_taire' and ${Age_du_r_pondant}>17

There are others where I directly shortened the field names to avoid the problem...
