### ISSUE TITLE
Make the org logo in the project page a link to the organization's page

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#182]
I suggest that in a project's page, the org logo should be a link going to the org's page.

**Comment by clash99** [comment]
Fixed with #234

**Comment by seav** [comment]
Hi @clash99. There's now a link to the organization, but there's no logo anymore. Is this intended?

![screen shot 2016-06-11 at 21 45 28](https://cloud.githubusercontent.com/assets/873653/15985384/dee16414-301d-11e6-973e-9416c9606471.png)

**Comment by clash99** [comment]
Yes, removing the org logo in header was intentional.  After review I felt it was competing too much with Cadasta logo and the placement seemed confusing.  Also concerned about quality of logos we might be receiving.  I did incorporate a large org logo on org overview page.
