### ISSUE TITLE
Need to support Aymara and Garifona languages

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1826]
See #1807 for reference. 

Aymara: 
- iso-639-2 code: aym
https://en.wikipedia.org/wiki/Aymara_language

Garifuna: 
- iso-639-3 code: cab
https://en.wikipedia.org/wiki/Garifuna_language

**Comment by oliverroick** [comment]
We need to add Oriya language (spoken in Odia, India) to the list of our supported languages here:
https://github.com/Cadasta/cadasta-platform/blob/fff14c69d400eac82127c17818585ee318392cb4/cadasta/config/settings/languages.py

We are working with a couple of partners in the region potentially using this language.

ISO-639-1 code is "or". Reference here. ISO-639-2 and ISO-639-3 code is "ori".
