### ISSUE TITLE
User cannot log out

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1845]
### Steps to reproduce the error
1. Log in to the Staging platform.
2. Try to log out.

### Actual behavior
I am redirected to my user dashboard.

### Expected behavior
I should be logged out.

### Notes
I have tried this with both Firefox and Chromium on my laptop, and on Chrome for Android using a different ISP.

Looking at the browser network tools, When the browser tries to load the `/account/logout/` URL, it gets a 302 redirect to `/account/login/` URL, which is expected. But when the browser tries to load the `/account/login/` URL, it gets a 302 redirect to the `/account/dashboard/` URL.

It seems there is a caching issue or another weird error where the user is not being logged out properly. Note that this behavior is also not consistent. Sometimes I do get logged out.

I don't see this issue on the dev VM.

**Comment by oliverroick** [comment]
It looks like Django is setting the `Cache-Control` response header to `age=86400` for the logout view. When the request is processed in the browser it redirects directly to the login page without hitting the server and thus not kicking off the logout procedure, which deletes the session cookie. 

This doesn't happen on our other systems (production for example). We have upgraded Django from 1.10.7 to 1.10.8 but I can't find any [changes](https://github.com/django/django/compare/1.10.7...1.10.8) that explain why this happens now. 

We could try to extend django-allauth's logout view and explicitly disable any caching for that one view. Other than that, I have no more ideas at the moment.

**Comment by seav** [comment]
Can we check if it is indeed Django that sets this `Cache-Control` header? It could be something in the NGINX server itself. Maybe something is configured wrong. Note that I haven't been able to reproduce this bug on the dev VM.

**Comment by seav** [comment]
Additionally, I've been encountering weird caching issues in other pages as well. Sometimes JavaScript async/API calls (like the list of spatial resources, or the spatial units) return the cached response. So if I delete a location, that location is still displayed on the map. It seems some extreme caching has been inadvertently set on the staging server.

**Comment by alukach** [comment]
Agree regarding that caching seems to be the cause of the logout issue.

![i2u3y4vgse](https://user-images.githubusercontent.com/897290/31416533-fc726044-ade6-11e7-9641-9b2062dda08e.gif)

Trying to hunt down how that would have arisen.
