### ISSUE TITLE
Rounding errors accumulate in the project area calculation

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1847]
### Steps to reproduce the error
Not sure how to reliably recreate this.

### Actual behavior
See the following screenshot showing 0 locations but with a small negative total area.

![screen shot 2017-10-11 at 01 14 59](https://user-images.githubusercontent.com/873653/31400363-e31d3638-ae21-11e7-87c8-128e3e686ce3.png)

### Expected behavior
I expect that no total area is shown similar to a brand new project that has no locations yet.

**Comment by clash99** [comment]
Fixed so area doesn't show unless it is greater than 0.
