### ISSUE TITLE
Don't display the add project link/button if the user does not have the project.create permission

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#185]
Currently<sup>†</sup>, any logged-in user can click the add project link/button and this displays a three-page project creation wizard. It is only after going through all three pages that the user is given a permission denied error if the user does not actually have the `project.create` action permission.

It would be better in terms of UX if the link/button is hidden if the user does not have this permission in the first place or immediately given the permission denied error when accessing the first page of the wizard.

<sup>†</sup> But only if the database has organizations:

    context['add_allowed'] = Organization.objects.count() > 0

**Comment by clash99** [comment]
Same thought should apply to adding a new location to a project.  Instead of messaging after the fact, we should hid the button from users that aren't eligible for that action.
