### ISSUE TITLE
Dashboard map and create project geometry map controls have wrong z-index

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#186]
The map controls (zoom buttons, search, layer selector, etc.) for the dashboard map and the create project geometry map have a z-index that is too high: they show on top of the main header area. This may or may not be caused by the fix for #140.

![cadasta map controls z-index defect](https://cloud.githubusercontent.com/assets/873653/15281803/09f44214-1b71-11e6-8249-78a32f508730.png)

**Comment by clash99** [comment]
This was fixed with #234
