### ISSUE TITLE
[Phone-login] Platform sends important text message to unverified phone number

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1862]
_**Note: This applies to the phone login feature branch. As such, this bug can only be confirmed by running the `additional-login-options` branch in the dev VM.**_

### Steps to reproduce the error
1. Using an existing account that has a verified email address, but no existing phone number, log in and go to the profile edit page.
2. Empty the email address field.
3. Add a new valid phone number to the phone field.
4. Input the correct password and click on the "Update profile" button.

### Actual behavior
Phone† corresponding to the new phone number receives the following text message:

> You are receiving this message because a user at Cadasta Platform removed the email address from the account linked to this phone number. If it wasn't you, please contact us immediately at security@cadasta.org

_† If running on the dev VM, the phone will not actually receive a message, but the Django server log will show the text message that would have been sent to the phone._

### Expected behavior
The message above should not have been sent because it contains important security information but the phone number has not been verified yet.

**Comment by valaparthvi** [comment]
@seav It has been previously decided that an update message must be sent to the user's phone/email even if it has not been verified.

**Comment by valaparthvi** [comment]
@seav @oliverroick @clash99 
Can you guys review [this](https://docs.google.com/document/d/1MwM_rfKoGZiT4q0CKEjxCjtbgGDYd_A8zGBeq7Jp6II/edit?usp=sharing)? There is a lot of confusion regarding when an update notification must be sent and what should be the verification status of phone/email to receive an update, so I have noted different cases down. Let me know. Thanks.

**Comment by oliverroick** [comment]
I'd say @seav is correct in this case. The info about the email being removed should only go to the email address. And the phone number should only receive a verification code. 

Same applies the other way around: If the user removes the phone number and adds an email address, the phone receives an info the number was removed and the email should receive a verification link.

All other cases in your document are correct.

**Comment by valaparthvi** [comment]
Since user account will only have one identifier( either phone or email), this issue will no longer be an issue.
Closing it.
