### ISSUE TITLE
[Phone-login] Platform deletes email when it is replaced with an unverified phone number

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1863]
_**Note: This applies to the phone login feature branch. As such, this bug can only be confirmed by running the `additional-login-options` branch in the dev VM.**_

### Steps to reproduce the error
1. Using an existing account that has a verified email address, but no existing phone number, log in and go to the profile edit page.
2. Empty the email address field.
3. Add a new valid phone number to the phone field.
4. Input the correct password and click on the "Update profile" button.
5. Log out.
6. Try to log in using the original email address and password.

### Actual behavior
User cannot log in.

### Expected behavior
User should still be able to log in while the new phone number hasn't been verified yet.

Note: This is the behavior when an existing email address is replaced with a new email address: until the user has verified the new email address, they can still log in using the old email address. In terms of security, I think this is the correct behavior because otherwise if the user accidentally enters the wrong phone number, they are then locked out of their account. In addition, it is stated in the [Functional Specification](https://docs.google.com/document/d/1D9o1HbJ95J4IG2dynQqJ3F0-EX6d3G1lCnTLcLTpTOc) that: "Do not remove the email address field until user verifies the phone number".

**Comment by valaparthvi** [comment]
@seav Do you suggest that if the user replaces the phone with email(or vice versa), the phone should not be added to the account and email should not be deleted from the account until user verifies the newly added phone number?

**Comment by valaparthvi** [comment]
@seav do you think we should allow the user to remove email address only if the phone is verified(and vice versa)? Should we raise a form error if a user tries to remove email when an unverified phone is linked to the account(and vice versa)?

**Comment by oliverroick** [comment]
@SteadyCadence suggested during the programs meeting:

It's unlikely that users will switch from a phone number to an email address once they have signed up, so there's no need to provide that option.

We will change the user profile form so that either the phone field or the email field is available, depending on the initial choice a user has made.
