### ISSUE TITLE
[Phone-login] User receives info message for a correct email address when resending the confirmation email

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1869]
**_Note: This applies to the phone login feature branch. As such, this bug can only be confirmed by running the `additional-login-options` branch in the dev VM._**

### Steps to reproduce the error
1. Register a new user account using an email address.
2. After registering, you should be on the "Account Verification" page. Follow the "Click here if you did not receive an email or text." link.
3. Enter the same email address you used in Step 1.
4. Click the "Send Verification" button.

### Actual behavior
You get an info alert message:

> Confirmation email sent to **_email-address_**.

### Expected behavior
This info alert message should not be shown and it does not match the success alert message that is also shown:

> Your email address has been submitted. If it matches your account on Cadasta Platform, you will receive a verification link to confirm your email.

In addition, if you provide a wrong email address at Step 3, you don't get the info alert message which is what is expected.

**Comment by valaparthvi** [comment]
The alert message is shown when a correct email address(or phone number) has been submitted. Since the messages do not match, it is better to remove the alert info.

**Comment by valaparthvi** [comment]
Displaying an info alert is something that django-allauth does implicitly when it sends a confirmation email. I don't think we can make changes there.
