### ISSUE TITLE
Platform allows same email in different case

### ISSUE THREAD

**Issue by alukach** [Cadasta/cadasta-platform#1878]
### Steps to reproduce the error

1. Register user with username `testuser1` and email address: `<your_cadasta_email_username>+testcase@cadasta.org`
1. Register user with username `testuser2` and with email address: `<your_cadasta_email_username>+TESTCASE@cadasta.org`

### Actual behavior

1. Registration will succeed
1. Try to login, 500 error returned, following error logged:
```
MultipleObjectsReturned at /account/login/
get() returned more than one User -- it returned 2!
```

### Expected behavior

Error thrown on registration of second username stating that account already exists.

**Comment by oliverroick** [comment]
This has been fixed with #1786

**Comment by alukach** [comment]
@oliverroick Do we have a plan for how we will deal with email case issues that currently exist in the database?

**Comment by oliverroick** [comment]
We have only one case in the production database and have already been in touch with them. We can handle this case individually
