### ISSUE TITLE
Draw tools not displaying after JS and CSS compression

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1882]
Drawing tools on the map are not displaying icons on staging as reported by @SteadyCadence. Related to #1860.

**Comment by clash99** [comment]
Troubleshooting: 

Leaflet draw css not compressed correctly on staging: 
![screenshot 2017-11-08 11 09 55](https://user-images.githubusercontent.com/1119621/32562911-76f9a5f8-c475-11e7-9c29-60c8c67dd50e.png)

**Comment by oliverroick** [comment]
Closing this, since we've reverted compression. Feel free to re-open if required.
