### ISSUE TITLE
Not able to (easily) create a project in orgs with more than 10 members

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1886]
### Steps to reproduce the error
1. Have/create an org with more than 10 members
2. Create a new project
3. In third step (assigning permissions) user is not able to continue. After clicking on next you are still redirected to the same page, unless you show all the users in the same page. 

See video for further clarification: 
https://screencast.com/t/vKTZqZvNOilh

### Actual behavior

See above

### Expected behavior

See above

**Comment by oliverroick** [comment]
Addressed in #1918.
