### ISSUE TITLE
[Phone-login] Password validation for phone number not implemented on client side

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1898]
### Steps to reproduce the error

1. Sign up using a phone number
2. Make the phone number part of the password

### Actual behavior

The form is submitted and returned with an error that the password contains the phone number. 

### Expected behavior

The validation should happen on client side, the form should not be submitted to the server.

**Comment by MappingKat** [comment]
I got the proper verification when I "changed" the password on the "Edit Profile" page.
<img width="616" alt="screen shot 2017-11-15 at 6 33 52 pm" src="https://user-images.githubusercontent.com/1077436/32869336-a5ac8334-ca33-11e7-8a7a-06a6e94e4a30.png">

**Comment by MappingKat** [comment]
Oh I misread the issue... you can disregard that above comment. @oliverroick, you think that the validation should be sooner?

**Comment by Edely** [comment]
Hi. I am writing a fix to this bug. For the validation should I consider the country code as part of the phone number or discard it?

**Comment by valaparthvi** [comment]
@Edely Consider only the phone number, you can discard the country code.

**Comment by clash99** [comment]
In progress notes - some of the custom validation is being blocked by django-parsley validation so I'm trying to untangle and simplify the validation of the registration form.
