### ISSUE TITLE
Taken to Error Page after trying to register fake phone number

### ISSUE THREAD

**Issue by MappingKat** [Cadasta/cadasta-platform#1902]
### Steps to reproduce the error

1. Registered user account with email
2. Went to "edit profile" and add number to profile
3. Typed fake phone number with spaces (profile did not save because of that formatting)
4. Typed fake phone number with wrong international code (+01) 

### Actual behavior

When I entered the fake number, I was sent to the "Platform Error Page". Then when I go back to Cadasta I see a banner that says that a verification token was sent to that number... so it seems like it may have worked?

### Expected behavior

I expect not to be taken to a "Platform Error" page if the number does not work/is fake

**Comment by valaparthvi** [comment]
Can you show the "Platform Error Page" or what phone number did you type in? And was the user created?

**Comment by oliverroick** [comment]
The corresponding error is [E#271](https://opbeat.com/cadasta/platform-staging/errors/271/).

This is related to #1897. We need to evaluate, which of the many errors types we should be handling and provide feedback to the user, which of these should result in an actual error. 

In this case, we should catch the error and provide the info to an invalid number as a form error to the user.
