### ISSUE TITLE
Update header ui

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#193]
Update header area to match wireframes

**Comment by clash99** [comment]
feature/ui-header is getting some functional testing errors.  @seav can you let me know what is needed to get this to pass?

**Comment by seav** [comment]
I see that the account links are now in a drop-down menu. The functional test function to logout a user needs to be modified to add the step of opening this menu. I can make a branch of your branch to add this step and then you can pull the changes.

**Comment by seav** [comment]
@clash99: I have pushed a fix to feature/ui-header. Just pull it to your local repository to get the changes.

**Comment by clash99** [comment]
Thank you for your help @seav  - I've created pull request #199.
