### ISSUE TITLE
Save/Cancel buttons are not fully visible when editing the project details or permissions

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#194]
When editing project details or permissions, the Save and Cancel buttons are partially overlapped by the page footer.

![cadasta - edit project details](https://cloud.githubusercontent.com/assets/873653/15348658/289a80a4-1cff-11e6-9ddb-3df1eb37b7d4.png)
![cadasta - edit project permissions](https://cloud.githubusercontent.com/assets/873653/15348659/289b50a6-1cff-11e6-849c-533c01c6de87.png)

**Comment by ian-ross** [comment]
Assigned to @seav for review.

**Comment by wonderchook** [comment]
I reviewed while updating issues.
