### ISSUE TITLE
Link Error (Page Not Found)

### ISSUE THREAD

**Issue by BrodieFord20** [Cadasta/cadasta-platform#1945]
1. Go to: https://platform.cadasta.org/account/login/
2. Login with acceptable account
3. Click on the "?" icon at the top right corner of the page
4. Then on the drop-down menu, click "User Guide Quick Links" 
5. In the Quick Links window, click the: "Collecting data using Geographical Open Data Kit (GeoODK)"option
6. This leads to the "Page Not Found" error

[Please try to describe the actions that led to the incorrect behavior
in as much detail as possible.]

"Page Not Found" error

[Please describe the outcome of your actions.]

The user should be brought to the: "Collecting Data with GeoODK Collect (Geographical Open Data Kit)" space in the Cadasta overview located here: https://docs.cadasta.org/en/05-odkcollect.html

[Please explain what behavior you would have expected instead.]

**Comment by oliverroick** [comment]
@clash99 could you please have a look at this when you have a moment?

**Comment by clash99** [comment]
Thanks for reporting @BrodieFord20. 

The quick links have been updated in inline manual to reflect recent documentation changes.  

![screenshot 2018-01-19 11 20 42](https://user-images.githubusercontent.com/1119621/35163049-00c22ed6-fd0b-11e7-9b0f-284b57ab1752.png)

**Comment by BrodieFord20** [comment]
Very welcome! My classmate and I are participating in a software development class and we chose your project to work with.

Could you possibly help us download the code to run the tests and/or walk through the code to see how the project works at a lower level?

Thank you for your time!

-Brodie

________________________________
