### ISSUE TITLE
Tooltip: Project translation dropdown (Functionality)

### ISSUE THREAD

**Issue by BrodieFord20** [Cadasta/cadasta-platform#1949]
### Steps to reproduce the error
1. Go to: https://platform.cadasta.org/account/login/
2. Login with user name and password
3. After logging on, click on the "?" icon
4. From the drop down menu, select the Tooltip: Project translation drop down
5. Nothing seems to be responding
I am not sure if a project needs to be created before or after this initial click but I was unable to see anything change
[Please try to describe the actions that led to the incorrect behavior
in as much detail as possible.]

### Actual behavior
Nothing seemed to occur visually on the screen
[Please describe the outcome of your actions.]

### Expected behavior
This is supposed to display the language options if I am not mistaken
[Please explain what behavior you would have expected instead.]

**Comment by clash99** [comment]
I've removed this option from the help widget in inlinemanual since it should only be seen relative to the tooltip launcher, not in the general help topics.
