### ISSUE TITLE
The imagery options

### ISSUE THREAD

**Issue by BrodieFord20** [Cadasta/cadasta-platform#1955]
### Steps to reproduce the error
1.Go to: https://platform.cadasta.org/dashboard/
2. Hover  on the menu with three squares (on the map) in the top right corner. 
3. Begin clicking through each view options
[Please try to describe the actions that led to the incorrect behavior
in as much detail as possible.]

### Actual behavior
The +Vivid imagery and Recent imagery, as well as the +Vivid imagery with OpenStreetMap and the Recent imagery with OpenStreetMap depict the same data based on the option. It seems as if the recent imagery option is paired with the +Vivid imagery option.
[Please describe the outcome of your actions.]

### Expected behavior
Are they supposed to depict different data on the screen?
[Please explain what behavior you would have expected instead.]

**Comment by oliverroick** [comment]
Hi @BrodieFord20,

thanks for your interest in the project. I checked and the imagery seems fine for Leipzig, Germany. Which area did you look at?

**Comment by BrodieFord20** [comment]
Hello Oliver,
Nothing with the display, it just seems as if the options display the same thing for all recent imagery and all +vivid imagery options.
-Brodie
________________________________

**Comment by oliverroick** [comment]
Recent imagery and vivid are different at the location that I checked. Could you point me to the area that you were looking at?

**Comment by BrodieFord20** [comment]
I was looking over North America, I think they just display the same thing, right?

________________________________

**Comment by oliverroick** [comment]
Yes, nothing we can change. Closing the ticket
