### ISSUE TITLE
Demo Sample Project Walkthrough

### ISSUE THREAD

**Issue by TyM16** [Cadasta/cadasta-platform#1956]
### Steps to reproduce the error

1. Sign in as a guest user on the demo.

2. Click on the "?" button at the top of the page and choose "Sample Project Walkthrough".

### Actual behavior

The page states that the account doesn't have the permissions to access the project and refreshes four times.

### Expected behavior

The page should navigate to the sample project.

**Comment by clash99** [comment]
![screenshot 2018-02-05 09 30 06](https://user-images.githubusercontent.com/1119621/35812989-11d7fc64-0a58-11e8-9356-32aa67313192.png)

Initial diagnosis reveals names have changed in demo so the tutorial needs to be updated to reference an existing project.

**Comment by clash99** [comment]
Updated Sample Project Walk-through available on https://demo.cadasta.org. Screencast available here: https://www.screencast.com/t/ygwRqtNfAr
