### ISSUE TITLE
The HTML <title> of add/edit project pages should be more specific

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#198]
Unlike other pages, the HTML `<title>` tag only specifies "Cadasta" while adding a new project and only "Cadasta | &lt;project name>" when editing a project. It would be better if these were more specific.

For comparison, adding a new organization has "Cadasta | Add new organization" while editing an organization has "Cadasta | Edit &lt;org name>".

**Comment by clash99** [comment]
Inventory of page titles changed:

- [ ] Organization dashboard
- [ ] Organization edit members
- [ ] Add new project - draw map
- [ ] Add new project - add details
- [ ] Add new project - assign team
- [ ] Project dashboard
- [ ] Project - edit location
- [ ] Project - edit details
- [ ] Project - edit member permissions
- [ ] Project - resource index
- [ ] Project - add new resource
- [ ] Project - upload new resource
- [ ] Project - edit resource
- [ ] Project - resource detail
- [ ] Project - add location
- [ ]  Project - edit location
- [ ] Project - delete location
- [ ] Project - location detail
- [ ] Project - location add relationship
- [ ] Project - location add new resource
- [ ] Project - location upload new resource
- [ ] Project - map
