### ISSUE TITLE
Datepicker styles are missing on add-relationship form

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1989]
### Steps to reproduce the error

1. Create a project using a questionnaire that contains a date field (for example the _Customary Rights Form_)
2. Create a location and then add a relationship. 

### Actual behavior

The date picker looks like this:

![screen shot 2018-02-15 at 16 24 05](https://user-images.githubusercontent.com/159510/36264551-4d5feb8a-126d-11e8-8b42-37dd455ffa62.png)

### Expected behavior

The date picker should look like this:

![screen shot 2018-02-15 at 16 29 22](https://user-images.githubusercontent.com/159510/36264582-6653d8c2-126d-11e8-8833-9c81a0c2c44a.png)

**Comment by clash99** [comment]
Updated link to css file. 

<img width="671" alt="screenshot 2018-02-18 14 27 38" src="https://user-images.githubusercontent.com/1119621/36356479-2a00a48e-14b8-11e8-8733-37d509d733b5.png">
