### ISSUE TITLE
Improve Cluster Tolerance on Platform Map

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1990]
Opening this as a placeholder for discussions and ancillary information.

@MappingKat/@clash99 could you coordinated what needs to be done.

**Comment by clash99** [comment]
Projects with lots of smaller parcels are having a hard time seeing all the parcels as boundaries, instead some are showing as the icon marker. I'm lowering the minimum threshold (minimum width and height in pixels to show) to 10 from 20 for the project views only.

**Comment by clash99** [comment]
**Before with minimum tolerance of 20:**

<img width="1348" alt="screenshot 2018-02-20 11 42 37" src="https://user-images.githubusercontent.com/1119621/36439651-33471aec-1633-11e8-81f7-f52bb59063ba.png">


**After with tolerance lowered to 6:** 

<img width="1346" alt="screenshot 2018-02-20 11 40 21" src="https://user-images.githubusercontent.com/1119621/36439650-33299094-1633-11e8-984d-d0da0c48b425.png">
