### ISSUE TITLE
Exports UI Improvement Implementation

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1991]
Following #1883, the UI for listing and accessing exports should be improved. 

This task is to implement the proposed for improvements.

**Comment by clash99** [comment]
Wireframes from slack discussion on 1/18/2018:

![exportmessaging](https://user-images.githubusercontent.com/1119621/36312275-796c9f08-12f3-11e8-91d0-006b50f08f3e.png)

![exportmessaging-alert](https://user-images.githubusercontent.com/1119621/36312287-89b7a39e-12f3-11e8-974e-9ce4ed53cbd4.png)

I will update ui without the option to remove from list (x in right column), which is added functionality from our current implementation.

**Comment by clash99** [comment]
**Project dashboard right column:**

<img width="366" alt="screenshot 2018-02-20 20 34 07" src="https://user-images.githubusercontent.com/1119621/36461610-1a862b82-1684-11e8-86c7-960cff89001c.png">

**Alert message after export:**

<img width="626" alt="screenshot 2018-02-20 21 19 27" src="https://user-images.githubusercontent.com/1119621/36461601-107f8f84-1684-11e8-85b9-8f8a81b6e618.png">
<img width="664" alt="screenshot 2018-02-20 21 19 50" src="https://user-images.githubusercontent.com/1119621/36461602-109b339c-1684-11e8-9550-419be97d57db.png">
<img width="651" alt="screenshot 2018-02-20 21 20 09" src="https://user-images.githubusercontent.com/1119621/36461603-10c55de8-1684-11e8-8111-e6ce7a43ff75.png">
<img width="645" alt="screenshot 2018-02-20 21 20 27" src="https://user-images.githubusercontent.com/1119621/36461604-10f16622-1684-11e8-8bf0-69f645b00cf3.png">
