### ISSUE TITLE
Searching on React.js tables does not reset pagination

### ISSUE THREAD

**Issue by alukach** [Cadasta/cadasta-platform#1995]
### Steps to reproduce the error

Open project with multiple pages of data, skip to second page.  Make search with query that should only match one record.

### Actual behavior

Being that results will be on first page and we're currently viewing the second page of data, table shows "No matching records found" and "Showing 11 - 11 of 1" in results.

### Expected behavior

The table should automatically send you back to either first page of data or to last page with results.

### Dev Notes

There is a bit of logic built in the table to prevent this problem when altering the page size of the table: https://github.com/Cadasta/cadasta-platform/blob/5f0d1a0644982392070c3e9243de20f160cb9f7a/cadasta/core/static/jsx/paginated-table.jsx#L50-L67

This logic should likely be moved or duplicated to the success handler of the `fetchData` call.

**Comment by seav** [comment]
Hmmm. I guess this is the reason why I somehow encountered negative record numbers "Showing -3 - -3 of 10" once before. I tried recreating this but couldn't remember what I did. :/
