### ISSUE TITLE
Searchable/Sortable/Filterable Lists

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#20]
all list views (organisations, projects, parcels, parties, relationships, resources) should be universally sortable (including a simple multi-column sort), filterable (again, by multiple columns, using quick dropdowns), free-text searchable and should support pagination for long lists (some of the lists might also require bulk operations, e.g. for adding users to an organisation or project; we should develop a pattern for these bulk operations that we use consistently across the platform).

**Comment by clash99** [comment]
Wireframe phase in progress.

**Comment by oliverroick** [comment]
I have extended `react-bootstrap-table` to match our requirements. I had to adapt pagination a little bit and added means to switch per column filtering on and off. 

The code lives in [our fork](https://github.com/Cadasta/react-bootstrap-table/) in branch [`pagination`](https://github.com/Cadasta/react-bootstrap-table/tree/pagination). A word of warning: The code is very ugly and not very nice to read. 

There are still some minor glitches in the UI; @clash99 is going to look at those.

**Comment by ian-ross** [comment]
@oliverroick How do you want to do review of this?  Are the examples in that repo enough to demonstrate that it's working (including your pagination changes, which I see are relatively small)?  Can you recommend any other approach to reviewing this?  Are you thinking we should just sign off that "Yup, this is an OK table widget to use"?

**Comment by oliverroick** [comment]
I have basically overwritten the pagination to do what we want, it is reflected it in the examples. For filter toggling, I created a new example at the end of the filter examples page. Both can be viewed by running the example-server as described in the Readme.

To answer your question, I would look at the example and check if it behaves the way you'd expect (the repository doesn't have any tests). I would wait with the final review until Chandra has had a look at the UI issues.

**Comment by ian-ross** [comment]
OK, I'll do that.

**Comment by ian-ross** [comment]
@oliverroick I've had a look at this.  A few comments:

 - I can't figure out if there's a good way to deal with translations for filter placeholder text, the "No data to display" message and so on.  Can we just use `t("blah")` and have it picked up by the gettext plugin somehow?
 - The date filter is a bit weird.  We might want to revisit that to have a date picker and date ranges.
 - Selecting table rows with checkboxes seems to be broken in Firefox (works OK in Chrome).  You can see this by playing with the `only-show-selected-table` and `externally-managed-selection` examples.
 - Pagination has a bit of an oopsie.  Go to the first pagination example, set the "items per page" to 10, go to page 7 (the last page), then set the "items per page" to 50.  You'll end up on "Page 7 of 2".
 - I couldn't figure out what "multi-column" search is supposed to do, but it's probably not important.
 - We might need to look at styling for cell editing: when you click on a cell to edit, the row height jumps around, which looks a bit shonky.

Generally though, I think it looks like something we can use.  I guess it's not impossible that we might want to do a cleanup later on, but the React API doesn't look too bad, so we ought to be able to refactor and tidy the code without changing that too much, which to me says that we're fine with going ahead with using this for now.

**Comment by ian-ross** [comment]
@oliverroick  OK, I see you've fixed the "7 of 2" bug and @clash99 has added some styling.  Do you want to do anything about any of the other things on the list above, or can we call this "done"?  (At least for now.  We might want to revisit when we start using it for real.)

**Comment by oliverroick** [comment]
@ian-ross If you're ok with the changes, we can merge the changes into our master and consider it done until we revisit.

Some answers the questions:

> I can't figure out if there's a good way to deal with translations for filter placeholder text, the "No data to display" message and so on. Can we just use t("blah") and have it picked up by the gettext plugin somehow?

I think, the gettext plugin will pick these translations up. Not sure about how to manage dependencies, since the translation system is built into `cadasta-platform`. We could extract translation into a separate library and use it in both  `cadasta-platform` and `react-bootstrap-table`.

> The date filter is a bit weird. We might want to revisit that to have a date picker and date ranges.

I agree, it's a bit useless as it is now. I think, we can implement date range filtering by building a custom filter.

> Selecting table rows with checkboxes seems to be broken in Firefox (works OK in Chrome). You can see this by playing with the only-show-selected-table and externally-managed-selection examples.

These seem to work fine; tested it against Chrome, Firefox and Safari (all on Mac). Maybe I'm missing something?

> We might need to look at styling for cell editing: when you click on a cell to edit, the row height jumps around, which looks a bit shonky.

This can probably only fixed by increasing the default row height of non-edited rows; maybe @clash99 has an idea what we can do.

**Comment by ian-ross** [comment]
OK, that all sounds like stuff that can wait until later to worry about.  I don't know what's going on with Firefox and the checkboxes.  It was pretty weird.

Anyway, I'll consider this closed for now!
