### ISSUE TITLE
CSS for Smaller Screens

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#200]
Made css adjustments to accommodate smaller screens.

- [x] Dashboard
- [x] Project Index
- [x] Project Overview
- [X] Project Resources
- [x] Organization Index
- [x] Organization Overview
- [x] Organization Members
- [x] Organization Members - Edit
- [X] Sign In
- [x] Register
- [x] Update Profile
- [x] Change Password
- [x] Reset your password
- [X] User List

I'm attaching screenshots here from FF viewpoint to catalog what I'm seeing in case someone is seeing something vastly different.  This is my first pass at responsive css for the platform so I will need to make some adjustments once released on different mobile devices, more browsers, etc...

**Comment by seav** [comment]
When the screen is small, the links to Projects, Organizations, and Users disappear. Is this intended to be fixed here?

**Comment by wonderchook** [comment]
@clash99 is this complete?

**Comment by clash99** [comment]
I will work to finalize remaining css pages in desktop - wizards and modals - and then work on css adjustments for smaller screens.

**Comment by clash99** [comment]
Responsive Screenshots: Dashboard

![screenshot 2016-06-21 10 58 21](https://cloud.githubusercontent.com/assets/1119621/16237002/1570935e-37a0-11e6-8fb0-a3a323841795.png)
![screenshot 2016-06-21 11 01 07](https://cloud.githubusercontent.com/assets/1119621/16237001/156eedba-37a0-11e6-99d5-b642cedc05e8.png)
![screenshot 2016-06-21 11 01 28](https://cloud.githubusercontent.com/assets/1119621/16237005/157387d0-37a0-11e6-9657-8ca52cb54108.png)
![screenshot 2016-06-21 11 01 38](https://cloud.githubusercontent.com/assets/1119621/16237004/1572e6ae-37a0-11e6-9434-f615027e7ee6.png)
![screenshot 2016-06-21 11 01 56](https://cloud.githubusercontent.com/assets/1119621/16237003/157098b8-37a0-11e6-8a9f-34ba118c5ec5.png)
![screenshot 2016-06-21 11 02 05](https://cloud.githubusercontent.com/assets/1119621/16237006/15763fac-37a0-11e6-835a-d623b809ec9a.png)

**Comment by seav** [comment]
As an OSM volunteer who has seen how other OSM volunteers become quite sensitive to the lack of attribution to OSM, the mobile landscape should still have the map attribution somehow.

**Comment by clash99** [comment]
Responsive Screenshots: Project Index

<img width="1328" alt="screenshot 2016-06-21 12 34 39" src="https://cloud.githubusercontent.com/assets/1119621/16240175/e2e2befe-37ad-11e6-9c15-7394ac0807e2.png">
![screenshot 2016-06-21 12 40 32](https://cloud.githubusercontent.com/assets/1119621/16240186/ed979efa-37ad-11e6-903f-10d5f5851881.png)
![screenshot 2016-06-21 12 40 38](https://cloud.githubusercontent.com/assets/1119621/16240195/fa199fca-37ad-11e6-9db8-8d152e9610c4.png)
![screenshot 2016-06-21 12 40 45](https://cloud.githubusercontent.com/assets/1119621/16240193/fa112dfe-37ad-11e6-8261-e597fa78245d.png)
![screenshot 2016-06-21 12 40 51](https://cloud.githubusercontent.com/assets/1119621/16240194/fa12f774-37ad-11e6-8d38-803192803d8d.png)
![screenshot 2016-06-21 12 43 58](https://cloud.githubusercontent.com/assets/1119621/16240202/00135cf4-37ae-11e6-9f76-624b183bac06.png)

**Comment by clash99** [comment]
Responsive Screenshots: Project Overview

<img width="1370" alt="screenshot 2016-06-21 18 42 07" src="https://cloud.githubusercontent.com/assets/1119621/16250092/41f4d4d6-37e0-11e6-86e6-f91e3ef00dc0.png">
![screenshot 2016-06-21 18 42 29](https://cloud.githubusercontent.com/assets/1119621/16250093/41f72c2c-37e0-11e6-93e2-7c24a7ef9f21.png)
![screenshot 2016-06-21 18 48 06](https://cloud.githubusercontent.com/assets/1119621/16250171/dffeb19c-37e0-11e6-86f1-8e6c27a1ec62.png)
![screenshot 2016-06-21 18 48 14](https://cloud.githubusercontent.com/assets/1119621/16250172/e007e3d4-37e0-11e6-8b62-e9292f02d817.png)
![screenshot 2016-06-21 18 48 24](https://cloud.githubusercontent.com/assets/1119621/16250174/e015fcf8-37e0-11e6-8385-858bad37fc30.png)
![screenshot 2016-06-21 18 48 31](https://cloud.githubusercontent.com/assets/1119621/16250173/e011fa7c-37e0-11e6-9845-1024722ad730.png)

**Comment by clash99** [comment]
Responsive Screenshots: Project Resources

<img width="1128" alt="screenshot 2016-06-21 19 41 28" src="https://cloud.githubusercontent.com/assets/1119621/16251069/a1343c4a-37e8-11e6-8fea-ee0c7b96dc6d.png">
![screenshot 2016-06-21 19 42 49](https://cloud.githubusercontent.com/assets/1119621/16251070/a134647c-37e8-11e6-8154-52f1d0576d9c.png)
![screenshot 2016-06-21 19 42 56](https://cloud.githubusercontent.com/assets/1119621/16251072/a134dc72-37e8-11e6-8cfe-867469987989.png)
![screenshot 2016-06-21 19 43 02](https://cloud.githubusercontent.com/assets/1119621/16251074/a1418620-37e8-11e6-97fb-7704f2e6f210.png)
![screenshot 2016-06-21 19 43 11](https://cloud.githubusercontent.com/assets/1119621/16251073/a1350efe-37e8-11e6-847a-a26b61e416e0.png)
![screenshot 2016-06-21 19 43 18](https://cloud.githubusercontent.com/assets/1119621/16251071/a134dfd8-37e8-11e6-9473-4dc9c8bd3b5b.png)

**Comment by clash99** [comment]
Responsive Screenshots: Organization Index
<img width="1336" alt="screenshot 2016-06-21 19 50 37" src="https://cloud.githubusercontent.com/assets/1119621/16251187/a1856ae2-37e9-11e6-97be-75cec6cad7e1.png">
![Uploading Screenshot 2016-06-21 19.50.43.png…]()
![screenshot 2016-06-21 19 50 53](https://cloud.githubusercontent.com/assets/1119621/16251188/a185c9c4-37e9-11e6-9599-83f47a4a6efe.png)
![screenshot 2016-06-21 19 50 58](https://cloud.githubusercontent.com/assets/1119621/16251190/a1868f1c-37e9-11e6-8d4d-b241b8756832.png)
![Uploading Screenshot 2016-06-21 19.51.06.png…]()
![Uploading Screenshot 2016-06-21 19.51.12.png…]()

**Comment by clash99** [comment]
Responsive Screenshots: Organization Overview

<img width="1240" alt="screenshot 2016-06-22 09 47 41" src="https://cloud.githubusercontent.com/assets/1119621/16271249/d9e84308-385e-11e6-8a4d-952ea1e48791.png">
![Uploading Screenshot 2016-06-22 09.47.58.png…]()
![Uploading Screenshot 2016-06-22 09.48.05.png…]()
![Uploading Screenshot 2016-06-22 09.48.11.png…]()
![screenshot 2016-06-22 09 48 20](https://cloud.githubusercontent.com/assets/1119621/16271252/d9eaaa9e-385e-11e6-8d9c-e63ad4090867.png)
![screenshot 2016-06-22 09 48 27](https://cloud.githubusercontent.com/assets/1119621/16271250/d9e9cc82-385e-11e6-9dd4-e5ae6014dfb3.png)

**Comment by clash99** [comment]
Responsive Screenshots: Sign In

<img width="1280" alt="screenshot 2016-06-22 09 58 38" src="https://cloud.githubusercontent.com/assets/1119621/16273658/105b265e-3868-11e6-961f-4485d664593b.png">
![screenshot 2016-06-22 09 59 07](https://cloud.githubusercontent.com/assets/1119621/16273656/105798e0-3868-11e6-806b-a0a6c51aa661.png)
![screenshot 2016-06-22 09 59 13](https://cloud.githubusercontent.com/assets/1119621/16273661/1061d314-3868-11e6-89e6-61dade80b9b4.png)
![screenshot 2016-06-22 09 59 18](https://cloud.githubusercontent.com/assets/1119621/16273660/10608220-3868-11e6-9544-320ac299aae0.png)
![screenshot 2016-06-22 09 59 30](https://cloud.githubusercontent.com/assets/1119621/16273657/105940c8-3868-11e6-87b8-f8b68a256d08.png)
![screenshot 2016-06-22 09 59 35](https://cloud.githubusercontent.com/assets/1119621/16273659/105c65b4-3868-11e6-9059-bec1b4750e39.png)

**Comment by clash99** [comment]
Responsive Screenshots: Register

![screenshot 2016-06-22 10 58 02](https://cloud.githubusercontent.com/assets/1119621/16273837/cf9da3a2-3868-11e6-9d34-24a4164a92b4.png)
![screenshot 2016-06-22 10 58 16](https://cloud.githubusercontent.com/assets/1119621/16273867/e81fab50-3868-11e6-8191-e951b8f305c8.png)
![screenshot 2016-06-22 11 01 25](https://cloud.githubusercontent.com/assets/1119621/16273875/ef713a36-3868-11e6-9c07-27083f0517c0.png)
![screenshot 2016-06-22 11 01 32](https://cloud.githubusercontent.com/assets/1119621/16273878/ef789d30-3868-11e6-94fa-30db9659c685.png)
![screenshot 2016-06-22 11 01 38](https://cloud.githubusercontent.com/assets/1119621/16273877/ef74af90-3868-11e6-9ffd-c3af9ff25799.png)
![screenshot 2016-06-22 11 01 44](https://cloud.githubusercontent.com/assets/1119621/16273876/ef739830-3868-11e6-919a-e2271b55bb1c.png)

**Comment by clash99** [comment]
Responsive Screenshots: Update Profile

![screenshot 2016-06-22 11 16 15](https://cloud.githubusercontent.com/assets/1119621/16274478/5ea51c54-386b-11e6-8b2a-60e827960ecc.png)
![screenshot 2016-06-22 11 16 31](https://cloud.githubusercontent.com/assets/1119621/16274474/5ea01128-386b-11e6-97d2-5aa06a2e0a4d.png)
![screenshot 2016-06-22 11 18 34](https://cloud.githubusercontent.com/assets/1119621/16274477/5ea3863c-386b-11e6-8039-a41d9bf84903.png)
![screenshot 2016-06-22 11 18 40](https://cloud.githubusercontent.com/assets/1119621/16274475/5ea0d054-386b-11e6-92e2-77a7e67705bb.png)
![screenshot 2016-06-22 11 18 54](https://cloud.githubusercontent.com/assets/1119621/16274479/5ea625b8-386b-11e6-8233-e7e4a76650a4.png)
![screenshot 2016-06-22 11 20 31](https://cloud.githubusercontent.com/assets/1119621/16274476/5ea22256-386b-11e6-9f59-287cb569eebe.png)

**Comment by clash99** [comment]
Responsive Screenshots: Change Password

![screenshot 2016-06-22 11 21 27](https://cloud.githubusercontent.com/assets/1119621/16274533/a0bea402-386b-11e6-9369-01a154b1ce9e.png)
![screenshot 2016-06-22 11 21 37](https://cloud.githubusercontent.com/assets/1119621/16274531/a0b80bf6-386b-11e6-8e0f-a6973f1da4d1.png)
![screenshot 2016-06-22 11 21 43](https://cloud.githubusercontent.com/assets/1119621/16274532/a0b82bd6-386b-11e6-854a-756ed5e5652f.png)
![screenshot 2016-06-22 11 21 49](https://cloud.githubusercontent.com/assets/1119621/16274528/a0b53944-386b-11e6-832a-e048279cc565.png)
![screenshot 2016-06-22 11 21 55](https://cloud.githubusercontent.com/assets/1119621/16274530/a0b799dc-386b-11e6-95ce-615f9eae6ee7.png)
![screenshot 2016-06-22 11 22 00](https://cloud.githubusercontent.com/assets/1119621/16274529/a0b57cc4-386b-11e6-8cd6-d73d856b7908.png)

**Comment by clash99** [comment]
Responsive Screenshots: Reset Password

![screenshot 2016-06-22 11 23 08](https://cloud.githubusercontent.com/assets/1119621/16274594/e8194492-386b-11e6-8ed4-9876fa79e041.png)
![screenshot 2016-06-22 11 23 28](https://cloud.githubusercontent.com/assets/1119621/16274595/e81a98ce-386b-11e6-9d99-8ee25a2bc512.png)
![screenshot 2016-06-22 11 23 35](https://cloud.githubusercontent.com/assets/1119621/16274598/e81d8e26-386b-11e6-8140-5efadaa47a9a.png)
![screenshot 2016-06-22 11 23 40](https://cloud.githubusercontent.com/assets/1119621/16274599/e81f10a2-386b-11e6-935b-e00dc1cdebee.png)
![screenshot 2016-06-22 11 23 45](https://cloud.githubusercontent.com/assets/1119621/16274597/e81bd982-386b-11e6-8b52-ee93097ee10d.png)
![screenshot 2016-06-22 11 23 51](https://cloud.githubusercontent.com/assets/1119621/16274596/e81bc938-386b-11e6-8da9-db44951f1b6d.png)

**Comment by clash99** [comment]
Responsive Screenshots: User List (Desktop version only for sys admin purposes)

<img width="1417" alt="screenshot 2016-06-22 11 56 53" src="https://cloud.githubusercontent.com/assets/1119621/16275702/c4f23384-3870-11e6-9326-8cbe984cb09f.png">

**Comment by clash99** [comment]
Responsive Screenshots: Organization Members

<img width="1417" alt="screenshot 2016-06-22 11 59 49" src="https://cloud.githubusercontent.com/assets/1119621/16275951/06f77702-3872-11e6-8691-6549eeca87c0.png">
![screenshot 2016-06-22 12 06 59](https://cloud.githubusercontent.com/assets/1119621/16275959/0e5e428c-3872-11e6-95d6-6f4f341ad493.png)
![screenshot 2016-06-22 12 07 07](https://cloud.githubusercontent.com/assets/1119621/16275960/0e60ef0a-3872-11e6-93a2-340c6f661d2c.png)
![screenshot 2016-06-22 12 07 12](https://cloud.githubusercontent.com/assets/1119621/16275963/0e61cce0-3872-11e6-81b7-cf8c99eec009.png)
![screenshot 2016-06-22 12 07 19](https://cloud.githubusercontent.com/assets/1119621/16275962/0e610cce-3872-11e6-87e0-754db1af21f5.png)
![screenshot 2016-06-22 12 07 31](https://cloud.githubusercontent.com/assets/1119621/16275961/0e60f86a-3872-11e6-924c-01a8b0357a69.png)

**Comment by clash99** [comment]
Responsive Screenshots: Organization Member - Edit

![screenshot 2016-06-22 14 07 58](https://cloud.githubusercontent.com/assets/1119621/16279967/fae0db6e-3882-11e6-915c-968119207f2c.png)
![screenshot 2016-06-22 14 08 35](https://cloud.githubusercontent.com/assets/1119621/16279968/faea31a0-3882-11e6-8ab6-5b46b70326cf.png)
![screenshot 2016-06-22 14 08 41](https://cloud.githubusercontent.com/assets/1119621/16279970/faf852da-3882-11e6-9829-db434c02c547.png)
![screenshot 2016-06-22 14 08 45](https://cloud.githubusercontent.com/assets/1119621/16279969/faf5e3f6-3882-11e6-9bde-c0629dd598ec.png)
![screenshot 2016-06-22 14 08 51](https://cloud.githubusercontent.com/assets/1119621/16279971/fb003dec-3882-11e6-96d3-04cdf6c5da06.png)
![screenshot 2016-06-22 14 08 57](https://cloud.githubusercontent.com/assets/1119621/16279972/fb01916a-3882-11e6-8d78-d91f3f52b77b.png)
