### ISSUE TITLE
Update icon on tab for CKAN platform

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#201]
Need to add Cadasta icon to tab header for platform.cadasta.org as was done for demo.cadasta.org

**Comment by wonderchook** [comment]
@bjohare is this something you updated recently on the demo site?

**Comment by wonderchook** [comment]
Issue moved to [Cadasta/cadasta #4](https://github.com/Cadasta/cadasta/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)
