### ISSUE TITLE
Page footer is no longer fixed to the bottom of the viewport

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#206]
Currently, the page footer is no longer fixed to the bottom of the viewport and scrolls along with the rest of the page content.

![cadasta - unfixed footer](https://cloud.githubusercontent.com/assets/873653/15414829/b9696c2c-1e70-11e6-986b-8fcb2b9962e2.png)

This seems like a recent regression. I guess this may have been caused by 756fa74c8fe2108ec42dbb8422c0cbce4af288ea.

**Comment by clash99** [comment]
@seav I believe this was fixed with the #234.  Can you verify?

**Comment by seav** [comment]
@clash99 I confirm that this is now fixed.
