### ISSUE TITLE
Dashboard map not centered over points being displayed

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#213]
The Pekapuran Laut Test Project is not being displayed on the dashboard because the pin is being placed on the Asian on the left-hand side, not the Asian that's centered in the viewport. If you move to the left on the map you can see it.

**Comment by linzjax** [comment]
So it looks like the UI is restricting which set of continents the user can access by snapping those back into center if they try to drag away from them. Since I import geojson points for the Pekapuran Laut Test Project, I didn't have these same constraints. If people are going to be import geojson we might want to find a way to translate those points.

**Comment by jnordling** [comment]
I also on the page where you create a new project. I felt from a user perspective that it was too far zoomed out. Maybe only show the bulk of one earth. Thats what you would except to see at least.

**Comment by linzjax** [comment]
The project "Chickens Everywhere" managed to be created outside of the center map. @wonderchook : Did you create this project from a really zoomed out state?

<img width="1280" alt="so_many_chickens_off_the_map" src="https://cloud.githubusercontent.com/assets/8128188/16586245/d973bd7e-4292-11e6-9455-146a2e02f084.png">

**Comment by wonderchook** [comment]
Hmmm apparently that is exactly what I did, reproduced it. 

![more-chickens](https://cloud.githubusercontent.com/assets/67992/16599420/0aae6a00-42b7-11e6-85b7-db4e0e6cc1e5.jpg)

**Comment by seav** [comment]
I think this is because the staging environment does not yet contain the out-of-bound geometry check that @linzjax added.

**Comment by seav** [comment]
I tried recreating this issue on the latest master and I can confirm that a project drawn outside of the "center" map gets re-placed within ±180° longitudes.
