### ISSUE TITLE
GeoODK/ODK Integration

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#219]
# Summary
GeoODK is a mobile data collection application. It allows customized forms to be created using XLSForms and then downloaded to an android device for online or offline data collection. Cadasta wants to support GeoODK as a method for users to create records. To do this we want to mimic the API that GeoODK expects to allow download of forms from the Cadasta platform and submission of data to the Cadasta platform.

# Links to requirements and functional testing script
- [Requirements](https://devwiki.corp.cadasta.org/GeoODK%20Api)

# Acceptance criteria
* User can login to the Cadasta platform from GeoODK or ODK
* User can download a list of available forms from the Cadasta platform
* User can select and download a form from GeoODK or ODK
* User can submit data to the Cadasta platform from GeoODK or ODK

# Task list

**Comment by ian-ross** [comment]
Closed by #370
