### ISSUE TITLE
Message placement on single org/project pages

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#229]
Need to figure out better placement for messaging on single organization and single project pages.

**Comment by clash99** [comment]
Added top margin and max-width so they don't conflict as much with underlying page for easier visibility.  Success messages also fade after 5 (they are also dismiss-able).

**Comment by clash99** [comment]
![screenshot 2016-07-10 10 46 00](https://cloud.githubusercontent.com/assets/1119621/16714532/9598a572-468b-11e6-82e7-b64da3df4aa0.png)
![screenshot 2016-07-10 10 46 11](https://cloud.githubusercontent.com/assets/1119621/16714531/95951a4c-468b-11e6-9396-a3acb41decde.png)
![screenshot 2016-07-10 10 46 17](https://cloud.githubusercontent.com/assets/1119621/16714530/9594c100-468b-11e6-8c22-cc931c1d62a5.png)

**Comment by seav** [comment]
Would adding a drop shadow help with visibility?

**Comment by clash99** [comment]
good idea - i'll add that

**Comment by clash99** [comment]
Better - thanks for the suggestion @seav 
![screenshot 2016-07-10 13 58 07](https://cloud.githubusercontent.com/assets/1119621/16715482/6805c192-46a6-11e6-8c0e-ad9afd566e6a.png)
