### ISSUE TITLE
Form field validation

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#23]
Form field validation: the same for all forms, so we can define the forms in HTML5 and build one reusable validation script.

**Comment by oliverroick** [comment]
I had a look at different form field validation libraries; most of what is available seems to be experimental or in early stages of development. There were three libraries that stood out:

1. [formsy-react](https://github.com/christianalfoni/formsy-react) provides solid validation with a lot of build-in field validation rules as well as a lot of flexibility to implement custom validation for selected forms. [formsy-react-components](https://github.com/twisty/formsy-react-components) brings React components based on formsy-react to define form field elements. It uses Bootstrap syntax, so plays nicely with what we already have. 
2. [newforms](https://github.com/insin/newforms) is a bit less intuitive, but provides similar functionality to formsy-react. There is also [bootstrap support](https://github.com/insin/newforms-bootstrap), but it doesn't seem to be actively developed and it's a bit buggy. Also documentation is a bit sparse. This wouldn't be my first choice.
3. [react-formal's](https://github.com/jquense/react-formal) functionality is comparable to the first two examples, but it's syntax is the least intuitive and the least readable. I took me a while to get started. It feels very stable and is under active development. 

I suggest, we go forward with formsy-react. I will start integrating  I will start to integrate formsy-react and formsy-react-components into the front-end today.

**Comment by ian-ross** [comment]
@oliverroick Sounds good.  Having some prebuilt React components to give us some ideas (and to use!) is definitely nice.

**Comment by oliverroick** [comment]
Implemented, see PR #77
