### ISSUE TITLE
Add Button for new organization is not visible

### ISSUE THREAD

**Issue by jnordling** [Cadasta/cadasta-platform#243]
When adding a organization, the add button at the bottom right is not visible. I have a 15in macbook. there is no overflow scroll for the dialog form. See image

<img width="1439" alt="screen shot 2016-06-15 at 10 49 51 am" src="https://cloud.githubusercontent.com/assets/11786919/16084566/4e7d70e4-32e7-11e6-8c47-a65c5caafa5d.png">

**Comment by clash99** [comment]
Should be covered this week when I do modal css in #156.
