### ISSUE TITLE
Edit project location leads to a blank page

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#247]
`http://localhost:8000/organizations/cadasta/projects/cadasta-indonesia-test-project/edit/geometry/`
<img width="1280" alt="screen shot 2016-06-15 at 2 17 41 pm" src="https://cloud.githubusercontent.com/assets/8128188/16091956/f0447a8c-3303-11e6-8b47-f757c3e1a317.png">

**Comment by oliverroick** [comment]
This seems to be related to #240. 

Not sure what's going on. The template file has not been touched and it works on my current feature branch which doesn't have the latest commits to master. I'll look into it.
