### ISSUE TITLE
Multiple scrollbars

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#249]
Project overview has three scrollbars, which are partly overlapped by page elements. 

![screen shot 2016-06-16 at 13 00 23](https://cloud.githubusercontent.com/assets/159510/16114595/56380a20-33c2-11e6-96d0-b4a355ab2d02.png)

**Comment by clash99** [comment]
@oliverroick :  Can you confirm that this issue has been fixed?  I was never able to recreate it but I think recent changes have solidified the css and this shouldn't be happening.  Just let me know.... thanks!

![screenshot 2016-06-27 11 07 01](https://cloud.githubusercontent.com/assets/1119621/16386756/6deb74c0-3c57-11e6-95df-bedeb96f23c6.png)

**Comment by oliverroick** [comment]
This is fixed now. Closing this.

**Comment by oliverroick** [comment]
Error regressed Chrome 51.0.2704.84 (64-bit):

![screen shot 2016-06-27 at 20 36 53](https://cloud.githubusercontent.com/assets/159510/16391332/eff26f06-3ca6-11e6-9093-59f8d3bb175b.png)

**Comment by clash99** [comment]
There should only be one scrollbar for the right panel.  This is how I'm seeing it in Chrome.  http://screencast.com/t/u67d8fuwS

**Comment by wonderchook** [comment]
I'm seeing the same issue with multiple scroll bars on Chrome version: Version 51.0.2704.103 m

![Org Overview](https://cloud.githubusercontent.com/assets/67992/16399601/d620f994-3c88-11e6-97a0-5c3f60716023.jpg)
![Project Overview](https://cloud.githubusercontent.com/assets/67992/16399614/df1790c6-3c88-11e6-8679-04664f799b00.jpg)

**Comment by oliverroick** [comment]
I have merged PR #275 but the problem is still not fixed. 

I have checked this on various browsers: 

- Chome 51.0.2704.106 (64-bit) (even cleared my complete cache)
- Safari 9.1.1 (11601.6.17)
- Firefox 47.0

**Comment by clash99** [comment]
Thanks for the info - I'll look into it.

**Comment by ian-ross** [comment]
Closing via #455
