### ISSUE TITLE
Responsive layout needs fix

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#250]
The general layout is currently responsive. The content elements, however, are not. Headlines and buttons are floating into each other and overlap. The main content block is not accessible at all. 

![screen shot 2016-06-16 at 13 06 23](https://cloud.githubusercontent.com/assets/159510/16114749/2f40197a-33c3-11e6-81d8-bb136d094c8e.png)

I would suggest sticking with a fixed-width layout or setting the minimum screen width to prevent this from happening.

**Comment by clash99** [comment]
Will tackle this in #200.

**Comment by seav** [comment]
When the screen is width but not tall, the links on the left side are not all visible and accessible.
![screen shot 2016-06-30 at 17 00 11](https://cloud.githubusercontent.com/assets/873653/16482809/28a31960-3ee4-11e6-9afd-da8a22a833c1.png)

**Comment by clash99** [comment]
Kate confirmed this is working correctly.  Marking complete.

**Comment by clash99** [comment]
@seav Can you confirm this is working as expected?

**Comment by seav** [comment]
@clash99: Is this already in master? If not, which branch? Anyway, I think setting `overflow-y` to `auto` instead of `hidden` must work.

**Comment by clash99** [comment]
This is in master now - sorry for the confusion.

http://www.screencast.com/users/clash/folders/Jing/media/a8859eeb-2a12-4cd7-be50-e2ed0fa52139

**Comment by seav** [comment]
I confirm that the tab bar now scrolls when the viewport is short.
