### ISSUE TITLE
Permissions system

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#26]
Permissions system: the reusable backend component of this is https://github.com/Cadasta/django-tutelary.

Initial use in platform: back-end system for policy-based access control (data model, policy grammar, permissions engine); fixed roles defined by developers; no user-visible reference to policies, user-level permissions, etc.

**Comment by ian-ross** [comment]
Remaining tasks here based on code review with @oliverroick:

 - [ ] Support function views
 - [ ] Documentation improvements
 - [ ] End-to-end tests
 - [ ] Better treatment of collective actions
 - [ ] Policy update handling
 - [ ] Modify policy format to allow for comments
 - [ ] Caching for performance
 - [ ] Django admin interface (low priority: not directly needed for Cadasta)

**Comment by ian-ross** [comment]
I'm closing this now, as the individual tasks are all there as tickets on the django-tutelary repo.
