### ISSUE TITLE
Initial release - hide components

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#271]
Items that are either unlinked or undeveloped for milestone 1.  We should consider hiding these items:

- [x] Header - Info button [updated link]
- [x] Header - User avatar [hidden]
- [x] Footer - Privacy link [updated link]
- [x] Footer - Terms of service link [updated link]
- [x] Single project - Project header - add a location in split button [updated link]
- [x] Single project - Project header - add a relationship in split button [hidden]
- [x] Single project - Project header - add a party in split button [hidden]
- [x] Single project - Project header - import data in split button [hidden]
- [x] Single project - Project subnav - Map tab [updated link]
- [x] Single project - Project subnav - Reports tab [hidden]
- [x] Single project - Project subnav - Activity tab [hidden]
- [x] Single project - Edit project location - "add a location" button [updated link]
- [x] Single project - Edit project location - link to video [removed]
- [x] Single project - Edit project location - link to help center [removed]
- [x] Single project - Add project location - link to video [removed]
- [x] Single project - Add project location - link to help center [removed]
- [x] Single project - Overview - "add a location" button [updated]
- [x] Single project - Overview - link to video [removed]
- [x] Single project - Overview - link to help center [removed]
- [x] Single organization - Org subnav - Projects tab [hidden]
- [x] Single organization - Org subnav - Reports tab  [hidden]
- [x] Single organization - Org subnav - Activity tab  [hidden]
- [x] Single organization - Overview - link to video [removed]
- [x] Single organization - Overview - link to help center [removed]

**Comment by wonderchook** [comment]
we can use the links off cadasta.org for the Privacy link and the Terms of Service Link.

http://cadasta.org/privacy-policy/
http://cadasta.org/terms-of-use/

**Comment by clash99** [comment]
Updated footer links.

**Comment by clash99** [comment]
I'm proposing that instead of removing the info icon in the header, we link it to a modal with a short paragraph explaining the early stage of development and a general email address that the user can contact.  Thoughts?

**Comment by oliverroick** [comment]
Don't like it. It's like those "Under construction" GIFs from the 90s.

**Comment by wonderchook** [comment]
For the first release likes direct "i" to : http://cadasta.org/platform

@aliensunrise is working on an updated page there and I think it would include the required information a user might want.

**Comment by seav** [comment]
In Single project - Project subnav, the Reports and Activity tabs are not hidden when the tab bar is horizontal.
![screen shot 2016-07-01 at 21 29 49](https://cloud.githubusercontent.com/assets/873653/16522889/ff68f494-3fd2-11e6-8bb5-ad6c7f28495a.png)
![screen shot 2016-07-01 at 21 29 24](https://cloud.githubusercontent.com/assets/873653/16522891/ffe8ec30-3fd2-11e6-85cc-d99b1f9c8a7e.png)

**Comment by clash99** [comment]
Hid menu items on smaller screens: 
![screenshot 2016-07-01 09 59 14](https://cloud.githubusercontent.com/assets/1119621/16525584/bf40c5d2-3f72-11e6-8d4b-ddde075dbccf.png)
![screenshot 2016-07-01 10 00 34](https://cloud.githubusercontent.com/assets/1119621/16525585/bf430806-3f72-11e6-8feb-8774ee91b2df.png)
