### ISSUE TITLE
Errors in Parsing XLSForm Should Happen Sooner than the Project Overview Page

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#272]
Show errors for the xlsform sooner. Right now the user goes all the way through the project creation process and then gets an error about uploading their form. 

![xlsformerror](https://cloud.githubusercontent.com/assets/67992/16399817/a6c72522-3c8a-11e6-999d-ff1b9ba4ddb1.jpg)

**Comment by ian-ross** [comment]
I think this is one for me, since it's to do with the project creation wizard.

**Comment by wonderchook** [comment]
okay sounds good. @bjohare see above.

**Comment by bjohare** [comment]
Might be worth fixing #480 at the same time as they're closely related.. see https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/questionnaires/managers.py#L173

**Comment by ian-ross** [comment]
Agreed.  I'll add it to my list.  That `pass` is a little bit naughty.
