### ISSUE TITLE
Password Strength Enforcement

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#273]
We should enforce some sort of password requirements.

**Comment by seav** [comment]
This needs a bit more thought. The UI for this is also important: it should indicate what the requirements are. Also if we wanted to, we can even add those nifty password strength assessment widgets.

**Comment by dpalomino** [comment]
Added to backlog (item 36.00).

**Comment by dpalomino** [comment]
Dup of #735. Closing.
