### ISSUE TITLE
Anonymous Users Should Not Be Offered Lots of Buttons They Can't Use

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#274]
Currently Anonymous users are offered lots of buttons to "Add a new project" and "Add new members" on the organizational overview page for example. We should provide a better experience for these users and not offer them buttons they are going to click and then be told they don't have permission.

**Comment by linzjax** [comment]
Seems like permissions in general could use a bit of attention: checking to make sure everything is correct, and hiding buttons the user shouldn't be clicking on. This should also apply to logged in users without permissions.

**Comment by dpalomino** [comment]
Not currently relevant, closing issue. Please reopen if needed.
