### ISSUE TITLE
Can't download resources

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#281]
I don't see a way to download a resource.  I can preview it in tables and in modal but I don't see a button or link to download original file.

<img width="639" alt="screenshot 2016-06-28 14 29 33" src="https://cloud.githubusercontent.com/assets/1119621/16429541/f1b9abe2-3d3c-11e6-8a9e-442736b834bf.png">
<img width="846" alt="screenshot 2016-06-28 14 29 46" src="https://cloud.githubusercontent.com/assets/1119621/16429543/f1c3c21c-3d3c-11e6-8537-c4c19170f8c3.png">

**Comment by oliverroick** [comment]
Added download functionality. The layout needs some love, though:

![screen shot 2016-07-01 at 11 18 48](https://cloud.githubusercontent.com/assets/159510/16517681/1df72d4e-3f7f-11e6-9883-c333e80a654a.png)
