### ISSUE TITLE
Edit resource 

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#282]
When I try to edit a resource's name or description and save, it doesn't work.  It will only update the resource if I remove and re-upload a new image.

**Comment by oliverroick** [comment]
Not able to reproduce this. Tried editing several resources. It always worked without uploading a new file. Can you please provide more context?

**Comment by seav** [comment]
I cannot reproduce this as well.

**Comment by clash99** [comment]
This is what it was doing before but it seems to be fixed now:  http://www.screencast.com/users/clash/folders/Jing/media/ae57b2f7-85d8-494b-8f24-ce0387e99025
