### ISSUE TITLE
Private/Public Slider & Text Mushed Together on Project Details Page on Mobile

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#297]
This was w/Chrome on my Galaxy S6

![screenshot_20160630-114830](https://cloud.githubusercontent.com/assets/67992/16500281/cb9f5cea-3eb8-11e6-9166-2a4ee32eceee.png)

**Comment by clash99** [comment]
Screenshots for project visibility toggle:

![screenshot 2016-07-01 10 52 11](https://cloud.githubusercontent.com/assets/1119621/16527072/3de6206a-3f7a-11e6-9d20-740e4142151d.png)
![screenshot 2016-07-01 10 53 42](https://cloud.githubusercontent.com/assets/1119621/16527073/3df4a914-3f7a-11e6-8949-c9974969e59e.png)
