### ISSUE TITLE
Management of roles and policies for organisations and projects

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#30]
- Projects and organisations have sets of active roles and policies.
- When a new organisation is created, a set of roles and policies for the organisation are copied from a platform-wide set of templates.
- When a new project is created, a set of roles and policies for the project are copied from the organisation-wide roles and policies.
- Roles and policies can be edited at the platform, organisation and project level.

**Comment by wonderchook** [comment]
Milestone version moved for future work on Roles and policies edits at the platform level.

**Comment by wonderchook** [comment]
@dpalomino currently we have defined roles. The plan was to allow organizations to define security roles within their orgs and projects. This is more complicated than just having the default roles, so it is something we need to think about as far as requirements and priority.

**Comment by dpalomino** [comment]
Included! Again as a generic user story, likely to be split in several when we commit to this.

**Comment by wonderchook** [comment]
@dpalomino thoughts on closing this? I don't think we are moving this way anytime soon

**Comment by wonderchook** [comment]
closing and can be reopened later
