### ISSUE TITLE
Cannot Add Resources to Location

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#303]
After adding a location when I choose "Resources" and then either "Add from library" or "Upload new resource" I get the error:

You don't have permission to add resources to this spatial unit. This is on a project my user created:
![cantresource](https://cloud.githubusercontent.com/assets/67992/16513504/2a5231b6-3f1a-11e6-8a31-7c81cf13499f.jpg)

If I try it as a user, I get as far as uploading the file and then get this error:
![admin-error](https://cloud.githubusercontent.com/assets/67992/16513414/70ddd6ae-3f19-11e6-87ab-5e177a56efa1.jpg)

**Comment by oliverroick** [comment]
I have fixed the CSRF token issue. PR to follow.

The permissions issue is very likely and issue with the default policies.
