### ISSUE TITLE
CSS "cursor" should be "pointer" for table rows that act as links

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#306]
We have many tables wherein if we click on a row, it will bring us to a page to view or edit the data represented by the row. The CSS "cursor" property should be "pointer" (pointing hand) when hovering over these rows to indicate that they are actually links.

**Comment by clash99** [comment]
Inventory since some are already doing this:

- Projects Index
- Organization Index

Need updating:

- [ ] Projects list on Organization Dashboard
- [ ] Member list under Organization
- [ ] Resource index under Projects

Others?
