### ISSUE TITLE
Need error message on add new location

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#309]
We need to add an error message when a user tries to advance from the "add new location" page and can't because they haven't marked the location on the map.

http://screencast.com/t/EyeS3Mcatbo

**Comment by clash99** [comment]
Good question - I'm thinking it should go in the panel on the right by the button since that is the highest visibility for the user.  I think the user directions/ messaging can be improved there too to better support the map drawing.  I will do a little research on best practice for that context.

The other options such as a popover message or modal is another way we could go in the future if we find that users are very confused but I don't think that is preferable.  Other ideas?

**Comment by oliverroick** [comment]
Right, I'll add it above the button then. The error needs styling though.
