### ISSUE TITLE
UI for User Management

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#31]
There is a page in the UI for administrators to control the assignment of roles to users.

Wireframes and user flow:  https://drive.google.com/open?id=0BzpiEtMtHC3rVy1HeEh4eVhmbEU

Wiki design documentation:  https://github.com/Cadasta/cadasta-platform/wiki/4.0-Users

**Comment by clash99** [comment]
Wireframe phase in progress.

**Comment by ian-ross** [comment]
@clash99 Did you really mean to change the title of this issue?  It was "User interface for assignment of roles to user" and it's now "UI for Organizations", which is something completely different.  Did you mean to make a new issue for the organisations UI?  If the old issue is now defunct, it's better to close it and make a new issue, rather than repurposing an existing one by changing the title.  Here, for example, the title no longer matches up with the issue description, which is confusing.

**Comment by ian-ross** [comment]
I've been looking through these in preparation for writing the API and front-end for this next week with @seav.  One thing that I'm not sure I understand is the need for the extra "user details" view.  The only information in the user details view that doesn't appear in the user index is the activated/deactivated state of the user.  It seems like it might make more sense to display that information in the user index table (greyed out names for deactivated users?), along with the activate/deactivate button as an "Active?" checkbox as a column in the table (with a confirmation modal for state changes in the active status).

Inactive users and activate/deactivate buttons would obviously only be displayed for users with the appropriate (`user.see-inactive`?  `user.modify-status`?) permissions.

Is the intention that there should eventually be more information that would be displayed in the user details modal?  If not, could we do without it and fold the activity stuff into the index table?

**Comment by clash99** [comment]
I agree, sounds good - I've updated the wireframes to reflect these changes.

I believe initially there were more items on the detail page.  There was also a request to make actions such as delete/deactivate more hidden in general and move it off of the index.  I think we could make the argument that this page should only be touched by system admins (advanced internal users) so inadvertently performing such actions would be minimized (?).  I added a toggle button to the index for each user and eliminated the additional details view.  We can shelf previous versions to revisit in the future if needed.

**Comment by seav** [comment]
It seems that users can have profile images based on the wireframes. I don't see this in the user model back-end. Something to think for the future?

**Comment by seav** [comment]
Based on the user back-end model, a user can only have one email address (I think a result of using the Django abstract user model). But a user can be a member of many organizations like as shown in the wireframe. This implies that users should be able to link their per-organization email address (if any) to their Cadasta user account, like how I linked both my personal and Cadasta email addresses to GitHub and Trello. Again, something to think for the future?

**Comment by wonderchook** [comment]
good point @seav I think this should be a future feature. At least at first most users will be likely to just have the one organization or at least only be using one email account. 

@ian-ross: as far as supporting this from a data model stand point are we in good shape?

**Comment by seav** [comment]
A question for the confirmation modal: Is this a plain JS confirmation dialog, or is this a custom overlay? For reference, GitHub uses plain JS.

**Comment by ian-ross** [comment]
Profile images: these will be treated as resources and stored in S3. For the first pass at the user stuff we'll just use a placeholder image, then we'll update that when we do resources.

Email addresses: users are identified by a primary email address, which is used for all account activation, password reset, etc. actions. There's no reason a user can't have extra email addresses though, and we would probably treat that as an attribute, which relies on another cross-cutting data model feature I need to implement. Not something for the first release anyway.

Dialogues: I'd vote for simple, unless there's a pre-existing component we can use.

**Comment by ian-ross** [comment]
One more comment about these: wouldn't "Last login" be more useful here than "Last updated"?  (Also, we already capture the last login date as part of the user model, but not a last updated date...)

**Comment by clash99** [comment]
For modals - should we leverage bootstrap?

If we can, let's do last login versus last updated.

**Comment by ian-ross** [comment]
Yeah, let's use Bootstrap for modals.  We'll have to look to see if there's a nice React wrapper for them.

**Comment by ian-ross** [comment]
Closed as mostly complete.  Profile images for users added as seperate issue (#110).
