### ISSUE TITLE
Increase Allowed maxZoom for Basemaps

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#311]
Per request from @nastynoel:

Increase the maxZoom for basemaps. I looked briefly and couldn't determine how this is being set.

**Comment by seav** [comment]
The maps currently have a maximum zoom of 18.

The OSM tileset that we are using can have a maximum zoom level of 19. If I checked Mapbox's docs correctly, the DigitalGlobe layer can have a maximum zoom level of 22, though the quality is not great anymore. Are these zoom levels enough? Do we want to ovezoom the OSM layer even if the tiles become pixellated?

**Comment by wonderchook** [comment]
@seav let's do the maxZoom of 19 for OSM and level 22 for DigitalGlobe.

**Comment by seav** [comment]
Here's the relevant documentation for Mapbox's satellite layer:
https://www.mapbox.com/help/satellite-coverage/

It says that the satellite layer only goes up to zoom 19, but I checked and Mapbox still serves tiles up to zoom level 22, though they are heavily pixellated already. I assume that if better imagery is available, such as from drones/aerial sources, then these will be provided. So I'll stick with zoom level 22.
