### ISSUE TITLE
Refine zoom of world view for creation of project geometry

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#313]
Need only one view of the world map, as opposed to multiple

![image](https://cloud.githubusercontent.com/assets/14871114/16571101/468351a0-4297-11e6-8c91-e7d41979ee8a.png)

**Comment by seav** [comment]
This is actually the standard behavior of the mapping library that we use. This can also be seen when you view the OpenStreetMap website as shown below. What we can do is to provide a more zoomed-in view, similar to the Dashboard map.
![screen shot 2016-07-05 at 08 26 41](https://cloud.githubusercontent.com/assets/873653/16571248/e9786f9c-428a-11e6-867a-df8d02bf9b06.png)

**Comment by seav** [comment]
OK. The latest master already contains the necessary code to avoid showing multiple world maps. It will try to show as much of the middle of a single world map. Of course depending on the browser window size, some wraparound will still be shown around the 180th meridian.

**Comment by seav** [comment]
@nastynoel: Can you check http://demo.cadasta.org/projects/new/ and see if this zoomed in view is enough? If yes, we can close this issue.

**Comment by wonderchook** [comment]
@nastynoel verify this is fixed and then you can close it.
