### ISSUE TITLE
Add Organization dialog box not fully visible and no scroll bar option

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#314]
When adding organisation details in the project work space the only way I could get to the bottom of the dialog box was to tab through all boxes.

![image](https://cloud.githubusercontent.com/assets/14871114/16571124/0137aa1e-4298-11e6-88fd-ec8df44ecea9.png)

**Comment by seav** [comment]
This was already fixed as of the latest version of master branch (see screenshot below). Let's close this issue when the staging platform is updated and the scrolling behavior is confirmed.
![cadasta_add_new_organization_-_2016-07-05_08 46 05](https://cloud.githubusercontent.com/assets/873653/16571373/46e2ddd2-428d-11e6-98df-df4688536307.png)

**Comment by seav** [comment]
@nastynoel: can you confirm if this issue is fixed on the [demo platform](http://platform-demo.cadasta.org/) so that we can close this issue?

**Comment by ian-ross** [comment]
This is fixed on staging.
