### ISSUE TITLE
Website throws an errors when you delete the single contacts row and then submit

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#315]
For the contacts sub-form in both the add organization and add project forms, the single contacts row has a delete contact icon to the right (circled below). Clicking on it, and then submitting the form results in an AttributeError being raised. This still happens even if you delete the row, and then click on "Add contact" afterwards to add back the single row. I think we should remove the delete contact icon when only 1 row is shown. **Update:** This error only occurs if the name field is left blank.

![screen shot 2016-07-05 at 08 52 40](https://cloud.githubusercontent.com/assets/873653/16571424/9b3b8aa4-428e-11e6-9ce1-7279350e18f4.png)
![screen shot 2016-07-05 at 08 53 34](https://cloud.githubusercontent.com/assets/873653/16571425/9ef0ba34-428e-11e6-9771-5c8d1ad40e54.png)

**Comment by oliverroick** [comment]
Which browser are you on? I can't reproduce it on Mac/Chrome.

**Comment by seav** [comment]
Linux/Firefox

**Comment by oliverroick** [comment]
Are there any JavaScript errors logged?

**Comment by seav** [comment]
Just a couple of warnings, both "Empty string passed to getElementById()." when I click on the delete icon. Unfortunately, these are logged against JQuery and datatables so I'm not sure what is the empty string supposed to contain.

Anyway, I actually get this warning on a lot of the interactive elements, such as whenever I click on the private-public widget on the project add details form.

**Comment by seav** [comment]
Here's more information on the error:

> In template /vagrant/cadasta/templates/organization/organization_add.html, error at line 23
> **'NoneType' object has no attribute 'get'**
```
22	          <div class="modal-body">
23	            {% include "organization/organization_form.html" %}
24	          </div>
```

**Comment by seav** [comment]
Tried it now with Linux/Chromium and I get the same error. But this time there are no JS warnings or errors on the console.

**Comment by seav** [comment]
OK, I tried this on the Staging website and I don't get an error, but I get no form, which is indicative of the same error (organization/organization_form.html is not being rendered).
![screen shot 2016-07-06 at 16 59 25](https://cloud.githubusercontent.com/assets/873653/16612726/059e0b80-439b-11e6-849a-4a741acdbf3b.png)

**Comment by oliverroick** [comment]
I tried this on Chrome, Firefox, Safari on Mac, it works for both the Organization and the Project forms. @Cadasta/cadasta-dev Can someone please give this a try on different platforms/browsers?

**Comment by wonderchook** [comment]
No issues on Firefox and Chrome on Windows. 

@seav could you make a screencast of what you are doing to make sure we are doing the same thing?

**Comment by seav** [comment]
Screenshot:
![gifrecord_2016-07-09_082344](https://cloud.githubusercontent.com/assets/873653/16704796/b63fa010-45ae-11e6-95ce-c25f0418f1fa.gif)

**Comment by seav** [comment]
Tried this on the following and was able to reproduce it:

- Linux/Firefox
- Linux/Chromium
- Windows 7/Chrome
- Android/Firefox

**Comment by wonderchook** [comment]
In your screenshot you aren't adding an organization name. If I leave that blank then yes it creates and error, but I think it is a different one than deleting the contact info.

**Comment by seav** [comment]
I would expect that in my screenshot, I would just get the "This field is required" error message instead of a website error. It seems that the combination of the missing name and the deleted contact row results into the website error. There's probably a missing guard condition in the platform somewhere.

**Comment by seav** [comment]
So there are 2 conditions required to show the bug:
1. Leave the name field blank
2. Delete the contact row

So here's a matrix of what happens depending on the conditions when the form is submitted.
<table>
<tr><th></th><th>Name is not blank</th><th>Name is blank</th></tr>
<tr><th>Contact row is not deleted</th><td>Submission is OK</td><td>Required name error message is returned</td></tr>
<tr><th rowspan="2">Contact row is deleted</th><td rowspan="2">Submission is OK</td><td><b>Expected:</b> Required name error message is returned</td></tr>
<tr><td><b>Actual:</b> Website throws an error</td></tr>
</table>
