### ISSUE TITLE
Add client-side form validation where possible

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#322]
Need to understand limits here and what implementations would work best.

**Comment by wonderchook** [comment]
@clash99 is this a good topic for a brainstorming meeting?

**Comment by clash99** [comment]
yes - maybe a breakout session in Frankfort?  even 30 minutes would be great to consolidate ideas...

**Comment by wonderchook** [comment]
Moving this off until the next release, but we'll discuss at the F2F the details

**Comment by clash99** [comment]
WIP notes:

Phase one validation (current Sprint 9)

- Required
- Email 
- Password minimum length 12
- Password confirm matches



Custom validation (future?)

- Username already exists

**Comment by clash99** [comment]
Password requirements and validation will be handled in task #735

**Comment by clash99** [comment]
Should move to Sprint 10 with other form tasks
