### ISSUE TITLE
Prevent duplicate organization names and duplicate project names within the same organization

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#324]
Should we force unique project names (at least within the same organization)?  Right now you can have multiple projects with the same name.  

![screenshot 2016-07-06 08 54 26](https://cloud.githubusercontent.com/assets/1119621/16620272/6f8208a6-4357-11e6-9c09-994a0d1b899d.png)

**Comment by wonderchook** [comment]
Let's enforce a constraint by org. Otherwise I don't think people will be able to know which project is which.

**Comment by ian-ross** [comment]
OK, we can do that easily within the data model.

**Comment by seav** [comment]
`unique_together`?

**Comment by wonderchook** [comment]
@ian-ross: should we push this off until "later"?

**Comment by ian-ross** [comment]
Yes.  Adding the constraint to the database is easy, but we also need to add messaging in the front end, so let's leave it for now.

**Comment by ian-ross** [comment]
Same thing goes for organization names: they should be globally unique.
