### ISSUE TITLE
Non-ASCII organization and project names will crash the website

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#327]
Because of how we slugify organization and project names, if the user provided an organization or project name that contains no ASCII characters (or basically any name that will not match this regex: `r'[\w\-]'`) a zero-length slug will result, and this completely crashes the website. (This is why the current staging website returns HTTP 500 for almost all pages. Oops.)

If you want you can try it with this name: "東京プロジェクト" ("Tokyo Project"). Fair warning though, you would need to drop and recreate the database if you try this at home.

Based on the [Django documentation](https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.text.slugify), the simplest fix is to add the `allow_unicode=True` option to all `slugify()` calls. This will result into non-ASCII URLs but the alternative would be to test for a generated empty slug and then manufacture a generic slug like "organization" or "project" for that.

BTW, if we don't use `allow_unicode=True`, a name like "東京プロジェクト2" will result into a functioning, though weird slug of just "2".

**Comment by oliverroick** [comment]
We had a similar issue at UCL, when people started adding names in Hebrew.

We addressed it like this:

```python
proposed_key = slugify(strip_tags(data.get('name')))
if len(proposed_key) < 1:
    proposed_key = 'key'
suggested_key = proposed_key

count = 1
while category.fields.filter(key=suggested_key).exists():
    suggested_key = '%s-%s' % (proposed_key, count)
    count = count + 1
```

It uses a standard key (slug in our case) and handles duplicates in the same way we already do.

**Comment by seav** [comment]
I see. So this is similar to the idea I mentioned about manufacturing a generic slug like "organization" or "project" if the initial generated slug is empty.

**Comment by seav** [comment]
So the question is, which approach do we take? Manufactured slugs or Unicode slugs?

**Comment by oliverroick** [comment]
`allow_unicode` is the simplest solution, I would try that first
