### ISSUE TITLE
If the organization or project name changes, should the slug change as well?

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#329]
I am looking at the `SlugModel` code and I am not sure if it is expected that if the organization or project name changes, the slug change as well. Please refer to the [current `SlugModel` code](https://github.com/Cadasta/cadasta-platform/blob/74b68256d0da287ad7b6561b0fbcdd27eab4be2f/cadasta/core/models.py#L30-L49).

In the code, there is a condition `self.__original_slug != self.slug`. But based on the code, this condition never becomes true except at organization or project creation. `self.__original_slug` is assigned with `self.slug` during `__init__()`. And in the `save()` method, the only time `self.slug` is assigned to (and thereby possibly become different from `self.__original_slug`) is if `not self.slug` is True, which is only the case when the organization or project is being created. But this is already handled by the `not self.id` condition, I think.

So, is the `self.__original_slug != self.slug` intended to allow name changes to propagate into the slug, or is this only intended to work at creation, which makes it redundant with `not self.id`?

**Comment by oliverroick** [comment]
The slug shouldn't change, because _[Cool URIs don't change](https://www.w3.org/Provider/Style/URI)_.

If we allow changing the slug then we must take care of redirecting from the old to the new URL.

**Comment by seav** [comment]
Thanks for the clarification. Well, we do allow users to change their username, and there is one place on the website where the username is in the URL (where org admins can change the project roles of org members) so we have some _uncool_ URLs.

Anyway, so is my assessment of the `SlugModel` logic correct in that there's redundant logic there?

**Comment by oliverroick** [comment]
The logic is not redundant; we just don't use all of it at the moment. The code already takes the possibility of changing slugs into account. 

`self.__original_slug` is set on model initialization, i.e. when the model is retrieved from the database, `self.__original_slug`is set to what is in the `slug` field in the database. When you then update the `slug`, the instance's field will be set to the new slug, hence the additional `self.__original_slug != self.slug` condition.

**Comment by seav** [comment]
So there is some possibility in the future that we can indeed change the slug (and hence the URLs), maybe as a superuser action?

**Comment by oliverroick** [comment]
I don't know if will allow changing slugs — it doesn't hurt to have it in place though

**Comment by wonderchook** [comment]
I could see allowing changing of slugs at some point, but not now.

**Comment by seav** [comment]
OK. This is makes sense. Closing this question issue.
