### ISSUE TITLE
Map should zoom to project extend when adding first location

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#338]
Currently if a location has already been added to a map it zooms to the locations available. If there are no locations yet added the map is zoomed to a world view. If no locations are added then the map should instead zoom to the project extent. Only if no project extent exists should it zoom to world view.

**Comment by seav** [comment]
Possible duplicate of #276?

**Comment by wonderchook** [comment]
Oops thanks you are right. It is a duplicate of #276
