### ISSUE TITLE
Home Page Search Box

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#339]
(still needs detailed requirements)

There should be a search box for the dashboard.

**Comment by clash99** [comment]
This is the preferred dashboard map from earlier testing:  

![screenshot 2016-08-08 09 47 51](https://cloud.githubusercontent.com/assets/1119621/17483834/3811fcfe-5d4d-11e6-8683-f5ecc34c9f6e.png)

The question of handling global projects should be addressed here too.

**Comment by wonderchook** [comment]
@dpalomino we should take on doing something about the front page at some point. Right now it isn't very compelling. See above screenshots for that was originally envisioned.

**Comment by dpalomino** [comment]
Thanks @wonderchook. Yes, I think this is part of the User Dashboard feature (backlog id 44.00), including links to projects/orgs the user is member of, statistics, saved queries, etc.

**Comment by clash99** [comment]
Renaming this to home page since I think the dashboard will be more personalized, focused on returning users.

**Comment by SteadyCadence** [comment]
On mobile, would the search bar sit above the map?  Or would the search bar and map be in different divs?  Looks great btw.

**Comment by clash99** [comment]
This is an old mock so I'm not sure how valid it still is but perhaps we can use some of the ideas here.  I don't think I will have time to work on it much until next sprint.

**Comment by dpalomino** [comment]
I think this is now followed by the new user dashboard issue #1491. 

Closing for now
