### ISSUE TITLE
Revise Export Text

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#342]
@oliverroick we decided to wait on shapefiles, right? If so we just need to remove the part that says "SHP and" from the text. 

![export](https://cloud.githubusercontent.com/assets/67992/16674976/f34ee8be-4471-11e6-8b41-a9b4eb67b8e2.jpg)

**Comment by oliverroick** [comment]
Yeah, just need to remove the "SHP" from the template
