### ISSUE TITLE
Locations should not be created outside project geometry

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#343]
Somewhat tied to Oliver's issue regarding zoom extent being set to project geometry #276. Once the geometry for my project area is set I should not be able to create parcels outside that geometry. 

It's recommended that a certain tolerance level be set in this regard though to account for the likelihood/possibility of lower accuracy tools being used, e.g. a GPS observation on a mobile phone records a point a few metres outside the set geometry.

**Comment by seav** [comment]
If there's no tolerance level, this would be a bit easy. Adding tolerance would imply buffering the project geometry, which should be doable with PostGIS (using `ST_Buffer`). To make the location check more efficient, we should store this buffered geometry in the database too together with the original geometry and compute the buffer when the geometry is added or updated.

One question is, what should happen if the project geometry is updated and locations suddenly fall outside this new geometry?

**Comment by wonderchook** [comment]
@nastynoel I'm not sure we want to require it be in the project extent at this time. The main reason for having a project extent was to give the map somewhere to zoom when there were no locations yet. I think we should wait and get some user feedback on this. 

A related issue is how would we then handle submissions through ODK if they are outside the project extent?

**Comment by nastynoel** [comment]
#276 may need to be re-opened.......just created my first project geometry and the Map view associated with adding a new location did not zoom to project geometry as had previously been the case when #276 was closed. 

Zooming in also didn't show the project geometry that had been created. 

![image](https://cloud.githubusercontent.com/assets/14871114/16750163/12880ba8-4813-11e6-9e68-caef34051953.png)

Clicking on the Map button then yielded this view

![image](https://cloud.githubusercontent.com/assets/14871114/16750187/4aabd71c-4813-11e6-98d5-678773e8a3a9.png)

**Comment by nastynoel** [comment]
in response to @seav, I think having the geometry with a buffer could also act as a QA/QC mechanism for users to be informed when the location they're trying to create falls outside the project area. 

@wonderchook - the only way I could see issues with data from ODK being resolved is through some messaging to the admin, or flagging the affected location for editing, but not sure how that would work in practice.

**Comment by wonderchook** [comment]
So @nastynoel I've been thinking about this a bit more. Couldn't people potentially have a global project? How should we handle those situations?

**Comment by nastynoel** [comment]
@wonderchook – would it be possible to have users define their project
geometry through either manual definition via polygon creation, or
selection of standard regions/countries from a check box/drop down list
that already has geometry defined in the back end? e.g. country borders,
global, MENA, LATAM, Pacific.

Users would be directed to either draw their area of interest or make the
selection.



*From:* Kate Chapman [mailto:notifications@github.com]
*Sent:* Wednesday, 13 July 2016 1:55 AM
*To:* Cadasta/cadasta-platform <cadasta-platform@noreply.github.com>
*Cc:* nastynoel <ntaylor@cadasta.org>; Mention <mention@noreply.github.com>
*Subject:* Re: [Cadasta/cadasta-platform] Locations should not be created
outside project geometry (#343)



So @nastynoel <https://github.com/nastynoel> I've been thinking about this
a bit more. Couldn't people potentially have a global project? How should
we handle those situations?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/343#issuecomment-232092938>,
or mute the thread
<https://github.com/notifications/unsubscribe/AOLqStbxZOTf5UQyjLY6nAlYj6wHYDC3ks5qU7jIgaJpZM4JHq0S>
.

**Comment by wonderchook** [comment]
@nastynoel it is possible to do any combination of those things. I think it makes sense to wait and get some feedback. Plus if we want some sort of flagging if locations are outside of the project area that is a completely additional workflow.

**Comment by dpalomino** [comment]
I think this issue is not longer needed. Please reopen if needed.
