### ISSUE TITLE
CSS outstanding pages

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#344]
Recently developed pages needing some css love:

- [x] Data download
- [x] Resource area
- [x] Location detail - overview
- [x] Location detail - relationships (add new party)
- [x] Location detail - resources

**Comment by wonderchook** [comment]
@clash99 I'm going to leave this on the current milestone, but if you think time is too short for it we can just push it off to the next one.

**Comment by clash99** [comment]
Screenshots for location details - add party modal: 
![screenshot 2016-07-15 07 22 05](https://cloud.githubusercontent.com/assets/1119621/16874085/e762dc4a-4a5c-11e6-85b1-36daa834f2de.png)
![screenshot 2016-07-15 07 22 11](https://cloud.githubusercontent.com/assets/1119621/16874084/e75f6010-4a5c-11e6-8d7d-3e8bbea868ce.png)

**Comment by clash99** [comment]
Location detail - resources:

Task #295, #407, #409, #427 - all future improvements for this area.

![screenshot 2016-07-15 08 19 33](https://cloud.githubusercontent.com/assets/1119621/16875803/f1669b0a-4a66-11e6-9f3b-5379c6a2ccca.png)
![screenshot 2016-07-15 08 19 55](https://cloud.githubusercontent.com/assets/1119621/16875802/f165b79e-4a66-11e6-8c52-33cab5c5eb53.png)

**Comment by clash99** [comment]
Download project data page:

![screenshot 2016-07-21 16 46 26](https://cloud.githubusercontent.com/assets/1119621/17039982/ddaf452a-4f62-11e6-88ce-0121d191b85c.png)

Question for @oliverroick:  Was this going to be a modal?  I think that would be ideal but if not, we should remove the "cancel" button.  Currently it is a dead link.  Just wanted to check....

**Comment by oliverroick** [comment]
In the wireframes, it was a modal. I decided to make this a page because users can open the download from anywhere in the project. To make this work as a modal, we would have to implement the functionality as an asynchronous operation, which would have taken much longer. 

I agree, we should remove the cancel button in this case.

**Comment by clash99** [comment]
Okay - understand.  I will remove cancel button.  Thanks, Chandra

**Comment by seav** [comment]
Sorry. I meant the "Cancel" button is missing on the last 2 wizard pages. I think the "Cancel" button should still be there so the user can cancel adding a new project.

**Comment by clash99** [comment]
Resources:

![screenshot 2016-07-25 10 54 20](https://cloud.githubusercontent.com/assets/1119621/17107984/2f75575e-5257-11e6-8aa7-6a4ce6c7c407.png)
![screenshot 2016-07-25 11 00 40](https://cloud.githubusercontent.com/assets/1119621/17107985/2f8916c2-5257-11e6-8c63-186872c6c744.png)

**Comment by clash99** [comment]
Party pages

![screenshot 2016-07-26 14 14 10](https://cloud.githubusercontent.com/assets/1119621/17151942/4994ffec-533b-11e6-818d-ed2f16c7c26e.png)
![screenshot 2016-07-26 14 24 23](https://cloud.githubusercontent.com/assets/1119621/17152270/af4a4580-533c-11e6-9b51-0c5883f7a47b.png)
![screenshot 2016-07-26 14 25 46](https://cloud.githubusercontent.com/assets/1119621/17152317/e0b23e5c-533c-11e6-9e9d-591ceb5537f3.png)

**Comment by clash99** [comment]
I believe I've covered css updates for all the outstanding pages as they currently are.  I'm going to mark this as complete with the css-fixes branch and will conquer new pages as they are developed or as bug fixes if we find something that needs adjusting.
