### ISSUE TITLE
Location error messaging

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#345]
Based off original #59 task for consistent messaging, we need to make sure verbiage and error messaging (if required) is being displayed correctly when adding a new project geometry and adding a new location within a project.

Pages:
- [x] New location geometry
- [x] Edit location geometry

**Comment by seav** [comment]
For the project geometry, #358 needs to be answered first.

**Comment by seav** [comment]
Assuming project geometry is not required (see #358), is there anything left to do for this issue now that #397 is already fixed by #473?

**Comment by clash99** [comment]
New location without map marked: 
![screenshot 2016-08-08 16 34 27](https://cloud.githubusercontent.com/assets/1119621/17497204/5564598a-5d86-11e6-9303-099ecda02b18.png)

If no new location is marked on the map when editing, the map location defaults to the original.
