### ISSUE TITLE
Email Templates Not Complete

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#346]
Current email templates say:

Hello from example.com!

You're receiving this e-mail because user kate at example.com has given yours as an e-mail address to connect their account.

To confirm this is correct, go to http://platform-staging.cadasta.org/account/confirm-email/9vr4k7hwfsshlmeqms2jpvxxjur9gfkggesseskmaysupjpem81cux6gryore4lj/

Thank you from example.com!
example.com

They need to be changed so they say the appropriate domain name.

**Comment by oliverroick** [comment]
Taking this over as I'm fixing template issues at the moment

**Comment by oliverroick** [comment]
@wonderchook 

Updated the email to the following:

> You're receiving this e-mail because user w_white at Cadasta Platform has given yours as an e-mail address to connect their account.
>
> To confirm this is correct, go to http://localhost:8000/account/confirm-email/apyjx7onlvoar5iz1elmaanhbwy7qdjygsfib26jvm12cxxzbiefr3uvr5ojwiwm/
>
> Thank you from Cadasta Platform!

"Cadasta Platform" comes from Django's sites framework. I wrote a data migration to update the default site from "example.com". It sounds a bit awkward in the text. Should we rename this or change the text?

**Comment by wonderchook** [comment]
Change the text so it just says "Thank you from Cadasta!" Seems less awkward
