### ISSUE TITLE
File icons for resource list thumbnail previews

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#355]
For resource file types for use when previews are not available (attached because I'm not sure where they need to be placed to be used):
- [x] pdf
- [x] mp3
- [x] mp4
- [x] doc
- [x] docx
- [x] gif
- [x] jpg
- [x] tiff
- [x] xls
- [x] xlsx

**Comment by clash99** [comment]
![pdf](https://cloud.githubusercontent.com/assets/1119621/16716500/bc33f58c-46c3-11e6-93c9-612c733db433.png)
![mp3](https://cloud.githubusercontent.com/assets/1119621/16716470/a3c77506-46c2-11e6-9dc2-b3213378aefe.png)
![mp4](https://cloud.githubusercontent.com/assets/1119621/16716469/a3c34a80-46c2-11e6-8bfd-cf5ac6b4147e.png)
![doc](https://cloud.githubusercontent.com/assets/1119621/16716467/a3ac36ec-46c2-11e6-8774-a085087ba533.png)
![docx](https://cloud.githubusercontent.com/assets/1119621/16716468/a3b62db4-46c2-11e6-8707-f0570dfd43f5.png)

**Comment by clash99** [comment]
@oliverroick: Here are 128X128 file icons to show when previews are not available.

**Comment by oliverroick** [comment]
@clash Can you also create a PNG icon, please?

**Comment by clash99** [comment]
Oops - sorry!  Here you go...

![png](https://cloud.githubusercontent.com/assets/1119621/16986937/fa97c064-4e4e-11e6-80a9-02e3bc64a014.png)

**Comment by oliverroick** [comment]
Thanks!

**Comment by clash99** [comment]
These are also in google drive folder here:  https://drive.google.com/a/cadasta.org/folderview?id=0BzpiEtMtHC3rbXRya0FiVVU2bm8&usp=sharing

New gpx and xml one has been added.
