### ISSUE TITLE
Add an indicator to indicate which fields are required in all of our HTML forms

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#357]
It's common practice to add an asterisk or something similar to indicate required fields, often with a legend like "* required field". This should help a long way towards users avoiding getting errors.

**Comment by clash99** [comment]
Recommend doing this in tandem with #322 and #561 in Sprint 9.

**Comment by clash99** [comment]
A red asterisk will appear after the label if required using the .control-label:after pseudo-element.

**Comment by clash99** [comment]
Form inventory

Account area

- [ ] Sign in (login.html)
- [ ] Register (signup.html)
- [ ] Reset password (password_reset.html)
- [ ] Change password (password_change.html)
- [ ] Update profile (profile.html)
- [ ] Email accounts (email.html)
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by clash99** [comment]
Should move to Sprint 10 - 

outstanding: 
- functional tests
- additional client-side tests?
- language to match platform
- required question
