### ISSUE TITLE
Remove Link to Org Logo from Org Overview Page

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#361]
There is still a link to the org logo on the Org Overview Page. Let's remove it for now so it doesn't show a dead link. 

![dead-image](https://cloud.githubusercontent.com/assets/67992/16709202/b728dd1a-45be-11e6-88bd-b4a48604aa2f.jpg)

**Comment by clash99** [comment]
Org logo shows if available, doesn't if not.

![screenshot 2016-07-10 11 04 38](https://cloud.githubusercontent.com/assets/1119621/16714603/26d0a36c-468e-11e6-8e91-0ed42a1a1f86.png)

**Comment by clash99** [comment]
This is fixed in branch bugfix/orglogo but is breaking a functional test.  @linzjax or @seav - if you have time, can you take a look?
