### ISSUE TITLE
Add New Members Button Doesn't work from Org Overview Page

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#362]
Add New Members Button doesn't do anything. Should ideally link to the new members modal, if too complicated for now could take user to members org list view. 

![add-new-members](https://cloud.githubusercontent.com/assets/67992/16709214/1376f0f2-45bf-11e6-9d09-e7175440e1f5.jpg)

**Comment by clash99** [comment]
Hid button and updated starter text. 
![screenshot 2016-07-10 11 04 38](https://cloud.githubusercontent.com/assets/1119621/16714609/6c19ceda-468e-11e6-9b67-91f22351d865.png)
