### ISSUE TITLE
Dead images on Project Listview

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#363]
Dead images on the project list view. 
![dead-images-project-listview](https://cloud.githubusercontent.com/assets/67992/16709234/8d75998a-45bf-11e6-827f-ade37ab55761.jpg)

**Comment by clash99** [comment]
Displays organization name if organization logo is not available.
<img width="1270" alt="screenshot 2016-07-10 17 53 50" src="https://cloud.githubusercontent.com/assets/1119621/16716620/5dec4a34-46c7-11e6-98b7-84f8939e4a15.png">

**Comment by clash99** [comment]
This is fixed in branch bugfix/orglogo but is breaking a functional test.  @linzjax or @seav - if you have time, can you take a look?
