### ISSUE TITLE
Consistent Error Messaging on Add Location

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#365]
The error messaging is not consistent here. 

![consistent-error-location](https://cloud.githubusercontent.com/assets/67992/16709268/6595a396-45c0-11e6-87e0-24847b22f451.jpg)

**Comment by clash99** [comment]
Ignore the testing field (filed as a bug in a separate task):

![screenshot 2016-07-12 06 49 00](https://cloud.githubusercontent.com/assets/1119621/16766033/04b3a804-47fd-11e6-9183-e31363120e1a.png)
