### ISSUE TITLE
Cannot add resources to location

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#367]
Different to #303.

When I try to upload a new resource I am able to navigate and select the file wanted, but I when I press 'open' to proceed, the Platform quickly displays the file name but then reverts back to saying No File Chosen. It also then returns the error not able to upload file. 

I have attempted doing this as both an administrator and data collector. I have tried multiple supported file extensions; jpg, doc, and pdf. 

![image](https://cloud.githubusercontent.com/assets/14871114/16711507/e6acc080-46a2-11e6-9c1e-0d9631adde36.png)

**Comment by wonderchook** [comment]
This is a known issue #337. Hoping to have it fixed on Monday.
