### ISSUE TITLE
Redirecting error & mass messages appear

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#369]
Redirecting not working if trying to create a new location in a project and you aren't signed in: http://screencast.com/t/z68KhgrcyOrm

If you work around it to get back the site (hit the back button, etc.), then you receive the multiple error message:  http://screencast.com/t/GSeXe8eqP

**Comment by clash99** [comment]
I should add that even though you can navigate through the site seemingly "normal", the permissions seems totally off.  You can't add projects, etc. as expected (which iross as a superuser should be able to do all the time).  You have to log out and then sign back in to get the proper permissions to continue as expected.  We should ensure when we fix the redirect, that is fixes this too.

**Comment by ian-ross** [comment]
This appears not to be reproducible in a clean VM.  Can you try to reproduce it after dropping the database in your VM and reprovisioning?  This will ensure that you have the correct OS and Python dependencies, as well as the right database setup.  (There's another error that might crop up if it does work, but Oliver may have fixed that already.)

**Comment by clash99** [comment]
Here it is on staging:  http://screencast.com/t/onQeeS1a

**Comment by wonderchook** [comment]
I can reproduce it on staging as well (browser doesn't matter I did it with chrome). 

Steps:

1. Go to public project your user isn't a member of (or the org)
2. Click "add location"
3. Login
4. Redirect Error appears
5. Lots of "You don't have permission to add spatial units to this project" appears
