### ISSUE TITLE
Remove "spatial units" text in error message

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#371]
Change to "You don't have permission to add locations to this project"

![screenshot 2016-07-10 10 16 57](https://cloud.githubusercontent.com/assets/1119621/16714405/8437e60c-4687-11e6-9bfa-ca8b5a1ce347.png)

**Comment by IvanSanchez** [comment]
I would find it nicer if the "add location" button was disabled, grayed out, or otherwise not clickable. I see no reason to have a button that will consistently give an error, and could be used to convey information ("permission to edit this site") instead.

**Comment by clash99** [comment]
Agree @IvanSanchez - thanks for the feedback.  I am updating the error messaging as a temporary fix until task #185 (which should only show actions available for that user's permissions) can be complete.

**Comment by clash99** [comment]
![screenshot 2016-07-15 13 37 04](https://cloud.githubusercontent.com/assets/1119621/16884926/abee8e40-4a91-11e6-8549-8956ba162296.png)
