### ISSUE TITLE
Add details to org and project overview

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#372]
Add org url and org contacts below description in right column of Organization Overview.

**Comment by seav** [comment]
This can also apply to the project overview, which has its own contacts and a URL. I suggest improving both pages for this issue.

**Comment by seav** [comment]
@clash99: Please see the `enhancement/#372` branch. I've added the template codes to access the URL and contacts for both organizations and projects. Just adjust the HTML as necessary and add any necessary classes and CSS definitions.

I would suggest that we have email and phone icons to act as links to the "mailto:" and "tel:" URLs for each contact.

**Comment by clash99** [comment]
Thanks @seav - I will look at this today.

I don't think we will include a public-facing phone number.  At one time we discussed masking the contact email for privacy - @wonderchook is that still a consideration?

**Comment by wonderchook** [comment]
@clash99 I think if people put their contact info in then we won't mask it. Should we maybe provide a warning to them that it will be public if it is put there?

**Comment by clash99** [comment]
Okay, I can do that.  I would think we would only show email and not phone numbers, or both?

**Comment by wonderchook** [comment]
both

**Comment by clash99** [comment]
Project Overview:  <img width="1265" alt="screenshot 2016-08-01 15 58 15" src="https://cloud.githubusercontent.com/assets/1119621/17308682/de439008-5800-11e6-8e28-86fdc300e153.png">

Organization Overview:
<img width="1263" alt="screenshot 2016-08-01 15 58 38" src="https://cloud.githubusercontent.com/assets/1119621/17308683/de4b096e-5800-11e6-957d-4be090f736d3.png">

**Comment by seav** [comment]
Closed via #519
