### ISSUE TITLE
Further work on entity attributes

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#376]
- [ ] Fix any issues with attribute schema creation based on @bjohare's work
- [ ] Basic attribute editing for organizations _(not in v0.1)_
- [ ] Basic attribute display for organizations _(not in v0.1)_
- [ ] Basic attribute editing for projects _(not in v0.1)_
- [ ] Basic attribute display for projects _(not in v0.1)_
- [ ] DRF serialization
- [ ] **Tests**: DRF serialization
- [ ] Documentation
- [ ] Decide on further work for form display, attribute rendering, validation, etc.

**Comment by dpalomino** [comment]
@bjohare, do you think this is still applicable or should we close the issue? Thanks!

**Comment by wonderchook** [comment]
I'm going to close this and we can reopen for specific issues and triage that way
