### ISSUE TITLE
Extra "testing" field in add location

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#381]
Looks like something from development is left over. 

Here is the file I [uploaded](https://drive.google.com/open?id=0B6yvvj_4PdlPUW9BLTdzSXF6d2c) and see below the result. 

![testing-screenshot](https://cloud.githubusercontent.com/assets/67992/16737412/09f26808-4746-11e6-885d-ec81ec51591f.jpg)

**Comment by bjohare** [comment]
This is just a stray Schema and will disappear when the db is re-created. Alternatively do:
```
./manage.py shell
>>> from jsonattrs.models import Schema
>>> for s in Schema.objects.all() # filter by project here if needed
>>>    s.delete()
```

**Comment by bjohare** [comment]
This gets loaded when the test fixture data gets loaded by ```./mangage.py loadfixtures```

**Comment by ian-ross** [comment]
OK.  So this data should no longer get loaded into the staging or demo environments.  Once @amplifi has updated the code on there and recreated the database, this should disappear.
