### ISSUE TITLE
TenureRelationship model should have a 'acquired_how' field

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#386]
Current workaround is to define an attribute group for tenure_relationship in the xform and define it there

**Comment by seav** [comment]
This was discussed before in Slack. The original `TenureRelationship` model had `geom`, `acquired_how`, and `acquired_date` fields. Not all projects need them so they are included as optional attributes instead.

**Comment by bjohare** [comment]
Phew! Thought I'd overlooked it :-)
