### ISSUE TITLE
Tenure type selection not available when adding relationship to a new location

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#392]
Tenure type selection list is blank 

![image](https://cloud.githubusercontent.com/assets/14871114/16750701/f831a27e-4816-11e6-9737-6e3d42297f27.png)

**Comment by wonderchook** [comment]
I suspect this is a deployment issue.

**Comment by bjohare** [comment]
On the VM the list is populated by TenureRelationshipType id's rather than the labels.

**Comment by ian-ross** [comment]
I think this should be fixed by the static data setup changes I made.  We'll need to check it once the new code is deployed to the staging or demo sites.

**Comment by wonderchook** [comment]
This is resolved on staging.
