### ISSUE TITLE
Unable to add member within Organization overview window

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#394]
Step 1 - selecting Add org member 
![image](https://cloud.githubusercontent.com/assets/14871114/16750884/5a069292-4818-11e6-8d6a-24292ee6b8b4.png)

Yields this
![image](https://cloud.githubusercontent.com/assets/14871114/16750895/68c28a84-4818-11e6-9e9d-3a7f564b16cf.png)

**Comment by ian-ross** [comment]
I can't reproduce this, either in the development VM or on the current demo site.

**Comment by nastynoel** [comment]
I was able to re-create it in the demo site on my notebook. This was also
done after I had cleared the cache and re-started my computer.



I was also able to re-create the error on my Oppo mobile. Apologies for the
screen grabs, but these pages don’t look to have been optimised for the
device yet. Other pages were fine.







*From:* Ian Ross [mailto:notifications@github.com]
*Sent:* Tuesday, 12 July 2016 5:00 PM
*To:* Cadasta/cadasta-platform <cadasta-platform@noreply.github.com>
*Cc:* nastynoel <ntaylor@cadasta.org>; Author <author@noreply.github.com>
*Subject:* Re: [Cadasta/cadasta-platform] Unable to add member within
Organization overview window (#394)



I can't reproduce this, either in the development VM or on the current demo
site.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/394#issuecomment-231954109>,
or mute the thread
<https://github.com/notifications/unsubscribe/AOLqSl9EGASk26Vc0K1UMVobWOw7XKa9ks5qUzt7gaJpZM4JJ64X>
.

**Comment by ian-ross** [comment]
You get the 500 immediately when you press the "Add org member" button or after you select a username or email address and press "Save" in the modal?

**Comment by wonderchook** [comment]
I was able to reproduce this yesterday, but I'm not getting it now. With the "wonderchook" account on demo however I'm not able to add users to an org I created. Seems to be weird issues just with that account. Wondering if it was create before a migration or something when we were trouble shooting yesterday and if it is in a weird place.

**Comment by ian-ross** [comment]
Yeah, I was going to revisit this once we've redeployed.

**Comment by ian-ross** [comment]
@wonderchook Can you see if you can reproduce this one?  I'm trying to figure out this Unicode business...

**Comment by wonderchook** [comment]
Seems to be resolved on staging. @nastynoel can you try it out here: http://platform-staging-api.cadasta.org/

**Comment by nastynoel** [comment]
Resolved



*From:* Kate Chapman [mailto:notifications@github.com]
*Sent:* Wednesday, 13 July 2016 4:06 AM
*To:* Cadasta/cadasta-platform <cadasta-platform@noreply.github.com>
*Cc:* nastynoel <ntaylor@cadasta.org>; Mention <mention@noreply.github.com>
*Subject:* Re: [Cadasta/cadasta-platform] Unable to add member within
Organization overview window (#394)



Seems to be resolved on staging. @nastynoel <https://github.com/nastynoel>
can you try it out here: http://platform-staging-api.cadasta.org/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/394#issuecomment-232129845>,
or mute the thread
<https://github.com/notifications/unsubscribe/AOLqSnc4hFYu9f9QobBL69zb5IAnvTH-ks5qU9eQgaJpZM4JJ64X>
.
