### ISSUE TITLE
Update map geometry field error

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#397]
Update current error from this: "No geometry value provided."

to this:  "No map location was provided.  Please use the tools provided on the left side of the map to mark your new location."

![screenshot 2016-07-12 06 50 35](https://cloud.githubusercontent.com/assets/1119621/16766055/37b6b5e8-47fd-11e6-823a-b3b4ee5ae61b.png)

**Comment by clash99** [comment]
@oliverroick I can't find this error message to update.  When you get a chance, can you point me in the right direction?  Thanks, Chandra

**Comment by oliverroick** [comment]
@clash99 This is coming from django-leaflet. It is possible to change this; I just don't know how exactly from the top of my head. I'm assigning this to myself. Will look into that later today or tomorrow.
