### ISSUE TITLE
Upload Point Data from Field Data Instruments

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#40]
As a user I want to be able to upload point data from field data instruments such as total stations and GPS

Requested by @nastynoel and moved over from trello

**Comment by dpalomino** [comment]
Included in backlog, item 37.00.

**Comment by wonderchook** [comment]
@nastynoel are there specific file formats from total stations or other field instruments that make them special? Or would it be pretty normal to be able to export to a common geospatial file format?

**Comment by dpalomino** [comment]
This is a dup for #1414 and #1588, closing.
