### ISSUE TITLE
Provide Sample XLSForm to Users

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#403]
Add a link to the "Project Details" page to a sample XLSForm and [documentation](http://docs.cadasta.org/en/XLSForms.html)

Here is the form to use as the sample.
[Minimum_cadasta_questionnaire_0.2.xlsx](https://github.com/Cadasta/cadasta-platform/files/424715/Minimum_cadasta_questionnaire_0.2.xlsx).

**Comment by wonderchook** [comment]
this needs to happen in conjunction with @fhpichel's platform update

**Comment by wonderchook** [comment]
@fhpichel we need a default sample form to use for this. Could you put something together?

**Comment by wonderchook** [comment]
moving to Sprint 8, waiting on @fhpichel

**Comment by clash99** [comment]
The documentation link in the details is broken.  Are there instructions to accompany the sample form?

**Comment by wonderchook** [comment]
This link is a better one: http://docs.cadasta.org/en/08-XLSForms.html

**Comment by clash99** [comment]
Should we rename "questionnaire" to "data collection form" across the platform?

**Comment by fhpichel** [comment]
My vote would be yes

**Comment by ian-ross** [comment]
@fhpichel One thing we talked about some time ago was having a glossary for names of things in the platform (and also, probably separately, for land terms that everyone in Cadasta should know).  There are a number of competing factors that go into choosing the names for things in the platform: clarity, correctness, lack of ambiguity, translatability and "friendliness" are only some of them.  We have a lot of discussions within the dev team about what to call things, but it seems like it's really something we should hand off to you.  What do you think?  We tell you what it is, you tell us what it is (or should be) called...

**Comment by fhpichel** [comment]
@ian-ross agreed.  I know we'd discussed that general glossary a while back, and certainly a need to be consistent / accurate within the platform.  @clash had started on a glossary for the platform - best thing to do would be buil off of that? https://docs.google.com/document/d/1Xrn-VUhY0xIpdD4URdf_uafgGlgoGntj486Jl9fVOts/edit#heading=h.j9xpg26t020b

**Comment by ian-ross** [comment]
That's a good place to put things.

**Comment by clash99** [comment]
Please review and let me know if this is what we want to say:

<img width="917" alt="screenshot 2016-09-02 08 08 37" src="https://cloud.githubusercontent.com/assets/1119621/18204844/8489ee7a-70e4-11e6-971e-2c445a48f63c.png">

Does it need more or less prominence?  I could add a little icon to draw attention to the spreadsheets if needed.  Let me know.

Sidenote: The user guide document we link to still has some "add image here" type of notes that we should clean up before the release.

**Comment by clash99** [comment]
Hmmm, I didn't start the glossary (maybe @wonderchook) but definitely a good idea!  We should make sure that the user guide is using the same language (http://docs.cadasta.org/en/) or if the public facing and internal terms are different, note that in our internal glossary.  It will be helpful in the long run.

@fhpichel - any feedback on the screenshot above?

**Comment by wonderchook** [comment]
Couple things:

1. Let's not change the labels in the platform right now. 
2. @dpalomino as the product owner should be responsible for this. Yes he could get input from @fhpichel + @nastynoel but this really part of the vision of the platform. It also needs to fit appropriately into the branding/communications we are doing generally.

**Comment by dpalomino** [comment]
btw, I think we could update the [standard questionnaire](https://docs.google.com/spreadsheets/d/1QsqMTLlPH5KVbBcgnh6MHWkIR0pIFchVzkqBSoL92fA/edit#gid=2006567796), for instance to include the new "geotype" capability (to select among geoshape, geotrace, etc). I will try to take a look and create a new version... 

I will try to review it later on..

**Comment by wonderchook** [comment]
@dpalomino that is fine. We need it to be finalized before the end of the sprint since we will make it a regular file and save within the platform.

**Comment by clash99** [comment]
Updated screenshot for feedback:

![screenshot 2016-09-02 11 35 40](https://cloud.githubusercontent.com/assets/1119621/18211117/9e92f8e4-7101-11e6-88c4-b96255e7960a.png)

**Comment by wonderchook** [comment]
"For assistance with questionnaires view our user guide. To help you get started to samples have been provided a minimal questionnaire and a standard questionnaire." 

I'm thinking we should reuse the term questionnaire even though it is a bit repetitive.  Thoughts?

**Comment by fhpichel** [comment]
I think we can get rid of the second use of questionnaire, ie ""For assistance with questionnaires view our user guide. To help you get started to samples have been provided a minimal  and a standard questionnaire."

**Comment by clash99** [comment]
Should these sample files be linked to in google docs like in the user guide or should we copy them into the platform and link there?  For the second option, we will need to maintain the current file.  The first option keeps it all in one place.

Let me know.  Thanks!

**Comment by wonderchook** [comment]
@clash99 I think we should have a regular file people can download. I think how to download the file from Google Docs might not be obvious to all users.

**Comment by dpalomino** [comment]
I agree, I think a regular xlsx file would be easier. I still need to provide the sample file including the capability to select geoshape, geotrace, etc.

**Comment by clash99** [comment]
@dpalomino I am going to use the current one for now but its easy to update.  We should make sure to update the one in google docs and in the platform together.  Let me know when the new one is available.

**Comment by clash99** [comment]
Added xlsx versions of the form to our s3 bucket so we can update the form anytime without having to coordinate with a code release.

Updated text and links on project add and edit pages.

![screenshot 2016-09-07 09 25 00](https://cloud.githubusercontent.com/assets/1119621/18315529/f90b5030-74dc-11e6-98ee-997d53866bec.png)

**Comment by wonderchook** [comment]
This all looks good to me.
