### ISSUE TITLE
Improve map pop-over button

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#406]
Since this location's details are already open on the side, I wonder if it would be better to have messaging such as "viewing" instead of "open location".

![screenshot 2016-07-12 12 03 00](https://cloud.githubusercontent.com/assets/1119621/16775949/ac79b9ae-4828-11e6-857e-5d57b6157296.png)

**Comment by wonderchook** [comment]
Seems reasonable, since you wouldn't want to open what is already open. Noting that if there are other locations on the map they should still say "Open location".
