### ISSUE TITLE
Annotate Resources from Analogue Format

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#41]
As a user I want to be able to annotate resources that were converted from analogue format.

requested by @nastynoel and moved over from trello

**Comment by wonderchook** [comment]
@dpalomino another feature for some point. We need to better define what annotate is as well. I could see using the scanned paper as an item for data entry or maybe the annotations involve some other approach. 

I quite like [Old Weather](https://www.oldweather.org/) which is crowdsourced ship log annotation as a really nice interface for doing data entry off of paper. I could see doing something similar.

**Comment by dpalomino** [comment]
Thanks! Included in the backlog. I've maintained as a generic description for now, when we would be considering to include it I guess we would need to split this into several user stories.

**Comment by oliverroick** [comment]
Out of scope, closing...
