### ISSUE TITLE
Forms Download to ODK should have human names

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#412]
Issue not seen on development since the django-buckets doesn't change the file names in dev mode. The form downloaded to ODK should have a human readable name. When people upload the file to their project let's have them add a name for the file. By default it could be the file name, but editable. 

![screenshot_20160712-114011](https://cloud.githubusercontent.com/assets/67992/16779199/1cc33ad0-4826-11e6-945d-97ee8a4b696c.png)

**Comment by linzjax** [comment]
I think this might be more of a django-buckets issue, which I'm not as familiar with. I can still take a look though

**Comment by wonderchook** [comment]
True, I was wondering if storing a file name would be the way to go. @oliverroick thoughts on how to manage this?

**Comment by linzjax** [comment]
So, looks like this was solved with the removal of the blank line in the xls settings tab. Can you confirm?

**Comment by oliverroick** [comment]
@wonderchook @linzjax Any news on this? Is this something I should look into?

**Comment by bjohare** [comment]
@oliverroick as @linzjax said, this was an xslform formatting issue but I will confirm this is fixed as part of work on xforms review.
