### ISSUE TITLE
Can't Download ODK Form from Staging

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#417]
See below error when trying to download an ODK form from staging. Believe this is deployment related. To reproduce do the following:

1. Get testing APK from [here](http://geomarvel-projects.s3.amazonaws.com/cadasta/collect-cadasta-dev.apk)
2. Create project with XLS Form
3. In general settings under "Configure platform settings" add http://platform-staging-api.cadasta.org/collect and your username and password for Cadasta
4. From main ODK select screen click "Get Blank Form"
5. Click okay when "Server Requires Authentication Screen" comes up
6. Make sure form is select and click "Get Selected"

![screenshot_20160712-122651](https://cloud.githubusercontent.com/assets/67992/16780765/f74c23d2-482c-11e6-8df2-6419fe438aab.png)

**Comment by linzjax** [comment]
The `downloadURL` for `/collect/` isn't being completed. Instead of 
```
http://platform-staging-api.cadasta.org/<whatever-the-url-is-to-access-this-file>/<filename-xml>.xml
```
It's spitting out
```
http://platform-staging-api.cadasta.orgfalse
``
the problem is that this chunk of code isn't working:
```
try:
                survey = create_survey_element_from_dict(json)
                xml_form = survey.xml().toprettyxml()
                content = str.encode(xml_form)
                url = instance.xml_form.storage.save(
                    '{}.xml'.format(instance.name), content)

                instance.xml_form = url
except PyXFormError:
                pass
```
So I added one line here:
```
try:
                survey = create_survey_element_from_dict(json)
                xml_form = survey.xml().toprettyxml()
                content = str.encode(xml_form)
                name = os.path.join(instance.xml_form.field.upload_to,
                                    os.path.basename(instance.name))
                url = instance.xml_form.storage.save(
                    '{}.xml'.format(name), content)

                instance.xml_form = url
except PyXFormError:
                pass
```
which might fix it, but I'm not sure what's causing the error. I also don't know how to go poking around to find it in production...

**Comment by linzjax** [comment]
Also, am I correct in assuming that we want this:
```
https://s3-us-west-2.amazonaws.com/cadasta-platformstaging-bucket/xml-forms/h3r4qyi9pn4e6w4qqx74d3k6.xlm
```
not this:
```
http://platform.cadasta.org/<whatever>/xml-forms/h3r4qyi9pn4e6w4qqx74d3k6.xlm
```

**Comment by wonderchook** [comment]
not sure it matters since the phone is doing the request and a human will never see it. 

**Comment by wonderchook** [comment]
@oliverroick believe this might be in django-buckets can you track it down?

**Comment by amplifi** [comment]
The string concatenation here: https://github.com/Cadasta/cadasta-platform/blob/6a511dc3a8f4f8aeb40acebb4eb8deffbb1f233b/cadasta/xforms/serializers.py#L27 is generating an incorrect URL. Commenting out line 27 and editing line 28 to return just `obj.xml_form.url` generates the correct URL, but there's a cleaner way to produce the file path.
