### ISSUE TITLE
Resource Editing Features

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#42]
As a user working with resources converted from analogue format, I want to be able to perform the following functions. 
- Despeckle
- Deskew
- Adjust brightness
- Adjust contrast
- Rotate (clockwise, 180degrees, counterclockwise)
- Blank selected area
- Fill selected area
- Crop
- Image info dialog box (name, size, resolution, paper size, dimensions in pixels, etc.)
- Area select tools (rectangle, oval, circle, freehand)
- Panning and zooming tools

Edits to a resource should result in the creation of a new resource so that edits can be tracked by version. On completion of editing tasks, users should be asked to commit final edits

Requested by @nastynoel and moved over from Trello

**Comment by wonderchook** [comment]
@dpalomino also for the backlog

**Comment by dpalomino** [comment]
Included! 

I've split in different User Stories, so we would be able to define different priorities. 

One question, what is the reason to include to ability to blank/fill selected areas of an image? 
 - Are we going to include some kind of "transparency level" so we can highlight specific parts of a scanned document for instance?

**Comment by wonderchook** [comment]
There are many, many questions. True requirements were really never developed for this.

**Comment by oliverroick** [comment]
Out of scope, closing...
