### ISSUE TITLE
Improve map interactions 

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#429]
I have some ideas on how to add a bit of finesse to the map interactions to improve usability.  I think perhaps we should discuss in a meeting with those involved?

After the meeting, I can turn this into a more tangible request.

**Comment by wonderchook** [comment]
Makes sense. Do you think we should do this in the mini-release or what and get more feedback from users?

**Comment by seav** [comment]
See also #496.

**Comment by seav** [comment]
Should this still be in Sprint 7 if we will be discussing this during the staff retreat?

**Comment by ian-ross** [comment]
@seav Agreed: moving to Sprint 8.

**Comment by clash99** [comment]
This seems like a duplicate of the more detailed #559.
