### ISSUE TITLE
Geoshape comes across as a polyline

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#430]
Geoshapes are coming over as polylines. ODK doesn't close the polygon for this geometry type.

**Comment by linzjax** [comment]
Is it unreasonable to add a line to the form for expected shape? i.e.:
What geometry type is this:
- Polygon
- LineString
- Point

I wanted to check whether the field was geotrace or geoshape, but for some reason I can't access the specific questions in the Questionnaire.

**Comment by wonderchook** [comment]
it would be preferable if we would automatically figure it out. People could potentially use different geoms with multiple survey instances.
