### ISSUE TITLE
Odd highlighting around resource checkboxes

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#436]
<img width="1280" alt="screen shot 2016-07-13 at 3 09 31 pm" src="https://cloud.githubusercontent.com/assets/8128188/16816466/f0fc0472-490b-11e6-965b-8501caf2a1e8.png">

**Comment by clash99** [comment]
Chrome issue (at least, may be more).

Removed form-control class from checkbox input.

**Comment by clash99** [comment]
@linzjax - Can you confirm this issue has been resolved? Thanks, Chandra

**Comment by linzjax** [comment]
Confirmed
<img width="455" alt="screen shot 2016-07-28 at 8 05 38 am" src="https://cloud.githubusercontent.com/assets/8128188/17211944/2f32c8b8-549a-11e6-8c3c-98bcd0bfca97.png">
