### ISSUE TITLE
Resolver for URLs with usernames do not include all valid characters

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#439]
URLs that contain usernames use the following regex to capture the username: `[-\w]+`. This does not match the actual allowed characters for Django usernames found in [django.contrib.auth.validators](https://github.com/django/django/blob/master/django/contrib/auth/validators.py): `[\w.@+-]+`.

This results in website errors when usernames containing periods, at signs, or plus signs.

**Comment by seav** [comment]
This affects the following URLs:

Website:
/organizations/&lt;org>/members/&lt;username>/
/organizations/&lt;org>/members/&lt;username>/remove/
/users/&lt;username>/activate/
/users/&lt;username>/deactivate/

API:
/organizations/&lt;org>/users/&lt;username>/
/organizations/&lt;org>/projects/&lt;project>/users/&lt;username>/

**Comment by oliverroick** [comment]
Three possible solutions here:

1. Restrict user names to `[-\w]+`
2. Change the URL pattern `[\w.@+-]+`. (Are `.` or `@` allowed in URLs, I don't know).
3. Change the URL pattern to use the user ID.

**Comment by seav** [comment]
Number 2 seems to be the simplest to implement. I think `.` and `@` are allowed in URLs. If not, they will get URL-encoded anyway, just like other Unicode characters.

**Comment by ian-ross** [comment]
Both `.` and `@` are explicitly allowed in URLs without encoding (see the BNF syntax here: https://www.w3.org/Addressing/URL/uri-spec.html#z8), so option 2 is definitely the best.
