### ISSUE TITLE
Organization model

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#44]
Organizations have:

- Name
- Description (optional)
- logo (optional)
- contact emails (0..n)
- telephone number
- Implicit list of organization admins (Managed by assigning roles to users)

Implement alongside:

- [x] Test factories

**Comment by oliverroick** [comment]
@wonderchook I got the following model setup for organisations:

```python
class Organization(RandomIDModel):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50)
    description = models.TextField(null=True, blank=True)
    archived = models.BooleanField(default=False)
    urls = ArrayField(models.URLField())
    contacts = JSONField(validators=[validate_contact]) # Array of hcard like JSON dictionaries
```

I have found different requirements for model fields in the data model sketches Ian did earlier this year and the user stories document. Is there anything I'm missing in the structure above?

**Comment by wonderchook** [comment]
@oliverroick this looks okay but I think there are things from Ian's data model that are needed. 

- Orgs should be able to upload a logo, though I'm thinking it is best to add that later once the resources part is done. 
- What about users associated with an organization? Or does that fit in a different way into the permissions model?

`class Organization(Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    logo = TemporalForeignKey('Resource')
    urls = ArrayField(models.URLField())
    contacts = JSONField()  # List of JSON-ised hCard records.
    users = models.ManyToManyField('User')  # Members of the organization.
    archived = models.BooleanField(default=False)`

**Comment by oliverroick** [comment]
- Agreed on the logo
- Users: I thought this is derived from permissions policies. Is that correct, @ian-ross?

**Comment by ian-ross** [comment]
About the users: I think it still makes sense to have a list of members of an organisation.  The place where listing users *doesn't* make so much sense is having a list of project admins separate from the permissions system, because they will become project admins by virtue of their permissions.  (You can think of other uses for a list of organisation members: sending messages, social media stuff, things like that?)

**Comment by oliverroick** [comment]
Ok, here we go:

```python
class Organization(RandomIDModel):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50)
    description = models.TextField(null=True, blank=True)
    archived = models.BooleanField(default=False)
    urls = ArrayField(models.URLField(), default=[])
    contacts = JSONField(validators=[validate_contact], default={})
    users = models.ManyToManyField('accounts.User')
```

Closing this if there are no objections.

**Comment by wonderchook** [comment]
No objections from me.

**Comment by ian-ross** [comment]
Looks good to me.
