### ISSUE TITLE
Improve party selection widget

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#441]
I think we can improve the party selection widget by using a searchable textbox/dropdown selector.  Perhaps something like selectize.js (http://selectize.github.io/selectize.js/) with a searchable text/select that allows us to show party name and type (individual/group).  The "add party" could be a button to the right of the select.

**Comment by clash99** [comment]
We should also add error for when a party is not selected.  Currently there is none. 
![screenshot 2016-07-14 08 12 06](https://cloud.githubusercontent.com/assets/1119621/16840528/c7282de4-499a-11e6-800e-299bd4283bfb.png)

**Comment by seav** [comment]
@clash99: are you already working on this? If not, I can take this.

**Comment by clash99** [comment]
@seav - that would be great - thank you.  

Right now the select party control is very confusing.  I spent some time a while ago looking at solutions and I thought selectize looked like it had potential.  I liked that it is a searchable text box/ select box combo and you can add details such as date of birth or ID to each option - which would be really helpful for cases where there are several common names.  Then the add button would just be a button to the right and the link below would be removed.  Hopefully that gives you some insight into the direction I was headed but I'm totally open if you have other ideas.

**Comment by clash99** [comment]
Another note, we talked about eventually being able to select multiple parties to create relationships.
