### ISSUE TITLE
Check button consistency across the platform

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#443]
Perhaps use default button vs link?

**Comment by wonderchook** [comment]
@clash99 can you expand on this a little more?

**Comment by clash99** [comment]
I need to do a review of the buttons platform-wide to make sure they are consistent.  I'm going to change out the link buttons below the "add contact" and "add party" to be buttons and not links.  And I think there are some cancel variations.  Just want to make sure they are consistent ...

**Comment by clash99** [comment]
![screenshot 2016-08-08 11 28 17](https://cloud.githubusercontent.com/assets/1119621/17487621/45ad2c7c-5d5b-11e6-8d51-fd80f100cd93.png)

**Comment by clash99** [comment]
Start of buttons for UX style guide https://drive.google.com/file/d/0BzpiEtMtHC3rMlFpenR4WDRIRFk/view?usp=sharing
