### ISSUE TITLE
How to handle duplicate party names?

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#448]
When adding a new party (after the user has entered a new party with the same properties as an already existing party) we should prompt them if they would like to add the existing party or add the newly created party (with probably a new name to differentiate).

Right now you can add multiple parties with the same name.
![screenshot 2016-07-14 11 33 35](https://cloud.githubusercontent.com/assets/1119621/16847537/27882d44-49b7-11e6-86dd-adaa9b097cde.png)

**Comment by seav** [comment]
Should this still be in Sprint 7? I think we discussed during the Sprint planning meeting that this will be consulted with Noel and to also check how other systems handle this issue.

**Comment by ian-ross** [comment]
I think that's right.  I'll move it to Sprint 8 for the moment.

**Comment by wonderchook** [comment]
After consulting with Noel. We should allow names are the same. There should be a warning to the user that there is already a party by this name, did they intend to add a duplicate. In many cases the answer will be yes

**Comment by dpalomino** [comment]
I think that was already covered, closing the issue. Please reopen if needed.
