### ISSUE TITLE
Prototype switchover to Leaflet 1.0.0-rc2

### ISSUE THREAD

**Issue by IvanSanchez** [Cadasta/cadasta-platform#450]
The Leaflet team will be releasing Leaflet 1.0.0 Really Soon™, and 1.0.0-rc2 in the upcoming weeks. 0.7.x can be still used, but it would be a good, low-priority idea to test out if switching to 1.0.0-rc is hard.

**Comment by seav** [comment]
Unfortunately, we are using [django-leaflet](https://github.com/makinacorpus/django-leaflet), which embeds a copy of Leaflet. It would be cleaner for us to wait for them to update instead of us trying to override Leaflet and any built-in integrations of django-leaflet.

**Comment by IvanSanchez** [comment]
Fair enough. I hope upstream (django-leaflet) will be updated when the time comes.

**Comment by seav** [comment]
Well, I have converted some of my personal Leaflet maps from 0.7 to 1.0.0-beta2 and rc1 and it was quite easy. I only encountered a regression from beta2 to rc1 that was already seen and filed already.
