### ISSUE TITLE
Add icons to "add contact" and "remove contact"

### ISSUE THREAD

**Issue by IvanSanchez** [Cadasta/cadasta-platform#451]
In the "add a new project" page, add little icons to the "add contact" and "remove contact". Consider wrapping the "add contact" link inside a button, for UI consistency.

![screenshot2](https://cloud.githubusercontent.com/assets/1125786/16849086/2791da32-49f9-11e6-9a24-bd023604177b.png)

**Comment by wonderchook** [comment]
@IvanSanchez thanks for the suggestion!

**Comment by Shruti9520** [comment]
@IvanSanchez There is no "remove contact" button on "add a new project page". Instead, there is a "cross mark" for removing contacts. Do I need to add a new button for removing contacts and then add icon to it?

**Comment by IvanSanchez** [comment]
If I remember correctly, the "cross mark" does not look like a button. My suggestion is to *replace* the "cross mark" with a button with a "remove person" icon, and make the UI for the "add contact" functionality look the same, for consistency.

**Comment by Shruti9520** [comment]
@IvanSanchez Thanks :)
Also, the version of bootstrap doesn't support "<span class="glyphicons glyphicons-user-add"></span>"
Should I add image to the button?

**Comment by clash99** [comment]
Hi @Shruti9520 and @IvanSanchez - 

Thank you for your suggestions.  We've decided to close this github task.  One of the main reasons is that our parties icon is very similar as the contact icon used by bootstrap.  We are in the process of reviewing our platform terminology and this could result in the renaming and updating of the parties icon but until then, it would be confusing to use the same icon for different entities.

@Shruti9520 - please don't let this discourage you from submitting another bugfix for the purpose of Outreachy!

**Comment by Shruti9520** [comment]
@clash99 It's fine :) . I have learned many new things while working on this. :)
