### ISSUE TITLE
Users tab

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#452]
Sometimes I see it, sometimes I don't.  Logged in as Ian Ross.  (Only internal so low priority)

![screenshot 2016-07-14 15 03 43](https://cloud.githubusercontent.com/assets/1119621/16853944/56309a92-49d4-11e6-9eb7-8ee5b2c9b569.png)
![screenshot 2016-07-14 15 03 56](https://cloud.githubusercontent.com/assets/1119621/16853945/563e2694-49d4-11e6-871b-75fb1fc255dd.png)

**Comment by ian-ross** [comment]
Are there any other views on which you don't see it that the project resources view?

**Comment by clash99** [comment]
Sorry, I was so focused on the scrollbar bug I didn't document this very well...  it only disappears on the Project > Resources page.

**Comment by ian-ross** [comment]
Thanks.  Pretty sure I've fixed it.

**Comment by ian-ross** [comment]
I'll make a PR in a minute.  There's some weird thing going on with Travis right now.
