### ISSUE TITLE
Consider adding either site-wide or fine-grained search index robot settings

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#454]
We can certainly argue that any data in the demo site should not be indexable by search engines, so we should add a way to configure our robots.txt.

Also, we may want to provide `meta` `noindex` or `nofollow` to individual pages as well, although private projects seems to take care of that.

**Comment by amplifi** [comment]
PR #751 adds noindex, nofollow, nosnippet, noarchive, noodp, noimageindex rules, plus blocking for specific bots/crawlers/scanners known to ignore robots config.
