### ISSUE TITLE
Improve dashboard as far as showing project existence geographically

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#460]
While the shaded blue polygon approach works okay for project geometries at smaller scale, that is not the case when it comes to global/regional/larger project areas......as seen in the screen grab below. Placing markers at the centroid for all projects on the dashboard map view, while keeping the shaded (or other drawing like a bounding box) area for the map view of projects may be an improvement.

![image](https://cloud.githubusercontent.com/assets/14871114/16905773/96c9de5c-4cee-11e6-9b46-53dbcfa4557f.png)

**Comment by wonderchook** [comment]
I think we should look at a couple different display options before making a change. I think for example of the bounding box wasn't shaded it wouldn't be an issue. @clash99 what do you think?

**Comment by clash99** [comment]
@wonderchook - I agree.  I think if we could visually remove the bounding box it would be a huge improvement - if we could make the shading and border transparent that would work.

**Comment by dpalomino** [comment]
Related with #524

**Comment by dpalomino** [comment]
I think we can remove this for now, with global projects already implemented and the new approach for project extent with the project designer this is now a lower priority. Please reopen if needed.
