### ISSUE TITLE
Add Calendar Widget for Date Fields

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#461]
I was only able to work out the DOB format through trial and error, as there is no guidance as to the format required. Without a calendar, better guidance of ISO 8601 is required, otherwise I see lots of mistakes and frustrations occurring with this attribute.

![image](https://cloud.githubusercontent.com/assets/14871114/16905841/d1344496-4cef-11e6-86a6-07b654f30ac4.png)

![image](https://cloud.githubusercontent.com/assets/14871114/16905845/dbd2c4ea-4cef-11e6-97f5-a947a1b65a8a.png)
 
![image](https://cloud.githubusercontent.com/assets/14871114/16905847/f15028e4-4cef-11e6-94ae-c844c7e0532b.png)

![image](https://cloud.githubusercontent.com/assets/14871114/16905856/0d9ced34-4cf0-11e6-95ea-da20f91334b2.png)

**Comment by wonderchook** [comment]
DOB is a custom field, I think what you really mean is there should be a calendar widget for all custom date fields.

**Comment by nastynoel** [comment]
agreed

**Comment by fhpichel** [comment]
Assume this would apply to date field for adding location as well, and not need to report the  issue 
![error_date](https://cloud.githubusercontent.com/assets/14877933/16983819/032539b4-4e77-11e6-8347-3fc8eda4ff42.png)

**Comment by wonderchook** [comment]
Correct this is a matter of adding a calendar widget for all date related custom attributes.
