### ISSUE TITLE
Projects, Organizations...and Users from homepage

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#462]
From the demo hope page we are presented with “Projects” & “Organizations”, while if looking at a condensed homepage with the drop down, the user can access “Users” in the above – not sure if that is intended

![image](https://cloud.githubusercontent.com/assets/14877933/16947590/42aa0d5c-4db0-11e6-9ddc-4ac3459be8bb.png)

vs.

![image](https://cloud.githubusercontent.com/assets/14877933/16947637/75d533fa-4db0-11e6-8e32-474165b2e339.png)

**Comment by clash99** [comment]
Added superuser conditional to hamburger menu:

![screenshot 2016-07-19 07 41 39](https://cloud.githubusercontent.com/assets/1119621/16950167/6829af96-4d84-11e6-95d3-8e64704742de.png)
