### ISSUE TITLE
Error in URL when adding new organization

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#463]
When adding a new organization, I received the error shown below in url section "Item 0 in the array did not validate". Perhaps text can be updated to be more meaningful
![image](https://cloud.githubusercontent.com/assets/14877933/16947717/e80086fa-4db0-11e6-8277-7608d658f64a.png)

**Comment by wonderchook** [comment]
Is this on the demo site?

**Comment by fhpichel** [comment]
Yes, on demo site

**Comment by wonderchook** [comment]
@fhpichel why did you close this?

**Comment by clash99** [comment]
I can't locate this error message.  I think its showing because of lack of a deliberate error message so we need to create one.

**Comment by clash99** [comment]
@seav - Do you have time to look at this one too?
