### ISSUE TITLE
"Draw Rectangle" while defining project areas

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#464]
After selecting “Draw a Rectangle” as an option while defining the project area, there doesn’t seem to be a way to delete the rectangle if you made an error in definition; the cancel button doesn’t work as it does with the “Draw a Polygon” option.

![image](https://cloud.githubusercontent.com/assets/14877933/16947773/2c55fa92-4db1-11e6-94bd-f53ae61b2649.png)

**Comment by seav** [comment]
The "Cancel" option only works when before you start drawing the rectangle. When you make a mistake, you can actually draw another rectangle and it will replace the first rectangle. Alternatively, you can use the trash icon to delete the rectangle and then draw a new one.

The cancel feature UX can be improved but the drawing feature is provided [by a third party](https://github.com/Leaflet/Leaflet.draw. So we would need to submit a bug report or issue to them to get this properly fixed.

**Comment by wonderchook** [comment]
@clash99 thoughts on improving this?

**Comment by clash99** [comment]
This is one of the first areas I think we should supply some supporting instructions and eventually a video demonstration.  I can try to enhance the instructions on the right to include more specific directions.

What about a quick png of something like this that we can link to:  http://2.bp.blogspot.com/-KWtBMMOCBCY/UuQEhGMGZKI/AAAAAAAAAk0/SeD6vzbVaFY/s1600/draw-01.png

Other ideas?

**Comment by wonderchook** [comment]
the interface has changed so we no longer have a cancel button here. Closing
