### ISSUE TITLE
Back Button When in process of adding new project

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#465]
When working to “Add New Project”, from the “Assigning Permissions” section, it would be useful to have a “back” button alongside the Save and Continue and Cancel buttons. Also note that while it seems like the “Draw Map” and “Add Details” icons are clickable when the user scrolls over, nothing happens when clicked.

![image](https://cloud.githubusercontent.com/assets/14877933/16947799/5682b9a4-4db1-11e6-97ca-6b701132dbc1.png)

**Comment by clash99** [comment]
Project wizard changes:

- Removed href links from progress circles at top
- Replaced buttons with Previous/ Next (need help with urls here for previous buttons)
- Reworked non-map pages to be a fixed width

<img width="1265" alt="screenshot 2016-07-20 16 03 07" src="https://cloud.githubusercontent.com/assets/1119621/17003132/2ac1f88c-4e94-11e6-827a-3dd14cb62c89.png">
<img width="1264" alt="screenshot 2016-07-20 16 03 22" src="https://cloud.githubusercontent.com/assets/1119621/17003133/2acca69c-4e94-11e6-9d79-8d912e819af2.png">
<img width="1262" alt="screenshot 2016-07-20 16 03 56" src="https://cloud.githubusercontent.com/assets/1119621/17003134/2add212a-4e94-11e6-9c18-520a1c4816ad.png">

**Comment by clash99** [comment]
@seav - I need help here with urls for the previous buttons and with a broken functional test.  The branch is feature/wizard-steps.

Do you have time to assist?  Either way, just let me know.  Thanks, Chandra

**Comment by seav** [comment]
@clash99, do you still need help? I looked at the latest Travis build and your branch passed. I also tried running the functional tests in my VM and they passed too.

**Comment by seav** [comment]
BTW, I think the "Cancel" button should still be there.

**Comment by clash99** [comment]
Good idea @seav.  I've reworked the buttons and I think this will be a good pattern to use in all our wizards going forward (right now this is the only one but I think there could be others).  

The functional tests are passing now but I'm not sure of the urls for the previous buttons on page 2 and 3.  I could use help there if you have a minute.

**Comment by seav** [comment]
@clash99, instead of an `<a>` element for the link to the previous step, please use a `<button>` element as follows:

```html
<button class="btn btn-default" type="submit" name="wizard_goto_step" value="{{ wizard.steps.prev }}">
```
