### ISSUE TITLE
Permission Denied when Adding New Project

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#468]
After establishing an organization, setting project name (shorter this time around) and attempting to create the project I get a "permission denied" response.  Strange, as I'm establishing the new project as the admin.

Images below are of the data entry leading to the "permission denied"

![error1](https://cloud.githubusercontent.com/assets/14877933/16950873/a5faa4b8-4dc2-11e6-8cf2-7f10edb892fe.png)

![error2](https://cloud.githubusercontent.com/assets/14877933/16950880/af84d81e-4dc2-11e6-9c4b-81052272324d.png)

![error3](https://cloud.githubusercontent.com/assets/14877933/16950885/b4ec2a32-4dc2-11e6-9aba-36fe7d35d289.png)

**Comment by wonderchook** [comment]
@amplifi can you see if you can find anything in the logs?

**Comment by amplifi** [comment]
@wonderchook Django is only logging uncaught exceptions, so there wasn't anything corresponding for this event. I'm not able to replicate the "Permission Denied" message using the same form inputs under another user in staging and demo. The database entries for the user account and organization in the screenshots look correct. The questionnaire attached to the form uploaded successfully and looks valid (except for the blank row at the top of the Settings tab, but that doesn't generate a "Permission Denied" message and wouldn't prevent the project being added).

**Comment by wonderchook** [comment]
@fhpichel can you try doing this again and write step by step what your inputs are?

**Comment by linzjax** [comment]
I'm also getting a permission denied error, but it's occurring because I appear to have the option to add a project to any organization I want to. The organization list should be limited to those you're a member of, and if you're not a member of any organization you should be redirected to create an organization first.

**Comment by ian-ross** [comment]
@linzjax Hah.  That explains something I saw earlier.  Chandra had created a project in an organization I'd created, and I couldn't figure out how she'd done it!

**Comment by wonderchook** [comment]
So I'm wondering if this is still an issue since it was on demo a month ago and we've fixed some of the UI elements that lead to this happening? For example with the latest release you only get orgs as an option when creating your project where you have access

**Comment by linzjax** [comment]
Oh yeah, if you go to the project list and try to add a project from there you get the **full** list of organizations in the drop down.

If you add a project from an organization page, you don't even see the option to select another organization.

**Comment by ian-ross** [comment]
That's kind of weird.  I only see a couple of organizations in the dropdown when I try to add a project from the project list.

**Comment by linzjax** [comment]
<img width="1280" alt="all of the organizations" src="https://cloud.githubusercontent.com/assets/8128188/17903335/276b5498-6939-11e6-8ff2-fee148269662.png">

**Comment by ian-ross** [comment]
That's on demo though.  I thought we were doing QA on staging?

**Comment by linzjax** [comment]
(face-palm) I'll see myself out...

**Comment by ian-ross** [comment]
Maybe we need different colour navbars for the different deployments?  It's really easy to get confused.

**Comment by ian-ross** [comment]
Or maybe a little thing like the "Fork me on GitHub" ribbon (or whatever you call it) saying "STAGING" or "DEMO"?

**Comment by wonderchook** [comment]
I'm going to close this as I believe it is no longer a problem with the upcoming release.
