### ISSUE TITLE
Long titles flow outside of page header

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#471]
![screen shot 2016-07-19 at 16 21 18](https://cloud.githubusercontent.com/assets/159510/16953339/f008cf6c-4dcc-11e6-8424-65c66c52c81e.png)

**Comment by clash99** [comment]
Ellipsis should show in md and lg screen resolution.  On hover text expands.

In sm and xs screen resolution, line wraps without truncating.

![screenshot 2016-07-19 10 36 11](https://cloud.githubusercontent.com/assets/1119621/16956171/fbe1a0f0-4d9c-11e6-8f17-df64829305eb.png)
![screenshot 2016-07-19 10 36 19](https://cloud.githubusercontent.com/assets/1119621/16956172/fbe27246-4d9c-11e6-9ee8-3dc0413008f7.png)
![screenshot 2016-07-19 10 37 15](https://cloud.githubusercontent.com/assets/1119621/16956173/fbe31994-4d9c-11e6-9a7b-b1a079b096aa.png)
