### ISSUE TITLE
Resources number on project overview

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#474]
The number of resources listed on the project overview says 7 although those are at the location level, not the project level.  So when a user selects the resources tab on the left or if we eventually linked that overview number to the resources, they see an empty list.  

Couple of ways to go from here:

1)  We could add a project/location/relationship/party filter on the resources page so that you can see all the resources within those from that page.

2)  We could modify dashboard number to just reflect project-level resources, which doesn't tell the whole story.

As we develop the records area more, we should take this into consideration and make a decision.

![screenshot 2016-07-19 10 48 55](https://cloud.githubusercontent.com/assets/1119621/16956636/dbf64e9c-4d9e-11e6-8fb5-82ff861c037c.png)

**Comment by seav** [comment]
The resources number actually pertains to the number of resources in the project's library.

**Comment by clash99** [comment]
Thanks for the update.

I think we should make the resources page (the one you would see if you selected the left tab here) be able to access all the resources instead of just the project ones.  We would need to add a filter at the top of the page to select the connection: project (default), location, relationship or party.  Definitely a future enhancement but I think it would make that page a lot more useful.  I will add a new issue and close this one.

**Comment by seav** [comment]
For this issue, we can probably link the number to the resources page. The issue to improve the project/library resources page has already been filed as #502.

**Comment by wonderchook** [comment]
this looks to be resolved.
