### ISSUE TITLE
Adding Location - Character Limit on Notes

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#479]
The character limit on notes is too low to be useful, possible to extend limit to 100 at a minimum.?

![notes](https://cloud.githubusercontent.com/assets/14877933/16983914/b0a64a7e-4e77-11e6-9ef9-f1c765cf2bfd.png)

**Comment by bjohare** [comment]
Try using **text_multiline** as the type rather than **text**?

**Comment by fhpichel** [comment]
Thanks @bjohare - fixed
