### ISSUE TITLE
Improve download processing

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#490]
The current process will create performance issues as soon as we have larger data sets as well as more resources. All resources are downloaded from AWS individually and then added to the zip, which will take more time the more files a project has. 

We should make this an asynchronous task. A project manager "orders" a download. This request is added to the download queue and processed as soon as the service has the required resources. When the download is ready, the project manager can be either notified either via email or by notification in the application.

**Comment by seav** [comment]
As mentioned by @wonderchook on #220, this asynchronous download processing is not intended for v0.1. But should this be targeted for the Post July Release or Version 1.0?

**Comment by dpalomino** [comment]
Included in the backlog, id 43.01.

**Comment by amplifi** [comment]
Decision record PR open for this architecture: https://github.com/Cadasta/decision-records/pull/7

**Comment by amplifi** [comment]
Pending decision record review and approval. Task breakdown scheduled for next week.

**Comment by alukach** [comment]
Should be resolved by #1400

**Comment by dpalomino** [comment]
Carrying over for Sprint 18.
