### ISSUE TITLE
Consider using an alternate map tileset

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#493]
We are currently using OSM's default tileset as our main base map. While this is tolerated by OSMF for low levels of traffic, we may want to consider using an alternate tileset, such as those provided by Mapbox (whose satellite imagery tileset we already use), or another provider. This allows us to make the base map match our site theme and lets us show only the details that we want on the base map.

**Comment by wonderchook** [comment]
@seav I'm going to close this for the time being. We can consider this later.
