### ISSUE TITLE
Weed out duplicate database requests in templates

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#494]
Templates currently create a lot of duplicate database requests. For instance, every time we call something like `{{ project.organization.name }}` the organization object is queried from the database. Model object that are used multiple times in a template should be queried once and added to the view's template context.

**Comment by seav** [comment]
I suggest that a follow-up action to help reduce database accesses is to also resolve #572. If we convert many modals into pages, then we don't need to access the database to render the data hiding behind the modals that can't be interacted with anyway.
