### ISSUE TITLE
How to handle duplicate resource names

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#495]
Similar to #448 and #324, resources can have duplicate names in a single project. This might make things confusing for the user if they want to select resources from the library.

Should duplicate resource names be allowed?

**Comment by wonderchook** [comment]
They should be allowed. We should do a warning that says "there is already a resource by this name, did you mean this one?" Allow the user to select no and go on

**Comment by oliverroick** [comment]
We decided this isn't a problem. Closing.
