### ISSUE TITLE
Columns of Resources tables for each type of entity is not consistent

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#497]
The resources table for projects, parties, and relationships on a wide screen has the following columns:
* Resource
* Type
* Connections
* Contributor
* Last updated

When the screen is narrow, the columns reduce to just Resource and Contributor.

For locations, the resources table always has Resource and Connections as the columns, no matter the screen width.

These should **probably** all be consistent.

**Comment by oliverroick** [comment]
_Connections_ everywhere
