### ISSUE TITLE
Resources table is not responsive

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#498]
The resources table for locations and relationships is not responsive on wide screens:

![screen shot 2016-07-22 at 17 54 25](https://cloud.githubusercontent.com/assets/873653/17053592/5b63b05a-5035-11e6-93cb-c9b8d903ab59.png)
![screen shot 2016-07-22 at 17 54 18](https://cloud.githubusercontent.com/assets/873653/17053593/5b67b1dc-5035-11e6-83ea-67bf2f2f100e.png)

This also affects the "Add" and "Upload" buttons.

**Comment by clash99** [comment]
Modifications for medium size screens:

<img width="1169" alt="screenshot 2016-07-25 22 23 36" src="https://cloud.githubusercontent.com/assets/1119621/17125133/8af3bc2e-52b6-11e6-875d-50da573a3cfb.png">

Large: 
<img width="1304" alt="screenshot 2016-07-25 20 51 12" src="https://cloud.githubusercontent.com/assets/1119621/17125105/5fa484a4-52b6-11e6-8cb7-f26f49e0d48a.png">

Small:
<img width="747" alt="screenshot 2016-07-25 22 23 59" src="https://cloud.githubusercontent.com/assets/1119621/17125132/8af31026-52b6-11e6-96ff-299102faf3ef.png">
