### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#50]
All labels must be translatable. Internationalisation will be based on [Jed](https://github.com/SlexAxton/Jed) and [Sprintf.js](https://github.com/alexei/sprintf.js). 

- [x] Move test-framework to karma, using a webpack pre-processor to compile `.po` files
  - [x] Mock HTTP requests (an alternative to Nock is required)
  - [x] Update testing docs, replace nock with sinon.fakeServer
- [x] Replace labels and messages with translate functions in the following components
  - [x] `account.Activate`
  - [x] `account.Login`
  - [x] `account.Logout`
  - [x] `account.Password`
  - [x] `account.PasswordReset`
  - [x] `account.PasswordResetConfirm`
  - [x] `account.Profile`
  - [x] `account.Register`
  - [x] `account.RegistrationForm`
  - [x] `core.App`
  - [x] `core.Header`
  - [x] `core.Home`
  - [x] `messages.actions`
- [x] Mark missing translations
- [x] Add styling for translations to CSS
- [x] Add React component handling

**Comment by oliverroick** [comment]
@Cadasta/cadasta-dev This is ready for review, see PR #5 

- It is based on [Sentry's approach](http://blog.getsentry.com/2016/01/07/react-i18n.html), using [Jed](https://github.com/SlexAxton/Jed) and [sprintf-js](https://github.com/alexei/sprintf.js)
- `gettext` files live in `app/src/locale`
- translation functions can be found in `app/src/js/i18n`

### How to use:

*Simple strings:*
```javascript
import { t } from './src/js/i18n'

t('Username'); // Nutztername
```

*Interpolated strings:*
```javascript
import { t } from './src/js/i18n'

t('Hello %(name)s', { name: Nicole }); // Hallo Nicole
```

*Plurals*
```javascript
import { tn } from './src/js/i18n'

tn('%d unread message', '%d unread messages', 0); // 0 ungelesene Nachrichten
tn('%d unread message', '%d unread messages', 1); // 1 ungelesene Nachricht
tn('%d unread message', '%d unread messages', 2); // 2 ungelesene Nachrichten
```

*Component templates*
```javascript
import { tct } from './src/js/i18n'

tct('For more information [link:click here]', {
  link: <a href="/info.html" />
}); // Für weitere Informationen <a href="/info.html">hier klicken</a>
```

### Highlighting translations in development mode

Run the development server from `app` using the `i18n_debug` flag:

```
npm start -- --build=i18n_debug
```

This will highlight all translated strings using a beautiful fuchsia background.

### What is missing

- Extracting translation from source. There’s a [babel plugin](https://github.com/getsentry/babel-gettext-extractor), but it does not work with Babel6. We can probably reuse parts of the plugin, but it needs to be adapated to Babel6.

**Comment by wonderchook** [comment]
Looks pretty slick @oliverroick. Should we move the "how to use" instructions over to the wiki?

**Comment by ian-ross** [comment]
Reviewed, merged, notes copied to wiki.
