### ISSUE TITLE
Question: Select Geotype in Your XLSForm

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#521]
I think this isn't currently possible, but wondering if I'm maybe being dense. Is there a way to have the user select a geotype in their form now? The scenario for this would be as follows:

Org is doing a community wide survey and mapping boundaries of individual plots of land. Portions of the land are inaccessible to walk around due to natural obstacles such as a river or lake. In these situations the surveyors will sketch the boundary on the phone using geoshape. In scenarios where the whole property is accessible they will walk the boundary using geotrace. 

Thoughts @linzjax and @bjohare?

cc @dpalomino

**Comment by linzjax** [comment]
First thought is yes: in the same way you can select between an individual and a group and get questions based on that, I would assume that you could do the same for geoshape vs geotrace.

In the `relevance` column you would add something like `${geo_type}='geotrace'`
[Example](https://docs.google.com/spreadsheets/d/1MUIYVa8UU7yM2vBY7_evFHzwECxgBXFnClykeUkIU-Q/edit?usp=sharing)

I'll have to test it, but I have a feeling the only thing that will be squirrly is the identical names..

**Comment by wonderchook** [comment]
Looks like it doesn't work, but I think we can worry about it a bit later.

**Comment by dpalomino** [comment]
Hi,

Thanks to both!

Sorry if this is a kind of trivial question but, do we have any document or
summary about the XLSForm features currently supported and not supported by
the platform?

I would try to do a couple of tests with geoshape/geotrace (it'd be useful
for a partner).

Thanks!
David

**Comment by linzjax** [comment]
I wrote up a half-hearted guide in the [API section of the wiki](https://devwiki.corp.cadasta.org/GeoODK%20API)

With the current iteration, you can change the `location_geometry` in the [standard form](https://docs.google.com/spreadsheets/d/1QsqMTLlPH5KVbBcgnh6MHWkIR0pIFchVzkqBSoL92fA/edit?usp=sharing) to be either geoshape or geotrace by editing the `type` column. I've been messing with it and found a way to allow the user to select which one they would like while in ODK Collect, but it won't be available until the end of this sprint (if it's something we want to include). Here's what the [updated form would look like](https://docs.google.com/spreadsheets/d/1MUIYVa8UU7yM2vBY7_evFHzwECxgBXFnClykeUkIU-Q/edit?usp=sharing).

**Comment by wonderchook** [comment]
@dpalomino what is in the default form is what is supported. If you want to have a call to review I'm available.

**Comment by wonderchook** [comment]
@linzjax do you have time to do this with your workload in the sprint? If so excellent, otherwise we might need to put it to the following sprint.

**Comment by linzjax** [comment]
@wonderchook already found one solution, so it'll be good to go 👍

**Comment by dpalomino** [comment]
That is great, thanks!

David

**Comment by wonderchook** [comment]
@linzjax what is the status of this? Was it finished with your pull request? We can also move off if needed.

**Comment by linzjax** [comment]
This was completed in the last PR
