### ISSUE TITLE
Need for global project option

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#524]
We need a way to flag projects as global if they don't have one set boundary.  In addition, we need a way to represent these projects on the home map with a list/filter/?? so that they can be selected.

I'm not sure how exactly we want to set up the logic but I would think if we could enforce a dialogue with the user so that if the project extends beyond one country(?), we could suggest making the project global.  Or let them know if a project doesn't have one set boundary, global would be the best option for them.

**Comment by wonderchook** [comment]
Agreed, I put it in the backlog for further discussion and prioritization. Probably something to add to the map interaction discussion as well

**Comment by dpalomino** [comment]
Backlog issue 11.00.

**Comment by wonderchook** [comment]
Are we done with this? Now users can select global for their projects.

**Comment by clash99** [comment]
Do we want to include a way for users to select global projects in this or is that part of #460?

**Comment by dpalomino** [comment]
@clash99, I think that could be part of #460 and close this issue...
