### ISSUE TITLE
UI for Base CSS

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#53]
Building base css for site.

Includes:

- [x] Header
- [x] Footer
- [x] Base fonts
- [x] Base colors

**Comment by clash99** [comment]
Questions:

- Do we need a platform footer?  Is there any sort of text we need to incorporate site-wide such as copyright or policy links?  (Landmark has "A partnership convened by the Instituto del Bien Común, the World Atlas of Indigenous Peoples' Territories, Liz Alden Wily, and the World Resources Institute in collaboration with numerous other organizations. " in a small header)

- Can we incorporate a language dropdown in the header?

**Comment by wonderchook** [comment]
@nastynoel I'd like your input on the platform footer. Let's discuss this ticket during "Github orientation"

**Comment by wonderchook** [comment]
Thinking this for the footer:

- Copyright
- Link to Github
- Terms of Service
- Privacy
- About
- Code of Conduct


One other question that came up was on where to put the help?

**Comment by ian-ross** [comment]
@clash99 Is this now done?  It's still listed as "To Do" on Zenhub.

**Comment by clash99** [comment]
Changed variable to match new Cadasta blue in style guide.
