### ISSUE TITLE
Project data is not preserved when stepping back in the add project wizard

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#530]
### Steps to reproduce the error
In the latest master branch (or the current [staging website](http://platform-staging.cadasta.org/)):

1. Go to the [add new project wizard](http://platform-staging.cadasta.org/projects/new/)
2. Add a geometry (or not) then click on the "Next" button
3. Enter any details such as organization, name, URL, contacts, etc.
4. Click on the "Previous" button
5. Click on the "Next" button
6. Notice that the fields are back to their default values
7. Enter any details such as organization, name, URL, contacts, etc.
8. Click on the "Next" button
9. Select non-default permissions for org members
10. Click on the "Previous" button
11. Click on the "Next" button
12. Notice that the permissions are back to their default values

### Actual behavior
- See steps 6 and 12 above

### Expected behavior
- The details entered at step 3 should be preserved at step 6
- The permissions selected at step 9 should be preserved at step 12

**Comment by ian-ross** [comment]
OK, that's totally not what's supposed to happen!  Maybe I misunderstood how the wizard stuff works when I originally set it up.  Let me look at this one.
