### ISSUE TITLE
It's not possible to remove the URL for an organization or a project

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#537]
### Steps to reproduce the error
1. Have an organization or project with a URL (either by creating a new entity or editing an existing entity, if there is no entity yet with a URL).
2. Edit that organization or project to leave the URL field blank. Save.
3. Notice that the organization or project overview page still displays a URL.
4. Go to the organization or project's edit details page.
5. Notice that the URL is still present.
### Actual behavior

See steps 3 and 5 above.
### Expected behavior

It is expected that there is no URL displayed in the overview page, and editing it shows up blank.
### Notes

Based on my testing and Googling, it seems that the `SimpleArrayField` and `SplitArrayField` form fields cannot be made to set their corresponding `ArrayField` model field back to empty once it has some data.

**Comment by seav** [comment]
I have investigated this issue and had to go through Django's innards. It seems the problem is more general and I believe this issue can be fixed by upgrading to Django 1.10 (released last August 1).

The root cause is that in `BaseModelForm._post_clean()`, the `construct_instance()` function is being called with the wrong `exclude` parameter. (The correct value is the list of fields that are excluded in the `ModelForm`'s `Meta` class; the wrong value is the list of fields that should not be validated anymore at the model level.) This issue is described in [Django's ticket #25349](https://code.djangoproject.com/ticket/25349) (apparently, this bug was a regression in 1.8) and has been fixed in Django 1.10.

**Comment by wonderchook** [comment]
@seav I don't think we should upgrade Django for this Sprint 7 release, so I'm going to move it to Sprint 8.

**Comment by seav** [comment]
It seems that after upgrading to Django 1.9.11 (or even 1.9.10), this issue has been fixed. I can now clear out the URL for organizations and projects.

**Comment by oliverroick** [comment]
Doesn't work on staging.

**Comment by seav** [comment]
That's weird. It indeed doesn't work now. But I'm sure it worked with v1.3.0-alpha.1. I wonder what changed.

**Comment by oliverroick** [comment]
Resolved with upgrade to Django 1.10
