### ISSUE TITLE
User name in header bug

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#543]
### Steps to reproduce the error

While logged in, select a member of an organization.  The user name in the right side of the header changes to the user name selected. 

Video:  http://screencast.com/t/ZLIuiED7KX0M

### Expected behavior

I would expect the user name in the header to remain constant to the user name that is logged in.

**Comment by wonderchook** [comment]
@seav I'm assuming you can take this one on?

**Comment by seav** [comment]
@wonderchook, sure I'll work on this today.
