### ISSUE TITLE
Organization Admin can delete herself, creating admin-less organization

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#548]
### Steps to reproduce the error

* Create an organization
* Add a member to the organization
* Delete organization creator

then enjoy endless errors!

[Please try to describe the actions that led to the incorrect behavior
in as much detail as possible.]

### Actual behavior

I thought I was actually deleting another member in my organization (Kate's account) but then I ended up deleting myself. 

When I tried to add myself back, I got an error message that I didn't have permissions to do so. I similarly didn't have permissions to archive or edit the organization account. 

Oddly enough, on the Organization Overview page, my information was still listed under Members.

* Organization: My Land Rights NGO
* Username: ngo-manager

[Please describe the outcome of your actions.]

### Expected behavior

[Please explain what behavior you would have expected instead.]

I don't think I expected my administrator account to be removed from the organization. Nor did I expect to see my account listed under members once I had been removed.

**Comment by linzjax** [comment]
So I added some logic to check if the current logged in user is looking at their own member page, and if they are, hide the remove button. Two questions:

1) Is there any instance when we would want to give users the option to delete themselves?

2) @clash99: if we go with this, I'm assuming we'll want to clean up the extra line?
<img width="325" alt="screen shot 2016-08-22 at 1 19 22 pm" src="https://cloud.githubusercontent.com/assets/8128188/17864300/86f30308-686b-11e6-92d7-fef8e67921e6.png">

<img width="323" alt="screen shot 2016-08-22 at 1 19 34 pm" src="https://cloud.githubusercontent.com/assets/8128188/17864304/8a513466-686b-11e6-9144-5e0d244bd2f7.png">

**Comment by seav** [comment]
Should we also prevent the admin from demoting him/herself from being an admin?

**Comment by wonderchook** [comment]
@seav I think so. If someone is no longer going to be an admin they should have to promote someone else to admin who can then remove them.

**Comment by clash99** [comment]
For an org admin, disabled button and added alert text below.

![screenshot 2016-08-26 15 05 26](https://cloud.githubusercontent.com/assets/1119621/18018809/a1f2dcf6-6b9e-11e6-9c49-913a314a3b5d.png)
