### ISSUE TITLE
Validation for contacts

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#55]
Organisation contacts will be stored as JSON using a hcard-like format. A custom validator function is required for the field, that checks if required fields are provided, correct types and formats. 

[jsonschema](https://github.com/Julian/jsonschema) can be used for validation.

**Comment by oliverroick** [comment]
I have implemented basic validation for contacts, based on [jsonschema](https://github.com/Julian/jsonschema). It is re-usable and can be reused for any validation of contacts.

I believe, that fully implementing the hcard format is overhead so I implemented a stripped-down version (but that can be changed, all we need to do is change the schema definition). The format is:

```
"name": {"type": "string"},
"email": {"type": "string", "format": "email"},
"url": {"type": "string", "format": "uri"},
"street-address": {"type": "string"},
"locality": {"type": "string"},
"postal-code": {"type": "string"},
"country-name": {"type": "string"},
"tel": {"type": "string"},
"job-title": {"type": "string"}
```

Am I missing any important information that should be collected for contacts?

Right now only `name` is required. I was thinking of making email and phone number, so that a user has to provide at least one of them.

**Comment by wonderchook** [comment]
@nastynoel any other contact information we should provide as an option? As stated only name is currently required, but all the others are available optionally.

**Comment by nastynoel** [comment]
@wonderchook - we're talking contacts for Project Administrators, field staff, or individuals who have data collected? Or all of the above. If Administrators, it should be mandatory to have either mobile phone or email included. Ideally, these details would be validated through a two step process, i.e. set up the account, after which the platform sends an email to the address requiring confirmation of the account creation, or sends a confirmation code via SMS to the mobile for entry back into the account creation page(s).

Any particular reason for including Job Title?

**Comment by wonderchook** [comment]
@nastynoel this is a reusable component for validating any contacts in the platform. So if I read you correctly you can't think of any other fields that we should include optionally?

Job Title might be useful in large organizations, not required in this case though.

**Comment by nastynoel** [comment]
correct
