### ISSUE TITLE
going to "my location" doesn't seem to work

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#551]
### Steps to reproduce the error

[Please try to describe the actions that led to the incorrect behavior
in as much detail as possible.]

From Map view on Cadasta Platform, click on the little map pin icon and see what happens. 

### Actual behavior

[Please describe the outcome of your actions.]

Clicking on the pin as described above does nothing.

### Expected behavior

[Please explain what behavior you would have expected instead.]

I expected to be taken to "my location" or for at least my location to light up on the map.

**Comment by clash99** [comment]
Works in Firefox.

Chrome error in console:
getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by clash99** [comment]
Decision was made to force ssl for platform and api.

**Comment by amplifi** [comment]
@bethschechter @clash99 All platform and API URLs now redirect from http to https. Functionality seems correct in Chrome; can we confirm?

**Comment by bethschechter** [comment]
confirming that it works in Chrome!

**Comment by clash99** [comment]
Works in Chrome but I am also seeing this in the console:

Mixed Content: The page at 'https://demo.cadasta.org/dashboard/' was loaded over HTTPS, but requested an insecure image 'http://c.tile.openstreetmap.org/1/1/1.png'. This content should also be served over HTTPS.

**Comment by wonderchook** [comment]
@clash99 looks like this might fix it: https://github.com/Leaflet/Leaflet/issues/3186

This something you can do?

**Comment by clash99** [comment]
The "my location" button is working and the error in console is no longer being displayed.  I think we can close this one.
