### ISSUE TITLE
Error editing a location when field length is greater than 32 chars in a text field

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#557]
### Steps to reproduce the error

* Open a location where there is a text field with more than 32 chars
* Go to Edit location
* Click on "Save" without really having done any actual edits
* You get an error saying that field is not allowed have more than 32 chars

### Actual behavior

* First, the error message does not appear at the top of the form response, user needs to scroll down
* Error message: "Please, make sure than this value length is less than 32 chars (actual length is 42)" (see screenshot) 

![screen shot 2016-08-18 at 12 00 31](https://cloud.githubusercontent.com/assets/17198051/17770109/4ccffc1c-653c-11e6-8d01-b3a1c8520e87.png)

### Expected behavior

* There should be no constrains regarding field length

**Comment by linzjax** [comment]
I think it's [here in django-jsonattrs](https://github.com/Cadasta/django-jsonattrs/blob/b1b9927ba0e276fd875ee84cf99b00cb0fbb52b3/jsonattrs/forms.py#L62-L63)
```
if atype.form_field == 'CharField':
    args['max_length'] = 32
```

There's the same logic in the [TenureRelationshipForm in the cadasta-platform](https://github.com/Cadasta/cadasta-platform/blob/b852b86fb9e76679379725c8aa78afd1513ee1e9/cadasta/spatial/forms.py#L103-L105)

**Comment by wonderchook** [comment]
In the short-term I think we should increase the length of the field. In the long term the field length should be taken from the XLSForm.

**Comment by ian-ross** [comment]
This is something that's actually a bit annoying in Django.  You have maximum lengths on model fields, maximum lengths for form field validation, and (nominally) maximum lengths that make sense for different kinds of text form widgets.  And, as far as I know, there's no mechanism to line them up in any sensible way.  I thought I'd put something like a multiline text (so unlimited length) field into django-jsonattrs, but apparently I deleted it at some point.  Let me think about the best way to deal with this.
