### ISSUE TITLE
Add Functional Test Coverage

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#558]

**Comment by wonderchook** [comment]
@seav I wasn't clear if you had worked on this in Sprint 8. If not I'm going to move off.

**Comment by seav** [comment]
@wonderchook, I have a work-in-progress code in the **test/more-ft** branch. Since this is all test code, I don't think this has any effect on the sprinting and I can continue to work on it for Sprint 9. I prefer to wait for @linzjax' PR first before this can be merged.

**Comment by wonderchook** [comment]
Okay moved over.

**Comment by wonderchook** [comment]
closing because this is more its own thing now.
