### ISSUE TITLE
Improve field messaging, define criteria

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#561]
Inventory field names that should include user messaging and perhaps have criteria defined (username, password, etc.)

**Comment by clash99** [comment]
Inventory here:  https://docs.google.com/a/cadasta.org/presentation/d/1ee7YkgsPzRSAYWOrSKYhC9xaQznEdiYanlmcdHfdVmM/edit?usp=sharing

We should relate this task to #735 and move to next sprint.

**Comment by clash99** [comment]
Fields I think could use additional help text "?" icon (or something similar).

- [ ] **Add new project wizard: Use the tools provided on the left side of the map to outline your new project boundary. Once complete, select the save button below.** 
Provide "?" with details on using map tool or a link to a short video demo.
<img width="1190" alt="screenshot 2016-10-13 08 55 39" src="https://cloud.githubusercontent.com/assets/1119621/19351846/fd5122d4-9122-11e6-9af3-adf68b17ef41.png">


- [ ] **Add new project - Select organization**
Add "?" for can't find or want to create new - an organization needs to be added before a project can be created under that organization.
<img width="1191" alt="screenshot 2016-10-13 08 57 34" src="https://cloud.githubusercontent.com/assets/1119621/19351922/4554ab1e-9123-11e6-8487-e3737f0efb04.png">


- [ ] **Add new location wizard: 1. Use the tools provided on the left side of the map to mark your new location.** 
Provide "?" with details on using map tool or a link to a short video demo.
<img width="1189" alt="screenshot 2016-10-13 08 51 08" src="https://cloud.githubusercontent.com/assets/1119621/19351669/4cb46346-9122-11e6-9f91-39857766f23a.png">

**Comment by clash99** [comment]
@bethschechter:  I'm making a list here of fields that I think could benefit from additional user messaging through a "?" icon.  We can discuss our plan of attack later today.

**Comment by clash99** [comment]
This is based on Beth's schedule so I'm not sure we can schedule this task at this time.

**Comment by clash99** [comment]
@bethschechter: Let me know when you get to this one and we can work out logistics....

**Comment by dpalomino** [comment]
Hi @clash99. Do you think this has been already completed? Can we close this issue or do we keep it open? Tks!

**Comment by clash99** [comment]
@dpalomino - Agree, let's close this and we can tackle on a feature basis.
