### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#566]
# Summary

Many users already have existing data outside of the Cadasta platform. This feature will allow users to import both data into a new project and an existing project.
# Links to requirements and functional testing script

[Requirements](https://devwiki.corp.cadasta.org/Data%20Import)
# Acceptance criteria
# Task list (including tests)

Needs to be updated as task is better defined and researched
- [ ] Research pieces needed for the feature

UI is dependent on task #565

**Comment by wonderchook** [comment]
#43 is something to consider when building this feature.

**Comment by dpalomino** [comment]
Epic for imports, clearing Milestone as it's being followed in the separated issues. 

References issues #833 #832 #813 #834 #831 #793 #791 #565

**Comment by dpalomino** [comment]
So main things related with imports were already implemented, so closing this issue.
