### ISSUE TITLE
Image handling in webpack

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#57]

**Comment by clash99** [comment]
Related webpack question - 

I have the Roboto and Steelfish fonts for our company branding that I would like to be able to use.  I think we need something like below to be able to use those fonts, which I've put inside a fonts folder within src/css.      
```
test: /\.(woff|woff2|eot|ttf|svg)$/,
loader: 'url?limit=100000'
```

Roboto is a google font so we can import that way if needed but Steelfish is not.

**Comment by oliverroick** [comment]
@clash99 For images do:

1. Install the file-loader (from inside `app`):

    ```
    npm install --save-dev file-loader
    ```

2. Add the loader to `webpack.config.js` to the module section:

		```javascript
		  module: {
		    loaders: [
		    // some existing loaders are already here
		    { // this is the scss loader, the last one in the list currently
		      test: /\.scss$/,
		      loaders: ['style', 'css', 'sass'],
		    }, { // this is what you add
		      test: /\.(jpe?g|png|gif|svg)$/i,
		      loader: 'file-loader?name=img/[name].[ext]',
		    }]
		  }
		```

3. Include the image from the React component (e.g. in Header.jsx, when you want to add the logo to the header)

		```html
		<img src={require('../../../img/cadasta.png')} />
		```

	This looks a bit odd, but the `require` function tells webpack to process the image. _Note:_ The path to the image is relative to where the files live inside `src`. 

It also works for images you include from CSS, only difference is that you use standard CSS `url(...)` and not `require`.

**Comment by oliverroick** [comment]
For fonts it's similar. You can also use the file loader you have installed previously. 

To process the fonts add the following to `webpack.confg.js`, just underneath where the image handling is specified:

```javascript
  module: {
    loaders: [
    // some existing loaders are already here
    {
      test: /\.(woff|woff2|eot|ttf|svg)$/,
      loader: 'file-loader?name=fonts/[name].[ext]',
    }]
  }
```

Reference the webfont from your CSS just like you would normally do.

**Comment by clash99** [comment]
Whenever I add in the logo image, it breaks my build.  Its fine on my local so I'm wondering if there is something missing on dev.

**Comment by oliverroick** [comment]
You need to add the file loaders to the karma webpack config as well. Open `app/karma.conf.js` and add the following after line 46.

```javascript
          {
            test: /\.(png|jpg|gif|svg)$/,
            loader: 'file-loader?name=img/[name].[ext]',
          },
          {
            test: /\.(woff|woff2|eot|ttf|svg)$/,
            loader: 'file-loader?name=fonts/[name].[ext]',
          },
```
