### ISSUE TITLE
Improve unregistered user experience with hopes to onboard them as registered users

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#575]
### Steps to reproduce the error
- As public user, open a project and try to select the map subtab on left.  
- As a public user, I try to open a location from the project overview map.

<a href="http://www.screencast.com/t/aww5q4Xei">2016-08-19_1005</a>
### Actual behavior

I am redirected to a sign in form.  A bit confusing since as an unregistered user I basically have the door slammed in my face.
### Expected behavior
- I would assume if I can see the map in the project overview, I could see the map in the map tab. 
- I would assume if I can see the "open location" button, I could open the location.

I think across the platform we have some options for public vs. registered users:
1. Hide all actions that aren't available to unregistered users (Not the best since isn't clear that more information is available, just not to them currently.  No motivation to register and loss of lots of potential registered users.)
2. Instead of hiding all unavailable actions, replace "open location" button with "Sign-in or Register" links.  (That way it is obvious to the user that more is available but not to them currently.  Moderate motivation to register.)
3. If the action is displayed and selected, we add messaging such as "The option you selected is only available to registered users of the Cadasta platform.  Would you like to sign-in now? (With sign-in and registration link).  (If done in a modal/popover implementation we could also provide bigger list of benefits of registering as a user as well as information such as its free. Biggest motivation scenario.)

I prefer #3.  Any other ideas?

**Comment by wonderchook** [comment]
I like option 3 as well. How would we handle when they sign in and they still don't have the rights to that action in a specific project?

**Comment by ian-ross** [comment]
We can probably work out what actions are going to be possible for a newly registered user (not a member of any organisations) and only display the message for those.  Other actions probably shouldn't appear for non-registered users, otherwise it might be kind of annoying for them when they sign up and still aren't allowed to do the thing they were offered as a teaser for signing up.

**Comment by dpalomino** [comment]
I think we can close this one as anonymous user experience was already being improved. @clash99 do you think we can close it? Ta!

**Comment by clash99** [comment]
Agree @dpalomino.  We've done some work on this by improving the redirected login.  The future enhancements on the project overview and request access task will do the rest.
