### ISSUE TITLE
Error Checking for Geotypes colliding w/being able to select Geotypes in XLSForms

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#577]
### Steps to reproduce the error
1. Create Project using this form [geoshape_questionnaire_0.1.xlsx](https://github.com/Cadasta/cadasta-platform/files/431356/geoshape_questionnaire_0.1.xlsx)
2. After saving project the error "There are two survey elements named 'location_geometry' in the section named 'b7rswi4e5qpehabiv425ujfx'." appears and the form is not uploaded. 

### Expected behavior

@linzjax added ability to select geotype in forms. The issue being that there are times where data collectors would not be able to use geotrace because of issues with terrain would make it impossible to walk the property boundary.

**Comment by dpalomino** [comment]
Thanks @wonderchook, this is useful. Some partners were asking for this indeed. @linzjax, please let me know if I can help testing this...

**Comment by linzjax** [comment]
@dpalomino @wonderchook: Try it with this questionnaire:

[geoshape_questionnaire_0.2.xlsx](https://github.com/Cadasta/cadasta-platform/files/433110/geoshape_questionnaire_0.2.xlsx)

**Comment by wonderchook** [comment]
Thanks @linzjax that works!
