### ISSUE TITLE
Project extent rendering is confusing

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#579]
### Steps to reproduce the error

Look at the main dashboard with a number of projects with large geometric extent:

![bug-02](https://cloud.githubusercontent.com/assets/1113720/17885231/97aaacd0-691c-11e6-9ff6-70a0d3133362.png)
### Actual behavior

The blue shading inside the project extent geometry makes it hard to see the underlying map, and makes it especially confusing when there are multiple projects with overlapping geometry.
### Expected behavior

The interior of the project geometry probably should not be shaded, so that the project extent geometry is displayed just with an outline.

**Comment by ian-ross** [comment]
After playing around a bit more with this, it seems that there's a more general issue here about rendering of polygons of different kinds on different map views.  It would be good to:

1. maintain a consistent style between the dashboard maps and project location maps, and
2. have a legend to explain what the different outlines mean.

For example, at the moment, project extents are displayed in this "blue outline + blue shade" style on the dashboard, but are displayed as dotted lines on the project map.  Locations are displayed either with "blue outline + blue shade" or "yellow outline + yellow shade" on the project map, depending on whether they're the "focused" location or other locations.  It seems like it would be better to do something like the following:

- Choose a colour for project extents, another colour for locations, other colours for other entities.
- Maintain the same colour choices for map polygons throughout the platform.
- Display all entities as outlines only (to prevent the overlapping extent problem shown above).
- Where there is an idea of a "focused" element, display this element with a thicker outline than non-focused elements.
- Provide a (collapsible) map legend on all map views.

**Comment by seav** [comment]
I think there was a discussion or suggestion about providing different colors or polygon styles for different types of locations (e.g., parcels vs. community boundaries) which can be customized by the project manager for usability purposes, though I can't find this discussion/suggestion. This may need to be considered in this Github issue.

**Comment by wonderchook** [comment]
Regarding project extent I think it would be useful to theme as well as outlined in ticket #340
