### ISSUE TITLE
Translations need to be updated

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#580]
### Steps to reproduce the error

Select any non-English language in the language menu and browse through the platform.
### Actual behavior

There aren't a lot of translations...  Most of the translations that there are were done some months ago, mostly to test the multi-lingual messaging machinery.  And the translations were done by people in the development team rather than by professional translators, so they're not particularly good or reliable.
### Expected behavior

Translations everywhere, at least for all the languages that appear in the language menu.

There are four steps needed to make this happen:
1. We need to check that all the text we want translated is set up for translation, both in Python source and in the templates.
2. We need to pull out the source messages and upload them to Transifex.
3. We need to decide what languages we need to support initially and engage translators.
4. Once the translators are done, we can pull the translated messages and check that none of the page views have been disrupted by differences in message lengths, etc.

Once the initial translation job is done, we also need to set up some process for maintaining translated message catalogues in future releases

**Comment by seav** [comment]
Step #1 above is already filed as #573.

**Comment by wonderchook** [comment]
Is step 1 a manual process where someone simple reviews all strings?

I'm thinking to test this we do the following:

- Review strings
- Pull out the source messages as suggested
- Have David translate into Spanish
- Pull translated messages
- @dpalomino can use the site in Spanish and look for things we've missed
- Engage translators (this is likely to be more partner based than specifically hiring translators for most languages)
- Pull translated messages from additional translations
- Rinse, repeat.

**Comment by ian-ross** [comment]
Yeah, step 1 involves manually looking for all strings that ought to be translated, and checking that they're within `_(...)` in Python files or within `{% trans ... %}` or `{% blocktrans %}` in templates.

I like your plan of getting quick Spanish translations from David: that will give us a good way of spotting where things are missing.  And Spanish is different enough to English that it's easy to spot when things really are missing.

Checking the strings is a tedious and error-prone job, so we should probably split it.  I don't know how to manage that, but everyone should probably do a bit (where "everyone" = me, Oliver, Eugene, Lindsey, Brian).

**Comment by wonderchook** [comment]
related to #573

**Comment by dpalomino** [comment]
Still not finished (58%), but there are some Spanish translations already in Transifex, I'll keep you posted.

**Comment by wonderchook** [comment]
@fhpichel the tech part is more or less done, so getting the translations becomes more a programs thing.

**Comment by wonderchook** [comment]
Closing this as it isn't really relevant to development. More if other languages are needed translators need to be sourced.
