### ISSUE TITLE
Browser geolocation not reliable?

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#581]
When I use the "Go to my location" button on the dashboard, I end up in Vienna, instead of where I really am.  The browser (Chrome in my case) HTML5 geolocation interface really is returning Vienna as my location.  I can see this being confusing for users if it happens to them.

(This may be because I'm using an LTE wireless internet connection, so maybe my ISP reports my location as being somewhere other than where I am, but it's something to think about.  Maybe it would be better to use a cookie to keep a record of the last location that a user was viewing and go there on the initial view of the dashboard, removing the "Go to my location" button?)

**Comment by seav** [comment]
In my experience, [HTML5 geolocation API](https://dev.w3.org/geo/api/spec-source.html), which this Leaflet feature uses, is not very accurate without some sort of GPS enabled and available.

I guess the question is whether we really need this button. I imagine that the geolocation API is mainly targeted for navigation apps and the like. I don't think our users need the use case of looking at projects or locations right where they are now.

**Comment by wonderchook** [comment]
I think this is something we are going to need to get feedback on. 

@dpalomino can you investigate with partners?

**Comment by dpalomino** [comment]
IMO I think it's more practical to go to the last visited location with a cookie as @ian-ross was suggesting. I can imagine most of cases partners working on the very similar area that they review frequently (probably from an office not necessarily close to that one). 

Another option could be to add a new icon with the last visited position, so we would have three location icons: search, home, and last (maybe a clock icon?). What do you think @clash99? 

In any case, we would try to figure out when working with the partners which options they would prefer...

**Comment by wonderchook** [comment]
@dpalomino the user needs to click the "go to my location" button for the zoom to occur. Agreed the default behavior should be where they last visited. Not sure we should take this out all together though. For example it goes directly to my house when I use the geoip location. Not sure how relevant this might be in places we work.

**Comment by dpalomino** [comment]
Really low prio issue. Closing for now, please reopen if needed.
