### ISSUE TITLE
Benghali font replacement

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#585]
### Steps to reproduce the error

Look at staging site organization index 

### Actual behavior

Unreadable font for Benghali organization

### Expected behavior

Fonts are replaced to be readable instead of boxes

Current:
![screenshot 2016-08-23 08 40 01](https://cloud.githubusercontent.com/assets/1119621/17894065/a38ce0a4-690d-11e6-8fad-aa88b9b2bfc1.png)

Expected:
![screenshot 2016-08-23 08 41 49](https://cloud.githubusercontent.com/assets/1119621/17894066/a3a6c820-690d-11e6-89e3-c482c0703546.png)

**Comment by seav** [comment]
As mentioned by @ian-ross in Slack, this can be remedied by using web fonts. We really cannot expect users to have fonts installed for all possible Unicode scripts.

**Comment by wonderchook** [comment]
How difficult is this to fix? @fhpichel is headed to Bangladesh so it would be good to tidy this up.

**Comment by clash99** [comment]
Not hard, I'll look at it this evening.

**Comment by clash99** [comment]
Spoke too soon - I don't think there is anything we can do.  Its a browser-based issue so fixes are available for the user to change the default font for their preferred browser.  

I'm trying to brainstorm if there is another way.  If we knew the project/org font was benghali, we could force a font substitution on our side via css but we currently don't have any way of knowing that and I'm not sure it would be that easy.  I'm totally open for other ideas on this one...

Is it currently broken for @fhpichel?  If so, I can reach out to assist him on getting it fixed on his browser.

**Comment by seav** [comment]
Couldn't a fallback font in the CSS work for this? https://en.wikipedia.org/wiki/Fallback_font

**Comment by wonderchook** [comment]
One thought is that most Bengali speakers would be likely to have the right font installed. (I'm guessing here)

**Comment by dpalomino** [comment]
Hi, 

I've just checked in my laptop with Chrome, Firefox and Safari (for desktop), and for Chrome for Android, and with all of them is working fine. 

Thanks!
David

**Comment by seav** [comment]
Regarding the fallback fonts. It's in the CSS specification that when you list a bunch of fonts in the `font-family` CSS property and the more preferred font does not have a glyph for a character, it will try the remaining fonts in turn until it finds one that does have a glyph. Otherwise, it will display the "missing character" glyph.

So there is no need to detect which language or script our organization or project names are using. Just provide a list of fonts in `font-family` that covers all of our likely Unicode scripts that can be used.

**Comment by ian-ross** [comment]
There's this, which has glyphs for all of the Unicode basic multilingual plane (which covers most languages currently in use): https://en.wikipedia.org/wiki/GNU_Unifont  I've been trying to find a webfont version of it, without luck though.

**Comment by clash99** [comment]
https://www.google.com/get/noto/#sans-beng

**Comment by seav** [comment]
Is this issue closed by #639? Note @clash99's request above: "I would like for someone who was seeing the hex boxes to confirm that this is working correctly for them."

**Comment by ian-ross** [comment]
I checked it and commented when I merged the PR, but I guess the PR didn't have the magic to close the issue. Anyway, it works!
