### ISSUE TITLE
select_multiple in XLS forms is not currently supported

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#586]
We are not currently supporting `select_multiple` questions in XLS forms (see [here](http://xlsform.org/#question-types)). 

It'd be a nice feature to support. It is a quite common use case for partners that would like to collect information that is not mutually exclusive (like infrastructures that are available in one specific location such as power supply, sewerage, etc).

**Comment by wonderchook** [comment]
@dpalomino I think we need to gather together what needs to happen for this to work. I'm going to slot in sprint 9 for the time being.

**Comment by dpalomino** [comment]
Hi @wonderchook! Sure, let me know when works for you (or just ping me on skype).

**Comment by dpalomino** [comment]
backlog item 6.00.
