### ISSUE TITLE
Geometry "persistence" when scrolling map view

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#587]
### Steps to reproduce the error

Go to the map view of a project with project extent geometry.  Zoom the map view until some but not all edges of the project extent are visible on the map.  Press and hold the left mouse button and drag the map view to bring more of the project extent into the view.
### Actual behavior

"Ghost" edges appear when dragging the map, lined up with where the project geometry was clipped by the viewport at the beginning of the drag action.  Releasing the left mouse button to end the drag action causes these "ghost" edges to disappear and the project geometry to be redrawn with edges in the correct positions.  (This happens for location boundaries as well, but it's easier to see it with the project extent geometry.)
### Expected behavior

There shouldn't be any "ghost" edges.  Project extent and location geometry should be rendered correctly during all map drag actions.

_This seems to be a Leaflet problem.  At least, I can reproduce it on some of the tutorial examples on the Leaflet website.  I don't yet know if there's a way to work around it._

**Comment by wonderchook** [comment]
Closing since it appears to be a leaflet issue. Can review when SMAP is finished.
