### ISSUE TITLE
Improve user error messaging consistency for forms

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#59]
This task covers consistent presentation of error messages.  Future tasks will cover improved verbiage and client-side validation.

Improve error messaging by: 
- Add error classes to turn error field borders red
- Turn error messages red
- Add background to fields with error to make them easier for users to locate

Page inventory:

- [x] Login
- [x] Register
- [x] Reset Password
- [x] Change Password
- [x] Profile
- [x] Add organization
- [x] Edit organization
- [x] Add organization members
- [x] Edit organization member
- [x] New project - details
- [x] Edit project details

**Comment by clash99** [comment]
Also once messages appear, you can select to go back to previous page and they still appear.  That is probably a bug.

**Comment by oliverroick** [comment]
I agree, improving error message is something we should address during the next sprint. 

Form fields should be validated on client side before the form is sent to the server. This will make it easier to highlight erroneous form fields along with an appropriate error message, as you described. 

We should implement generic form field validation that we can apply to all form throughout the client.

**Comment by wonderchook** [comment]
@clash99 is this complete?

**Comment by clash99** [comment]
No - I will try to update this issue this week with more details.

**Comment by clash99** [comment]
In addition to improving messaging, we should also present them consistently.

![screenshot 2016-07-01 15 50 10](https://cloud.githubusercontent.com/assets/1119621/16534210/bebfa2c8-3fa3-11e6-8b3a-bf197240dc06.png)
![screenshot 2016-07-01 15 49 51](https://cloud.githubusercontent.com/assets/1119621/16534218/c399594c-3fa3-11e6-94e7-71d0630ebdaa.png)

**Comment by wonderchook** [comment]
@clash99 I think the first option is more obvious. What do you think?

**Comment by clash99** [comment]
I think the first option only works in cases where the error messaging is limited.  Since some fields can have more than one error message, I think we have to work with something like this.  We are increasing usability just by changing the field border, label and error messages color.  

Also a bigger task of providing some client-side form validation and improving error messaging text should occur separately.

<img width="1045" alt="screenshot 2016-07-05 13 39 39" src="https://cloud.githubusercontent.com/assets/1119621/16596807/2d9245e2-42bb-11e6-8f7e-f3c33c26b048.png">

**Comment by clash99** [comment]
Page inventory:

- [ ] New project - geometry (unsure how to do error messaging on empty leaflet)
- [ ] New project - details
- [ ] New project - permissions
- [ ] Edit project geometry
- [ ] Edit project details
- [ ] Edit project permissions

**Comment by wonderchook** [comment]
@clash99 an you explain the geometry one a little further?

**Comment by clash99** [comment]
In the location wizard, you can't proceed without selecting a location on the map but there isn't an error message to inform the user.  I'm not sure how to check that no area has been selected on the map to throw the error.

Location:  http://screencast.com/t/Ue1cqzBh3C1B

When creating a new project, you can continue without selecting an area on the map but I'm not sure that you should be able to.  Seems like an error should be included on that page too and the map geometry should be required.  

Project:  http://screencast.com/t/Ilms1EBilww

**Comment by seav** [comment]
Based on the back-end model, having a geometry for the project is not required.

So is this intended? I think the platform can work even if the project has no geometry.

**Comment by wonderchook** [comment]
I think a project should have a geometry though I don't think it was discussed if it was required or not. Locations don't have to have geometries, though I think that is going to be difficult to deal with in the short term.

**Comment by clash99** [comment]
Using novalidate to suppress html5 form validations to avoid double messages like this:  
![screenshot 2016-07-07 11 20 32](https://cloud.githubusercontent.com/assets/1119621/16666364/e9cf2fb2-444c-11e6-8842-eb8c63eedfbd.png)

**Comment by clash99** [comment]
Screenshots (future tasks include improving verbiage and client-side validation):

![screenshot 2016-07-07 13 39 30](https://cloud.githubusercontent.com/assets/1119621/16666411/2c94e09e-444d-11e6-91c4-8ad0c2037ac8.png)
![screenshot 2016-07-07 13 48 17](https://cloud.githubusercontent.com/assets/1119621/16666427/34fec38a-444d-11e6-8899-d9105d6ef682.png)
![screenshot 2016-07-07 13 43 02](https://cloud.githubusercontent.com/assets/1119621/16666413/2c95c1ee-444d-11e6-914d-509d7583c6cc.png)
![screenshot 2016-07-07 13 45 21](https://cloud.githubusercontent.com/assets/1119621/16666412/2c94fd86-444d-11e6-89dd-a7008f4e622b.png)
![screenshot 2016-07-07 13 51 29](https://cloud.githubusercontent.com/assets/1119621/16666426/34fad338-444d-11e6-9c10-e95aa47127cf.png)
![screenshot 2016-07-07 14 11 03](https://cloud.githubusercontent.com/assets/1119621/16666428/35011ae0-444d-11e6-9ac5-c683ea5c9ed6.png)
![screenshot 2016-07-07 13 33 33](https://cloud.githubusercontent.com/assets/1119621/16666482/6eddcf42-444d-11e6-8739-2389ee3a61a6.png)

**Comment by clash99** [comment]
Moved geometry pages to #345 for further discussion.

**Comment by clash99** [comment]
I have a broken functional test that need fixed in branch enhancement/error-msgs before I can make a pull request.  @linzjax or @seav - do you have any availability to take a look?  Just let me know...  thanks!

**Comment by linzjax** [comment]
Fixed
