### ISSUE TITLE
Inconsistent Overview/Map Location Display

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#590]
### Steps to reproduce the error
- Log in as a user without permissions to project x. 
- Go view project x.
- Overview page will display all locations/spatial units, and deny a lot of permissions.
- Click on the map tab.
- Map page will not display any locations/spatial units.
### Actual behavior

<img width="1280" alt="overview_without_permission" src="https://cloud.githubusercontent.com/assets/8128188/17900621/e75153fe-692d-11e6-86b1-607244c49aa1.png">
<img width="1280" alt="map_without_permission" src="https://cloud.githubusercontent.com/assets/8128188/17900625/ecff2dd0-692d-11e6-978c-bac95ba4aa7c.png">
### Expected behavior

I'm not sure what the expected behavior is, but I suspect it's not what's currently happening.

Should non-permissioned users be able to see spatial units, but not open them? Should they not be able to see anything except the project extent?

**Comment by wonderchook** [comment]
Non-permissioned users should be able to see spatial units and not open them. It is a bit weird it is happening on the overview page though.

**Comment by ian-ross** [comment]
For reference, users without any special project roles aren't supposed to be able to list or view any entities within the project (column "None" at https://devwiki.corp.cadasta.org/Permissioning%20policies).  That's what seems to be happening here (so at least the permissioning mechanisms are working right, even if the permissions are wrong!).

@wonderchook What do you mean by "able to see spatial units and not open them"?  Do you mean the spatial units should be visible on the map, but there should be no way to view the details of individual spatial units?  If so, I think it's just a matter of adding the `spatial.list` permission to the default policy for everyone.

**Comment by wonderchook** [comment]
@ian-ross be able to see the outlines but not get to the details

**Comment by ian-ross** [comment]
OK, thanks: in that case, I think just adding `spatial.list` to the default policy should make the outlines visible.  We might need to add a flag to disable the popovers linking to the details as well, but that should be simple to do.  I'll assign this one to myself.

**Comment by linzjax** [comment]
There's still some oddities with this. If there are no locations I can open the map tab. If there are, I get a permissions denied.

<img width="1280" alt="screen shot 2016-09-13 at 3 05 23 pm" src="https://cloud.githubusercontent.com/assets/8128188/18487531/ace05430-79c3-11e6-8522-435f3c973238.png">
<img width="1280" alt="screen shot 2016-09-13 at 3 05 26 pm" src="https://cloud.githubusercontent.com/assets/8128188/18487536/aea8e426-79c3-11e6-96f7-d95c7d3f428e.png">
<img width="1280" alt="screen shot 2016-09-13 at 3 05 34 pm" src="https://cloud.githubusercontent.com/assets/8128188/18487543/b1f23010-79c3-11e6-81e1-f5268fb9ae52.png">
<img width="1280" alt="screen shot 2016-09-13 at 3 05 38 pm" src="https://cloud.githubusercontent.com/assets/8128188/18487548/b40f7146-79c3-11e6-8363-374d81fe30e2.png">

**Comment by ian-ross** [comment]
Hmmm.  I wonder if this was a victim of always logging in as a superuser for testing.  (Which is naughty.)  I'll put it back on my list.  Thanks for noticing this!

**Comment by ian-ross** [comment]
@linzjax Is this really a bug?  If there are no locations, opening the map doesn't show you anything you're not allowed to see.  What behaviour are you expecting to see here?  Should you get a permission denied message when trying to open the map view if there's no data?  If that's the case, what permission are you being denied?

**Comment by linzjax** [comment]
I think my confusion lies in that the map view and the overview pages show the exact same thing, regardless of whether or not I have permission to see the map page. So it's odd to me that I'm denied permission to see a page with the same information I'm already seeing... Does that make sense?

**Comment by ian-ross** [comment]
I agree.  I've never understood the difference between the overview and map pages.

**Comment by seav** [comment]
I prefer @clash99's option (1). If the user doesn't have the `spatial.list` permission, then the Map tab should be hidden. Similarly, if the user doesn't have the `resource.list` permission, the the Resources tab should be hidden.

**Comment by clash99** [comment]
I don't know if hiding is the best option because if I'm not a registered user, I'm not sure why I would want to register.  Being able to see there is more information available will have greater success in converting those public users into registered users.  I think the messaging needs to be on-point.  Perhaps this is another one @bethschechter can help with.

**Comment by dpalomino** [comment]
I agree with @clash99 regarding it would be nice to show the map but including the overlay with the login information. That would be a good incentive for the user to register.

**Comment by clash99** [comment]
This will not be an issue with the new project creation wizard ( #966 ).  The proposed project "about" page for non-project members will just show a project map with locations with zero interaction.  There is no additional navigation within the project.  I'm closing this issue @dpalomino.
