### ISSUE TITLE
Reset password page needs some CSS love.

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#591]
### Steps to reproduce the error

Using Chrome, click "forgot password" link on login page.
Follow the link in the email.
Arrive at this page:
<img width="1280" alt="reset_password_page" src="https://cloud.githubusercontent.com/assets/8128188/17900775/8250c434-692e-11e6-80e1-291e59f466af.png">

### Actual behavior
Sad default styling.

### Expected behavior
Lovely styling consistent with branding.

**Comment by oliverroick** [comment]
Is this supposed to happen in Sprint 9? It's not in the spreadsheet.

**Comment by wonderchook** [comment]
Pushed off to Sprint 10, thanks for catching this.

**Comment by clash99** [comment]
I'm cleaning up forms so I think I'm going to be doing some of these in Sprint 9 with client-side validation changes.

**Comment by clash99** [comment]
Files that were brought into css fold:

- [ ] account_inactive.html
- [ ] email_confirm.html
- [ ] logout.html
- [ ] password_reset_done.html
- [ ] password_reset_from_key.html
- [ ] password_reset_from_key_done.html
- [ ] password_set.html
- [ ] signup_closed.html
- [ ] verified_email_required.html

Email.html included in #322.

**Comment by clash99** [comment]
Few sample screenshots:

![screenshot 2016-09-28 20 20 07](https://cloud.githubusercontent.com/assets/1119621/18938012/00f839c2-85bb-11e6-806e-e6eed0085398.png)
![screenshot 2016-09-28 20 23 02](https://cloud.githubusercontent.com/assets/1119621/18938015/00fb4a90-85bb-11e6-910f-5e77f79c4143.png)
![screenshot 2016-09-28 20 24 02](https://cloud.githubusercontent.com/assets/1119621/18938013/00f88bf2-85bb-11e6-95fb-bfc910bdbe02.png)
![screenshot 2016-09-28 20 24 48](https://cloud.githubusercontent.com/assets/1119621/18938014/00f95e74-85bb-11e6-9884-d9b527a50022.png)
