### ISSUE TITLE
Questionnaires with select_one questions MUST have default or be required

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#592]
### Steps to reproduce the error

Create a questionnaire with a select_one question without a default that's not required.
Swipe through questions without selecting an answer
Enjoy your 500 server error
### Actual behavior

JSON attributes tries to save `""` as a value, and is not happy with the results.
### Expected behavior

Either we configure jsonattr to accept blank answers, or we force the user to make select_one questions have a **default** or be **required**.

**Comment by wonderchook** [comment]
@linzjax would this be blank or null? I'm guessing that ODK is sending null?

**Comment by linzjax** [comment]
From what I remember of the error messages it's sending a blank string (or at least a non-answer is getting saved as a blank string)

**Comment by wonderchook** [comment]
@ian-ross thoughts on the suggested jsonattr fix?

**Comment by ian-ross** [comment]
If I understand what's being suggested, it's inconsistent with the fix to https://github.com/Cadasta/django-jsonattrs/issues/1 -- the whole blank vs. null thing in text fields in Django is a bit vexing.  Anyway, let me look at it.  I'm not quite clear on what the semantics of these `select_one` fields should be: if they're not required, you're basically saying that there's an extra implicit blank choice, aren't you?  Or does there need to be a distinction between a "real blank value choice" and "no choice"?

**Comment by wonderchook** [comment]
I think there are questions that would be skipped and not have a default choice. I think that required fields shouldn't have a blank choice. Non-required fields however people should be able to skip.

**Comment by ian-ross** [comment]
@linzjax Are you trying to write a blank value into that attribute yourself?  Or are you saying that `django-jsonattrs` is generating a blank value itself?  If the former, I think the behaviour is correct: you would be trying to write a value that's not one of the allowed choices into the field.  Instead you can just not write a value at all (the field isn't required, so you don't need to put a value in for it).  If it's the latter, let me know and I'll see if I can come up with a test case for it.

**Comment by linzjax** [comment]
@ian-ross So, when going through a form, I come across a `select_one` question (let's say a yes_no question) without either yes or no selected. I ignore it and continue through the form because it's not required. When I try to submit, I get this error:
```
<Model> error: ['Invalid choice for <attribute>: ""']
```
So if a `select_one` question has neither a default answer, nor is required, django-jsonattr (or geoODK) generates a blank string `""` if it doesn't receive an answer from collect.

**Comment by ian-ross** [comment]
OK, let me see if I can figure out where that's coming from.  I don't think that `django-jsonattrs` ever generates data for attributes itself, so the blank value must be coming from somewhere before that point.

**Comment by bjohare** [comment]
Noticed that _django-jsonattrs_ is not the latest version in _requirements/common.txt_ which may have an impact on this issue?

**Comment by ian-ross** [comment]
Oopsie.  That's definitely not right.

**Comment by ian-ross** [comment]
Dammit.  Let me try updating that and seeing if everything still works.

**Comment by linzjax** [comment]
Turns out integer fields also can't be left blank. They're sent empty strings, which (correctly) are not validated as integers.

**Comment by dpalomino** [comment]
Thanks a lot @linzjax for let us know. Are we sure that these (select_one and integer) are the only types affected? We need to be careful with this when creating the forms for the partners...

**Comment by linzjax** [comment]
I'll run a test with every possible attribute type today, and let you know.

**Comment by linzjax** [comment]
@dpalomino: The only types affected are select_one, integer, and decimal.

**Comment by linzjax** [comment]
Is this the problem:
`default = field.get('default', '')`
https://github.com/Cadasta/cadasta-platform/blob/783c8a5c0f18317feddce44c73f7e6e445769ddb/cadasta/questionnaires/managers.py#L119

**Comment by ian-ross** [comment]
I'm getting a 400 for this, rather than a 500, which makes sense since it's an error in the data submitted from the client, rather than something that went wrong on the server.

More substantively though, it seems that the way to deal with this problem is for `django-jsonattrs` to do a better job of handling defaults.  I'm thinking that adding an explicit `has_default` flag to the `Attribute` table would help with the blank/null/no-default confusion.  I think that Lindsey is right about the `default = field.get('default', '')` line causing trouble, but there's no obvious way to deal with that in `django-jsonattrs` at the moment.

**Comment by wonderchook** [comment]
@ian-ross I think this makes sense and is something we should consider tackling in Sprint 9.

**Comment by dpalomino** [comment]
Great, thanks! Added to the backlog (as tentative).

**Comment by dpalomino** [comment]
Moving this to low priority until we have a GUI solution for handling forms.

**Comment by dpalomino** [comment]
Just noticed that select_multiple fields are also affected by this issue. So the types affected are: 
- select_one
- integer
- decimal
- select_multiple

Same workaround works with select_multiple (setting this as required with a default value). Moving this to medium prio for discussion.
