### ISSUE TITLE
Cannot click on profile button while adding a project

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#593]
### Steps to reproduce the error
Chrome:

- Log in
- Start creating a project
- Get to step 2 (Add Details)
- Try clicking on your user name (top right corner)

### Actual behavior
Nothing happens (no drop down, no change of page)

### Expected behavior
I expect to see a drop down that allows me to edit my profile or log out.

**Comment by clash99** [comment]
@linzjax - I cannot recreate this bug in FF or Chrome.  Can you verify that I fixed it, I mean that it is no longer an issue. :)

**Comment by linzjax** [comment]
Looks good! 👍

**Comment by seav** [comment]
@clash99, do you know how this was fixed? Or what the cause was?

**Comment by ian-ross** [comment]
@seav I might have fixed it in passing when doing something else.  I vaguely remember fixing something like this.  I think it was just something missing from a template, but I can't remember the details.
