### ISSUE TITLE
Clicking on a resource row doesn't automatically check the checkbox

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#595]
### Steps to reproduce the error
Chrome:
- Go to a project
- Click the resources tab
- Add a resource from library
- Click on a resource anywhere except the checkmark.

### Actual behavior
Nothing

### Expected behavior
Checkbox is checked.

**Comment by kavindya89** [comment]
Hi All,

I have added fix for the issue with pull request https://github.com/Cadasta/cadasta-platform/pull/725.
Please let me know any correction to be done.

Thanks,

**Comment by kavindya89** [comment]
![screen](https://cloud.githubusercontent.com/assets/22070016/18813936/0cf34026-8329-11e6-8fa9-d4eabdf44a45.png)
