### ISSUE TITLE
Edit Project Location should be changed to Edit Project Boundary

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#596]
It is confusing to use the word location to mean multiple things in the platform. Change Edit Project Location to Edit Project Boundary. 

![edit-project-location](https://cloud.githubusercontent.com/assets/67992/17911134/034e506c-6941-11e6-8115-51b6330ae4a5.jpg)

**Comment by wonderchook** [comment]
be nice to get this in sooner rather than later.

**Comment by seav** [comment]
I am going to assume that we also want to consistently use the term "boundary" instead of "extent" to refer to this particular geometry.
