### ISSUE TITLE
Support GPS with Accuracy in XLSForm

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#597]
Updated format: 

### Problem Statement

Some partners would require to check the GPS accuracy prior to accepting the submitted information into the platform. 

### Context / Use Case

A partner working in a urban slum requiring sub-meter accuracy for validating the data. Being able to "block" capturing coordinates with less than a specified accuracy would be very critical for them. 

### User Story

As a project manager, I want to define the level of minimum GPS accuracy that would be required in ODK app when collecting geometries

### Description 

Compiling the info from the [XLSForm documentation](http://xlsform.org/). 

When working with ODK/GeoODK you can specify the minimum accuracy level of the GPS in meters. You can set the minimum value of accuracy by including a new column *body::accuracyThreshold* and setting a value (in decimal) for the rows of *geopoint*, *geotrace*, and *geoshape*.  

There is no UI impact as the change is done directly in the XLSForm file. However, this should be taken into account when implementing the Project Designer (#1444). 

The reference to XLSForm spec is [here](http://xlsform.org/#gps-accuracy-threshold). 

The column that we need to add in the *survey* tab is 'body::accuracyThreshold' with the accuracy threshold specified in meters (X.X format) for geopoint, geoshape, and geotrace. Also a reference can be checked [here](https://opendatakit.github.io/xforms-spec/). 

A simple example can be found [here](https://docs.google.com/spreadsheets/d/1kdV-UF65WONU251Zh7ngdPiQ_VrEKTNmgOHyNonSsGw/edit#gid=0).

**Comment by dpalomino** [comment]
Backlog item 33.00.

**Comment by dpalomino** [comment]
Compiling the info from the [XLSForm documentation](http://xlsform.org/). 

When working with ODK/GeoODK you can specify the minimum accuracy level of the GPS in meters. You can set the minimum value of accuracy by including a new column *body::accuracyThreshold* and setting a value (in decimal) for the rows of *geopoint*, *geotrace*, and *geoshape*.  

An example of a xlsform file using this can be found [here](http://xlsform.org/). 

There is no UI impact as the change is done directly in the XLSForm file. However, this should be taken into account when implementing the Project Designer (#1444). 

(Moving this description to the first comment for more clarity).

**Comment by dpalomino** [comment]
Updated format: 

### Problem Statement

Some partners would require to check the GPS accuracy prior to accepting the submitted information into the platform. 

### Context / Use Case

A partner working in a urban slum requiring sub-meter accuracy for validating the data. Being able to "block" capturing coordinates with less than a specified accuracy would be very critical for them. 

### User Story

As a project manager, I want to define the level of minimum GPS accuracy that would be required in ODK app when collecting geometries

### Description 

Compiling the info from the [XLSForm documentation](http://xlsform.org/). 

When working with ODK/GeoODK you can specify the minimum accuracy level of the GPS in meters. You can set the minimum value of accuracy by including a new column *body::accuracyThreshold* and setting a value (in decimal) for the rows of *geopoint*, *geotrace*, and *geoshape*.  

An example of a xlsform file using this can be found [here](http://xlsform.org/). 

There is no UI impact as the change is done directly in the XLSForm file. However, this should be taken into account when implementing the Project Designer (#1444).

**Comment by dpalomino** [comment]
The reference to XLSForm spec is [here](http://xlsform.org/#gps-accuracy-threshold). 

The column that we need to add in the *survey* tab is 'body::accuracyThreshold' with the accuracy threshold specified in meters (X.X format) for geopoint, geoshape, and geotrace. Also a reference can be checked [here](https://opendatakit.github.io/xforms-spec/). 

A simple example can be found [here](https://docs.google.com/spreadsheets/d/1kdV-UF65WONU251Zh7ngdPiQ_VrEKTNmgOHyNonSsGw/edit#gid=0).
