### ISSUE TITLE
API: Deleting user from an organization member list completely deletes the user account

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#603]
### Steps to reproduce the error
(using httpie)
Add a user to an organization.
Delete them from the organization:
```
http DELETE http://localhost:8000/api/v1/organizations/<organization>/users/<username>/ AUTHORIZATION:'Token <token>'
```
Try to add them back.
Discover there is no longer a user with that username.

### Actual behavior
Deleting a user from an organization completely removes them from the database.

### Expected behavior
Deleting a user from an organization only removes them from that member list. The user account still exists.

**Comment by ian-ross** [comment]
This is happening here: https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/organization/views/api.py#L67-L68  What the code calls `role` there is actually the user, not the role.  Easy to fix by doing something like `role = OrganizationRole.objects.get(organization=self.org, user=user)` instead.  I'll fix it.
