### ISSUE TITLE
XLSForms with blank line in settings tab raise 500 Error

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#605]
### Steps to reproduce the error

Upload an XLSFile with a blank line in the settings tab.

### Actual behavior

Raises 500 Server error. The actual error is _jsonattrs_ **KeyError**

### Expected behavior

Should raise _ValidationError_. This could be achieved by checking that ```questionnaire.filename != questionnaire.id_string```.

**Comment by seav** [comment]
Should this be fixed before Monday (Aug 29)?

**Comment by bjohare** [comment]
Not a showstopper as long as we're careful with partner forms. We should also rationalize the forms in _questionnaires/tests/files_. Not all are required and some have the blank line issue.

**Comment by dpalomino** [comment]
I agree, as far as we would be careful this should not be a major issue. I've included a comment about this in [Questionnaire Guide in wiki](https://devwiki.corp.cadasta.org/Questionnaire%20Guide).

**Comment by bjohare** [comment]
This issue was mis-reported as being caused by a blank line in the settings tab of an uploaded XLSForm. The actual issue was that the `loadstatic` script was deleting all existing `Attributes` from the database causing `KeyErrors` when attempting to load any platform entities with associated `Attributes`.

**Comment by wonderchook** [comment]
@bjohare so I'm thinking this can be closed since that was fixed?
