### ISSUE TITLE
Footer glitching on smaller screen sizes on Organization Dashboards

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#606]
### Steps to reproduce the error
[CHROME]: Go to an individual organization page and start to decrease the screen width. Watch the footer get really enthusiastic about the space it's taking up.

(This is not newly introduced, it appears on demo as well)

### Actual behavior
<img width="931" alt="screen shot 2016-08-25 at 10 24 08 am" src="https://cloud.githubusercontent.com/assets/8128188/17972928/81a740e0-6aae-11e6-85eb-02c21e0c52b9.png">

(it's also a little odd on the sign-in page)
<img width="697" alt="screen shot 2016-08-25 at 10 22 26 am" src="https://cloud.githubusercontent.com/assets/8128188/17972940/88b7087a-6aae-11e6-883e-41b168a4f96b.png">

### Expected behavior
I expect it to behave like it does on project pages:
<img width="773" alt="screen shot 2016-08-25 at 10 28 35 am" src="https://cloud.githubusercontent.com/assets/8128188/17972995/b3a7a0ee-6aae-11e6-98b8-a295c2d1d524.png">

**Comment by clash99** [comment]
Org overview - Fixed css for row-height responsive design and updated page to include projects and hide members.  Flipped left and right columns for responsive small screens.

![screenshot 2016-09-09 10 53 21](https://cloud.githubusercontent.com/assets/1119621/18395475/0a3f126c-7684-11e6-8c65-7ee3f8d67ff3.png)

Also made footer fixed height with no visible overflow in sm screens for dashboard and registration area.  Eventually we may want to change this to another format.

![screenshot 2016-09-09 12 02 31](https://cloud.githubusercontent.com/assets/1119621/18395801/ddbd1516-7685-11e6-877d-67c27dd0290c.png)

**Comment by clash99** [comment]
Closed by #657
