### ISSUE TITLE
API: Members added to an organization are automatically assigned as administrators

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#608]
### Steps to reproduce the error
Using httpie:
```
http POST http://localhost:8000/api/v1/organizations/<organization>/users/ 'username'=<username> AUTHORIZATION:'Token <token>'
```
Check newly added users admin status

### Actual behavior
Users are assigned admin status automatically.

### Expected behavior
Users are assigned as members, and must explicitly be made admins.

**Comment by ian-ross** [comment]
This and #603 sort of go together, so I'll pick this one up too.
