### ISSUE TITLE
Can't view members... but I can

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#609]
![screenshot 2016-08-26 14 33 57](https://cloud.githubusercontent.com/assets/1119621/18018494/e9c18368-6b9c-11e6-8b61-c91d0c4b1e7b.png)
### Steps to reproduce the error

As only a member of an organization or public, select the organization overview page.  You will see in the right column members listed.  (Right now it shows all but I think eventually it will only show 5?)  Select the "View all" button or the "Members" subnav tab on the left.

### Actual behavior

Gives me a permissions error

### Expected behavior

If I truly am not supposed to see the member of an organization, then I should see the ones listed in the right column.

**Comment by clash99** [comment]
Two things here - 

1)  I'm a little confused on viewing permissions so I can't say for sure this is a bug.

2)  We need to think what is available (if anything) to public users.  This page could be sort of a waste.

**Comment by wonderchook** [comment]
The public shouldn't be able to see all the members of a project. I think with the current permissions they shouldn't be able to see any of them. if we someday end up having public/private users or more granular permissions then maybe that would work differently.

**Comment by wonderchook** [comment]
@dpalomino what do you think about this?

**Comment by dpalomino** [comment]
I agree with @wonderchook, I think users should only be able to see other users within their own organization, so public users or users pertaining to other organizations will not see any user details on the right column  when accessing to the overview section of organizations other than theirs.
