### ISSUE TITLE
Currently there is no way for a user to see which orgs they are a member of

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#610]
Future enhancement to see which organization a member belongs to and what permissions a user has (for org, projects, more?).  Would most likely be a build-out of the profile area.

**Comment by wonderchook** [comment]
@clash99 and @dpalomino what about having a short brainstorm next week about the profile area? I think we need to work it into the priorities.

**Comment by khantaalaman** [comment]
@wondercook Has this been worked upon?

**Comment by wonderchook** [comment]
@khantaalaman no but it also not completely designed yet. @clash99 do you have mocks of this?

**Comment by khantaalaman** [comment]
@clash99 Can you please help me in getting a direction for working over this issue?

Thanks!

**Comment by wonderchook** [comment]
@khantaalaman this is not marked "First Contributor Friendly" and we aren't in a rush to design it.

**Comment by khantaalaman** [comment]
No problem @wonderchook 
Thanks! :)

**Comment by clash99** [comment]
This is a feature of the new user dashboard. We can close this issue.
