### ISSUE TITLE
Catch schema / attribute errors during project page load

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#614]
### Steps to reproduce the error

Browse to https://demo.cadasta.org/organizations/frankfurt-2-org/projects/frankfurt-main/. The page displays a 500 Server Error. 

### Actual behavior

The page displays a 500 Server Error

### Expected behavior

The project page should be displayed.

**Comment by bjohare** [comment]
This is related to the `loadstatic` issue in which `Attributes` we're being deleted during re-provisioning. There is no recovery from this situation so I added a 500 Error template to report the issue to the user. Also, @adri has enabled email reports to platform admins in the case of XForm submission and 500 Errors. The `loadstatic` issue was fixed by https://github.com/Cadasta/cadasta-platform/pull/619. The 500 Error template was added by https://github.com/Cadasta/cadasta-platform/pull/616

**Comment by ian-ross** [comment]
Do you think this needs any further action, or should we close it as "one of those things"?

**Comment by bjohare** [comment]
I'm not sure there's anything we can do in case of attribute errors like these as the platform entities fail to load. I think these are genuine 500 errors and should be reported as such.

**Comment by ian-ross** [comment]
Now I'm proper confused!  If a 500 is the correct behaviour here (and I think you're right about that), then this ticket is basically saying that things work the way we want them to, isn't it?

**Comment by bjohare** [comment]
Yes, it can be closed.

**Comment by ian-ross** [comment]
Go on then!  Press the button!  You know you want to!  It's so satisfying!  Press the button and it just *goes away*!
