### ISSUE TITLE
Make pseudo-links behave more traditionally

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#615]
Currently, we have many pseudo-links on the website that require JavaScript to activate. These are mainly table rows, such as the table of organizations or table of projects. To go to an organization's overview page or the project's overview page, you need to click on the table row corresponding to the organization or project.

These pseudo-links do not behave like traditional links and therefore users are not able to do normal link actions to them such as hovering the mouse pointer over them to show the URL, or to middle-click them to open the target page in a new browser tab, or to right-click them to show the context menu that lets users bookmark the link or to copy the link URL to the clipboard.

One simple way to improve the situation is to provide normal links within the row, such as on the organization or project name.

**Comment by linzjax** [comment]
Related to [#595](https://github.com/Cadasta/cadasta-platform/issues/595)

**Comment by clash99** [comment]
We should talk about this.  Maybe there is a middle ground here - I know there are ways to add some of those features while still maintaining a linked row.  For mobile and probably most our users, having a large clickable target is more appealing than being able to see the url or open in a new target.  Any table with checkboxes would be an exception (resources).  Just thinking out loud here but perhaps its worth testing out...

**Comment by seav** [comment]
@clash99: Basically, it's OK to retain the linking behavior of the whole row. But my suggestion is to also add a duplicate normal link somewhere inside the row, such as the organization name or project name.

**Comment by clash99** [comment]
@seav - Sounds like a good idea.  I would assume the "main" text (typically name).  Is that what you were thinking?

**Comment by seav** [comment]
Yup! That was what I was thinking.

**Comment by manoramahp** [comment]
@seav Please find the PR https://github.com/Cadasta/cadasta-platform/pull/727 for the enhancement mentioned in this issue.
Please let me know if there are any other pages that needs this enhancement and if there's any css changes needed.
