### ISSUE TITLE
Replace "i" link in header

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#622]
Replace "i" link in header from platform page on cadasta to help widget for inlinemanual.  Allows for searching and contextual help to be displayed in right panel.

- [x] Ensure links to all walkthroughs are displayed
- [x] Add a redirect to user guides (or do we want user guides in inlinemanual)
- [x] Add a redirect in the help to platform page on cadasta.org

**Comment by wonderchook** [comment]
Does this need to happen for the walkthrough to be started this week? Or is this an enhancement?

**Comment by clash99** [comment]
Enhancement - quick fix but it will allow us to have walkthroughs available to anyone at anytime.  Also we should consider integrating user guides here.  It would allow users to search them on the platform.  We could also provide results contextual to page they are on.

**Comment by wonderchook** [comment]
Is there multilingual support for the user guides if we integrate in this way?

**Comment by clash99** [comment]
It does support multiple languages.   The way it would work is we would need to pass the variable from the footer language selection through to the player to tell it which one language to choose.

**Comment by clash99** [comment]
"I" icon is replaced.  Rest of work needs to be completed in inlinemanual.
