### ISSUE TITLE
demo user credentials not working on staging/platform

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#624]
### Steps to reproduce the error

1. Go to https://platform.cadasta.org
2. Click on "?" icon close to "Sign in"
3. Follow the instructions and use demo/password as credentials

### Actual behavior

Either in staging or platform we get a password error. However in demo.cadasta.org is working fine. 

### Expected behavior

Demo user should be working in demo, staging, and platform. 

![screen shot 2016-08-31 at 17 13 11](https://cloud.githubusercontent.com/assets/17198051/18134349/61a217b2-6f9e-11e6-9f5b-7b238a661a79.png)

**Comment by clash99** [comment]
This should only be displayed on demo so let me checkout what is going on.

**Comment by clash99** [comment]
Added contextual paths so the three current walkthroughs we have will only display on demo.cadasta.org.   These include:
- Sign in as demo user
- Quick start for dashboard
- Sample project tour (short version up but hope to expand this one)

This brings up a good question for future enhancements about what should be displayed for which server.  I'm assuming that there would be different versions per site for some but others could be shared across sites.

**Comment by clash99** [comment]
@dpalomino:  Can you verify that this is only being displayed on demo for you and close if correct?

**Comment by dpalomino** [comment]
Now it works perfectly! Only shown in demo.cadasta.org. 

Thanks @clash99!
