### ISSUE TITLE
Use username in place of empty full name

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#626]
### Steps to reproduce the error

Member permissions page (under Organizations > Members > Select specific user) 

Since username is required and full name isn't, we should use username instead of (or in place of) full name in member permissions title.

### Actual behavior

When full name isn't present, title is empty behind "Member:"

### Expected behavior

Would have expected username to show in cases of empty full name field.

**Comment by kavindya89** [comment]
I'll work on this. This will be my first issue as a contributor. :)

**Comment by oliverroick** [comment]
Great!

**Comment by kavindya89** [comment]
@oliverroick @clash99 I noticed one more thing. In member list page when there isn't full name member first column. I'll fix that as well :)

**Comment by kavindya89** [comment]
@oliverroick @clash99 I noticed one more thing. In member list page when there isn't full name member first column. I'll fix that as well :)

**Comment by kavindya89** [comment]
Hi All,

I submit a pull request. Since this is my first pull request for the project, it may need changes. Appreciate your suggestions. Attached images as well.

Thanks you

**Comment by kavindya89** [comment]
![screen1](https://cloud.githubusercontent.com/assets/22070016/18412770/e592f370-77b4-11e6-9ecf-c3827a6b8e36.png)
![screen2](https://cloud.githubusercontent.com/assets/22070016/18412771/e59c141e-77b4-11e6-8237-2d5d3bfb0a02.png)

**Comment by kavindya89** [comment]
The user Geshani don't have a full name :)
