### ISSUE TITLE
Hamburger menu responsiveness

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#628]
### Steps to reproduce the error

View platform on iphone.  

### Actual behavior

See hamburger menu not in header area on iphone (viewed on iphone6).  Looks alright in replicated responsive views but for some reason, not the same on actual phone :(

### Expected behavior

Adjust css so hamburger menu stays in header.  (After user in signed in, behavior is as expected)

Actual:
![canvas](https://cloud.githubusercontent.com/assets/1119621/18172344/a34efee6-702a-11e6-83c4-7e489f164e62.png)
Emulated in desktop web browser:
<img width="357" alt="screenshot 2016-09-01 09 56 15" src="https://cloud.githubusercontent.com/assets/1119621/18172364/b1e88b5c-702a-11e6-8cfe-ba3a036823d2.png">

**Comment by clash99** [comment]
While in the area, ideas to improve usability:
- Add border around hamburger 
- Reduce project name size

**Comment by clash99** [comment]
Appears to be a safari error only.

**Comment by seav** [comment]
Is this issue resolved by PR #651? (Note the PR follow-up action: "Once released to staging, qa in mobile safari browser")

**Comment by clash99** [comment]
Passed QA in mobile Safari browser on staging.  Closing this task.
