### ISSUE TITLE
"Contact us" should have emailto link

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#631]
After resetting your password the messaging says "We have sent you an e-mail. Please contact us if you do not receive it within a few minutes." We should make "contact us" a link to email support@cadasta.org

![screenshot_20160901-154053](https://cloud.githubusercontent.com/assets/67992/18186998/f241d48a-705a-11e6-98a1-02895f058543.png)

**Comment by nathalier** [comment]
Hi! 
I'd like to work on it as my first issue here:)

**Comment by nathalier** [comment]
While I'm researching how to update translation (https://gitter.im/Cadasta/cadasta?at=57d6a3f383c1556511bd4c90), this is what I have so far: https://github.com/Cadasta/cadasta-platform/commit/5a95bd6ef905f02d8691ccda608d2bf76e8dc6d8 . 
Any comments are appreciated!

**Comment by ian-ross** [comment]
Ah, I'd forgotten that we'd already overridden the `allauth` templates.  That should work fine, I think, and the strings all get pulled out for translation.  This should be enough to fix this, so you could make a PR more or less immediately!

**Comment by nathalier** [comment]
Do you mean it will be translated soon? Without fix, lokalized version of the phrase is shown in other languages. But the fix breaks it (because of changed msgid), and phrase in English is shown instead.

**Comment by wonderchook** [comment]
@nathalier translations are done [in Transifex](https://www.transifex.com/cadasta/cadasta-platform/dashboard/), so first the fix would happen in English and then be translated later.

**Comment by ian-ross** [comment]
Yeah, that's OK.  You just need to change the source language text in the templates (which you've done).  Then we pull all the messages out, upload them to Transifex, someone translates them, then we download the translations and Django picks up the appropriate translation from the message catalogues.  The process is described here: https://devwiki.corp.cadasta.org/Translation

**Comment by nathalier** [comment]
@wonderchook @ian-ross Thanks for guidance! `:-)`
