### ISSUE TITLE
Geopoint parse failure when there are also geotrace and geoshape questions in xlsform

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#643]
### Steps to reproduce the error

Try to submit to a form that has `geotrace`, `geoshape` and `geopoint` typed questions. See [here](https://docs.google.com/spreadsheets/d/1ZqhPeO8YAgZ_ikNmTb2X5esK83_R5W82fqDT6S8szOA/edit#gid=1077080677) for an example.

### Actual behavior

Throws a `400` error where the exception is `list index out of range`.

### Expected behavior

Form should submit successfully.

**Comment by bjohare** [comment]
See https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/xforms/mixins/model_helper.py#L79. The following line should be `geotrace=False`

Also wondering if this database query is required? https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/xforms/mixins/model_helper.py#L70

**Comment by dpalomino** [comment]
Thanks @bjohare for checking this and help to find out what was going on! 

Is it possible to try to fix this in this milestone (if it's not too difficult)? I think it's important for several partners...

**Comment by bjohare** [comment]
This has reappeared in the latest master.
