### ISSUE TITLE
Order permission roles according to level of permissions in select dropdown

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#650]
### Steps to reproduce the error

Select member permissions page for a project.  

### Actual behavior

Dropdown to assign permission is out-of-order.

### Expected behavior

I would assume permissions would be listed in least amount to most amount of permission to show some sort of visual hierarchy for the user.

Recommended order:
- Public user (default/ least permissions)
- Project user 
- Data collector
- Project manager (most permissions)

![screenshot 2016-09-07 11 28 33](https://cloud.githubusercontent.com/assets/1119621/18321058/0c260362-74f2-11e6-8a66-2b23a96d8d91.png)

**Comment by wonderchook** [comment]
I agree!

**Comment by kavindya89** [comment]
@wonderchook @ian-ross I have fixed it and attached screen shot. Let me know anything to be correct.
![screen](https://cloud.githubusercontent.com/assets/22070016/18633231/ea45284e-7e98-11e6-8ffb-dc40d74931b8.png)

**Comment by seav** [comment]
Closed via #705.
