### ISSUE TITLE
API Features for QGIS Plugin

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#653]
# Summary
There are some features not currently existing that need to be exposed by the API for the QGIS plugin features to be possible. They are permissions based filtering and attribute schema manipulation. 
# Links to requirements and functional testing script
More details are available here [API Features are required for QGIS Plugin to work](https://devwiki.corp.cadasta.org/@QGIS%20Plugin)
# Acceptance criteria
# Task list (including tests)

**Comment by oliverroick** [comment]
I'm splitting this into two separate tasks:

- Updating Questionnaires via the API (#686)
- Add Permission Filtering to the API (#685)

**Comment by wonderchook** [comment]
I'm going to close this then (I've updated the Sprint Spreadsheet and other references accordingly.
