### ISSUE TITLE
Determine Migration Rules for Schemas

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#654]
We need to decide on a set of migration rules for when a project schema is changed prior to beginning work creating the migration. 

related to: #640 and https://github.com/Cadasta/django-jsonattrs/issues/8

**Comment by ian-ross** [comment]
I've spoken to @oliverroick, and this isn't needed at the moment, so I'm going to push it off of Sprint 9.

**Comment by dpalomino** [comment]
Related to discussion regarding changes in questionnaires: 

https://github.com/Cadasta/decision-records/pull/4

**Comment by dpalomino** [comment]
I think we can close this issue once the decision record was created. Please reopen if needed.
