### ISSUE TITLE
Design Resource API

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#66]
- [ ]  Resource list with search, filter, sort
- [ ] Access resource details
- [ ] Create, update
- [ ] Archive/unarchive

Should there being and features for getting thumbnails from images or other resource specific actions?

(broken out from #15)

**Comment by oliverroick** [comment]
There should thumbnails, I would offer a few common thumbnail sizes: 75x75, 150x150 to 300x300
