### ISSUE TITLE
Improve browser detection of .gpx files on GPX import

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#662]
### The problem

Currently, browser mime-type detection of files with `.gpx` extension is unreliable. GPX files that need to be imported into the platform must be renamed to have a `.xml` extension. We should investigage how to improve correct mime-type detection of `.gpx` files and/or improve _django-buckets_ error reporting if this is not possible.
### Actual behavior

GPX files to be imported must be renamed to have a `.xml` extension. Error messaging if the user attempts to upload a `.gpx` file is not detailed enough.
### Expected behavior

Ideally we would be able to import `.gpx` files directly. Failing that, the error reporting should be improved.

**Comment by dpalomino** [comment]
Just as a comment to be considered, Windows OSs are usually hiding file extensions,  so for a regular user it could be not trivial to change the file extension. 

http://www.howtohaven.com/system/show-file-extensions-in-windows-explorer.shtml

Just to remember this when we'd be guiding a user on this process.

**Comment by wonderchook** [comment]
I'm running windows and this hasn't been an issue with GPX. I don't think I have special settings.
