### ISSUE TITLE
Use marker clustering on GPX imported waypoints

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#663]
### Steps to reproduce the error

Marker clustering should be implemented for imported GPX waypoints.
### Actual behavior

No marker clustering is currently applied.
### Expected behavior

Imported waypoints should use the markerclustering library to cluster waypoints that are geographically proximate.

**Comment by dpalomino** [comment]
backlog 3.06, updated requirements.

**Comment by wonderchook** [comment]
closing we can review again after the SMAP
