### ISSUE TITLE
XML file type not accepted as resource

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#670]
### Steps to reproduce the error

- Try to upload xml file as resource

### Actual behavior

- Looks like it was accepted but upon save, receive error (see screenshots below)

### Expected behavior

- Expected to return to resource index and see xml file listed

Couple of examples from different xml files:

![screenshot 2016-09-12 11 10 33](https://cloud.githubusercontent.com/assets/1119621/18443280/c5147256-78d9-11e6-8645-765c17cfa242.png)

![screenshot 2016-09-12 11 16 51](https://cloud.githubusercontent.com/assets/1119621/18443427/7e46aa78-78da-11e6-8e15-478012e3156a.png)

**Comment by bjohare** [comment]
@clash99  in the first case above, it looks like the database migration hadn't been applied.. is that possible? The second one is definitely a bug.
