### ISSUE TITLE
MP3 file type not accepted as resource

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#671]
### Steps to reproduce the error

- Upload mp3 as resource file

### Actual behavior

- Receive error message that file is not accepted although listed as acceptable file type

### Expected behavior

- Upload file and return to index with file listed

![screenshot 2016-09-12 11 19 20](https://cloud.githubusercontent.com/assets/1119621/18443678/935c4bba-78db-11e6-89ff-9e2fe0f52f0c.png)

**Comment by bjohare** [comment]
We need to add **audio/mpeg** and **audio/mp3** to the _MIME_LOOKUPS_ in settings as the current settings don't cover all possible mime types for mp3 files.
