### ISSUE TITLE
GPX file type not accepted as resource

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#672]
### Steps to reproduce the error

- Upload gpx file

### Actual behavior

- Receive message file type is not accepted although listed as acceptable file type

### Expected behavior

- Typical file upload

![screenshot 2016-09-12 11 27 04](https://cloud.githubusercontent.com/assets/1119621/18443759/07fbcf4a-78dc-11e6-9b52-e4c4096f7c85.png)

**Comment by wonderchook** [comment]
@clash99 using .xml or .gpx extension? For GPX we are #662 open. The XML has been fixed though.
