### ISSUE TITLE
Long xform errors break layout

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#678]
### Steps to reproduce the error

Upload [this XLSForm](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/questionnaires/tests/files/test_standard_questionnaire_bad.xlsx) to a project and save the project.

### Actual behavior

![screen shot 2016-09-13 at 11 48 51](https://cloud.githubusercontent.com/assets/159510/18469407/669bb67e-79a8-11e6-99a9-493ef1ee2449.png)

### Expected behavior

I would suggest to display error messages as a list below the label here, instead of having it float to the right.

**Comment by clash99** [comment]
Should be fixed with #322

**Comment by clash99** [comment]
Moved error-block into well area and made background transparent.

![screenshot 2016-09-28 14 24 27](https://cloud.githubusercontent.com/assets/1119621/18928844/85803e58-8587-11e6-989e-50eccb15a840.png)

**Comment by clash99** [comment]
Fixed in #357 branch.

**Comment by clash99** [comment]
Should move to Sprint 10 - fixed in form branch.
