### ISSUE TITLE
Non-project members should not see "Congratulations" message

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#682]
### Steps to reproduce the error
Create a new project, don't add information to it.
Log in as a different user without access to the project.
See this:
<img width="1280" alt="screen shot 2016-09-13 at 4 55 38 pm" src="https://cloud.githubusercontent.com/assets/8128188/18491183/316627a2-79d3-11e6-92c8-7b0add83b377.png">

### Actual behavior
Same view as a project member.

### Expected behavior
Something similar to organization pages without projects, or just zeros across the board.

**Comment by manoramahp** [comment]
@wonderchook My suggestion for this is, if the logged user isn't a project member, 'Add Location' button shouldn't be shown in the UI. And we can show the project overview as 
PROJECT STATS
0           | 0          |0
location | parties | resources
what do you think?

**Comment by seav** [comment]
@manoramahp, that is exactly what is suggested by @linzjax above.

**Comment by manoramahp** [comment]
@wonderchook 
I've done a fix for this issue. Can you please review and merge PR https://github.com/Cadasta/cadasta-platform/pull/702

**Comment by wonderchook** [comment]
@manoramahp your pull request has failing tests, please review.

**Comment by manoramahp** [comment]
@wonderchook I've fixed all the test failures. https://github.com/Cadasta/cadasta-platform/pull/703
