### ISSUE TITLE
Change Highlighting on Sample forms so geotrace is white

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#691]
In the documentation we instruct users to only modify the "white" parts of the xlsform. They should be able to change the geometry collection type so that needs to also be white. 

![image](https://cloud.githubusercontent.com/assets/67992/18534964/0f9f489c-7aa5-11e6-9653-dff62dd08184.png)

/cc @bethschechter

**Comment by wonderchook** [comment]
@clash99 below are the updated forms. I don't think I have access to update them though. 

[standard_cadasta_questionnaire.xlsx](https://github.com/Cadasta/cadasta-platform/files/473728/standard_cadasta_questionnaire.xlsx)
[minimum_cadasta_questionnaire.xlsx](https://github.com/Cadasta/cadasta-platform/files/473729/minimum_cadasta_questionnaire.xlsx)

**Comment by clash99** [comment]
@wonderchook: will do, have the ones linked to from the documentation also been updated?  I hate that we have to do it in two places but can't think of another way right now...

**Comment by wonderchook** [comment]
@clash99 not yet. That is something @bethschechter can do. Maybe we should update the links in the documentation to point at the ones in S3. Would that work?

**Comment by clash99** [comment]
I think so but s3 has no versioning.  Is that an issue?

**Comment by wonderchook** [comment]
I think it would be okay. I think we want to be using the same files they find in the platform and the documentation.

**Comment by clash99** [comment]
Files updated:

- https://s3-us-west-2.amazonaws.com/cadasta-resources/sample-forms/minimum_cadasta_questionnaire.xlsx
- https://s3-us-west-2.amazonaws.com/cadasta-resources/sample-forms/standard_cadasta_questionnaire.xlsx

I noticed the documentation now uses the terms **basic** and **expanded**.  I think the questionnaire note in the platform should be using the same terminology and we should even update the file titles to match.  Is this change official?  Its an easy change but keeping everything in sync is the challenge.

**Comment by bethschechter** [comment]
@clash99 @wonderchook rad! I had been linking to the Google docs but this is so much better. Thank you!

**Comment by wonderchook** [comment]
@bethschechter thoughts on the language? I'm inclined to say we use standard and minimum since that is what the files say. And I don't think it matters too much

**Comment by bethschechter** [comment]
@wonderchook I like minimal vs. minimum, but that's my only thought
Also, I think I remember seeing that someone may change the standard form? David perhaps?

**Comment by wonderchook** [comment]
let's stick with standard and minimum. Regarding the form being changed we should do that as part of releases, so we'll leave things the way they are now for the release on Monday.

**Comment by bethschechter** [comment]
ok, so for the docs, don't link to these new forms? or wait until Monday?

**Comment by wonderchook** [comment]
Link to them now. I more meant we wouldn't be changing them again until the next release.

**Comment by bethschechter** [comment]
ok copy. thank you!

**Comment by clash99** [comment]
Cool - looks like we can mark this one complete.  Let me know if you need any assistance with the files @bethschechter or if we do decide on terminology updates.  Thanks all!
