### ISSUE TITLE
Unhandled exception if user already exists

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#696]
### Steps to reproduce the error

A user attempts to sign up with an email address that is already associated with an account, but the email address is not yet verified.
### Actual behavior

A Django platform error is generated: 

> Internal Server Error: /account/signup/
> 
> IntegrityError at /account/signup/ 
> duplicate key value violates unique constraint "account_emailaddress_email_key"
> DETAIL: Key (email)=(someone@something.com) already exists.```
### Expected behavior

The user should receive a relevant error message in the UI that describes the issue and no platform error is generated.

**Comment by manoramahp** [comment]
This issue cannot be seen in https://platform-staging-api.cadasta.org/account/signup/. It correctly gives the error message as "Another user with this email already exists".

**Comment by wonderchook** [comment]
@amplifi I'm also not seeing the error on staging.

**Comment by ian-ross** [comment]
I think we've already talked about this one.  @amplifi was going to add a comment.  The problem only occurs if the user account in question has not had its email verified.  (Discussion here: https://cadasta.slack.com/archives/development/p1474027720000307)

**Comment by amplifi** [comment]
Isolated issue that hasn't reoccurred. Appears to have been related to a specific user entry in the staging database for a user that had registered but had no initial login date recorded. That bug has been resolved so I don't see this one happening again. Safe to close.
