### ISSUE TITLE
Users/Login/Registration

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#7]
Users should provide: user name, password, email address, full name, optional avatar image.
User-selected username account ID (not email address).
Account verification, password reset, “remember me” cookies, etc.
Password reset and change from profile page.
API authentication.
Email addresses should be verified (this should be fine since we’re not requiring “public” viewers to have an account). Handling unverified emails: When a user signs up they can use their account without verified the email for some time. An information message should be displayed when their email is not verified. After some time the account is suspended, providing the user the option to resend the verification email.
Allow updates of email address (with verification), but not multiple email addresses per account.
No user should be able to edit or delete user accounts other than their own account. It should be possible for an OA to remove a user from their organisation, but not otherwise to modify the user’s account. A SU should probably be able to archive user accounts, but not an OA.

Use a translation framework from the start. Should be compatible with Transifex or a comparable service.

OA+s can list all users registered with the platform (searchable, sortable, filterable list). They should be able to bulk select from that list for further actions, such as adding permissions.
OAs can see user profiles with all permissions.

**Comment by wonderchook** [comment]
Reopened until the UI piece is finished.

**Comment by ian-ross** [comment]
This issue needs to be broken apart anyway: some of the items in it are not for the current sprint.

**Comment by clash99** [comment]
@oliverroick  Where did you want an images folder for the site to house the cadasta logo, etc.?   I would assume src?  I wanted to check with you first.

**Comment by oliverroick** [comment]
@clash99 I'd create a directory `img` inside `src`.

**Comment by clash99** [comment]
Pulled out UI tasks to #51
