### ISSUE TITLE
User account dropdown does not work during the project add details page 

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#707]
### Steps to reproduce the error
1. While logged in as an org admin, go to the add new project page.
2. Go to step 2 (Add Details) of the add new project wizard.
3. Click on your username at the top bar.

### Actual behavior
Nothing happens.

### Expected behavior
The dropdown menu (with the "Edit profile" and "Logout" choices) should appear.

**Comment by ian-ross** [comment]
Duplicate of #593, I think.

**Comment by seav** [comment]
@ian-ross, so it is! I guess I should search first instead of relying on my memory. Closing this.

**Comment by ian-ross** [comment]
Sometimes it's easier just to open the issue and rely on the collective memory of the team!
