### ISSUE TITLE
Page and permissions caching

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#714]
At the moment, we don't use any page caching, and there is some ad hoc caching within django-tutelary that is dangerous for a multi-process environment such as the UWSGI-based setup we use in production.  To fix both of these issues, we should switch to using the Django caching framework in django-tutelary (https://github.com/Cadasta/django-tutelary/issues/32) and should then set up memcached-based caching in production.

**Comment by amplifi** [comment]
Memcached instance is up and running on staging.

**Comment by amplifi** [comment]
Live in demo and prod.

**Comment by oliverroick** [comment]
Can we close it then, or is there more to do?

**Comment by amplifi** [comment]
@oliverroick Good to close from my side; @ian-ross ?
