### ISSUE TITLE
Catch jsonattrs KeyError

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#715]
### Steps to reproduce the error

This one is hard to reproduce, maybe @dpalomino can clarify what he did before project broke. 
### Actual behavior

An internal server error is returned when accessing the project.

Error log:

```
Internal Server Error: /organizations/david-org-second-org/projects/jei-testing/

KeyError at /organizations/david-org-second-org/projects/jei-testing/
'close_railroad_details'
```
### Expected behavior

The exception should be caught and an appropriate error message should be presented to the user.

**Comment by dpalomino** [comment]
Hi @oliverroick, sorry for the late replay. 

There was a change in the partner's questionnaire (removing one field, and adding others). I guess removing the field caused this to fail. I will email to you the questionnaires by mail now (due to partner's privacy). 

Cheers!
David

**Comment by oliverroick** [comment]
I have been staring at this for a bit now. The exception happens when a record is created with a questionnaire and another questionnaire that is missing a field is uploaded after that. 

As far as I can tell, there is no way of actually solving this problem. The issue will go away after we blocked questionnaire updates for projects that already have data. For the time being we can only display a message like "You can't see the object because the questionnaire is out of date”, which is something I would not recommend, simply from a user experience perspective. It makes some projects useless and it’s our fault because we didn’t design and implement necessary constraints.

I could extract the code to prevent uploading to questionnaires from my feature branch into to separate PR, which we can roll-out sooner.

**Comment by oliverroick** [comment]
We will prevent uploading new XLSForms when a project has data; this will solve the issue.
