### ISSUE TITLE
Add DigitalGlobe Vivid Layer and options with OSM to Basemap Options

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#716]
There are multiple imagery layers we have access to through our DigitalGlobe subscription. The one we currently used is the most current, but unfortunately sometimes that means it is cloudy. 

Let's add the "Vivid" layer which is the best imagery available for a area. 

digitalglobe.n6ngnadl is the key for the "Vivid" layer
digitalglobe.nal0g75k is the key for the "Recent Imagery"
digitalglobe.nal0mpda is the key for the "Recent Imagery with OpenStreetMap"
digitalglobe.n6nhclo2 is the key for the "Vivid Imagery with OpenStreetMap"

Each should be labeled as suggested above. The imagery combined with OpenStreetMap needs to credit DigitalGlobe and OpenStreetMap.

**Comment by seav** [comment]
Hmmm... the current OSM attribution refers to CC-BY-SA. This should be ODbL.

**Comment by seav** [comment]
#493 is tangentially related.

**Comment by wonderchook** [comment]
Good point, we could default to another OSM layer that is coming from our DigitalGlobe agreement.
