### ISSUE TITLE
Canceling adding/editing a location does not work

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#719]
### Steps to reproduce the error

Adding a location:

1. Start adding a location.
2. Click "Save" without adding geometry to force an error.
3. Click "Cancel".

Editing a location:

1. Start editing a location.
2. Delete the geometry by using the "delete" map function.
3. Click "Save" to show the error.
4. Click "Cancel".

### Actual behavior
The cancel button brings you to the same add/edit page.

### Expected behavior
When editing, cancel should bring you to the location detail page. When adding, cancel should bring you to where you were when you brought up the add location feature, or to the project dashboard.

### Cause
This is caused by setting the HTTP referrer to the cancel button. When you get an error, the HTTP referrer is the add/edit location page.

**Comment by seav** [comment]
So half of this bug is fixed (canceling editing a location), but the remaining half (canceling adding a location) isn't. The problem is that we can add a location from practically anywhere in the project due to the big "Add location" button in the project header. The decision now is: when the user cancels adding a location, do we (1) put the user back to page where they clicked the "Add location" button by storing the HTTP referrer somehow, or (2) put the user to the project dashboard page, ignoring the HTTP referrer?

**Comment by clash99** [comment]
I think the HTTP referrer would be helpful so that the user isn't losing their context.

**Comment by seav** [comment]
OK. If there are no objections, I'll try to see if I can somehow store the HTTP referrer when the page is first rendered so that if adding the location encounters errors, we still maintain that HTTP referrer as the URL for the "Cancel" link all throughout.

**Comment by seav** [comment]
**Status:** I currently have working code for this in a branch (**bugfix/#719**), but it currently has a workaround for a limitation in django-skivvy, which I've already [filed as an issue](https://github.com/Cadasta/django-skivvy/issues/15).
