### ISSUE TITLE
Send an email when a user changes the password

### ISSUE THREAD

**Issue by manoramahp** [Cadasta/cadasta-platform#724]
### Steps to reproduce the error
1. Click on user name > Edit profile.
2. Click on Change Password.
3. Change the password.
4. Check your inbox.
### Actual behavior

No email is sent to inform about the password change.
### Expected behavior

An email to inform about the password change should be sent

**Comment by seav** [comment]
Related to #724.

**Comment by hiteshgarg14** [comment]
Hello,
I would like to solve this issue. I will be approaching this issue by using django-sendmail and using PasswordChangeView.

**Comment by wonderchook** [comment]
@hiteshgarg14 can you provide more information. Including what the steps would be as well as proposed text for the email?

**Comment by hiteshgarg14** [comment]
In PasswordChangeView I will define a post function and by using that whenever there will a post request to this view I will use django-sendmail to send a confirmation mail to the related user. 
The format of text for email will be:-

Subject:- Changed Password On {{ site_name }}
Body:- 
You have recently changed your password at {{ site_name }}.
If this was not you then contact us for further information.

Thanks,
The {{ site_name }} Team.

**Comment by oliverroick** [comment]
Hi @hiteshgarg14, thanks for your interest in fixing this issue. We have already two PRs ongoing to fix this issue, one of which will likely be accepted to resolve the issue. You can work on the issue but it's unlikely that your contribution will land in `master`.

**Comment by artiladdha** [comment]
I am interested to working on this issue.So please let me know if it is not solved yet.

**Comment by seav** [comment]
Hi @artiladdha, thanks for your interest in fixing this issue, but we already have an approved PR (#1174) to solve this issue. Please select another bug to work on.

**Comment by artiladdha** [comment]
Okay! Thanks:)
