### ISSUE TITLE
Org Admin should have Administrator role automatically assigned for all projects within organization

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#737]
### Steps to reproduce the error

View an organization administrator member page
### Actual behavior

Dropdowns are available for every project to allow member role assignments
### Expected behavior

If a user is an organization administrator, the should be assigned as administrator to all projects within organization.

<img width="1155" alt="screenshot 2016-09-27 13 56 03" src="https://cloud.githubusercontent.com/assets/1119621/18887694/cdee13b8-84ba-11e6-9833-16ba67c3a593.png">

This is correctly assigned when adding a new project within an organization.  You can see in the screenshot below "administrator" is assigned and no dropdown is present.

<img width="1151" alt="screenshot 2016-09-27 13 56 30" src="https://cloud.githubusercontent.com/assets/1119621/18887699/da759e80-84ba-11e6-9e4e-96f209086b4f.png">

**Comment by kavindya89** [comment]
Hi All,

I have added pull request in https://github.com/Cadasta/cadasta-platform/pull/742. Let me know anything to be changed.

Thank you

**Comment by kavindya89** [comment]
![mypermissions](https://cloud.githubusercontent.com/assets/22070016/18925613/495c1fd2-85d2-11e6-869d-c46af453069f.png)

**Comment by clash99** [comment]
Thanks @kavindya89 for your work on this.

For consistency, this would be better as text-only as displayed on the project permissions page:

![screenshot 2016-09-28 13 12 22](https://cloud.githubusercontent.com/assets/1119621/18926397/43d4f03e-857d-11e6-8997-722fb60f38e4.png)

**Comment by kavindya89** [comment]
@clash99 thank you. I have made necessary changes. Please review whether I need to do any changes

**Comment by kavindya89** [comment]
![done](https://cloud.githubusercontent.com/assets/22070016/18928063/27b1bc0c-85dc-11e6-8119-1c21c8358b9f.png)

**Comment by kavindya89** [comment]
@clash99 I need to adjust some changes. Let me fix them.

**Comment by kavindya89** [comment]
@clash99 is it must have in UI? Once I made changes to display like that, I'm getting some null pointer issues which is due to not submitting any values when user click save.

**Comment by manoramahp** [comment]
@clash99 I've fixed this issue in https://github.com/Cadasta/cadasta-platform/issues/750. Please review and merge.

**Comment by kavindya89** [comment]
@clash99 since @manoramahp fixed the issue. I'll move to another one. Had exam for couple of days. @clash99 thanks you your inputs.

**Comment by seav** [comment]
I have some UI/UX questions for this issue.

So if a member is to be promoted from being an org member to org admin by selecting the "Administrator" option in the Role select form field, do the project roles on the right instantly become static "Project Manager" texts from select form fields? Or do they retain their appearance as select form fields and the server just ignores them when the form is submitted and return the static "Project Manager" text in response?

On the other hand, if the member is to be demoted from being an admin to a regular member, shouldn't the static "Administrator" (should really be "Project Manager") texts become select form fields? Otherwise, you need to update the member's permissions twice if you want to demote them from being an org admin, and also demote them from being a project manager in all/some of the projects.

**Comment by clash99** [comment]
So looking back at the wireframes, there should be a modal that appears immediately after changing the "Role" selection.  @kavindya89:  I know this expands the scope of this task.  Would you be up for giving it a go?  If not, I completely understand.

Take a look at the wireframes and let me know if you can follow the flow or if you have any questions.  Again if this is more time than you can commit, just let me know.

![screenshot 2016-10-07 09 45 40](https://cloud.githubusercontent.com/assets/1119621/19195094/a1cfce08-8c75-11e6-9342-feb1bb9951d0.png)
**Screen 1** - Member Permissions Page with Role = Member.  Save/ Cancel buttons should be under table on right.
**Screen 2** - Member Permission Page with Role = Administrator.  Basically a list of projects on right with "Administrator" text (as you have already done).

![screenshot 2016-10-07 09 46 16](https://cloud.githubusercontent.com/assets/1119621/19195093/a1bc6c00-8c75-11e6-90aa-fbf0cced5db6.png)
**Confirmation modals** after selection from "Role" dropdown has changed.  In production, confirmation buttons on modal are actually on right.

![screenshot 2016-10-07 09 46 28](https://cloud.githubusercontent.com/assets/1119621/19195095/a1dacfce-8c75-11e6-9ea7-806e52016f7f.png)
**Confirmation modal** that should appear "Remove member" button has been selected.

**Comment by kavindya89** [comment]
@clash99 Thank you for detailed wireframes. They are very clear, If you can give me a couple of days as I'm working on outreach proposal. I definitely can con continue the work on this issue. Hope it would be fine.

**Comment by clash99** [comment]
@kavindya89:  Thanks for your willingness to take on the extra work.  The time frame is perfectly fine.  Please let me know if you have any questions.

**Comment by kavindya89** [comment]
@clash99 thanks, extremely sorry for the delay. Had to complete few assignments. I'll look into this from today. Will get back if I need any clarification.

**Comment by kavindya89** [comment]
@clash99 while I was working basically we need to have a custom information message based on the role assignment right? When user move from administrative to less privilege role we need to indicate it saying these privileges are going to remove and vice versa.

**Comment by clash99** [comment]
@kavindya89 yep, basically informing the user that moving forward with the role change will affect the permissioning on the right.  We can also move the "Save" button back to the right side only since it won't be needed for the left column anymore after these changes.

**Comment by kavindya89** [comment]
@clash99 thanks for the clarifications!

**Comment by clash99** [comment]
Hi @kavindya89 - I'm looking forward to meeting you for your internship - congratulations!

Thank you for your work on this but we are going to go ahead and work on this internally for the upcoming sprint.  Let me know if you have any questions.
