### ISSUE TITLE
Can't add a resource in a location uploading a file 

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#754]
### Steps to reproduce the error
(seen on staging) 

1.  Open an existing location 
2. Go to resources tab
3. Try to attach a new resource *uploading* a file (choosing it from library works fine)
4. When clicking on "Upload new" you're automatically redirected to "Attach from library"

Video here: http://screencast.com/t/XdI86pUqi

Note that this issue is not happening for parties, only for locations. 

### Actual behavior

Not possible to upload new resources for a location

### Expected behavior

It should be possible to attach new resources uploading files.

**Comment by kavindya89** [comment]
@dpalomino added fix in https://github.com/Cadasta/cadasta-platform/pull/757. Please review and let me know if I need to change anything. 
I have attached screen-shot as well

**Comment by kavindya89** [comment]
![myscr](https://cloud.githubusercontent.com/assets/22070016/19019794/18722e52-88b1-11e6-9882-e13b00fa0722.png)
