### ISSUE TITLE
When user has no full name empty space there on top of that users' username in organization member side menu

### ISSUE THREAD

**Issue by kavindya89** [Cadasta/cadasta-platform#758]
### Steps to reproduce the error

Add a user without a full name
Go to organization and add him as a member and go to organization page again

### Actual behavior

Empty space on top of user name

### Expected behavior

If full name is not present show user name
![bug](https://cloud.githubusercontent.com/assets/22070016/19020212/e505531e-88bf-11e6-9225-d84c0e4923d8.png)

**Comment by kavindya89** [comment]
Hi @oliverroick @ian-ross 
I have added a fix. Please review.

**Comment by kavindya89** [comment]
![bug2](https://cloud.githubusercontent.com/assets/22070016/19020262/a6e31b0a-88c1-11e6-951b-2b21832399e3.png)

**Comment by clash99** [comment]
Can we reverse the username and full name so that it won't be as strange if they don't have a username? 

![screenshot 2016-10-05 13 59 16](https://cloud.githubusercontent.com/assets/1119621/19127283/f2a57d50-8b03-11e6-9ee4-e4d6fefb02a8.png)

**Comment by seav** [comment]
@clash99, I agree. Since the username is always present, and the full name is optional, it makes sense to show the username first and only have an optional second line for the full name.

**Comment by kavindya89** [comment]
@clash99 @seav sure I will do that

**Comment by kavindya89** [comment]
@clash99 @seav updated pull request with requested changes.

**Comment by kavindya89** [comment]
![screen123](https://cloud.githubusercontent.com/assets/22070016/19140042/2779bfde-8ba7-11e6-982e-acb4ff78eac3.png)

**Comment by kavindya89** [comment]
![screen234](https://cloud.githubusercontent.com/assets/22070016/19140058/44dd4276-8ba7-11e6-9224-69d807ec784f.png)

**Comment by ian-ross** [comment]
Fixed by #809
