### ISSUE TITLE
When adding new members to the organization, you can see archived projects

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#763]
### Steps to reproduce the error
- Login as an organization admin
- Archive a project
- Add a member to the organization
- See the archived project in the project permission list

### Actual behavior
- You select permission levels for archived projects.

### Expected behavior
- Not sure. If you're a member of an organization you have access to all projects, and an archived project still technically exists. Should we quietly assign default permission to archived projects, and just not display the option to the organization admin?

**Comment by dpalomino** [comment]
I agree, I would say better not to list the archived projects and assigning "Public User" permissions by default. It could be a bit confusing to list the archived projects.
