### ISSUE TITLE
Party list and add party pages are unused

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#768]
We currently have a URL and a template for the party list page as well as for the add party page. But the website do not currently provide a path to these pages. Should we delete these pages or still maintain them for possible future use?

**Comment by clash99** [comment]
I think those will be used in the future since we haven't fully developed the records section yet.  But I have a similar question about some of the pages I found when going through all the forms.  There are a handful under the account section that I couldn't find meaning for.  Off the top of my head:  
- registration_form.html
- logout.html

**Comment by clash99** [comment]
Assigning to myself to move forward with integrating party index into project subnav.

**Comment by clash99** [comment]
Added party index into project subnav.  I think we may want to enhance this page in the future similar to resource index.  Perhaps add # of relationships for each party, date added, other useful info? (future sprint)

<img width="534" alt="screenshot 2016-12-01 15 47 38" src="https://cloud.githubusercontent.com/assets/1119621/20814462/54d54994-b7df-11e6-98fe-75d3aafb67d6.png">
<img width="1361" alt="screenshot 2016-12-01 15 47 49" src="https://cloud.githubusercontent.com/assets/1119621/20814463/54da1ff0-b7df-11e6-80cc-d8edad496a39.png">

**Comment by seav** [comment]
While the party list page is now linked from the sidebar, the add party page is still unused. Adding this page should also be done as part of resolving #973.

**Comment by clash99** [comment]
@seav  - Is this adding parties in context to a relationship or a location?  Or just adding parties to a project?

**Comment by dpalomino** [comment]
We think this is no longer relevant with the map interactions work that is ongoing. Please reopen if needed.
