### ISSUE TITLE
Organization Dashboards with no information aren't very exciting...

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#769]
### Steps to reproduce the error

Go to an organization page without a description or contact information.
<img width="1019" alt="screen shot 2016-10-04 at 9 13 08 am" src="https://cloud.githubusercontent.com/assets/8128188/19075410/ca130a84-8a12-11e6-994e-ae97eaa35084.png">
<img width="1280" alt="screen shot 2016-10-04 at 9 10 51 am" src="https://cloud.githubusercontent.com/assets/8128188/19075411/cb8a8040-8a12-11e6-9cfd-3c2958cb2342.png">
### Actual behavior

Since we're no longer displaying members to non-permissioned users, there's a lot of wasted realty.
### Expected behavior

Something? Anything? I don't know if this is really a bug since someone actually using the platform would probably bother putting in a description and contact information...

**Comment by clash99** [comment]
Initially we were thinking we would be able to show some stats or an overview type of map for the organization.  Are there other stats that we could offer at this point to enhance the user experience?  At a minimum we should add a reusable snippet on the right the provides unregistered users information about the benefits of registering and a link to the registration form.  Other ideas?

![screenshot 2016-10-04 08 46 40](https://cloud.githubusercontent.com/assets/1119621/19076618/2e77e322-8a0f-11e6-8c39-77d6d3202034.png)

**Comment by clash99** [comment]
This page will be replaced with a new organization overview for non-registered members and a new organization dashboard for registered users. This is part of the new project data design project. I think we can close this task.
