### ISSUE TITLE
Option to add new organization when creating new project

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#772]
When adding a new project, if you only belong to one organization it is pre-selected.  What if I wanted to add a new organization?  Should we be providing users something similar to adding a new party when adding a relationship to a location?

This is a low priority because it would only affect users creating new projects.

**Comment by seav** [comment]
Adding a new organization while adding a new project would be quite complicated. Adding a new organization entails a lot of stuff (like assigning member roles) compared to adding a new party.

Besides, when you get to Step 3 of the add project wizard, you are then supposed to assign project roles to organization members. But at this point, the new organization would not have been created yet (remember, you can still go back to Step 2 and select another organization) and so there would be no members to assign project roles to.

I think the proper way would be for the user to create a new organization first before creating a new project.

**Comment by clash99** [comment]
I agree but I think we are missing some user messaging.  Its not obvious that you need to create an organization before creating a project so we should add some help text here.  There is an upcoming project to do this across the platform so I'm going to note this for @bethschechter and mark this closed.
