### ISSUE TITLE
Safari is auto-filling project name with contact name

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#773]
### Steps to reproduce the error

When creating a new project, Safari is offering contact autofill for project name.

### Actual behavior

Adds option to autofill with contact name.

### Expected behavior

We should provide that autofill option for contact section below, not project name.  We should make sure field names/types aren't conflicting with auto-fill options to prevent inaccurate data entry.

![screenshot 2016-10-04 09 20 46](https://cloud.githubusercontent.com/assets/1119621/19078075/8ccd5466-8a14-11e6-93f4-43abc06cc1cb.png)

**Comment by seav** [comment]
Is this a Safari-only thing? If so, is this something that we should really be worrying about? Is there a documentation on how and when Safari decides to autofill form fields?

**Comment by clash99** [comment]
I don't think anyone is too worried about it :) 

I did a little research on this bug and it appears to not be easily fixed without a lot of unnecessary trickery.  I'm going to note I don't recommend fixing and mark this issue closed.
