### ISSUE TITLE
Increase length of choices tab labels in questionnaires from 200 chars to 2500 chars

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#775]
We had some issues with long descriptive labels included in the choices tab for XLSForms (specially for multi-language). It would be useful to increase this limit up to 2500 chars (the same that we did for labels in survey tab in issue #659).

**Comment by dpalomino** [comment]
@amplifi @linzjax  Do you know if it's possible to increase this limit?

**Comment by linzjax** [comment]
It's really easy, it would just take a small migration. Is it worth trying to throw that in this week as well?

**Comment by ian-ross** [comment]
This is no longer relevant: the choice labels are now stored as JSON fields, so there's no length limit imposed by us.
