### ISSUE TITLE
Resource download filenames

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#778]
### Steps to reproduce the error
- Add a resource with a user-friendly name to a project.
- Go to the resources view and download the resource.
### Actual behavior

The file is downloaded with the random S3 key name.
### Expected behavior

The file should be downloaded with the user-friendly name.

**Comment by oliverroick** [comment]
So S3 sets the `Content-Disposition` header to the S3 file name, which is preferred to the `download` attribute value. Unless there's a way the set S3's `Content-Disposition` to `inline` we're out of luck with this one.

**Comment by ian-ross** [comment]
I can think of another way of doing it, but you're not going to like it.  How about changing django-buckets so that when you upload a file, it makes a random key, but uses that to make a *directory* to put the file in under its original name, and *not* the actual filename.  So if you upload `foo.pdf`, it gets stored in `s3://my-bucket/random-key/foo.pdf`.  Then when you download, it comes down as `foo.pdf`, not `random-key.pdf`.  Feel free to tell me where to stick my "extra level of indirection" idea, because migrating all the existing storage to the new scheme would be horrible, but I think it would work.

**Comment by amplifi** [comment]
As @oliverroick asked above, you can override Content-disposition and set to inline. See https://www.bennadel.com/blog/2696-overriding-content-type-and-content-disposition-headers-in-amazon-s3-pre-signed-urls.htm
