### ISSUE TITLE
Integrate language translation option

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#78]
Provide users a way to change language option upon entering platform.

- Users should be able to select language without being logged in.  
- Logged in users should have language preference saved as part of profile.

**Comment by wonderchook** [comment]
We should also detect the user's language preference as well if they aren't logged in an if we have that language use it.

**Comment by clash99** [comment]
Currently we have an option to change languages in the footer.  As a future enhancement we want to add the option to save as part of the user profile.
