### ISSUE TITLE
Geometry editing: cancel prevents further editing

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#781]
### Steps to reproduce the error

- Select a location (a polygon is easiest) and select "Edit location".
- Drag the corners of the polygon around a bit.
- Hit the geometry editing "Cancel" button.

### Actual behavior

The geometry edits are reverted, and you end up in the "Edit location" view with geometry editing disabled, so there's no possibility of continuing to modify the geometry.

### Expected behavior

The geometry edits are reverted, you remain in the "Edit location" view, and geometry editing is still possible.  This means that you can make some edits, revert them, make some more edits and save them without leaving the "Edit location" view.

**Comment by seav** [comment]
You can still edit the geometry: just click on the "Edit" button to enable Leaflet.draw's edit mode again.
