### ISSUE TITLE
Add support for select_multiple attributes to data import

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#791]
### The issue

PR https://github.com/Cadasta/cadasta-platform/pull/756 added support for `select_multiple` attribute types to questionnaires. The CSV importer should support these attribute types as well.

**Comment by dpalomino** [comment]
Agreed with Brian to move this to Sprint 11.

**Comment by dpalomino** [comment]
Moved back to S10. Only a minor tweak is needed. Importing select_multiple fields works now if separated by blanks, we will be adding also commas for this.
