### ISSUE TITLE
Fixed user roles and permissions

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#8]
Fixed permissions policies for stereotyped user roles (“roles” have a policy assigned to them with a particular set of permissions):
* Super user (SU): An administrator of the platform. SUs should be able to to access all data and perform any actions.
* Organisation admin (OA): Works directly with organisations and communities. Can create new organisations and projects and has wide-spread permissions to access and act on objects. Appoints PM(s). Is appointed by a SU or other OA.
* Project Manager (PM): Works in-field on specific projects. Can access and act on objects assigned to a project (parcels, relationships, parties). Is appointed by OA. Appoints DC(s).
* Data Collector (DC): Works in-field with the communities mostly using their mobile phone. Can add, edit, import, or review data in a project (parcels, relationships, parties). Is appointed by PM.
* User (USER): Public users. Don’t need to sign up. Can access public information only.

**Comment by wonderchook** [comment]
**Super User**: A platform administrator, very few people would have this type of access. Has access to all organizations and all projects. Would be held by few Cadasta team members. 

**Organization Administrator**: 
- Can create projects
- Has access to all projects in an organization (both public/private)
- Can add users to the organization and to a project
- Can edit organization information
- Has project manager permissions for all projects. 

**Project Manager**:
- Only has explicit access to projects within an organization. 
- Can add users to projects where they are a manager. This adds those users to the organization. 
- Can perform data verification
- Can run reports

**Data Collector**:
- Able to add data and resources
- Can edit data and resources, when data is edited its status goes back to needing verification. 

@nastynoel + @fhpichel am I forgetting other steps these positions would do?

**Comment by nastynoel** [comment]
Kate – are these the only user roles we’re enabling, or are we providing
the flexibility to customize roles and permissions depending on user needs?



*From:* Kate Chapman [mailto:notifications@github.com]
*Sent:* Tuesday, 1 March 2016 8:23 AM
*To:* Cadasta/cadasta-platform <cadasta-platform@noreply.github.com>
*Cc:* nastynoel <ntaylor@cadasta.org>
*Subject:* Re: [cadasta-platform] Fixed user roles and permissions (#8)



*Super User*: A platform administrator, very few people would have this
type of access. Has access to all organizations and all projects. Would be
held by few Cadasta team members.

*Organization Administrator*:

   - Can create projects
   - Has access to all projects in an organization (both public/private)
   - Can add users to the organization and to a project
   - Can edit organization information
   - Has project manager permissions for all projects.

*Project Manager*:

   - Only has explicit access to projects within an organization.
   - Can add users to projects where they are a manager. This adds those
   users to the organization.
   - Can perform data verification
   - Can run reports

*Data Collector*:

   - Able to add data and resources
   - Can edit data and resources, when data is edited its status goes back
   to needing verification.

@nastynoel <https://github.com/nastynoel> + @fhpichel
<https://github.com/fhpichel> am I forgetting other steps these positions
would do?

—
Reply to this email directly or view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/8#issuecomment-190402634>
.

**Comment by wonderchook** [comment]
@nastynoel these are simply the initial user roles we are going to release. The permissions system is built so we can do custom roles as a release at some point or simply add other defined roles if they are needed.

**Comment by seav** [comment]
> A user that makes an organization is initially an organization administrator
Isn't it that super users are the ones that can create an organization? If so, then the super user will then assign an existing user account to have the org admin role.

**Comment by wonderchook** [comment]
@seav sorry that is not clear at all. So any user should be able to make an organization. The reason for this is a new person should be able to sign-up for Cadasta and then create an organization to start a project without a human at Cadasta getting involved.

**Comment by seav** [comment]
@wonderchook, I understand. I guess in the future we would then need a policy or technical measure to prevent spam organizations and to eventually delete or clean-up dummy/sandbox/spam organizations.

An alternate option is that we could provide a sandbox platform instance where interested people can play around. The problem with this one is there may be a need to migrate data to the actual platform.

**Comment by wonderchook** [comment]
@seav yeah, I think we are going to have pretty typical issues with that. People get really creative. On Geocommons people used to upload a single point that was a business as spam for example. 

I think at some point we will want to be able to migrate data between instances of Cadasta. I could imagine for example a government having a hosted instance and then publishing their open data to the main cloud hosted Cadasta instance. I think that will be a ways off on the roadmap though.

**Comment by ian-ross** [comment]
Closed by #88, at least for now.
