### ISSUE TITLE
Malware Prevention for Documentation Files

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#80]
Data type support – in light of known vulnerabilities of various file formats (such as jpeg or pdf), it will be incumbent on the Grantee to implement preventive or detective controls such as routine malware scans to ensure files loaded onto the database do not contain malware

**Comment by wonderchook** [comment]
@amplifi nothing we have to do right now but a due diligence task related to our grant at some point is figuring this out.

**Comment by amplifi** [comment]
ClamAV scanning of file uploads can be implemented as part of resource-handling process. It'd be best to add this as a post-processing step in an async workflow decoupled from the platform, i.e. resource still uploads directly to S3 using django-buckets, SQS triggers file scan, 'safe' files trigger post-processing (thumbnail generation, data import, etc), 'unsafe' files trigger quarantine/alert/user flag.

**Comment by amplifi** [comment]
File upload processing to include security scanning as implemented under #490 -- progress will be tracked via that issue.
