### ISSUE TITLE
Deleted records are not detached from resources

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#803]
### Steps to reproduce the error

Create a record (project/location)
Attach a resource
Delete the record
Go to the resource list
Try to view the resource
### Actual behavior

Get a shiny `<model> matching query does not exist.` error message
### Expected behavior

Should still be able to see the resource, it's just no longer attached to the model

**Comment by linzjax** [comment]
This a regression caused by deferring attributes for parties and spatial_units. I've got a fix for it in the works.

**Comment by dpalomino** [comment]
Already fixed. Closing issue.
