### ISSUE TITLE
Automatic calculation of a polygon area (for project locations)

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#811]
(Editing to include requirements on top) 

Hi, 

I'm trying to recap here the requirements for this feature. In the first stage we will be only considering location areas and not boundary lengths for polylines. Polylines are far less frequent and perimeter length information has not been required by any partner. 

I'm just compiling the requirements taking into account all of your contributions (thanks!)

**User Stories** 
1. As a user, I want to see the area and length of each of the locations of the project calculated based on their geometry. 
2. As a user, I want to see in the project dashboard the total project area as a sum of the location areas for all the geometries in the project

**Details** 

1. Calculation of the location area will be done each time the geometry is modified 
2. The location area will be stored in the database to avoid performance issues of having to recalculate everything when the location is queried. Up to performance/implementation convenience to store both imperial and metric values, or just metric and calculate imperial values from metric ones. 
3. Areas will be presented in both metric and imperial units, and they will not be subject to l10n (for an easier implementation)
4. Metric units: 
   - For areas smaller than 1000m2 (i.e. 0.1ha), m2 will be used
   - For areas greater than 0.1ha, ha will be used
5. Imperial units: 
   - For areas smaller than 4356 ft2 (i.e. 0.1 acres), ft2 will be used
   - For areas greater than 4356 ft2, acres will be used
6. Two decimal figures would be used
7. Project area will be presented in the project dashboard as described in the wireframes (thanks @clash99)
8. Location area are will be presented in the location details as it is described in the Map Interactions wireframes (again thanks @clash99) 
9. Location areas will be exported either with project downloads or search exports

----

I don't know if this would something easy to calculate. I've found a similar discussion [here](http://gis.stackexchange.com/questions/171319/given-a-geojson-file-how-do-i-calculate-the-area-of-the-embedded-features).

**Comment by dpalomino** [comment]
Some ideas about how this could work. I think this information could be shown when opening a location, under the Overview tab. I think we could show information regarding: 

- For polygons: area enclosed (in hectares?), perimeter (in kilometers?)
- For lines: length of the line (in kilometers?)

A plus would be to can show the information in different units depending on the size (i.e. area in hectares only if it's larger than 1 ha, otherwise in square meters; length/perimeter in kilometers only if larger than 1km, otherwise in meters). 

It would be desirable also to store this in a spatial unit field, so it will be also available when downloading the project data.

Thoughts?

**Comment by wonderchook** [comment]
Should we think about people being able to localize their unit of measure?

**Comment by seav** [comment]
I suggest just picking the most appropriate magnitude of units based on the area/length of the geometry and showing both the metric and imperial values. Sorta like "65.5 ha / 161.9 acres", "12.3 km / 7.6 mi", or "350 m / 1148 ft". This is assuming that almost all people are familiar with either the metric or imperial system and they are not using any indigenous system. I think this is a reasonable assumption because I assume that the data our partners are collecting is meant to be presented or used outside the community and therefore standardization with the metric/imperial system is paramount.

**Comment by seav** [comment]
> It would be desirable also to store this in a spatial unit field, so it will be also available when downloading the project data.

This should be the case. We don't want to calculate the area/length every time this value is needed. We only calculate the measure every time the geometry is created/updated and then cache it in the database.

**Comment by dpalomino** [comment]
Thanks a lot for the input. @seav, I think you had a great idea for showing both metric and imperial units, so we don't need to localize.

**Comment by dpalomino** [comment]
Hi, 

I'm trying to recap here the requirements for this feature. In the first stage we will be only considering location areas and not boundary lengths for polylines. Polylines are far less frequent and perimeter length information has not been required by any partner. 

I'm just compiling the requirements taking into account all of your contributions (thanks!)

**User Stories** 
1. As a user, I want to see the area and length of each of the locations of the project calculated based on their geometry. 
2. As a user, I want to see in the project dashboard the total project area as a sum of the location areas for all the geometries in the project

**Details** 

1. Calculation of the location area will be done each time the geometry is modified 
2. The location area will be stored in the database to avoid performance issues of having to recalculate everything when the location is queried. Up to performance/implementation convenience to store both imperial and metric values, or just metric and calculate imperial values from metric ones. 
3. Areas will be presented in both metric and imperial units, and they will not be subject to l10n (for an easier implementation)
4. Metric units: 
   - For areas smaller than 1000m2 (i.e. 0.1ha), m2 will be used
   - For areas greater than 0.1ha, ha will be used
5. Imperial units: 
   - For areas smaller than 4356 ft2 (i.e. 0.1 acres), ft2 will be used
   - For areas greater than 4356 ft2, acres will be used
6. Project area will be presented in the project dashboard as described in the wireframes (thanks @clash99)
7. Location area are will be presented in the location details as it is described in the Map Interactions wireframes (again thanks @clash99) 

Sounds good? Am I missing something?

**Comment by seav** [comment]
How many significant figures or decimal places should be shown when displaying area values?

**Comment by seav** [comment]
I also assume that the area values also need to be included in the project/search export as an additional column?

**Comment by dpalomino** [comment]
Good point @seav, thanks for the heads-up. I think with two decimal figures would be enough. And yes, we need to include them in the project/search exports....

**Comment by SteadyCadence** [comment]
Just curious, where are the measurements going to be viewed on the GUI?  Will it be a field/value on the location attributes?  Or a number on the polygon in the map?

**Comment by dpalomino** [comment]
Hi @SteadyCadence 

In the [Map Interactions wireframes](https://drive.google.com/open?id=0BzpiEtMtHC3rTXktREpOdU5uZzQ) (for instance look at page 5), close to location type.

**Comment by SteadyCadence** [comment]
Ah gotcha.  Didn't see that before.  Will that field be read-only?

I am wondering if there will be instances where the measurement is a little off and someone needs to adjust the measurement manually?

**Comment by dpalomino** [comment]
It would be read only I think, the other option I guess would be difficult to handle. Partners I think can include an additional area field for registering other areas (like those in deeds etc)....

**Comment by wonderchook** [comment]
I don't think they should be able to change the area measurement that is automatically calculated. They would need to use another field if they were going to manual enter areas.
