### ISSUE TITLE
Import tool fails to import tenure_relationship_attributes

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#812]
### The issue

Imports against schemas which have `tenure_relationship_attributes` defined currently fail. 

### Expected behavior

The import tool should be able to import `tenure_relationship_attribute` fields from the import csv.

**Comment by dpalomino** [comment]
I'd suggest to try to to do this in milestone 10...

**Comment by dpalomino** [comment]
Tentatively assigned for Sprint 10.
