### ISSUE TITLE
[Import] improve handling of required fields in imports

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#813]
### The issue

At the moment the user is required to manually map the schema required fields to columns in the import csv. This happens in the third step of the import wizard (see below):

![wizard_step_3](https://cloud.githubusercontent.com/assets/3308136/19269121/7a98883c-8fb0-11e6-8337-a740e5689242.png)

Instead, we should mandate that the `CSV` contains all the required fields, eg `party_name`, `party_type`, `tenure_type` and `location_type`.

This would improve the flexibilty of tool and enable the import of any type of party or location in a single import.
### Actual behavior

Currently the user is required to map the incoming columns in the `CSV` to the required fields in the schema.
### Expected behavior

The `CSV` should contain columns which are named for the required fields in the project schema. The import tool should handle the import of these fields automatically and report errors correctly if these fields are missing from the import.

**Comment by wonderchook** [comment]
I don't agree with this. I think instead if the user has the required fields then it should automatically map them, but we shouldn't expect people to change their data to fit into the import wizard. Eventually we'll want to get things to the point where people can just import data without too much manipulation.

**Comment by bjohare** [comment]
or that, but either way the 'party_type' and 'location_type' fields are not optimal and need to be changed to point to the import column containing this information. At the moment we're restricting the import to one party or location type.

**Comment by wonderchook** [comment]
Ah that makes sense. @dpalomino I think this would relate to people being able to choose their own types.

**Comment by bjohare** [comment]
@wonderchook my thinking was that the user has defined the schema anyway so the import would/should probably contain those required fields, in which case we could simplify the third step.. but I suppose that might not hold in all cases..

**Comment by dpalomino** [comment]
Yes, that was the reason @wonderchook. We were limited to import one party or one location type so including this in the csv will allow us to import all types of party_type and location_type, and not having to split the csv per types.

**Comment by dpalomino** [comment]
Agreed to move this to Sprint 11.
