### ISSUE TITLE
Ansible error

### ISSUE THREAD

**Issue by eomwandho** [Cadasta/cadasta-platform#82]
I keep getting this [error](https://gist.github.com/eomwandho/6c5e0e1ca0b8f9a27bbf) when running vagrant up. Even after doing vagrant destroy and deleting the env/ folder.

What could be the issue

**Comment by eomwandho** [comment]
I think this issue has been fixed in [0.4.1 ](https://github.com/sunscrapers/djoser/issues/101)

**Comment by ian-ross** [comment]
I wouldn't worry about it. It's just a deprecation warning. We can update to the newer version of djoser to make it go away. We just need to check what other changes have been made to djoser: from the commit log, it all looks pretty benign. You could try upgrading to the latest version (0.4.3) and seeing whether all our tests still work. (I'll do that on Monday if you don't get to it before me.)

**Comment by wonderchook** [comment]
@eomwandho + @ian-ross did either of you get a chance to try the upgrade? (I don't think this is urgent, just was going to close the ticket though if it wasn't pending)

**Comment by ian-ross** [comment]
Fixed at some point: djoser is now at 0.4.3.

**Comment by eomwandho** [comment]
After the upgrading djoser, the error no long shows.
