### ISSUE TITLE
Missing API endpoints

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#822]
The API is currently missing the following API endpoints, which need to be implemented:
- [ ] `/organizations/<organization>/projects/<project>/spatialresources/<resource_id>` to access, update and delete spatial resources
- [x] `/organizations/<organization>/projects/<project>/spatial/resources/` to list and create resources for spatial units
- [x] `/organizations/<organization>/projects/<project>/spatial/resources/<resource_id>` to access, update and delete resources for spatial units
- [x] `/organizations/<organization>/projects/<project>/parties/resources/` to list and create resources for parties
- [x] `/organizations/<organization>/projects/<project>/parties/resources/<resource_id>` to access, update and delete resources for parties
- [x] `/organizations/<organization>/projects/<project>/relationships/tenure/<tenure_rel_id>/resources/` to list and create resources for tenure relationships
- [x] `/organizations/<organization>/projects/<project>/relationships/tenure/<tenure_rel_id>/resources/<resource_id>` to access, update and delete resources for tenure relationships

**Comment by linzjax** [comment]
Do we want to be able to delete resources from this points, or just detach?

**Comment by wonderchook** [comment]
I think just detach for now until we have better logging.
