### ISSUE TITLE
Presentation of records search results

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#829]
Linked to #825 for records search epic. Complete requirements are included [in the wiki](https://devwiki.corp.cadasta.org/Search%20and%20Filtering). 

The locations matching the search query should be presented both on a map and on a list of locations. Wireframes and details being developed.

**Comment by dpalomino** [comment]
Being discussed not to include in the MVP: 
- Pagination
- Filtering capabilities
- Scores 
- Ordering

So in the first stage only a basic page result will be shown.

**Comment by seav** [comment]
@clash99, can you create the search icon on the project sub-navigation bar, similar to [this one](https://github.com/Cadasta/cadasta-platform/blob/59a8d0cfb60f125ce16d20c7ae8027f9df231699/cadasta/core/static/img/icon-parties.png)?

**Comment by clash99** [comment]
@seav Here you go:  
![icon-search](https://cloud.githubusercontent.com/assets/1119621/20983687/fe7eb140-bc82-11e6-9c05-9c55c8a0bbee.png)

**Comment by seav** [comment]
@clash99, awesome! Thanks!

**Comment by dpalomino** [comment]
@seav I guess we are ok to close this issue. Please reopen if needed. Thanks!
