### ISSUE TITLE
Create Test Data Fixtures

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#83]
The data base of a new development VM is empty initially. We should create fixtures with test data for all models available that can be loaded into the data base when required.

**Comment by ian-ross** [comment]
Good idea.  Might we do this as a management command in the server, so it's optional, rather than happening for every new VM instance?  So when you SSH into the VM, before starting the server, you'd just do `./manage.py populate` or something.

**Comment by oliverroick** [comment]
Yes, optional. There's Django's [`loaddata`](https://docs.djangoproject.com/en/1.9/ref/django-admin/#loaddata) management command.

**Comment by ian-ross** [comment]
Doesn't that mean using JSON fixtures?  I thought that wasn't such a good option because keeping them in sync with changing models is annoying.  Do you know of anything for managing fixtures that you create through Python scripts?  Just using factory_boy or something to make and save the instances?

**Comment by oliverroick** [comment]
Good point. Another option is implementing [custom management command](https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/) that uses factory_boy. 

Something like `manage.py createsampledata --projects`, which would create project instances and some models that are related, e.g. organizations, users, resources.

**Comment by ian-ross** [comment]
That's exactly the sort of thing I was thinking of.  And as you say, having it as that sort of management command will make it easy to have custom datasets, which might be useful for functional testing -- reset the database, load a test dataset, do some tests, repeat for other datasets.

**Comment by ian-ross** [comment]
Some requirements for this:

 - Include names for users using a number of different alphabets (e.g. European names with diacritics, Greek, Chinese, Korean, Arabic, Thai, etc.).
 - Facility to load one of a selection of test datasets.
 - Modular setup so that you can load part of a dataset only (e.g. just users).
 - Initially: users, organisations, projects, permissions data, assignment of users to organisations and projects with varying roles.
 - Eventually also: parties, parcels, relationships, resources, questionnaire data, historical information, etc.

**Comment by ian-ross** [comment]
Moving this back to "In Progress" since Lindsey can start cleaning it up now that most of the reorganisation is done.

**Comment by oliverroick** [comment]
Open issues:

- [ ] Add organization logos to test data fixtures
- [ ] Remove existing audit logs when deleting test data from database

**Comment by ian-ross** [comment]
@linzjax Did you finish the two things listed in Oliver's comment above?

**Comment by linzjax** [comment]
Yes, I did.

**Comment by ian-ross** [comment]
Ah-ha!  And now you've ticked the boxes.  Excellent.  I'll review this tomorrow.  (You should tick the boxes when you do things, to avoid annoying questions from people like me.  Well, let's be honest here, to avoid annoying questions from from me.  There aren't any other people on the team as annoying as me.)

**Comment by ian-ross** [comment]
Hah.  I already reviewed this when I merged PR #138.
