### ISSUE TITLE
Export results from records search query in xlsx format

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#830]
Linked to #825 for records search epic. Complete requirements are included [in the wiki](https://devwiki.corp.cadasta.org/Search%20and%20Filtering). 

We should be able to export the records matching the query in the same format used for downloading the data from a project (in _.xlsx_). 

Wireframes to be referenced.

**Comment by wonderchook** [comment]
I think aspect of the epic might need to be implement in Sprint 11 instead of 10.

**Comment by dpalomino** [comment]
Yep, I think the same. I'm just trying to include all the tasks now to choose which ones will be started in sprint 10 or sprint 11 (same comment applies to the sprint backlog).

**Comment by dpalomino** [comment]
@clash99 and I have been reviewing this topic (thanks Chandra!). 

To be consistent with the "Download Project Data" (see screenshot attached for reference) we should provide the same options to "Export Search Results". Something like: 
- SHP: "A ZIP containing shape files for result locations, relationships, and parties."
- XLS: "A single XLS spreadsheet containing result locations, relationships, and parties."
- Resources: "A zip file containing result resources."
- All Data: "A zip file containing result data XLS, SHP files and resources."

![screen shot 2016-12-28 at 16 29 18](https://cloud.githubusercontent.com/assets/17198051/21525991/3bbfd792-cd21-11e6-87ed-140952d9c23d.png)

**Comment by clash99** [comment]
Design documents have been updated here:  https://drive.google.com/open?id=0BzpiEtMtHC3rVFlVelgzNHBxaUk

**Changes**
- Updated export results modal
- Updated Phase 3 saved search pages
