### ISSUE TITLE
Data import: support for xlsx format used in data download

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#832]
As a project manager, I want to be able to import data that have been downloaded from an existing project in Cadasta Platform. 

That means that we should support the _.xlsx_ format that is used when downloading data from a project in Cadasta platform, containing the _locations_, _parties_ and _relationships_ tabs. 

Not targeted for Sprint 10.

**Comment by manoramahp** [comment]
@dpalomino If I'm not mistaken, Cadasta supports xlsx format though the download option is displayed as XLS.

**Comment by dpalomino** [comment]
Hi @manoramahp, you are right. But we were referring to the possibility to import this downloaded data (with xlsx and the three tabs) into another project in the Cadasta platform.
