### ISSUE TITLE
Nothing happens on clicking the info symbol "i" 

### ISSUE THREAD

**Issue by aakanshavatsa** [Cadasta/cadasta-platform#842]
### Steps to reproduce the error
Go to https://platform-staging-api.cadasta.org/dashboard/
Click on the "i" symbol at the top.

### Actual behavior

On clicking the link, nothing happens. No redirect.

### Expected behavior
Should redirect to some info URL
<img width="1440" alt="cadasta issue" src="https://cloud.githubusercontent.com/assets/9761817/19417465/56b63c42-93cb-11e6-9706-04158bcdf3b1.png">

**Comment by aakanshavatsa** [comment]
Hi @wonderchook, @ian-ross  - Can you'll please let me know if this is an issue in the staging environment so that I can go ahead with a fix.

**Comment by manoramahp** [comment]
@aakanshavatsa 
Please have a look on;
https://github.com/Cadasta/cadasta-platform/pull/802
https://github.com/Cadasta/cadasta-platform/issues/722

**Comment by aakanshavatsa** [comment]
Thanks for the info @manoramahp.
