### ISSUE TITLE
Previews for non-image resources

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#847]
### Steps to reproduce the error
upload a resource that is not an image file.

### Actual behavior
<img width="1168" alt="screen shot 2016-10-17 at 2 34 33 pm" src="https://cloud.githubusercontent.com/assets/8128188/19450321/f3ce8966-9476-11e6-8e28-555ad5d64d30.png">

### Expected behavior
I think that's up for discussion, but maybe a 🎶 or something? How do we want to handle pdfs, or word docs?

**Comment by linzjax** [comment]
Oooor this might be an issue I caused with my mimetype fix. I'll report back.

**Comment by clash99** [comment]
@linzjax - here are the default file icons we have right now:  https://drive.google.com/open?id=0BzpiEtMtHC3rbXRya0FiVVU2bm8

Let me know if you need another one and I can create it.  thanks, chandra
