### ISSUE TITLE
Drawing Tools Do Not Show Up in Safari

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#858]
### Steps to reproduce the error

Using Safari:
1. Go to a project
2. Click "Add Location"
3. Drawing tools do not appear.
### Expected behavior

Would expect drawing tools to show up the same as they do in Firefox and Chrome

**Comment by wonderchook** [comment]
Appears to be an issue with Safari 9.1.3, not an issue with 10.0

**Comment by clash99** [comment]
WIP notes:

- Not a css issue, left controls are not being rendered
- Looking into js but need to do some cleanup since looks like we are calling same file multiple times (see screenshot below)
- I suspect something is going on in draw translation file that is choking Safari  9

**Comment by clash99** [comment]
Looks like this is limited to Safari 9.0 and 9.1 with OSX.

Console error:

![screen shot 2016-10-31 at 3 43 28 pm](https://cloud.githubusercontent.com/assets/1119621/19871104/6e4bfe7a-9f81-11e6-8ca9-611c8ab61005.png)

Without fix (only zooms show):

![screen shot 2016-10-31 at 3 55 27 pm](https://cloud.githubusercontent.com/assets/1119621/19871353/86e8ed2a-9f82-11e6-8993-20cc164085cb.png)


With fix (default draw toolbar):

![screen shot 2016-10-31 at 3 41 52 pm](https://cloud.githubusercontent.com/assets/1119621/19871278/37da9fe4-9f82-11e6-88cc-c55095364788.png)

In all other browsers (custom draw toolbar):

![screen shot 2016-10-31 at 3 42 06 pm](https://cloud.githubusercontent.com/assets/1119621/19871227/0a27e93a-9f82-11e6-91f3-09e715c08fd1.png)

**Comment by clash99** [comment]
@wonderchook:  I've done a lot of research trying to find a complete solution for this bug and haven't found one yet.  Until then I propose showing the default leaflet draw toolbar for Safari 9.0 & 9.1 (right now nothing shows).  The custom toolbar will still show for all other browsers.  Do you have any thoughts on this proposed solution?

**Comment by oliverroick** [comment]
I looked at this and opened PR #889 that fixes the issue and makes sure that the complete toolbar is displayed in Safari < 10.x.
