### ISSUE TITLE
Small screen member list isn't centered

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#859]
### Steps to reproduce the error

[Chrome, Safari, and Firefox - screen width at the final design adjustment for smallest screens]
Go to an organization which you have permissions for.
Go to member list page.
### Actual behavior

<img width="505" alt="screen shot 2016-10-24 at 10 54 01 am" src="https://cloud.githubusercontent.com/assets/8128188/19651183/d6256304-99d9-11e6-80a9-e2a0236edc7c.png">
### Expected behavior

same width as the other data tables.

**Comment by clash99** [comment]
Need to adjust responsive css for this one.

**Comment by clash99** [comment]
WIP comment:  Problem seems to be with datatables.js creating column widths inline.

**Comment by clash99** [comment]
@linzjax:  I couldn't recreate this but I suspect its from the datatables plugin assigning inline widths to columns.  I added css to override this in the smallest (max 400px) resolutions.  Can you check it with branch bug/css-fixes and see if that fixes it?  

I'm going to be review the whole platform today for other wonkiness.  

<img width="378" alt="screenshot 2016-10-27 11 46 29" src="https://cloud.githubusercontent.com/assets/1119621/19776968/c3756a10-9c3b-11e6-9c0d-f62f8174f0f9.png">
<img width="460" alt="screenshot 2016-10-27 11 47 20" src="https://cloud.githubusercontent.com/assets/1119621/19776969/c379984c-9c3b-11e6-8613-2fc44e5d496f.png">

**Comment by linzjax** [comment]
Looks fixed to me! Once the changes are pulled in we can close this.

**Comment by clash99** [comment]
Few other css tweaks included:

- Adjusted css for pelias and geolocate on touch screens to be consistent size as zooms
- Added form-control tag to language dropdown so appears as field on mobile
- Made wizard steps smaller for mobile
- Tightened up subheader on project pages for responsive
- Hid country column on xs screen to remove horizontal scroll on responsive
