### ISSUE TITLE
Need for a new drop-down button for selecting the language in labels

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#861]
We were discussing this in slack, just opening a new issue for continuing the discussion and decide on a solution. 

Right now, when working with forms with multilingual labels (let's say for instance English + Bengali) and this is presented through the web interface, then behaviour is: 
1. When platform is configured in "English (en)", labels are always shown in English
2. When platform is other language (right now only Portuguese), labels are shown in Bengali

But we don't have an option to show the labels in Bengali and the rest of interface in English (as Bengali is not available in the platform). 

To solve this I think we have two alternatives: 
1. As we discussed in slack, to create a new "language" on the existing drop-down menu for displaying everything in English but the labels in the default language (could be named something like "English (en)+Default labels").
2. Create a new drop-down menu close to the existing one to select the language to use for the labels. This drop-down menu would only appear for projects which questionnaires are multilingual. 

Option (1) is likely easier to implement but it could be confusing for the user, and would not cover the case of having English plus two other languages in the forms (that could be a common use case in many countries). 

Option (2) is less confusing for the user and can support as many languages in labels as we'd need. But likely more difficult to implement. 

Thoughts?

**Comment by ian-ross** [comment]
Can someone explain why there appears to be no effort or interest to translate the platform text for these projects?  The solutions suggested above are really extremely poor from a usability perspective.  Why not engage an English-to-Bengali translator for a couple of days to translate everything?  Then we just add Bengali as a language option for the platform, and everything will work seamlessly.

**Comment by dpalomino** [comment]
Hi @ian-ross. I agree with you, the best solution from an UX perspective would be to translate the platform to these languages. But the problem is that we are expecting to work with many different local languages. Bengali was just an example, but there will be many (almost any new partner that we talk with is targeting a new language). Unfortunately I don't think we will able to translate the platform to all those languages in the short/medium term. 

If we opt for solution (2), we can also add the condition of showing the additional drop-down menu only for those projects that contain labels in languages currently not supported in the platform. That would allow that if we are not supporting Bengali now (to continue with this example), there would be an option to show the labels in Bengali today, but if the platform is localized in Bengali in the future, then the additional menu will not be shown.

**Comment by ian-ross** [comment]
I really don't understand the economics of this.  For each partner, there's (at least) some months of preliminary work, there are field visits and training with concomittant staff and travel costs, yet you're saying that there isn't a budget to get translations done?  That makes no sense at all.

Can you explain exactly what you're trying to achieve with the approach you're suggesting?  You really want a site where *all* of the text is in English except for the multilingual strings pulled from the XLS forms?  Who does that benefit?  For someone who reads English, it's just going to be jarring and look weird having all of the site in English except for these things.  For someone who doesn't read English, the site will still be unusable.

**Comment by dpalomino** [comment]
The issue was raised to discuss the best way to handle labels when the platform is not localized in those languages. I would be happy to be proven wrong, but I don't think we will have all languages translated in the platform as we don't have currently an active community of people doing the translations. In any case, when those languages are translated then the additional drop-down menu will not appear. 

There are some users with a basic knowledge of English that are still able to use the platform in English (at least for the basic features), but they have many difficulties understanding the information contained in the records if it's in English (specially in the case of large questionnaires). That's why I thought this kind of approach would be useful. And for those users able to read in English everything would be presented in English, so that should not be a problem. 

So, if we implement something like suggested in option (2), for English+Other_Langugage  behaviour would be: 

1-. If Other_Language is supported in the platform, no additional drop-down menu would appear 
2-. If Other_Language is not supported, then the additional drop-down will be shown showing the different languages (two in this example) contained in the forms for the user to select.

**Comment by dpalomino** [comment]
We're starting to work with more local languages and probably we'd need to implement this soon. Summary was to include a new drop-down menu to select language to use in the labels. 

Ideally we could include this drop-down menu only in the pages where the labels are shown (location detail, party detail, etc), and only if there are languages in labels currently not available in the platform. What do you think @clash99?

**Comment by dpalomino** [comment]
Added to backlog id 62.00.

**Comment by dpalomino** [comment]
Adding @clash99 for wireframes.

**Comment by clash99** [comment]
Below is a proposed placement for this new form language dropdown.  Since this affects viewing form text across various pages within the project, I thought it would best at this project level.  The other option would be sprinkling it through each page next to where the form labels are shown.

![projects-formlanguages](https://cloud.githubusercontent.com/assets/1119621/22261066/23f88c10-e231-11e6-9993-9839fdfae4b2.png)

Please review and provide feedback. Thanks!

**Comment by wonderchook** [comment]
I think the location makes sense. Perhaps @bethschechter can suggest the text.

**Comment by dpalomino** [comment]
I think it is looking great @clash99! Thanks!

Just as a side note, the default language to use in forms is: 
- Currently specified via the XLSForm file (default_language column in the settings tab) 
- It will be specified in the future via the Project Creation Wizard

**Comment by oliverroick** [comment]
I have come closer to a solution for this. There are still a few things that need to be addressed and others where I have no idea what we can do about it. 

For reference, the current state is in branch `feature/language-dropdown`.

## Things I need to address

- Standard fields for entities (the party name and type for instance) do not change the language either. This is because these fields are not created through jsonattrs, hence the labels from the questionnaire are currently not available. I'm going to look into this later this week.
- The dropdown itself needs some CSS love. @clash99, would you be able to look into that?

## Issues that are not solvable to the best of my knowledge

- The questionnaires do not provide any information about the languages that are available. I'm inferring the available languages from the labels of the first field I can find for the questionnaire. That will work most of the time but it's not 100% deterministic; if that first field doesn't define all languages you won't be able to switch to languages that are missing. 
- There are no human-readable labels for the languages in a questionnaire. When I infer the available languages from labels all I get is language codes (e.g., `en`, `fr` or `in`) but not what they mean. There is nothing usable I can add to the dropdown.

**Comment by dpalomino** [comment]
Thanks a lot @oliverroick!

>  The questionnaires do not provide any information about the languages that are available. I'm inferring the available languages from the labels of the first field I can find for the questionnaire. That will work most of the time but it's not 100% deterministic; if that first field doesn't define all languages you won't be able to switch to languages that are missing.

That's enough I think. All fields should contain defined labels for all languages. 

> There are no human-readable labels for the languages in a questionnaire. When I infer the available languages from labels all I get is language codes (e.g., en, fr or in) but not what they mean. There is nothing usable I can add to the dropdown.

We are using [iso-639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), I don't know whether a table with [supported languages](https://github.com/django/django/tree/master/django/conf/locale) could be hardcoded somewhere? If not at least we can provide the iso-639-1 codes (not ideal, but we can assume that partners will be familiar with the codes from the couple of languages they would be using).

**Comment by bethschechter** [comment]
How about:

Select the language you'd like to use on the platform. (Don't worry - you can always change it back!)

For something more formal, how about:

By selecting a language here, you'll change the language used by the platform.

**Comment by clash99** [comment]
@oliverroick - Added CSS for new translation dropdown and also reworked project and organization page-header to prevent overlapping.  I've checked the changes into your branch.  Tomorrow I just need to do a final QA in BrowserStack.

![screenshot 2017-01-31 14 32 04](https://cloud.githubusercontent.com/assets/1119621/22495175/992e03d4-e803-11e6-8cee-b257a337b33d.png)
![screenshot 2017-01-31 14 32 11](https://cloud.githubusercontent.com/assets/1119621/22495174/992d0740-e803-11e6-9a68-0db38487f28f.png)

**Comment by clash99** [comment]
@bethschechter - So this dropdown actually just changes the language in the project form fields if that language is not available in the platform.  The platform language is still controlled by the dropdown in the footer.  Maybe @dpalomino is a good contact for more info if that doesn't make sense.

**Comment by dpalomino** [comment]
For the text, how about something like: "Select the language in which you want to see your project data"?

**Comment by wonderchook** [comment]
Isn't it the actual input though? Maybe something about "Select language of input fields?" okay that sounds terrible, but something like that with then a link to a longer explanation in the documentation that leads people to how to become a translator?

**Comment by bethschechter** [comment]
@clash99 @dpalomino so this is specifically for data? And does it only show languages that are available in the xlsform? Yeah, I'd love a little more information.

**Comment by bethschechter** [comment]
Ok I have clarification from @dpalomino. So how about:

Use this dropdown to select a language from your questionnaire. 
_Want to see more languages on the Cadasta platform? [Learn about translating it here.](https://docs.cadasta.org/en/10-translation.html)_.

**Comment by oliverroick** [comment]
@bethschechter This dropdown only changes the labels of the form fields to collect data, i.e. when you create or edit locations, relationships and parties. The input into the fields itself is not translated. It also does not affect anything else on the platform.

We need this dropdown because the languages available for the platform and the languages defined in an XLSForm can be different, e.g. an XLSForms uses English and Bengali but the platform itself is not translated to Bengali.

**Comment by clash99** [comment]
I believe the help can be added via inlinemanual.  I just need to make sure we can hide it when the dropdown doesn't appear.  I'll look into that today.

**Comment by clash99** [comment]
Looks like we can add the "?" and tooltip text via inlinemanual so we can do this outside the platform code.

**Comment by dpalomino** [comment]
Hi @oliverroick 
> I can create a settings file that lists all the codes and their labels. It will work for many languages. But thinking a bit further down the road and also out of curiosity: What iso-639-1 code is Karen script?

You are right, Karen is iso-639-2 (reference [here](http://www-01.sil.org/iso639-3/documentation.asp?id=kar)). But as it is not supported by django (issue #1009) probably we cannot include it yet until we fix #1009. 

I was saying that maybe we can include the django [supported languages](https://github.com/django/django/tree/master/django/conf/locale), 78 I think, with the corresponding iso-639-1/2/3 codes? Note that in that list there are multiple variations for English, Spanish, etc, so maybe we can just include the generic version of those.

**Comment by oliverroick** [comment]
I have managed to translate the standard fields; the only thing that is left before I open a PR is providing labels for the language dropdown. 

I am, however, not at all happy with the result and I am going to suggest that we are not releasing this feature as it is currently implemented.

As always with anything remotely related to questionnaires, the solution is a patch-work of workarounds that adds code all over the place. However, the main reason for suggesting not to release the feature is that the solution I have implemented is a good as it gets and yet the resulting interface will likely not solve any problems but cause more confusion.

Here's why:

1. Having two dropdowns with different options will confuse users. We'll have to do a pretty good job explaining to our users what this all means. 
2. When you add a relationship, there's a mix of different languages. The dropdown to select an existing party is not defined through the XLSForms; hence there is no translation for some of the labels.
3. In dropdowns of standard fields (for example, the party type) the choice that indicates the "not selected" state is not defined in XLSForms, therefore is not translated. 
4. The geometry field is not named consistently in the XLSForms. There's no way to get the translated label for the field. Therefore I'm not translating it. 

We end up with different languages all over the place. For example, create a project using the standard questionnaire, select Bahasa Indonesia as the primary language and use English for the forms. What you get for the form to create a relationship is this:

![screen shot 2017-02-03 at 17 13 58](https://cloud.githubusercontent.com/assets/159510/22601471/4bdb2ace-ea3f-11e6-9fcf-749080c34557.png)

**Comment by wonderchook** [comment]
@dpalomino do you know if most users set their language on their computers?

Would it be better when people go to add data if the first time during that session we ask them something along the lines of. "The questions for your data entry are in a language not available in the software interface. Would you like to use a different language for this part?"

**Comment by dpalomino** [comment]
Hi @wonderchook @oliverroick 

Yes, most of users are using their own languages. And yes, if we could ask them this question would be more clear I think. We can also of course include this in the documentation and training materials as well. 

Clearly the UI is far from ideal... but the main issue is the partners being able to see their questions and drop-down options in their own labels, and we cannot support all languages that the orgs are going to use. Maybe we can try to improve the help messaging and highlight this during trainings and in the docs but, I think it'd be useful for them to have this. 

@fhpichel, what do you think?

**Comment by wonderchook** [comment]
@oliverroick does the drop down only appear when there is more than one language? Was thinking maybe this doesn't effect that many users.

**Comment by clash99** [comment]
@wonderchook - I'm not sure of the % of users affected, but the dropdown appears when there is a language in the project form that doesn't appear in the platform, and the user also has to have a platform language selected that doesn't appear in the form.  For example in this screencast, you don't see the dropdown with English selected, but once you select French (which isn't available in the project form) you have the option of translating to another language.  https://screencast.com/t/D4sWbYCE2R4K
