### ISSUE TITLE
Standard questionnaire making platform error for new projects

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#862]
### Steps to reproduce the error

Create a new project and try to use standard questionnaire on wizard page 2 (https://s3-us-west-2.amazonaws.com/cadasta-resources/sample-forms/standard_cadasta_questionnaire.xlsx).

### Actual behavior

After completing wizard page 3, select finish button and receive a Platform error.

### Expected behavior

Would expect to be dropped off at project overview page for newly created project.

<img width="577" alt="screenshot 2016-10-24 13 48 03" src="https://cloud.githubusercontent.com/assets/1119621/19659200/b166dc3e-99f0-11e6-90ca-df3ae3d951a1.png">

**Comment by dpalomino** [comment]
I think there is a syntax error in the standard questionnaire. In "choices" tab, rows 37 and 38 (geoshape and geotrace) there are no labels. 

![screen shot 2016-10-24 at 22 07 39](https://cloud.githubusercontent.com/assets/17198051/19659912/7ae959ca-9a36-11e6-8ac5-b7d0a0026afd.png)

**Comment by clash99** [comment]
Sounds like we probably need to update the questionnaire in s3.  Can you provide me a corrected one and I will make sure its gets updated for the link?

**Comment by linzjax** [comment]
[standard_cadasta_questionnaire_0.1.xlsx](https://github.com/Cadasta/cadasta-platform/files/548770/standard_cadasta_questionnaire_0.1.xlsx)

**Comment by clash99** [comment]
Uploaded new standard questionnaire (thanks @linzjax).  Fixed issue.  I'm closing this one.
