### ISSUE TITLE
Uploading a XLSForm with empty labels throws IntegrityError

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#869]
### Steps to reproduce the error

- Create a new project
- In the wizard, upload an XLSForm with empty labels
- Finish the remaining steps in the wizards and save the project. 

### Actual behavior

Saving the project throws an IntegrityError. The field `label_xlat` in `QuestionOption` models can be an empty `dict` but not `None`. [This line](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/questionnaires/managers.py#L64) reads empty values to `None`, which leads to the exception. The line should read `label_xlat=o.get('label_xlat', o.get('label', {}))` instead.

### Expected behavior

The form should be processed without throwing an exception.

**Comment by ian-ross** [comment]
Agreed.  Silly mistake.  I'll fix it now.
