### ISSUE TITLE
Project overview stats needs CSS adjustment for large numbers

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#872]
### Steps to reproduce the error

Go to the project overview page of a project that has thousands of locations, parties, or resources.
### Actual behavior

Stats number overflows its container. (See screenshot below.)
### Expected behavior

Stats number does not overflow its container.

![screen shot 2016-10-27 at 17 05 25](https://cloud.githubusercontent.com/assets/873653/19761304/e5488f92-9c67-11e6-95ba-ff01b3c6eb2c.png)

**Comment by dpalomino** [comment]
Thanks @seav, good catch!

If this is not difficult, it'd be nice to have it solved more or less soon (maybe next sprint?). We are expecting to have this numbers soon.

**Comment by clash99** [comment]
This is a great problem :)

I can include this sprint with a few other css changes.

**Comment by clash99** [comment]
Made responsive font adjustments for 6 figure numbers.

<img width="1439" alt="screenshot 2016-11-01 15 32 08" src="https://cloud.githubusercontent.com/assets/1119621/19906436/c442b496-a048-11e6-9418-181119b9d20b.png">
<img width="343" alt="screenshot 2016-11-01 15 33 55" src="https://cloud.githubusercontent.com/assets/1119621/19906435/c44187a6-a048-11e6-84ea-e5e9406c939e.png">
<img width="504" alt="screenshot 2016-11-01 15 36 21" src="https://cloud.githubusercontent.com/assets/1119621/19906685/c464777e-a049-11e6-80e2-7a8c75259035.png">
<img width="496" alt="screenshot 2016-11-01 15 38 20" src="https://cloud.githubusercontent.com/assets/1119621/19906686/c46dc98c-a049-11e6-8d4c-8a32cebae3f4.png">
<img width="661" alt="screenshot 2016-11-01 15 39 52" src="https://cloud.githubusercontent.com/assets/1119621/19906687/c46e5e88-a049-11e6-8dfd-2a641dc08dff.png">

**Comment by dpalomino** [comment]
Looks great, thanks @clash99!

**Comment by seav** [comment]
Things are much better now, but we still have some overlaps. Not sure if this should really be fixed at all or in the (far?) future.

When the viewport width is at exactly 992px, the font size becomes larger compared to at 993px. (At 991px, the layout changes to the medium size layout.) See screenshot below.

![screen shot 2016-11-09 at 17 18 08](https://cloud.githubusercontent.com/assets/873653/20133176/5f344916-a6a1-11e6-9083-daaecd8c19c9.png)

At 993px to around 1020px, the numbers overlap their borders:

![screen shot 2016-11-09 at 17 26 29](https://cloud.githubusercontent.com/assets/873653/20133250/b7028676-a6a1-11e6-8c0c-d53b28a14436.png)
