### ISSUE TITLE
"Leave this site" confirmation box

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#875]
### Steps to reproduce the error
- From within a project, select "Edit project boundary" from ellipsis menu.  Don't make any map adjustments.
- Select Cancel or the Overview tab on the left
### Actual behavior

In Chrome, I'm getting confirmation dialog asking if I want to leave the site.
### Expected behavior

I didn't expect a dialog at all.

---

I know this is due to the "edit" mode of the map but can change to hide this dialog or change the messaging to create our own before the browser message?  The Firefox message isn't as bad but the Chrome one is rather confusing because it says you are leaving the site.

https://www.dropbox.com/s/irk95qlg1ax5mc1/Screenshot%202016-10-27%2019.26.30.png?dl=0

Chrome message:
<img width="465" alt="screenshot 2016-10-27 19 26 30" src="https://cloud.githubusercontent.com/assets/1119621/19790185/dcdad5cc-9c7b-11e6-8908-9be681e87d1c.png">

Firefox message:
<img width="596" alt="screenshot 2016-10-27 19 31 20" src="https://cloud.githubusercontent.com/assets/1119621/19790201/00738254-9c7c-11e6-8ab2-984ebefed8db.png">

**Comment by dpalomino** [comment]
To be checked when upgrading Leaflet. Changed to low-priority.

**Comment by clash99** [comment]
This shouldn't be as big an issue in the new project pages where you "turn on" the drawing tools to modify the project boundary. I don't think its worth the time creating a workaround with that project on the horizon.  Feel free to reopen @dpalomino if you don't agree.
