### ISSUE TITLE
PATCH /api/v1/organizations/{organization_slug}/projects/{project_slug}/users/{username}/ 

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#881]
### Steps to reproduce the error

Using the API UI, tried to change user dpalomino's role from DC to PM. 

Produced a Platform Error
### Actual behavior

see above
### Expected behavior

Expected the role to be updated and for the UI to return an updated user JSON object.

**Comment by oliverroick** [comment]
Related are Opbeat (platform-staging) errors E#27 and E#28
