### ISSUE TITLE
Upgrade Django to resolve security vulnerabilities

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#886]
Current version: 1.9.6
Latest stable version: 1.10.2

Multiple vulns affecting v1.9, listed here: https://docs.djangoproject.com/en/1.10/releases/security/

Changelogs for upgrading from 1.9.6 to 1.10.2: https://docs.djangoproject.com/en/1.10/releases/

Note there are some backwards incompatible changes when coming from 1.9.x: https://docs.djangoproject.com/en/1.10/releases/1.10/#backwards-incompatible-1-10

**Comment by seav** [comment]
Resolving this issue _should_ also resolve #537, though the latter should be confirmed to be fixed first before closing.

**Comment by oliverroick** [comment]
I opened a #887 to upgrade to Django 1.9.10, which has the necessary security fixes. Upgrading to 1.10 will take a bit longer, because of incompatible changes.
