### ISSUE TITLE
User management UI implementation

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#90]
- [x] User index
- [x] User activate/deactivate

**Comment by ian-ross** [comment]
@clash99 Chandra, do you think you could have a look at this and tell me whether you think it's OK?  In particular, I didn't include a confirmation dialogue for user activation/deactivation, because those actions are immediately reversible right at the point you do them -- if you accidentally deactivate a user, you can just click on the same button right away to reactivate them.  Does that seem OK to you?  (If you need any help getting the test data loaded into the new setup, give me a shout.)

**Comment by wonderchook** [comment]
Moved to UI CSS Clean-up
