### ISSUE TITLE
Installation fails: pip 2 not installed because pip 1.5 already exists

### ISSUE THREAD

**Issue by IknowJoseph** [Cadasta/cadasta-platform#900]
Running "vagrant up --provision" as per setup I received a fatal error (copied below) that pip 2 could not be installed because pip 1.5 was already present on my VM.

To resolve I ran "vagrant ssh" to access the VM, followed by "sudo apt-get remove python-pip"

I was then able to complete the installation via "vagrant up --provision"

I don't know where the original pip 1.5 installation came from, whether this can be omitted, or if the installation of  pip 2 can be forced over 1.5 - I'll take a look today.

fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 install -U pip", "failed": true, "msg": "stdout: Downloading/unpacking pip from https://pypi.python.org/packages/3f/ef/935d9296acc4f48d1791ee56a73781271dce9712b059b475d3f5fa78487b/pip-9.0.0-py2.py3-none-any.whl#md5=55f554c8be55cba2a766e40fdb1bb25d\nInstalling collected packages: pip\n  Found existing installation: pip 1.5.4\n    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS\nCompiling /tmp/pip_build_vagrant/pip/pip/_vendor/html5lib/treewalkers/etree.py ...\n  File \"/tmp/pip_build_vagrant/pip/pip/_vendor/html5lib/treewalkers/etree.py\", line 13\n    from pip._vendor. import string_types\n                           ^\nSyntaxError: invalid syntax\n\n  Can't roll back pip; was not uninstalled\nCleaning up...\nException:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/pip/basecommand.py\", line 122, in main\n    status = self.run(options, args)\n  File \"/usr/lib/python2.7/dist-packages/pip/commands/install.py\", line 283, in run\n    requirement_set.install(install_options, global_options, root=options.root_path)\n  File \"/usr/lib/python2.7/dist-packages/pip/req.py\", line 1436, in install\n    requirement.install(install_options, global_options, *args, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/pip/req.py\", line 672, in install\n    self.move_wheel_files(self.source_dir, root=root)\n  File \"/usr/lib/python2.7/dist-packages/pip/req.py\", line 902, in move_wheel_files\n    pycompile=self.pycompile,\n  File \"/usr/lib/python2.7/dist-packages/pip/wheel.py\", line 206, in move_wheel_files\n    clobber(source, lib_dir, True)\n  File \"/usr/lib/python2.7/dist-packages/pip/wheel.py\", line 193, in clobber\n    os.makedirs(destsubdir)\n  File \"/usr/lib/python2.7/os.py\", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip-9.0.0.dist-info'\n\nStoring debug log for failure in /home/vagrant/.pip/pip.log\n"}

**Comment by ian-ross** [comment]
This is a bug in Ansible 2.2.0.0 (https://github.com/ansible/ansible-modules-core/issues/5470).  Try downgrading to Ansible 2.1.2.0.  (You may have other problems related to GDAL that we're trying to resolve at the moment, but downgrading Ansible should fix the PIP problem.)

**Comment by manoramahp** [comment]
Faced the same issue after upgrading to ubuntu 16.04. 
`pip install ansible==2.1.2.0` fix the issue.
