### ISSUE TITLE
Error uploading questionnaires

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#907]
### Steps to reproduce the error

Create a new project on staging. Either during project creation or during editing of project try to add a questionnaire to the project. A platform error is thrown.

### Actual behavior

A platform error is thrown when adding questionnaires to new or existing projects. The error stacktrace is available at https://opbeat.com/cadasta/platform-staging/errors/32/. Several questionnaires were tried including the standard questionnaire at https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/questionnaires/tests/files/standard_cadasta_questionnaire_0.5.xlsx.  Questionnaire upload works correctly locally using the latest master.

### Expected behavior

It should be possible to add a questionnaire to a new or existing project.

**Comment by oliverroick** [comment]
This might be because a of a migration that was run when we deployed `feature/686-questionnaire-api` to staging. It adds a not-null field to the question-group table and the code on master does not reflect that. 

Reverting the migration should fix the problem /cc @amplifi

**Comment by amplifi** [comment]
Should be all sorted on staging; works with the standard questionnaires. Reverted 0014 questionnaires migration.
