### ISSUE TITLE
Implement a search index batch update daemon

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#908]
This GH issue is to support the implementation of the search feature (#825) and was discussed during the search call on Nov. 7/8.

When records and resources are created/updated/deleted in the Cadasta platform, the Elasticsearch index needs to be updated to reflect the platform data's new state. Because the search index update operation may be potentially expensive, it was decided to implement this asynchronously from the platform data update operation.

The basic idea is that there will be a separate daemon that will accept metadata on which records/resources were updated in the platform, store them in a deduplicated queue (one per project), then periodically perform a batch search index update operation by taking the queued metadata (flushing the queue in the process), retrieving the updated records/resource data from the platform database corresponding to the metadata, then push these into the Elasticsearch cluster via its bulk API.

**Some implementation details:**
1. The daemon must expose a simple HTTP API that can be accessed by the platform for the latter to push metadata on records/resources that were updated. There should also be API endpoints so that the platform can inform the daemon on which projects are existing and active so that the daemon can manage its queues.
2. In the short term, the daemon can run on the same network node that runs the platform. In the long term, the daemon can run on a separate node if performance is an issue.
3. In the short term the queues can be stored in-memory. In the long term, these queues can be stored in the database if performance is an issue.
4. The batch update operation needs to be run periodically on each project's queue. The update interval should be specific to and configurable per project, depending on the amount of data and any existing conditions. For example, if a project is currently having an import operation, then the update operation can be suspended until after the import is finished. Some feasible intervals are between 5 minutes to 1 hour.
5. Because ES accepts searchable documents to be indexed as JSON, the daemon needs information about how to serialize the records/resource metadata into JSON. So it would be nice if the daemon can reuse the platform DRF JSON serializers.
6. The daemon code may be a separate GH repository if that makes sense.

**Possible alternate architecture:**
Instead of having an API and in-memory queues, fold these into the Cadasta platform and implement the queues into the database and accessible to the platform as Django models. So the queue and queue management is internal to the platform. Then the daemon would simply just implement the batch update operations that access the queue and platform data from the database and push these to the ES cluster. The daemon can even just be regular cron jobs (one per project) that run a batch update script.

**Comment by ian-ross** [comment]
The way you're talking about this makes it sound as though you want us to implement a lot of this ourselves.  Do you know about Celery?  And SQS?  And all the other AWS services that we could use for managing this sort of thing?  Saying that you want a daemon exposing HTTP endpoints and for the daemon to manage task queues in memory or in the database is putting mechanism before strategy and policy.  Have you looked into pre-existing components that we could use to manage this process?

**Comment by amplifi** [comment]
Yeah, I think there's quite a bit getting lost in translation here. I'll write up an architecture doc to clarify implementation.

**Comment by amplifi** [comment]
Completed using Logstash to index the database to Elasticsearch directly.
