### ISSUE TITLE
Implement a mock ES cluster for testing purposes

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#910]
This GH issue is to support the implementation of the search feature (#825) and was discussed during the search call on Nov. 7/8.

To be able to develop and improve the search function, a mock ES cluster is needed for testing purposes. This is basically a simple HTTP server that represents the ES API. For maximum flexibility, the tests should be able to dynamically program the HTTP responses that are returned by mock server in response to any HTTP request, so there is no need to actually write code that emulates the ES API. (Unless emulating the API in some fashion would simplify the test coding, of course.)

If this mock server is generic and flexible enough, then this can also be reused to mock the batch update daemon's API (see #908).

**Comment by seav** [comment]
@oliverroick suggested appending another view on the platform to act as the mock ES server, a bit similar to the solution used for the mock S3 endpoint for the resources uploading feature in django-buckets. I will be investigating this in order for us to be able to provide some (mock) results to test with on the UI side while running the platform on the dev VM.

My initial concern with this suggestion, as opposed to running a separate server in the VM, is that I find it weird that the platform will be sending an HTTP request to itself. While this is technically OK, I'm not familiar enough with Django to know if this is kosher. With the mock S3 endpoint, it is the user's browser that is accessing the mock endpoint and not the platform.

Also, this means that the dev VM platform will need to serve the following URL patterns `/project-<project.id>/*` based on how the ES server has been set up. Fortunately, this doesn't clash with any of the platform's existing URL patterns.

**Comment by wonderchook** [comment]
@seav has there been discussion about this?

**Comment by seav** [comment]
@wonderchook, I have submitted PR #1132 to resolve this. I provided there some background material and that can form the basis for further discussions. But generally, I followed Oliver's suggestions.
