### ISSUE TITLE
Inline Manual player script still contains template variables

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#912]
### Steps to reproduce the error
Check out the following static JavaScript file on staging:
https://platform-staging.cadasta.org/static/js/inline-manual-player.js

### Actual behavior
See `{{ user.id }}` and `{{ user.username }}`.

### Expected behavior
I assume that these should actually refer to the current user.

### Notes
Based on PR #892, the bit of JavaScript that contains these template variables got moved from a Django template (core/base.html), into an Ansible template. When they are in the Django template, these variables should indeed be interpolated with the current user's ID and username. But as an Ansible template that is written out to a static JS file, they become static values irrespective of the current user.

**Comment by clash99** [comment]
@seav good catch - I'll break these apart and ask @adri to update that file.

**Comment by amplifi** [comment]
Ansible side is done and @clash99 has taken care of the Django side.
