### ISSUE TITLE
User roles for projects and organizations are not assigned correctly.

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#914]
There are several issues with assigning user roles both on the organization and project levels. I believe these issues are related, so I'll create just this one issue. 

For reference, the issues were observed on staging:

- Organization: [Oliver's](https://platform-staging-api.cadasta.org/organizations/olivers/)
- Project: [Leipzig](https://platform-staging-api.cadasta.org/organizations/olivers/projects/leipzig/)

#### Steps to reproduce the error

1. Create an organization with several projects. 
2. Add a new member to the organization.

#### Actual behavior

The role for project selected projects is not _Public User_ by default. In my example project, there was another organization member (iross), and the default roles for the new user match exactly the roles of the existing member

#### Expected behavior

The role for all projects should be _Public User_ by default.

#### Steps to reproduce the error

1. Go to an organization that has at least two members who are not organization admins.
2. Go to organization members and select one of the members who are not admins. 
3. Change the roles of a few projects for that role and save. 

#### Actual behavior

The project roles of the other non-admin match the roles of the user you have just changed. 

#### Expected behavior

The project roles of the other non-admin should be untouched.

**Comment by linzjax** [comment]
I'm fixing this in the branch that it's in. For some reason it was pull initial ProjectRoles for the whole organization, not specific to the user that you're viewing.
