### ISSUE TITLE
Longer-term solution for intermittent functional test failures

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#919]
We have experienced intermittent functional test failures on Travis on-and-off for a long time.  #902 is the latest instance of this.  These problems are getting harder and harder to fix, mostly because we've dealt with the easy cases (to do with non-deterministic ordering of database query results) and the problems we're now seeing seem to be related to interactions between Selenium, the browser we're using for testing and Javascript we have on some pages.  We need to do something about this because there have been periods where it's made it more or less impossible to merge PRs.

A couple of options:

1. Try harder to make the test environment on Travis closer to the environment in the development VM.  Some of the more recent test failures appear not to happen at all in the dev VM, so I'm wondering whether they're to do with differences in Selenium or Firefox versions between the dev VM and Travis.  We're using the versions of Selenium and Firefox that are made available by default in the Travis environment, so maybe we should take control over that and use the same versions that we use in the dev VM.  (Interactions between Selenium and browsers seem to be very unstable and problems come and go with different versions of Selenium and Firefox, so pinning this down might help.)

2. We should try to identify the features in failing functional tests that are most likely to be problematic for Selenium.  Things like timing issues, script loading, and so on.  We can then try to modify our functional tests to make them less dependent on these features.  For example, instead of waiting for an alert to appear and dismissing it (which seems to be part of the problem with #902), base the test on a more static element of the page.

This is probably going to be an ongoing struggle, but point number 1 above may help to alleviate some of the pain, then we need to come up with a strategy for writing functional tests that avoids as many of the problems in point 2 as possible, and *write that strategy down* for people to follow when writing new functional tests.

**Comment by ian-ross** [comment]
An attempt at point #1 above didn't seem to help (https://github.com/Cadasta/cadasta-platform/pull/930).

**Comment by dpalomino** [comment]
We have the new test cases spreadsheet, so we can close this issue.
