### ISSUE TITLE
Data download from projects with non-ASCII slugs encounters error

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#925]
### Steps to reproduce the error
1. Create a project with a non-Latin alphabet name. (東京財団 ["Tokyo Foundation"] would work.) (This should result in a non-ASCII project slug.)
2. Go to the download project data page.
2. Select either the "SHP" or "All data" options then download.

### Actual behavior
Error!

### Expected behavior
Project data should have been downloaded.

### Notes
**In Opbeat:** https://opbeat.com/cadasta/platform-staging/errors/34/

I've tried digging into this and this bug might be related to whether the OS filesystem supports Unicode filenames and if those filenames are stored as UTF-8 or not. When the shape files are created, they are created with the project slug (which may not be ASCII) in their filenames. Later, when these files are zipped, the Python zipping library chokes on those filenames. I tried this on my dev VM and the data can be downloaded without error presumably because the dev VM filesystem stores filenames as UTF-8. It appears that this is not the case in AWS.

Here is the deepest Python call that results in the error. Note the use of `'utf-8'`.
```python
return self.filename.encode('utf-8'), self.flag_bits | 0x800
```

**Comment by ian-ross** [comment]
I don't think the filesystem on the AWS instances is the problem:

```
[seneca:~] $ ssh -l debug -i ~/.ssh/cadasta-debug.pem platform-staging.cadasta.org
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-67-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

Last login: Mon Oct 24 07:57:26 2016 from 91.141.2.139.wireless.dyn.drei.com
debug@ip-10-0-0-92:~$ pwd
/home/debug
debug@ip-10-0-0-92:~$ mkdir tst
debug@ip-10-0-0-92:~$ cd tst
debug@ip-10-0-0-92:~/tst$ mkdir '東京財団'
debug@ip-10-0-0-92:~/tst$ ls
東京財団
debug@ip-10-0-0-92:~/tst$ cd '東京財団'
debug@ip-10-0-0-92:~/tst/東京財団$ echo first > 1.txt
debug@ip-10-0-0-92:~/tst/東京財団$ echo second > 2.txt
debug@ip-10-0-0-92:~/tst/東京財団$ echo third > '東京財団.txt'
debug@ip-10-0-0-92:~/tst/東京財団$ ls
1.txt  2.txt  東京財団.txt
debug@ip-10-0-0-92:~/tst/東京財団$ cd ..
debug@ip-10-0-0-92:~/tst$ ls -R
.:
東京財団

./東京財団:
1.txt  2.txt  東京財団.txt
```

However, the documentation for the Python `zipfile` module says:

> **Note:** There is no official file name encoding for ZIP files. If you have unicode file names, you must convert them to byte strings in your desired encoding before passing them to write(). WinZip interprets all file names as encoded in CP437, also known as DOS Latin.

So it does sound as though we need to add some calls to `encode` to force everything to UTF-8.

**Comment by dpalomino** [comment]
Thanks Ian for volunteering!
