### ISSUE TITLE
Review the use of hard-coded jsonattrs schema selectors in platform code

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#936]
### The issue

At several points in the platform, `django-jsonattrs` schema selectors are hard coded as `project.organization.id, project.id, project.current_questionnaire`. In particular, this occurs in the [TenureRelationshipAdd](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/spatial/views/default.py#L187) view, in the base [Exporter](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/organization/download/base.py#L14) and in the base [Importer](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/organization/importers/base.py#L37).

In the case of the `TenureRelationshipAdd` view, it means that attribute fields that are defined per `party_type` are not added to the form: the `type` selector is not used. Since these attribute fields are not added to the form they cannot be rendered when the user chooses the `party_type` when adding a new `Party` in the UI. The same issue applies when editing a `Party` in the UI and the user changes the `party_type` (although its debatable whether changing the `party_type` should even be possible). See https://github.com/Cadasta/cadasta-platform/issues/761

In the case of the base `Exporter`, only attributes defined by the selectors `project.organization.id, project.id, and project.current_questionnaire` are exported. Attributes selected by entity `type` are not exported. See #935.

In the case of the base `Importer`, only those attributes selected by `project.organization.id, project.id, project.current_questionniare` can be mapped to columns in the imported dataset. Its not currently possible to import attributes that correspond to a particular `party_type`. See #813.

### Expected behavior

There should be a way, either in platform code or in `django-jsonattrs` to select all available attributes for a project and to map these to the domain entity `content_types`, including to domain entities which can have different `types`. This might be achieved by extending a structure like [JSONATTRS_SCHEMA_SELECTORS](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/settings/default.py#L264) which could then be queried for the appropriate attributes, and/or made available to platform code using a `SchemaSelectorMixin`... however, its not straightforward and the issue needs more investigation..

**Comment by wonderchook** [comment]
@bjohare did you mean to make this an epic or a bug?

**Comment by bjohare** [comment]
@wonderchook maybe I'm misusing the `Epic` label, I understood it as a 'meta' label for issues that touch several areas of the platform..

**Comment by wonderchook** [comment]
@bjohare an epic should be a label for a specific feature. So if there was a series of mini-features for an area of the platform we would use it.

**Comment by wonderchook** [comment]
@bjohare is this partially fixed? I'm noticing the issue with individual vs. group parties is a bit funny. It seems to work when you edit an existing party.

**Comment by bjohare** [comment]
@wonderchook I haven't committed anything for this yet. The reason it 'works' for existing parties is that we only know what attributes are available for a party once we have an actual instance and we know the type. We don't know the type for a party that hasn't been created yet so the conditional attributes can't be rendered on the form.

**Comment by wonderchook** [comment]
@bjohare related to this. When you switch party types things tend to explode. Will what you are doing assist with this or should I be opening a bug about that as an entirely different thing?

**Comment by bjohare** [comment]
@wonderchook no need for a separate bug report, its all related. It should be fixed when my changes get merged.
