### ISSUE TITLE
UI for projects

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#94]
Wireframing and design for projects.

* [2.0 Projects - User Flow](https://drive.google.com/open?id=0BzpiEtMtHC3rUGtBUURXbC1SZ2M)
* [2.0 Projects - Wireframes](https://drive.google.com/open?id=0BzpiEtMtHC3rSFk5Tk81REJ3Wjg)

**Comment by clash99** [comment]
Added first draft of project index, steps to create a new project, and project overview.  I think this is what will be covered in this sprint.  Continuing work on projects area for next sprint.

**Comment by ian-ross** [comment]
OK!  Thanks for that.  Definitely enough for me to get started.

**Comment by eomwandho** [comment]
I will also modify the [projects API design wiki page](https://github.com/Cadasta/cadasta-platform/wiki/Projects-API) to include missing fields and possible responses.

**Comment by ian-ross** [comment]
One small request: when you make these PDFs, do you think you could make them so they're on consistent page sizes so that they're easily printable?  This one has 4 pages all of different sizes, and one seems to be some sort of double height page, which makes it kind of hard to deal with.  Thanks!

**Comment by clash99** [comment]
I've updated the wireframe pdf - I was optimizing for screen viewing put not it should fit on a letter-sized paper.

**Comment by ian-ross** [comment]
Great!  Thanks -- you're right that the layout you had before was better for on-screen viewing, but when it comes time to implement these things, it's useful to print them out so that you can scribble notes on them.

**Comment by ian-ross** [comment]
Oh, I forgot, but I had another question about these.  Here, and in some of the other wireframes as well, you have "Last updated" datetime fields for things.  Is there a specific reason for having this in these views, or is it just a holdover from the fact that SpatialDev had these kinds of things in some of their views (mostly because they were easily available in CKAN, I think)?

From my perspective, there are two factors with this:

1. I'm not sure I'd find this information very useful.  What does "Last updated" really mean?  The last time the project details were updated?  Or the last time any entity in the project was updated?  And what entities?  Just parties, parcels, relationships?  Resources too?  Administrative policies and things like that?  I'm just not sure it's a meaningful thing to collect.

2. It's not information we're collecting in the current iteration of the data model.  Once we have all the history stuff in place, it will be trivial to extract this kind of information, but for the moment, it's just not there.  We could add it, of course.

I think we'll eventually want to have a possibility to sort projects by "activity", but that would be some sort of composite measure based on numbers of edits to interesting entities, number of page views, number of active users, and so on (and it wouldn't be something you'd display as a field on a page, but would just use for sorting).

**Comment by wonderchook** [comment]
I think last activity of some sort is reasonable. Though I think we can leave this out for now.

**Comment by clash99** [comment]
The "last updated" field would reflect the latest activity of any sort within that project (basically the most recent entry date on the project activity feed).  As we develop our dashboards and project overviews more, this is the type of information administrators are going to want to see at-a-glance.  Its not necessary for initial release, but we are going to need think about implementing this type of information in the future.

**Comment by wonderchook** [comment]
Completely agreed that people are going to want it, but I think better done when the history is in place as @ian-ross mentioned
