### ISSUE TITLE
Implement exponential back-off for password attempts

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#945]
As a follow-up to password criteria and Argon2, we should implement exponential back-off for password attempts. This would replace our current model of locking attempts after x incorrect tries.

**Comment by dpalomino** [comment]
Thanks @linzjax for volunteering to take a look on this!

**Comment by linzjax** [comment]
Do we currently have any lock out method in place?

**Comment by clash99** [comment]
Here is the message I'm getting after 6 attempts:

<img width="689" alt="screenshot 2016-12-07 16 12 14" src="https://cloud.githubusercontent.com/assets/1119621/20988868/301cd794-bc98-11e6-8d54-abd0828b1694.png">

**Comment by linzjax** [comment]
Couple of questions:
I chose to implement [this version](https://devcentral.f5.com/articles/implementing-the-exponential-backoff-algorithm-to-thwart-dictionary-attacks) of the exponential back-off algorithm. It recommended capping the wait time at 24 hours. Does this work for us?

How long do we want the cache to hold onto login attempts? I currently have it set to 24 hours as well.

Can we set the `default` cache in the dev environment to `LocMemCache`? There are several functions I'm having to include just to set `cache` to `caches['accounts']` which just seems repetitive and unnecessary. [Code here](https://github.com/Cadasta/cadasta-platform/blob/5a53bfe2782b72057e27ceb119c3e272d789167c/cadasta/accounts/adapter.py#L34-L40). The other option would be to submit a PR to django-allauth with updates to include an exponential back-off option, so we don't have to piece things together.

**Comment by oliverroick** [comment]
24 hours for maximum back-off time and caching sounds reasonable to me. Maybe we can implement those using settings, so we can easily change that later. 

No objections to using `LocMemCache` as the default cache for development; if the cache in dev gets too big, we can always move back to `DummyCache` once your work is done. For testing, you can temporarily [overwrite Django settings](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#overriding-settings) in your tests.
