### ISSUE TITLE
UI for resource management

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#95]
Creation of user flows and wireframes.

* [2.0 Projects - User Flow](https://drive.google.com/open?id=0BzpiEtMtHC3rUGtBUURXbC1SZ2M)
* [2.0 Projects - Wireframes](https://drive.google.com/open?id=0BzpiEtMtHC3rSFk5Tk81REJ3Wjg)

**Comment by clash99** [comment]
Unclear what this task is...  are we talking about supporting documents/ files within a project?

**Comment by ian-ross** [comment]
Yes, this is for images, PDFs, audio, video, etc.  We need some general ideas about how this is going to work before we think about fitting it into the different areas where it will be used (more or less everywhere: images for logos, PDFs, images, audio and video for documentation for parties, parcels, etc., and so on).

**Comment by wonderchook** [comment]
@clash99 if it would help we can talk through this a bit more. I think there would be one way people would upload a file and we'd need to use it in at least a couple different places.
