### ISSUE TITLE
Project Creation Wizard Wireframes

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#954]
Tracking issue for wireframes and requirements regarding creating XLSForms through the web GUI.

**Comment by dpalomino** [comment]
We will be tracking the wireframes through this task, and in #966 will be used for requirements.

**Comment by clash99** [comment]
Wireframes are available: https://drive.google.com/open?id=0BzpiEtMtHC3rTzREZkY4b3dYSUU

**Comment by clash99** [comment]
@dpalomino - do you think we can mark this closed since we have an approved set of wireframes?

**Comment by dpalomino** [comment]
Yes, I agree @clash99. I'm keeping #966 open for outlining the user stories and tasks, and generally discussing regarding phases and MVP.
