### ISSUE TITLE
Permissions issue:  Data Collector Role

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#960]
### Steps to reproduce the error

Based off this user's permissions (which I setup locally):
![screenshot 2016-12-01 08 13 12](https://cloud.githubusercontent.com/assets/1119621/20801996/361343be-b7b0-11e6-9c1e-9e1923c0fd51.png)
 
The user should have data collector rights to the Pekapuran Laut Test Project.  Generally this user should have the ability to view/add/edit all locations, relationships, parties, resources, as well as import and download project data. 

### Actual behavior

I'm getting an alert that I don't have permission to import data.  This new import data dropdown option is only available with PR #942.  There isn't an option to download data.  I think we need to revisit this from a UI perspective too.  Maybe they should have a modified view of the ellipsis menu instead of removing it entirely. 

![screenshot 2016-12-01 10 30 31](https://cloud.githubusercontent.com/assets/1119621/20802523/eb047fee-b7b1-11e6-987b-5994bcec64d3.png)
![screenshot 2016-12-01 10 30 44](https://cloud.githubusercontent.com/assets/1119621/20802527/ef6e0848-b7b1-11e6-8065-c6f33404b3ff.png)

### Expected behavior

I should be able to import data if I'm a data collector.

**Comment by seav** [comment]
Hmmm. I would expect that only project managers would be able to import data. I view data collectors as people given the permission to add/edit/delete records one at a time but not being able to bulk add records except through ODK.

**Comment by dpalomino** [comment]
Thanks @seav for the input. As just discussed, although in theory it makes sense to allow data collectors to import data, as it results in "collecting" new data into the project, in practice this is a task too complex to be performed by data collectors and it will be typically done by project managers. It could be too risky to allow all data collectors to perform this kind of tasks. 

So I'd suggest to restrict import data just to project managers. Thoughts @clash99 @wonderchook @fhpichel?

**Comment by wonderchook** [comment]
In agreement with that as far as the data collectors not doing imports

**Comment by oliverroick** [comment]
@clash99 The "import data" link can be found in the "Add location" dropdown and the "More actions" dropdown. Is that correct or should it just be in one of the dropdowns?

**Comment by clash99** [comment]
@oliverroick It is my understanding that Data Collectors cannot see the second "More Actions" button.  Is that correct?

**Comment by oliverroick** [comment]
Data collectors can not see the "More actions" button, that's correct. Was just checkin in if it's correct that the link appears in both menus. If so, we leave them in both and I just look at hiding the link when the user can't import.

**Comment by clash99** [comment]
That sounds perfect - thank you @oliverroick.
