### ISSUE TITLE
Permissions issue: Public user role within an organization

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#961]
### Steps to reproduce the error

Based off this user's permissions (which I setup locally):
![screenshot 2016-12-01 08 13 12](https://cloud.githubusercontent.com/assets/1119621/20801996/361343be-b7b0-11e6-9c1e-9e1923c0fd51.png)
 
The user should have public user rights to the H4H Test Project.  Generally this user should have the  ability to view the project overview page with the locations on the map.  This user should not be able to view location details, relationships, parties, resources. 

### Actual behavior

I'm able to view all the location details, relationships, parties and resources through the location popup on the overview map.  Following PR #942, the sidebar is removed within the project for public users. 

![screenshot 2016-12-01 10 42 56](https://cloud.githubusercontent.com/assets/1119621/20802941/3d9276c0-b7b3-11e6-91ee-87988332f167.png)

### Expected behavior

I should get a message that I don't have permission to view the location data (and ideally an option to request permission.)

**Comment by oliverroick** [comment]
The [organization member policy grants](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/permissions/org-member.json#L14-L18) `view` permissions on all spatial units of any project in an organization. (Same goes for parties and relationships.)

I can remove the permissions from the policy to fix this issue as described. But I'm not sure that this is correct. @dpalomino can you clarify what the intended behaviour should be?

**Comment by dpalomino** [comment]
Hi @oliverroick. So the Public User should not be able to see the details regarding locations, relationships, parties or resources within the project. Only the project overview page (I think that is the "list" permission?). 

I am not sure if I totally understand the code you pointed to. I would say yes unless you think that removing those permissions could have some other collateral effect apart from preventing public users viewing the details of those entities?

**Comment by oliverroick** [comment]
I'm moving the policies that grant `view` permissions for locations, parties, resources and all relationships into the `project-user` policy document.

That means, if you're an org member but not member of a project you can list everything but not see the details. If you're a "Project User" you can list and see the details.

**Comment by dpalomino** [comment]
> That means, if you're an org member but not member of a project you can list everything but not see the details. If you're a "Project User" you can list and see the details.

Ok, that's perfect. Thanks!

**Comment by clash99** [comment]
Great!  I would love to make a graphic for these permissions to help with testing.  I'll use this as a start.

**Comment by oliverroick** [comment]
I double check how we handle this in other views. Turns out, the party list is filtered according to the permissions the user has. It lists only parties for which a user also has `party.view` permission. 

This is different from how we handle relationships and locations. Is this intended or does this need to be fixed?

**Comment by dpalomino** [comment]
> I double checked how we handle this in other views. Turns out, the party list is filtered according to the permissions the user has. It lists only parties for which a user also has party.view permission.
>
>This is different from how we handle relationships and locations. Is this intended or does this need to be fixed?

Thanks for the heads-up @oliverroick. I think it is not intended but we were not aware as we didn't have Parties page until recently. In my opinion, I think we should list the parties for which the user has party.list.permission. So that would be coherent with what we do with locations... Does it make sense? Thanks!

**Comment by oliverroick** [comment]
> Does it make sense?

It does, for consistency at least. I don't understand why we would list things the user can't access (same with putting locations on a map when the user can't access them). I think, it's confusing to users.
