### ISSUE TITLE
Implement password strength indicator

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#967]
Related to #735, add an interactive password strength indicator.  Ideally we would have some metrics in place to make sure this enhances the experiences instead of deterring registrations.

**Comment by dpalomino** [comment]
Backlog id #36.02.

**Comment by dpalomino** [comment]
Hi @clash99. As a suggestion, as we've already the password validation criteria (issue #735), maybe it'd not be easier to have a all/none password strength indicator (green ok, red not ok) maybe? (thanks btw to @oliverroick for the idea!).

**Comment by amplifi** [comment]
Can we implement one of the existing open source Django password strength meter widgets/plugins? There are several versions available, and should be a simple setup.

**Comment by clash99** [comment]
Sounds like a good plan to use something already available.  I see some also include show password options.  Any recommended ones @amplifi?  I can look around next week to see which might work best.

**Comment by Divya063** [comment]
@clash99 @amplifi  I'm trying to use this django-password-strength package
This package contains an extention of the Django password widget including a password strength meter and crack time powered by zxcvbn,but getting trouble in implementing it

**Comment by oliverroick** [comment]
Hi @Divya063, for this issue we need to do some additional design work to work out what kind of indicator we actually need/want. Unfortunately, we don't have much time at the moment to do the necessary preliminary work or provide support for this issue as this is currently not one of our higher priorities. We're sorry about that, we appreciate the work you have already put in.

**Comment by Divya063** [comment]
@oliverroick it's okay

**Comment by oliverroick** [comment]
Thank you!
