### ISSUE TITLE
Malformed error message during import when a required attribute is missing

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#970]
### Steps to reproduce the error

Create a new project and upload a questionnaire. Import a file in which an attribute required by the project schema is missing. The platform reports the error but the message is malformed:

![malformed_error](https://cloud.githubusercontent.com/assets/3308136/20925510/54edfee8-bbaf-11e6-9f73-974796b03020.png)

### Expected behavior

The error message should be formatted correctly.

**Comment by clash99** [comment]
I will take look at this from ui and also earlier layout question.

**Comment by bjohare** [comment]
@clash99  the malformed error is fixed in https://github.com/Cadasta/cadasta-platform/tree/regression/%23970

**Comment by clash99** [comment]
Brian fixed the error so I'm only making a few ui changes with this one.  Related to #976, we should consider removing the first radio button question at that time and be able to deduct the value with the file type uploaded. 

<img width="648" alt="screenshot 2016-12-08 08 52 00" src="https://cloud.githubusercontent.com/assets/1119621/21014493/e862410a-bd23-11e6-9bad-29486dc7cb9f.png">
