### ISSUE TITLE
Add platform tagline to right of logo

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#975]
Add tagline to right of logo 

Inspired by LandMark (http://www.landmarkmap.org/)

**Comment by pranjaltale16** [comment]
@clash99, Hello I would like to work on this and add a tagline to right of the logo.
1. What is the exact tagline that I have to add? 
2. Do I have to add an image for it or plain text?

**Comment by kera99** [comment]
HI @clash99 ,

Can I work on this for GSoC17 ?

Thanks.

**Comment by clash99** [comment]
Closing this for now.  We are going to be adding demo/staging to right of logo.  After communications person is hired, we may want to bring this issue up with them but will need to consider spacing, etc. at that time.
