### ISSUE TITLE
Data Collector User Can't Download Forms

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#978]
I created a new org and project. I then created a new user and added them to the org as a member and the project as a Data Collector. Then I entered the users credentials into GeoODK and I was able to list the available forms but not download one. I'm getting a 403 error (see screenshot)

![screenshot_20161206-153331](https://cloud.githubusercontent.com/assets/67992/20948631/dd2236de-bbc9-11e6-9085-46de7eb0a556.png)

**Comment by wonderchook** [comment]
I have confirmed this is not the case on demo, so this appears to be issue brought up in the current sprint.

**Comment by oliverroick** [comment]
I updated a few permission policies, which affect form download. This might be because the policies have not been updated on staging using `./manage.py loadpolicies --update`. Can you confirm, @amplifi?

**Comment by amplifi** [comment]
@oliverroick @wonderchook I've run `loadpolicies --update` on staging; is the error still occurring?

**Comment by bjohare** [comment]
Can confirm this is working.

**Comment by amplifi** [comment]
Thanks, @bjohare! I'm updating the provisioning side and management command to better handle this.

**Comment by wonderchook** [comment]
Yes, is working now.
