### ISSUE TITLE
User model should have "full name" not "first name, last name"

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#98]
The default Django user model has `first_name` and `last_name` fields, which is bad for internationalisation -- bad enough that I'd consider this a bug.

We're already using a custom user model, so we should update this to use a `full_name` field instead.  That's a more substantial change from the defaults than our current custom user model, but the changes are mostly mechanical and really just a matter of copying the `AbstractUser` base class from `django.contrib.auth.models`, changing the fields it has and changing our user model to derive from it (or just folding the new "abstract user" definition into our user model.

These changes then need to propagate through the API and to the front end as well, obviously.

**Comment by Avin-Techv** [comment]
Is there an alternate solution to this?

**Comment by oliverroick** [comment]
Hi @Avin-Techv, you can have a look at our [custom `User` class](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/accounts/models.py#L40-L130) to learn how we solved this.

**Comment by singitaN** [comment]
Hi @oliverroick I'm applying the same code but I get an OperationalError at /admin with a `no such column: core_user.full_name`
