### ISSUE TITLE
Broken password for demo users

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#985]
### Steps to reproduce the error

1. Navigate to instructions for signing in as a demo user (under the ? in top nav)
2. Enter username: demo
3. Enter password: password

### Actual behavior

Password did not work

### Expected behavior

Expected that password would work

![image](https://cloud.githubusercontent.com/assets/3361475/20995300/f057929e-bcaa-11e6-9c9d-b755ea2f2eca.png)

**Comment by amplifi** [comment]
I'm guessing this password was changed to something different either during testing or by a user. I've reset it to 'password' to match the help prompts. We should consider a mechanism to ensure this account's credentials aren't changed.

**Comment by bethschechter** [comment]
thanks, I can confirm that this is working.
