### ISSUE TITLE
On view party details page, the map tab is highlighted

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#993]
### Steps to reproduce the error
Click parties
view an individual party's page.

### Actual behavior
<img width="1280" alt="screen shot 2016-12-08 at 11 52 18 am" src="https://cloud.githubusercontent.com/assets/8128188/21018955/e720ba42-bd3c-11e6-9f49-8358ea81fd7e.png">

### Expected behavior
The parties tab would stay highlighted

**Comment by clash99** [comment]
Second choice for party icon btw:
![screenshot 2016-12-08 11 34 13](https://cloud.githubusercontent.com/assets/1119621/21020485/5002ca9e-bd3a-11e6-909f-7b249f5ba0f3.png)

Updated left subnav so party detail shows highlighted parties tab: 
<img width="1070" alt="screenshot 2016-12-08 11 32 26" src="https://cloud.githubusercontent.com/assets/1119621/21020433/1c7bf02e-bd3a-11e6-96bc-0a99dc3526a3.png">

**Comment by dpalomino** [comment]
I think this issue is already solved, I cannot reproduce it in demo or production.
