### ISSUE TITLE
Organize project list to show user membership

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#994]
Maybe this is an idea for the user dashboard, but as the project index grows it would be helpful to be able to sort out what projects I am a member of.

Initial ideas:
- Add an indicator to display which projects user belongs to
- Have a dropdown to filter by membership
- Group projects that you belong to above others?

**Comment by wonderchook** [comment]
I think also a way to see what orgs you are a member of would also be helpful. This might be felt more acutely by Cadasta team members but I know I get lost right now already in projects and orgs.

**Comment by dpalomino** [comment]
I was also thinking about including this in the future user dashboards (backlog id 44.00), among other information:
- Links to the organizations the user is a member of
- Links to the projects the user is a member of
- Some statistics, like number of projects and orgs, number of locations you contributed, etc.

**Comment by clash99** [comment]
Closing this task. It is covered in #1137 and #1483.
