### ISSUE TITLE
Incorrect URL - "reach out to us" in user guide

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#998]
On the Importing Data page (https://docs.cadasta.org/en/08-upload.html) of the user guide, the "reach out to us" links all point to this URL.....
 
http//cadasta.org/contact/

**Comment by wonderchook** [comment]
Issue moved to [Cadasta/cadasta-docs #8](https://github.com/Cadasta/cadasta-docs/issues/8) via [**ZenHub**](https://www.zenhub.com/)
