### ISSUE TITLE
Link to Questionnaire in Importing Data page doesn't work

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#999]
This link - https://docs.cadasta.org/en/08-upload.html#09-XLSForms.md goes nowhere when I click on it from the Importing Data page

**Comment by wonderchook** [comment]
@nastynoel I assume this is documentation?

**Comment by wonderchook** [comment]
Issue moved to [Cadasta/cadasta-docs #7](https://github.com/Cadasta/cadasta-docs/issues/7) via [**ZenHub**](https://www.zenhub.com/)
